/*
This file is part of the Nervatura Framework
http://www.nervatura.com
Copyright © 2011-2016, Csaba Kappel
License: LGPLv3
https://raw.githubusercontent.com/nervatura/nervatura/master/LICENSE
*/

module.exports = {
  en: {
    changed_password: "Password changed",
    data_deleted: "The data was deleted",
    dirty_password: "Empty password: Please change after the first login!",
    disabled_insert: "New record requires the insert_row parameter!",
    disabled_readonly_type: "Disabled or readonly type",
    disabled_type: "Disabled type",
    disabled_update: "Disabled update",
    empty_password: "The new password can not be empty!",
    exists_template: "The template already exists!",
    info_export_ok: "The database export is complete!",
    info_export: "Independent from the database type. Recommended for data migration.",
    info_create_ok: "The database was created successfully!",
    info_process_ok: "The process has run without error!",
    info_import_ok: "The data import is complete!",
    info_start: "Process started. Waiting for the server to respond ...",
    insecure_err: "is disabled because insecure channel",
    integrity_error: "Integrity error. The object can not be deleted!",
    invalid_fieldname: "Invalid fieldname:",
    invalid_nervatype: "Invalid nervatype value:",
    invalid_platform_win: "Not yet supported for win32",
    invalid_printer: "Missing or unknown printer",
    invalid_python_path: "Invalid Python path or version",
    invalid_refnumber: "Invalid refnumber:",
    invalid_template: "Invalid template!",
    invalid_user: "Invalid user:",
    invalid_value: "Invalid value type",
    label_accounts: "User Accounts",
    label_alias: "Alias",
    label_export_file: "Data File",
    label_export: "Database Export",
    label_cancel: "Cancel",
    label_change_password: "Change Password",
    label_close: "Close",
    label_creation: "Database Creation",
    label_database: "Database",
    label_databases: "Customer Databases",
    label_delete: "Delete Data",
    label_description: "Description",
    label_download: "Download",
    label_edit: "Edit Data",
    label_engine: "Engine",
    label_exit: "EXIT",
    label_fieldname: "Fieldname",
    label_format: "Export format",
    label_host: "Host",
    label_login: "Login",
    label_login_title: "NAS Login",
    label_management: "Database Management",
    label_menu: "MENU",
    label_ndi_enabled: "NDI Enabled",
    label_encrypt_password: "Encrypting Password",
    label_dbs_host_restriction: "Limit connections (ip pattern) to",
    label_new_password: "New Password",
    label_new: "New Data",
    label_ntura_framework: "©2011-2016 Nervatura Framework",
    label_old_password: "Old Password",
    label_password: "Password",
    label_port: "Port",
    label_report_delete: "Delete",
    label_report_edit: "Edit template",
    label_report_group: "Group",
    label_report_install: "Install",
    label_report_labels: "Report labels",
    label_report_name: "Report Name/ Description",
    label_report_preview: "Preview",
    label_reports: "Report Templates",
    label_import: "Database Import",
    label_search_name: "Report Name",
    label_search: "Search",
    label_settings: "Server Settings",
    label_update: "Save Data",
    label_upload_file: "Upload File",
    label_username: "Username",
    label_value: "Value",
    label_verify_password: "Verify Password",
    label_xml_template: "XML template",
    li_dbs_create_1: "Create a new database alias. See",
    li_dbs_create_2: "The SQLite, Google SQL and OpenShift databases are created automatically. Other types of databases must be created manually before.",
    li_dbs_create_3: "Please select an alias and start the creation!",
    li_dbs_start: "Starting the process...",
    log_create_demo: "Create a DEMO database (optional)",
    log_create_index: "Creating indexes ...",
    log_create_table: "Creating the tables...",
    log_database_alias: "Database alias",
    log_drop_table: "The existing table is dropped...",
    log_end_process: "End process",
    log_error: "Error",
    log_init_data: "Data initialization ...",
    log_load_data: "Loading data ...",
    log_load_template: "Loading report templates and data ...",
    log_start_process: "Start process",
    missing_database: "Missing database:",
    missing_fieldname: "Missing fieldname",
    missing_insert_field: "Unknown fieldname and missing insert_field parameter:",
    missing_nervatype: "Missing or unknown nervatype",
    missing_params: "Missing parameters",
    missing_reportkey: "Missing reportkey",
    missing_required_field: "Missing required field:",
    missing_sql: "Sql datatype, but missing sql parameter!",
    missing_user: "Missing user!",
    missing_usergroup: "Missing usergroup!",
    msg_delete_info: "This action cannot be undone.",
    msg_delete_text: "Are you sure you want to delete these data?",
    ndi_cross_format: "Cross tab format and invalid output. Valid output value: html, excel",
    ndi_deffields_1: "Additional field xml output is not allowed in where string: @colname. Use the search fieldvalue object 'description' field!",
    ndi_deffields_2: "Additional field xml output is not allowed in orderby string:",
    ndi_disabled: "Disabled interface connection!",
    ndi_invalid_datatype: "Invalid datatype",
    ndi_invalid_login: "Login required!",
    ndi_missing_refnumber: "Missing refnumber value",
    ndi_no_data: "No data available",
    not_connect: "Could not connect to the database",
    not_exist: "does not exist",
    not_included: "Not included",
    protected_data: "Protected data can not be deleted",
    title_about: "ABOUT",
    title_client_side: "CLIENT-SIDE",
    title_documentation: "DOCUMENTATION",
    title_help: "HELP",
    title_home: "HOME",
    title_more_info: "More info",
    title_more: "More",
    title_nas: "NAS ADMIN",
    title_overview: "Overview",
    title_server_side: "SERVER-SIDE",
    unknown_fieldname: "Unknown fieldname:",
    unknown_method: "Unknown method:",
    unknown_user: "Incorrect user!",
    unsupport_db: "Invalid database type!",
    update_error: "An error occurred when saving data!",
    update_ok: "Successful update!",
    user_delete_err: "There must be at least one user in the database!",
    valid_sql: "Valid sql query: select, update or insert!",
    verify_password: "Password fields don't match",
    wrong_password: "Incorrect password!"
  }
};
