ALTER TABLE address RENAME TO bck_address;
ALTER TABLE barcode RENAME TO bck_barcode;
ALTER TABLE contact RENAME TO bck_contact;
ALTER TABLE currency RENAME TO bck_currency;
ALTER TABLE customer RENAME TO bck_customer;
ALTER TABLE deffield RENAME TO bck_deffield;
ALTER TABLE employee RENAME TO bck_employee;
ALTER TABLE event RENAME TO bck_event;
ALTER TABLE fieldvalue RENAME TO bck_fieldvalue;
ALTER TABLE groups RENAME TO bck_groups;
ALTER TABLE item RENAME TO bck_item;
ALTER TABLE link RENAME TO bck_link;
ALTER TABLE log RENAME TO bck_log;
ALTER TABLE movement RENAME TO bck_movement;
ALTER TABLE numberdef RENAME TO bck_numberdef;
ALTER TABLE pattern RENAME TO bck_pattern;
ALTER TABLE payment RENAME TO bck_payment;
ALTER TABLE place RENAME TO bck_place;
ALTER TABLE price RENAME TO bck_price;
ALTER TABLE product RENAME TO bck_product;
ALTER TABLE project RENAME TO bck_project;
ALTER TABLE rate RENAME TO bck_rate;
ALTER TABLE tax RENAME TO bck_tax;
ALTER TABLE tool RENAME TO bck_tool;
ALTER TABLE trans RENAME TO bck_trans;
ALTER TABLE ui_audit RENAME TO bck_ui_audit;
ALTER TABLE ui_menu RENAME TO bck_ui_menu;
ALTER TABLE ui_menufields RENAME TO bck_ui_menufields;
ALTER TABLE ui_message RENAME TO bck_ui_message;
ALTER TABLE ui_printqueue RENAME TO bck_ui_printqueue;
ALTER TABLE ui_report RENAME TO bck_ui_report;
ALTER TABLE ui_userconfig RENAME TO bck_ui_userconfig;

DROP TABLE IF EXISTS ref17890714;

DROP INDEX IF EXISTS address_deleted_idx;
DROP INDEX IF EXISTS address_nervatype_idx;
DROP INDEX IF EXISTS barcode_code_idx;
DROP INDEX IF EXISTS barcode_defcode_idx;
DROP INDEX IF EXISTS barcode_parts_id_idx;
DROP INDEX IF EXISTS contact_deleted_idx;
DROP INDEX IF EXISTS contact_nervatype_idx;
DROP INDEX IF EXISTS currency_curr_idx;
DROP INDEX IF EXISTS customer_custname_idx;
DROP INDEX IF EXISTS customer_custnumber_idx;
DROP INDEX IF EXISTS customer_custtype_idx;
DROP INDEX IF EXISTS customer_deleted_idx;
DROP INDEX IF EXISTS customer_inactive_idx;
DROP INDEX IF EXISTS deffield_deleted_idx;
DROP INDEX IF EXISTS deffield_fieldname_idx;
DROP INDEX IF EXISTS deffield_nervatype_id_idx;
DROP INDEX IF EXISTS employee_deleted_idx;
DROP INDEX IF EXISTS employee_empnumber_idx;
DROP INDEX IF EXISTS employee_inactiv_idx;
DROP INDEX IF EXISTS employee_username_idx;
DROP INDEX IF EXISTS event_calnumber_idx;
DROP INDEX IF EXISTS event_deleted_idx;
DROP INDEX IF EXISTS event_eventgroup_idx;
DROP INDEX IF EXISTS event_fromdate_idx;
DROP INDEX IF EXISTS event_nervatype_idx;
DROP INDEX IF EXISTS event_ref_idx;
DROP INDEX IF EXISTS event_uid_idx;
DROP INDEX IF EXISTS fieldvalue_fieldname_idx;
DROP INDEX IF EXISTS fieldvalue_ref_id_idx;
DROP INDEX IF EXISTS groups_deleted_idx;
DROP INDEX IF EXISTS groups_groupname_idx;
DROP INDEX IF EXISTS groups_groupvalue_idx;
DROP INDEX IF EXISTS groups_inactive_idx;
DROP INDEX IF EXISTS groups_namevalue_idx;
DROP INDEX IF EXISTS idx_audit_pk;
DROP INDEX IF EXISTS idx_audit_usergroup;
DROP INDEX IF EXISTS idx_link_deleted;
DROP INDEX IF EXISTS idx_link_nervatype_1;
DROP INDEX IF EXISTS idx_link_nervatype_2;
DROP INDEX IF EXISTS idx_link_ref_id_1;
DROP INDEX IF EXISTS idx_link_ref_id_2;
DROP INDEX IF EXISTS idx_userconfig_ec;
DROP INDEX IF EXISTS idx_userconfig_employee_ide;
DROP INDEX IF EXISTS idx_userconfig_pk;
DROP INDEX IF EXISTS item_deleted_idx;
DROP INDEX IF EXISTS item_product_id_idx;
DROP INDEX IF EXISTS item_tax_id_idx;
DROP INDEX IF EXISTS item_trans_id_idx;
DROP INDEX IF EXISTS log_logstate_idx;
DROP INDEX IF EXISTS log_nervatype_idx;
DROP INDEX IF EXISTS menucmd_menukey_idx;
DROP INDEX IF EXISTS menucmd_modul_idx;
DROP INDEX IF EXISTS menufields_menu_idx;
DROP INDEX IF EXISTS message_fieldname_idx;
DROP INDEX IF EXISTS message_lang_idx;
DROP INDEX IF EXISTS message_pk_idx;
DROP INDEX IF EXISTS message_secname_idx;
DROP INDEX IF EXISTS movement_deleted_idx;
DROP INDEX IF EXISTS movement_movetype_idx;
DROP INDEX IF EXISTS movement_place_id_idx;
DROP INDEX IF EXISTS movement_product_id_idx;
DROP INDEX IF EXISTS movement_shipdate_idx;
DROP INDEX IF EXISTS movement_tool_id_idx;
DROP INDEX IF EXISTS movement_trans_id_idx;
DROP INDEX IF EXISTS numberdef_numberkey_idx;
DROP INDEX IF EXISTS pattern_deleted_idx;
DROP INDEX IF EXISTS pattern_description_idx;
DROP INDEX IF EXISTS pattern_transtype_idx;
DROP INDEX IF EXISTS payment_deleted_idx;
DROP INDEX IF EXISTS payment_paiddate_idx;
DROP INDEX IF EXISTS payment_trans_id_idx;
DROP INDEX IF EXISTS place_deleted_idx;
DROP INDEX IF EXISTS place_placetype_idx;
DROP INDEX IF EXISTS place_planumber_idx;
DROP INDEX IF EXISTS price_curr_idx;
DROP INDEX IF EXISTS price_deleted_idx;
DROP INDEX IF EXISTS price_product_id_idx;
DROP INDEX IF EXISTS price_validfrom_idx;
DROP INDEX IF EXISTS price_validto_idx;
DROP INDEX IF EXISTS price_vendor_idx;
DROP INDEX IF EXISTS printqueue_nervatype_idx;
DROP INDEX IF EXISTS printqueue_usename_idx;
DROP INDEX IF EXISTS product_deleted_idx;
DROP INDEX IF EXISTS product_inactive_idx;
DROP INDEX IF EXISTS product_partnumber_idx;
DROP INDEX IF EXISTS product_protype_idx;
DROP INDEX IF EXISTS product_tax_id_idx;
DROP INDEX IF EXISTS product_webitem_idx;
DROP INDEX IF EXISTS project_customer_id_idx;
DROP INDEX IF EXISTS project_deleted_idx;
DROP INDEX IF EXISTS project_inactive_idx;
DROP INDEX IF EXISTS project_pronumber_idx;
DROP INDEX IF EXISTS rate_curr_idx;
DROP INDEX IF EXISTS rate_deleted_idx;
DROP INDEX IF EXISTS rate_ratedate_idx;
DROP INDEX IF EXISTS rate_ref_idx;
DROP INDEX IF EXISTS report_filetype_idx;
DROP INDEX IF EXISTS report_reportkey_idx;
DROP INDEX IF EXISTS report_reporttype_idx;
DROP INDEX IF EXISTS tax_inactive_idx;
DROP INDEX IF EXISTS tax_taxcode_idx;
DROP INDEX IF EXISTS tool_deleted_idx;
DROP INDEX IF EXISTS tool_groups_id_idx;
DROP INDEX IF EXISTS tool_inactive_idx;
DROP INDEX IF EXISTS tool_product_id_idx;
DROP INDEX IF EXISTS tool_serial_idx;
DROP INDEX IF EXISTS trans_crdate_idx;
DROP INDEX IF EXISTS trans_cruser_idx;
DROP INDEX IF EXISTS trans_curr_idx;
DROP INDEX IF EXISTS trans_customer_idx;
DROP INDEX IF EXISTS trans_department_idx;
DROP INDEX IF EXISTS trans_direction_idx;
DROP INDEX IF EXISTS trans_duedate_idx;
DROP INDEX IF EXISTS trans_employee_id_idx;
DROP INDEX IF EXISTS trans_paidtype_idx;
DROP INDEX IF EXISTS trans_project_id_idx;
DROP INDEX IF EXISTS trans_ref_transnumber_idx;
DROP INDEX IF EXISTS trans_transdate_idx;
DROP INDEX IF EXISTS trans_transnumber_idx;
DROP INDEX IF EXISTS trans_transtate_idx;
DROP INDEX IF EXISTS trans_transtype_idx;

ALTER TABLE IF EXISTS bck_address ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_barcode ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_contact ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_currency ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_customer ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_deffield ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_employee ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_event ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_fieldvalue ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_groups ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_item ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_link ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_log ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_movement ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_numberdef ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_pattern ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_payment ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_place ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_price ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_product ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_project ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_rate ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_tax ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_tool ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_trans ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_ui_audit ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_ui_menu ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_ui_menufields ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_ui_message ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_ui_printqueue ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_ui_report ALTER COLUMN id SET DEFAULT NULL;
ALTER TABLE IF EXISTS bck_ui_userconfig ALTER COLUMN id SET DEFAULT NULL;

DROP SEQUENCE IF EXISTS address_id_seq;
DROP SEQUENCE IF EXISTS barcode_id_seq;
DROP SEQUENCE IF EXISTS contact_id_seq;
DROP SEQUENCE IF EXISTS currency_id_seq;
DROP SEQUENCE IF EXISTS customer_id_seq;
DROP SEQUENCE IF EXISTS deffield_id_seq;
DROP SEQUENCE IF EXISTS employee_id_seq;
DROP SEQUENCE IF EXISTS event_id_seq;
DROP SEQUENCE IF EXISTS fieldvalue_id_seq;
DROP SEQUENCE IF EXISTS groups_id_seq;
DROP SEQUENCE IF EXISTS item_id_seq;
DROP SEQUENCE IF EXISTS link_id_seq;
DROP SEQUENCE IF EXISTS log_id_seq;
DROP SEQUENCE IF EXISTS movement_id_seq;
DROP SEQUENCE IF EXISTS numberdef_id_seq;
DROP SEQUENCE IF EXISTS pattern_id_seq;
DROP SEQUENCE IF EXISTS payment_id_seq;
DROP SEQUENCE IF EXISTS place_id_seq;
DROP SEQUENCE IF EXISTS price_id_seq;
DROP SEQUENCE IF EXISTS product_id_seq;
DROP SEQUENCE IF EXISTS project_id_seq;
DROP SEQUENCE IF EXISTS rate_id_seq;
DROP SEQUENCE IF EXISTS tax_id_seq;
DROP SEQUENCE IF EXISTS tool_id_seq;
DROP SEQUENCE IF EXISTS trans_id_seq;
DROP SEQUENCE IF EXISTS ui_audit_id_seq;
DROP SEQUENCE IF EXISTS ui_menu_id_seq;
DROP SEQUENCE IF EXISTS ui_menufields_id_seq;
DROP SEQUENCE IF EXISTS ui_message_id_seq;
DROP SEQUENCE IF EXISTS ui_printqueue_id_seq;
DROP SEQUENCE IF EXISTS ui_report_id_seq;
DROP SEQUENCE IF EXISTS ui_userconfig_id_seq;

ALTER TABLE IF EXISTS bck_link DROP CONSTRAINT IF EXISTS link_pkey;
ALTER TABLE IF EXISTS bck_link DROP CONSTRAINT IF EXISTS link_nervatype_1_fkey;
ALTER TABLE IF EXISTS bck_link DROP CONSTRAINT IF EXISTS link_nervatype_2_fkey;
ALTER TABLE IF EXISTS bck_log DROP CONSTRAINT IF EXISTS log_pkey;
ALTER TABLE IF EXISTS bck_log DROP CONSTRAINT IF EXISTS log_employee_id_fkey;
ALTER TABLE IF EXISTS bck_log DROP CONSTRAINT IF EXISTS log_logstate_fkey;
ALTER TABLE IF EXISTS bck_log DROP CONSTRAINT IF EXISTS log_nervatype_fkey;
ALTER TABLE IF EXISTS bck_address DROP CONSTRAINT IF EXISTS address_pkey;
ALTER TABLE IF EXISTS bck_address DROP CONSTRAINT IF EXISTS address_nervatype_fkey;
ALTER TABLE IF EXISTS bck_barcode DROP CONSTRAINT IF EXISTS barcode_pkey;
ALTER TABLE IF EXISTS bck_barcode DROP CONSTRAINT IF EXISTS barcode_barcodetype_fkey;
ALTER TABLE IF EXISTS bck_barcode DROP CONSTRAINT IF EXISTS barcode_product_id_fkey;
ALTER TABLE IF EXISTS bck_contact DROP CONSTRAINT IF EXISTS contact_pkey;
ALTER TABLE IF EXISTS bck_contact DROP CONSTRAINT IF EXISTS contact_nervatype_fkey;
ALTER TABLE IF EXISTS bck_event DROP CONSTRAINT IF EXISTS event_pkey;
ALTER TABLE IF EXISTS bck_event DROP CONSTRAINT IF EXISTS event_eventgroup_fkey;
ALTER TABLE IF EXISTS bck_event DROP CONSTRAINT IF EXISTS event_nervatype_fkey;
ALTER TABLE IF EXISTS bck_item DROP CONSTRAINT IF EXISTS item_pkey;
ALTER TABLE IF EXISTS bck_item DROP CONSTRAINT IF EXISTS item_product_id_fkey;
ALTER TABLE IF EXISTS bck_item DROP CONSTRAINT IF EXISTS item_tax_id_fkey;
ALTER TABLE IF EXISTS bck_item DROP CONSTRAINT IF EXISTS item_trans_id_fkey;
ALTER TABLE IF EXISTS bck_movement DROP CONSTRAINT IF EXISTS movement_pkey;
ALTER TABLE IF EXISTS bck_movement DROP CONSTRAINT IF EXISTS movement_movetype_fkey;
ALTER TABLE IF EXISTS bck_movement DROP CONSTRAINT IF EXISTS movement_place_id_fkey;
ALTER TABLE IF EXISTS bck_movement DROP CONSTRAINT IF EXISTS movement_product_id_fkey;
ALTER TABLE IF EXISTS bck_movement DROP CONSTRAINT IF EXISTS movement_tool_id_fkey;
ALTER TABLE IF EXISTS bck_movement DROP CONSTRAINT IF EXISTS movement_trans_id_fkey;
ALTER TABLE IF EXISTS bck_numberdef DROP CONSTRAINT IF EXISTS numberdef_pkey;
ALTER TABLE IF EXISTS bck_pattern DROP CONSTRAINT IF EXISTS pattern_pkey;
ALTER TABLE IF EXISTS bck_pattern DROP CONSTRAINT IF EXISTS pattern_transtype_fkey;
ALTER TABLE IF EXISTS bck_payment DROP CONSTRAINT IF EXISTS payment_pkey;
ALTER TABLE IF EXISTS bck_payment DROP CONSTRAINT IF EXISTS payment_trans_id_fkey;
ALTER TABLE IF EXISTS bck_rate DROP CONSTRAINT IF EXISTS rate_pkey;
ALTER TABLE IF EXISTS bck_rate DROP CONSTRAINT IF EXISTS rate_place_id_fkey;
ALTER TABLE IF EXISTS bck_rate DROP CONSTRAINT IF EXISTS rate_rategroup_fkey;
ALTER TABLE IF EXISTS bck_rate DROP CONSTRAINT IF EXISTS rate_ratetype_fkey;
ALTER TABLE IF EXISTS bck_price DROP CONSTRAINT IF EXISTS price_pkey;
ALTER TABLE IF EXISTS bck_price DROP CONSTRAINT IF EXISTS price_calcmode_fkey;
ALTER TABLE IF EXISTS bck_price DROP CONSTRAINT IF EXISTS price_product_id_fkey;
ALTER TABLE IF EXISTS bck_trans DROP CONSTRAINT IF EXISTS trans_pkey;
ALTER TABLE IF EXISTS bck_trans DROP CONSTRAINT IF EXISTS trans_cruser_id_fkey;
ALTER TABLE IF EXISTS bck_trans DROP CONSTRAINT IF EXISTS trans_customer_id_fkey;
ALTER TABLE IF EXISTS bck_trans DROP CONSTRAINT IF EXISTS trans_department_fkey;
ALTER TABLE IF EXISTS bck_trans DROP CONSTRAINT IF EXISTS trans_direction_fkey;
ALTER TABLE IF EXISTS bck_trans DROP CONSTRAINT IF EXISTS trans_employee_id_fkey;
ALTER TABLE IF EXISTS bck_trans DROP CONSTRAINT IF EXISTS trans_paidtype_fkey;
ALTER TABLE IF EXISTS bck_trans DROP CONSTRAINT IF EXISTS trans_place_id_fkey;
ALTER TABLE IF EXISTS bck_trans DROP CONSTRAINT IF EXISTS trans_project_id_fkey;
ALTER TABLE IF EXISTS bck_trans DROP CONSTRAINT IF EXISTS trans_transtate_fkey;
ALTER TABLE IF EXISTS bck_trans DROP CONSTRAINT IF EXISTS trans_transtype_fkey;
ALTER TABLE IF EXISTS bck_ui_printqueue DROP CONSTRAINT IF EXISTS ui_printqueue_pkey;
ALTER TABLE IF EXISTS bck_ui_printqueue DROP CONSTRAINT IF EXISTS ui_printqueue_employee_id_fkey;
ALTER TABLE IF EXISTS bck_ui_printqueue DROP CONSTRAINT IF EXISTS ui_printqueue_nervatype_fkey;
ALTER TABLE IF EXISTS bck_ui_printqueue DROP CONSTRAINT IF EXISTS ui_printqueue_report_id_fkey;
ALTER TABLE IF EXISTS bck_ui_userconfig DROP CONSTRAINT IF EXISTS ui_userconfig_pkey;
ALTER TABLE IF EXISTS bck_ui_userconfig DROP CONSTRAINT IF EXISTS ui_userconfig_employee_id_fkey;
ALTER TABLE IF EXISTS bck_employee DROP CONSTRAINT IF EXISTS employee_pkey;
ALTER TABLE IF EXISTS bck_employee DROP CONSTRAINT IF EXISTS employee_department_fkey;
ALTER TABLE IF EXISTS bck_employee DROP CONSTRAINT IF EXISTS employee_usergroup_fkey;
ALTER TABLE IF EXISTS bck_project DROP CONSTRAINT IF EXISTS project_pkey;
ALTER TABLE IF EXISTS bck_project DROP CONSTRAINT IF EXISTS project_customer_id_fkey;
ALTER TABLE IF EXISTS bck_tool DROP CONSTRAINT IF EXISTS tool_pkey;
ALTER TABLE IF EXISTS bck_tool DROP CONSTRAINT IF EXISTS tool_product_id_fkey;
ALTER TABLE IF EXISTS bck_tool DROP CONSTRAINT IF EXISTS tool_toolgroup_fkey;
ALTER TABLE IF EXISTS bck_currency DROP CONSTRAINT IF EXISTS currency_pkey;
ALTER TABLE IF EXISTS bck_customer DROP CONSTRAINT IF EXISTS customer_pkey;
ALTER TABLE IF EXISTS bck_customer DROP CONSTRAINT IF EXISTS customer_custtype_fkey;
ALTER TABLE IF EXISTS bck_deffield DROP CONSTRAINT IF EXISTS deffield_pkey;
ALTER TABLE IF EXISTS bck_deffield DROP CONSTRAINT IF EXISTS deffield_fieldtype_fkey;
ALTER TABLE IF EXISTS bck_deffield DROP CONSTRAINT IF EXISTS deffield_nervatype_fkey;
ALTER TABLE IF EXISTS bck_deffield DROP CONSTRAINT IF EXISTS deffield_subtype_fkey;
ALTER TABLE IF EXISTS bck_fieldvalue DROP CONSTRAINT IF EXISTS fieldvalue_fieldname_fkey;
ALTER TABLE IF EXISTS bck_place DROP CONSTRAINT IF EXISTS place_pkey;
ALTER TABLE IF EXISTS bck_place DROP CONSTRAINT IF EXISTS place_placetype_fkey;
ALTER TABLE IF EXISTS bck_product DROP CONSTRAINT IF EXISTS product_pkey;
ALTER TABLE IF EXISTS bck_product DROP CONSTRAINT IF EXISTS product_protype_fkey;
ALTER TABLE IF EXISTS bck_product DROP CONSTRAINT IF EXISTS product_tax_id_fkey;
ALTER TABLE IF EXISTS bck_tax DROP CONSTRAINT IF EXISTS tax_pkey;
ALTER TABLE IF EXISTS bck_ui_audit DROP CONSTRAINT IF EXISTS ui_audit_pkey;
ALTER TABLE IF EXISTS bck_ui_audit DROP CONSTRAINT IF EXISTS ui_audit_inputfilter_fkey;
ALTER TABLE IF EXISTS bck_ui_audit DROP CONSTRAINT IF EXISTS ui_audit_nervatype_fkey;
ALTER TABLE IF EXISTS bck_ui_audit DROP CONSTRAINT IF EXISTS ui_audit_usergroup_fkey;
ALTER TABLE IF EXISTS bck_ui_menufields DROP CONSTRAINT IF EXISTS ui_menufields_pkey;
ALTER TABLE IF EXISTS bck_ui_menufields DROP CONSTRAINT IF EXISTS ui_menufields_fieldtype_fkey;
ALTER TABLE IF EXISTS bck_ui_menufields DROP CONSTRAINT IF EXISTS ui_menufields_menu_id_fkey;
ALTER TABLE IF EXISTS bck_ui_menu DROP CONSTRAINT IF EXISTS ui_menu_pkey;
ALTER TABLE IF EXISTS bck_ui_menu DROP CONSTRAINT IF EXISTS ui_menu_method_fkey;
ALTER TABLE IF EXISTS bck_ui_message DROP CONSTRAINT IF EXISTS ui_message_pkey;
ALTER TABLE IF EXISTS bck_ui_report DROP CONSTRAINT IF EXISTS ui_report_pkey;
ALTER TABLE IF EXISTS bck_ui_report DROP CONSTRAINT IF EXISTS ui_report_direction_fkey;
ALTER TABLE IF EXISTS bck_ui_report DROP CONSTRAINT IF EXISTS ui_report_filetype_fkey;
ALTER TABLE IF EXISTS bck_ui_report DROP CONSTRAINT IF EXISTS ui_report_nervatype_fkey;
ALTER TABLE IF EXISTS bck_ui_report DROP CONSTRAINT IF EXISTS ui_report_transtype_fkey;
ALTER TABLE IF EXISTS bck_groups DROP CONSTRAINT IF EXISTS groups_pkey;


