ALTER TABLE `address` RENAME TO `bck_address`;
ALTER TABLE `barcode` RENAME TO `bck_barcode`;
ALTER TABLE `contact` RENAME TO `bck_contact`;
ALTER TABLE `currency` RENAME TO `bck_currency`;
ALTER TABLE `customer` RENAME TO `bck_customer`;
ALTER TABLE `deffield` RENAME TO `bck_deffield`;
ALTER TABLE `employee` RENAME TO `bck_employee`;
ALTER TABLE `event` RENAME TO `bck_event`;
ALTER TABLE `fieldvalue` RENAME TO `bck_fieldvalue`;
ALTER TABLE `groups` RENAME TO `bck_groups`;
ALTER TABLE `item` RENAME TO `bck_item`;
ALTER TABLE `link` RENAME TO `bck_link`;
ALTER TABLE `log` RENAME TO `bck_log`;
ALTER TABLE `movement` RENAME TO `bck_movement`;
ALTER TABLE `numberdef` RENAME TO `bck_numberdef`;
ALTER TABLE `pattern` RENAME TO `bck_pattern`;
ALTER TABLE `payment` RENAME TO `bck_payment`;
ALTER TABLE `place` RENAME TO `bck_place`;
ALTER TABLE `price` RENAME TO `bck_price`;
ALTER TABLE `product` RENAME TO `bck_product`;
ALTER TABLE `project` RENAME TO `bck_project`;
ALTER TABLE `rate` RENAME TO `bck_rate`;
ALTER TABLE `tax` RENAME TO `bck_tax`;
ALTER TABLE `tool` RENAME TO `bck_tool`;
ALTER TABLE `trans` RENAME TO `bck_trans`;
ALTER TABLE `ui_audit` RENAME TO `bck_ui_audit`;
ALTER TABLE `ui_menu` RENAME TO `bck_ui_menu`;
ALTER TABLE `ui_menufields` RENAME TO `bck_ui_menufields`;
ALTER TABLE `ui_message` RENAME TO `bck_ui_message`;
ALTER TABLE `ui_printqueue` RENAME TO `bck_ui_printqueue`;
ALTER TABLE `ui_report` RENAME TO `bck_ui_report`;
ALTER TABLE `ui_userconfig` RENAME TO `bck_ui_userconfig`;

DROP TABLE IF EXISTS ref17890714;

DROP INDEX `address_deleted_idx` ON `bck_address`;
DROP INDEX `address_nervatype_idx` ON `bck_address`;
DROP INDEX `barcode_code_idx` ON `bck_barcode`;
DROP INDEX `barcode_defcode_idx` ON `bck_barcode`;
DROP INDEX `barcode_parts_id_idx` ON `bck_barcode`;
DROP INDEX `contact_deleted_idx` ON `bck_contact`;
DROP INDEX `contact_nervatype_idx` ON `bck_contact`;
DROP INDEX `currency_curr_idx` ON `bck_currency`;
DROP INDEX `customer_custname_idx` ON `bck_customer`;
DROP INDEX `customer_custnumber_idx` ON `bck_customer`;
DROP INDEX `customer_custtype_idx` ON `bck_customer`;
DROP INDEX `customer_deleted_idx` ON `bck_customer`;
DROP INDEX `customer_inactive_idx` ON `bck_customer`;
DROP INDEX `deffield_deleted_idx` ON `bck_deffield`;
DROP INDEX `deffield_fieldname_idx` ON `bck_deffield`;
DROP INDEX `deffield_nervatype_id_idx` ON `bck_deffield`;
DROP INDEX `employee_deleted_idx` ON `bck_employee`;
DROP INDEX `employee_empnumber_idx` ON `bck_employee`;
DROP INDEX `employee_inactiv_idx` ON `bck_employee`;
DROP INDEX `employee_username_idx` ON `bck_employee`;
DROP INDEX `event_calnumber_idx` ON `bck_event`;
DROP INDEX `event_deleted_idx` ON `bck_event`;
DROP INDEX `event_eventgroup_idx` ON `bck_event`;
DROP INDEX `event_fromdate_idx` ON `bck_event`;
DROP INDEX `event_nervatype_idx` ON `bck_event`;
DROP INDEX `event_ref_idx` ON `bck_event`;
DROP INDEX `event_uid_idx` ON `bck_event`;
DROP INDEX `fieldvalue_fieldname_idx` ON `bck_fieldvalue`;
DROP INDEX `fieldvalue_ref_id_idx` ON `bck_fieldvalue`;
DROP INDEX `groups_deleted_idx` ON `bck_groups`;
DROP INDEX `groups_groupname_idx` ON `bck_groups`;
DROP INDEX `groups_groupvalue_idx` ON `bck_groups`;
DROP INDEX `groups_inactive_idx` ON `bck_groups`;
DROP INDEX `groups_namevalue_idx` ON `bck_groups`;
DROP INDEX `idx_audit_pk` ON `bck_ui_audit`;
DROP INDEX `idx_audit_usergroup` ON `bck_ui_audit`;
DROP INDEX `idx_link_deleted` ON `bck_link`;
DROP INDEX `idx_link_nervatype_1` ON `bck_link`;
DROP INDEX `idx_link_nervatype_2` ON `bck_link`;
DROP INDEX `idx_link_ref_id_1` ON `bck_link`;
DROP INDEX `idx_link_ref_id_2` ON `bck_link`;
DROP INDEX `idx_userconfig_ec` ON `bck_ui_userconfig`;
DROP INDEX `idx_userconfig_employee_ide` ON `bck_ui_userconfig`;
DROP INDEX `idx_userconfig_pk` ON `bck_ui_userconfig`;
DROP INDEX `item_deleted_idx` ON `bck_item`;
DROP INDEX `item_product_id_idx` ON `bck_item`;
DROP INDEX `item_tax_id_idx` ON `bck_item`;
DROP INDEX `item_trans_id_idx` ON `bck_item`;
DROP INDEX `log_logstate_idx` ON `bck_log`;
DROP INDEX `log_nervatype_idx` ON `bck_log`;
DROP INDEX `menucmd_menukey_idx` ON `bck_ui_menu`;
DROP INDEX `menucmd_modul_idx` ON `bck_ui_menu`;
DROP INDEX `menufields_menu_idx` ON `bck_ui_menufields`;
DROP INDEX `message_fieldname_idx` ON `bck_ui_message`;
DROP INDEX `message_lang_idx` ON `bck_ui_message`;
DROP INDEX `message_pk_idx` ON `bck_ui_message`;
DROP INDEX `message_secname_idx` ON `bck_ui_message`;
DROP INDEX `movement_deleted_idx` ON `bck_movement`;
DROP INDEX `movement_movetype_idx` ON `bck_movement`;
DROP INDEX `movement_place_id_idx` ON `bck_movement`;
DROP INDEX `movement_product_id_idx` ON `bck_movement`;
DROP INDEX `movement_shipdate_idx` ON `bck_movement`;
DROP INDEX `movement_tool_id_idx` ON `bck_movement`;
DROP INDEX `movement_trans_id_idx` ON `bck_movement`;
DROP INDEX `numberdef_numberkey_idx` ON `bck_numberdef`;
DROP INDEX `pattern_description_idx` ON `bck_pattern`;
DROP INDEX `pattern_transtype_idx` ON `bck_pattern`;
DROP INDEX `payment_deleted_idx` ON `bck_payment`;
DROP INDEX `payment_paiddate_idx` ON `bck_payment`;
DROP INDEX `payment_trans_id_idx` ON `bck_payment`;
DROP INDEX `place_deleted_idx` ON `bck_place`;
DROP INDEX `place_placetype_idx` ON `bck_place`;
DROP INDEX `place_planumber_idx` ON `bck_place`;
DROP INDEX `price_curr_idx` ON `bck_price`;
DROP INDEX `price_deleted_idx` ON `bck_price`;
DROP INDEX `price_product_id_idx` ON `bck_price`;
DROP INDEX `price_validfrom_idx` ON `bck_price`;
DROP INDEX `price_validto_idx` ON `bck_price`;
DROP INDEX `price_vendor_idx` ON `bck_price`;
DROP INDEX `printqueue_nervatype_idx` ON `bck_ui_printqueue`;
DROP INDEX `printqueue_usename_idx` ON `bck_ui_printqueue`;
DROP INDEX `product_deleted_idx` ON `bck_product`;
DROP INDEX `product_inactive_idx` ON `bck_product`;
DROP INDEX `product_partnumber_idx` ON `bck_product`;
DROP INDEX `product_protype_idx` ON `bck_product`;
DROP INDEX `product_tax_id_idx` ON `bck_product`;
DROP INDEX `product_webitem_idx` ON `bck_product`;
DROP INDEX `project_customer_id_idx` ON `bck_project`;
DROP INDEX `project_deleted_idx` ON `bck_project`;
DROP INDEX `project_inactive_idx` ON `bck_project`;
DROP INDEX `project_pronumber_idx` ON `bck_project`;
DROP INDEX `rate_curr_idx` ON `bck_rate`;
DROP INDEX `rate_deleted_idx` ON `bck_rate`;
DROP INDEX `rate_ratedate_idx` ON `bck_rate`;
DROP INDEX `rate_ref_idx` ON `bck_rate`;
DROP INDEX `report_filetype_idx` ON `bck_ui_report`;
DROP INDEX `report_reportkey_idx` ON `bck_ui_report`;
DROP INDEX `report_reporttype_idx` ON `bck_ui_report`;
DROP INDEX `tax_inactive_idx` ON `bck_tax`;
DROP INDEX `tax_taxcode_idx` ON `bck_tax`;
DROP INDEX `tool_deleted_idx` ON `bck_tool`;
DROP INDEX `tool_groups_id_idx` ON `bck_tool`;
DROP INDEX `tool_inactive_idx` ON `bck_tool`;
DROP INDEX `tool_product_id_idx` ON `bck_tool`;
DROP INDEX `tool_serial_idx` ON `bck_tool`;
DROP INDEX `trans_crdate_idx` ON `bck_trans`;
DROP INDEX `trans_cruser_idx` ON `bck_trans`;
DROP INDEX `trans_curr_idx` ON `bck_trans`;
DROP INDEX `trans_customer_idx` ON `bck_trans`;
DROP INDEX `trans_department_idx` ON `bck_trans`;
DROP INDEX `trans_direction_idx` ON `bck_trans`;
DROP INDEX `trans_duedate_idx` ON `bck_trans`;
DROP INDEX `trans_employee_id_idx` ON `bck_trans`;
DROP INDEX `trans_paidtype_idx` ON `bck_trans`;
DROP INDEX `trans_project_id_idx` ON `bck_trans`;
DROP INDEX `trans_ref_transnumber_idx` ON `bck_trans`;
DROP INDEX `trans_transdate_idx` ON `bck_trans`;
DROP INDEX `trans_transnumber_idx` ON `bck_trans`;
DROP INDEX `trans_transtate_idx` ON `bck_trans`;
DROP INDEX `trans_transtype_idx` ON `bck_trans`;