package nervatura

import "time"

//ModelField - Model (table/document) field description
type ModelField struct {
	Type       string //Valid values:"id",integer","float","string","text","date","datetime"
	Unique     bool
	NotNull    bool
	Length     int
	Default    interface{} //Default value
	Requires   IM          //Field validation rules
	References []string
	Refname    string
}

//ModelIndex - Model index description
type ModelIndex struct {
	Model  string
	Fields []string
	Unique bool
}

//MF is a ModelField type short alias
type MF = ModelField

//MI is a ModelIndex type short alias
type MI = ModelIndex

const noAction = "NO ACTION"

//DataModel - database table models
func DataModel() IM {
	return IM{
		"model": IM{
			"groups": IM{
				"_access":     SL{"setting"},
				"_key":        SL{"groupname", "groupvalue"},
				"_fields":     SL{"id", "groupname", "groupvalue", "description", "inactive", "deleted"},
				"id":          MF{Type: "id"},
				"groupname":   MF{Type: "string", Length: 150, NotNull: true},
				"groupvalue":  MF{Type: "string", Length: 150, NotNull: true},
				"description": MF{Type: "text"},
				"inactive":    MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}},
				"deleted":     MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}}},

			"ui_menu": IM{
				"_access":     SL{"setting"},
				"_key":        SL{"menukey"},
				"_fields":     SL{"id", "menukey", "description", "modul", "icon", "method", "funcname", "address"},
				"id":          MF{Type: "id"},
				"menukey":     MF{Type: "string", Length: 255, NotNull: true, Unique: true},
				"description": MF{Type: "string", Length: 255, NotNull: true},
				"modul":       MF{Type: "string", Length: 255},
				"icon":        MF{Type: "string", Length: 255},
				"method":      MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true, Requires: IM{"method": SL{}}},
				"funcname":    MF{Type: "string", Length: 255},
				"address":     MF{Type: "text"}},

			"ui_menufields": IM{
				"_access":     SL{"setting"},
				"_key":        SL{"menukey", "fieldname"},
				"_fields":     SL{"id", "menu_id", "fieldname", "description", "fieldtype", "orderby"},
				"id":          MF{Type: "id"},
				"menu_id":     MF{References: SL{"ui_menu", "CASCADE"}, NotNull: true, Refname: "menukey"},
				"fieldname":   MF{Type: "string", Length: 150, NotNull: true},
				"description": MF{Type: "string", Length: 255, NotNull: true},
				"fieldtype": MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true,
					Requires: IM{"fieldtype": SL{"bool", "date", "integer", "float", "string"}}},
				"orderby": MF{Type: "integer", Default: int64(0), NotNull: true}},

			"ui_message": IM{
				"_access":   SL{"setting"},
				"_key":      SL{"secname", "fieldname", "lang"},
				"_fields":   SL{"id", "secname", "fieldname", "lang", "msg"},
				"id":        MF{Type: "id"},
				"secname":   MF{Type: "string", Length: 150, NotNull: true},
				"fieldname": MF{Type: "string", Length: 150, NotNull: true},
				"lang":      MF{Type: "string", Length: 2},
				"msg":       MF{Type: "text", NotNull: true}},

			"ui_report": IM{
				"_access":     SL{"setting"},
				"_key":        SL{"reportkey"},
				"_fields":     SL{"id", "reportkey", "nervatype", "transtype", "direction", "repname", "description", "label", "filetype", "report"},
				"id":          MF{Type: "id"},
				"reportkey":   MF{Type: "string", Length: 255, NotNull: true, Unique: true},
				"nervatype":   MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true, Requires: IM{"nervatype": SL{}}},
				"transtype":   MF{References: SL{"groups", "RESTRICT", noAction}, Requires: IM{"transtype": SL{}}},
				"direction":   MF{References: SL{"groups", "RESTRICT", noAction}, Requires: IM{"direction": SL{}}},
				"repname":     MF{Type: "string", Length: 255, NotNull: true},
				"description": MF{Type: "string", Length: 255},
				"label":       MF{Type: "string", Length: 255},
				"filetype":    MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true, Requires: IM{"filetype": SL{}}},
				"report":      MF{Type: "text"}},

			"employee": IM{
				"_access":          SL{"employee"},
				"_key":             SL{"empnumber"},
				"_fields":          SL{"id", "empnumber", "username", "usergroup", "startdate", "enddate", "department", "registration_key", "inactive", "deleted"},
				"id":               MF{Type: "id"},
				"empnumber":        MF{Type: "string", Length: 150, NotNull: true, Unique: true, Default: "nextnumber"},
				"username":         MF{Type: "string", Length: 150, Unique: true},
				"usergroup":        MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true, Requires: IM{"usergroup": SL{}}},
				"startdate":        MF{Type: "date"},
				"enddate":          MF{Type: "date"},
				"department":       MF{References: SL{"groups", "RESTRICT", noAction}, Requires: IM{"department": SL{}}},
				"registration_key": MF{Type: "string", Length: 512},
				"inactive":         MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}},
				"deleted":          MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}}},

			"ui_printqueue": IM{
				"_access":     SL{"setting"},
				"_key":        SL{},
				"_fields":     SL{"id", "nervatype", "ref_id", "qty", "employee_id", "report_id", "crdate"},
				"id":          MF{Type: "id"},
				"nervatype":   MF{References: SL{"groups", "CASCADE"}, NotNull: true, Requires: IM{"nervatype": SL{}}},
				"ref_id":      MF{Type: "integer", NotNull: true},
				"qty":         MF{Type: "float", Default: float64(0), NotNull: true},
				"employee_id": MF{References: SL{"employee", "CASCADE", noAction}, NotNull: true, Refname: "empnumber"},
				"report_id":   MF{References: SL{"ui_report", "CASCADE", noAction}, NotNull: true, Refname: "reportkey"},
				"crdate":      MF{Type: "datetime", NotNull: true}},

			"ui_userconfig": IM{
				"_access":     SL{"setting"},
				"_key":        SL{"empnumber", "section", "cfgroup", "cfname"},
				"_fields":     SL{"id", "employee_id", "section", "cfgroup", "cfname", "cfvalue", "orderby"},
				"id":          MF{Type: "id"},
				"employee_id": MF{References: SL{"employee", "CASCADE"}, NotNull: true, Refname: "empnumber"},
				"section":     MF{Type: "string", Length: 150},
				"cfgroup":     MF{Type: "string", Length: 150, NotNull: true},
				"cfname":      MF{Type: "string", Length: 150, NotNull: true},
				"cfvalue":     MF{Type: "text"},
				"orderby":     MF{Type: "integer", Default: int64(0), NotNull: true}},

			"link": IM{
				"_access": SL{"address", "barcode", "contact", "currency", "customer", "employee", "event", "groups", "item",
					"movement", "payment", "price", "place", "product", "project", "rate", "tax", "tool", "trans", "setting"},
				"_key":        SL{"nervatype1", "refnumber1", "nervatype2", "refnumber2"},
				"_fields":     SL{"id", "nervatype_1", "ref_id_1", "nervatype_2", "ref_id_2", "deleted"},
				"id":          MF{Type: "id"},
				"nervatype_1": MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true, Requires: IM{"nervatype": SL{}}, Refname: "nervatype1"},
				"ref_id_1":    MF{Type: "integer", NotNull: true, Refname: "refnumber1"},
				"nervatype_2": MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true, Requires: IM{"nervatype": SL{}}, Refname: "nervatype2"},
				"ref_id_2":    MF{Type: "integer", NotNull: true, Refname: "refnumber2"},
				"deleted":     MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}}},

			"ui_audit": IM{
				"_access":     SL{"setting"},
				"_key":        SL{"usergroup", "nervatype", "subtype"},
				"_fields":     SL{"id", "usergroup", "nervatype", "subtype", "inputfilter", "supervisor"},
				"id":          MF{Type: "id"},
				"usergroup":   MF{References: SL{"groups", "CASCADE"}, NotNull: true, Requires: IM{"usergroup": SL{}}},
				"nervatype":   MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true, Requires: IM{"nervatype": SL{}}},
				"subtype":     MF{Type: "integer"},
				"inputfilter": MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true, Requires: IM{"inputfilter": SL{}}},
				"supervisor":  MF{Type: "integer", Default: int64(1), NotNull: true, Requires: IM{"bool": true}}},

			"deffield": IM{
				"_access":   SL{"setting"},
				"_key":      SL{"fieldname"},
				"_fields":   SL{"id", "fieldname", "nervatype", "subtype", "fieldtype", "description", "valuelist", "addnew", "visible", "readonly", "deleted"},
				"id":        MF{Type: "id"},
				"fieldname": MF{Type: "string", Length: 150, NotNull: true, Unique: true},
				"nervatype": MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true,
					Requires: IM{"nervatype": SL{"address", "barcode", "contact", "currency", "customer", "employee", "event", "item", "link",
						"log", "movement", "payment", "price", "place", "product", "project", "rate", "tax", "tool", "trans", "setting"}}},
				"subtype": MF{References: SL{"groups", "RESTRICT", noAction},
					Requires: IM{"custtype": SL{}, "placetype": SL{}, "protype": SL{}, "toolgroup": SL{}, "transtype": SL{}}},
				"fieldtype":   MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true, Requires: IM{"fieldtype": SL{}}},
				"description": MF{Type: "text", NotNull: true},
				"valuelist":   MF{Type: "text"},
				"addnew":      MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}},
				"visible":     MF{Type: "integer", Default: int64(1), NotNull: true, Requires: IM{"bool": true}},
				"readonly":    MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}},
				"deleted":     MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}}},

			"fieldvalue": IM{
				"_access": SL{"address", "barcode", "contact", "currency", "customer", "employee",
					"event", "groups", "item", "link", "log", "movement", "price", "place", "product",
					"project", "rate", "tax", "tool", "trans", "setting"},
				"_key":      SL{"fieldname", "refnumber", "rownumber"},
				"_fields":   SL{"id", "fieldname", "ref_id", "value", "notes", "deleted"},
				"id":        MF{Type: "id"},
				"fieldname": MF{Type: "string", Length: 150},
				"ref_id":    MF{Type: "integer", Refname: "refnumber"},
				"value":     MF{Type: "text"},
				"notes":     MF{Type: "text"},
				"deleted":   MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}}},

			"log": IM{
				"_access":     SL{"setting"},
				"_key":        SL{"empnumber", "crdate"},
				"_fields":     SL{"id", "employee_id", "crdate", "nervatype", "ref_id", "logstate"},
				"id":          MF{Type: "id"},
				"employee_id": MF{References: SL{"employee", "RESTRICT", noAction}, NotNull: true, Refname: "empnumber"},
				"crdate":      MF{Type: "datetime", NotNull: true},
				"nervatype": MF{References: SL{"groups", "RESTRICT", noAction},
					Requires: IM{"nervatype": SL{"address", "barcode", "contact", "currency", "customer", "employee", "deffield", "event", "groups",
						"item", "link", "movement", "payment", "price", "place", "product", "project", "rate", "tax", "tool", "trans", "setting"}}},
				"ref_id":   MF{Type: "integer", Refname: "refnumber"},
				"logstate": MF{References: SL{"groups", "CASCADE"}, NotNull: true, Requires: IM{"logstate": SL{}}}},

			"numberdef": IM{
				"_access":     SL{"setting"},
				"_key":        SL{"numberkey"},
				"_fields":     SL{"id", "numberkey", "prefix", "curvalue", "isyear", "sep", "len", "description", "visible", "readonly", "orderby"},
				"id":          MF{Type: "id"},
				"numberkey":   MF{Type: "string", Length: 150, NotNull: true, Unique: true},
				"prefix":      MF{Type: "string", Length: 150},
				"curvalue":    MF{Type: "integer", Default: int64(0), NotNull: true},
				"isyear":      MF{Type: "integer", Default: int64(1), NotNull: true, Requires: IM{"bool": true}},
				"sep":         MF{Type: "string", Length: 1, Default: "'/'", NotNull: true},
				"len":         MF{Type: "integer", Default: int64(5), NotNull: true},
				"description": MF{Type: "text"},
				"visible":     MF{Type: "integer", Default: int64(1), NotNull: true, Requires: IM{"bool": true}},
				"readonly":    MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}},
				"orderby":     MF{Type: "integer", Default: int64(0), NotNull: true}},

			"address": IM{
				"_access": SL{"customer", "employee", "event", "place", "product", "project", "tool", "trans"},
				"_key":    SL{"nervatype", "refnumber", "rownumber"},
				"_fields": SL{"id", "nervatype", "ref_id", "country", "state", "zipcode", "city", "street", "notes", "deleted"},
				"id":      MF{Type: "id"},
				"nervatype": MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true,
					Requires: IM{"nervatype": SL{"customer", "employee", "event", "place", "product", "project", "tool", "trans"}}},
				"ref_id":  MF{Type: "integer", NotNull: true, Refname: "refnumber"},
				"country": MF{Type: "string", Length: 255},
				"state":   MF{Type: "string", Length: 255},
				"zipcode": MF{Type: "string", Length: 150},
				"city":    MF{Type: "string", Length: 255},
				"street":  MF{Type: "text"},
				"notes":   MF{Type: "text"},
				"deleted": MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}}},

			"contact": IM{
				"_access": SL{"customer", "employee", "event", "place", "product", "project", "tool", "trans"},
				"_key":    SL{"nervatype", "refnumber", "rownumber"},
				"_fields": SL{"id", "nervatype", "ref_id", "firstname", "surname", "status", "phone", "fax", "mobil", "email", "notes", "deleted"},
				"id":      MF{Type: "id"},
				"nervatype": MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true,
					Requires: IM{"nervatype": SL{"customer", "employee", "event", "place", "product", "project", "tool", "trans"}}},
				"ref_id":    MF{Type: "integer", NotNull: true, Refname: "refnumber"},
				"firstname": MF{Type: "string", Length: 255},
				"surname":   MF{Type: "string", Length: 255},
				"status":    MF{Type: "string", Length: 255},
				"phone":     MF{Type: "string", Length: 255},
				"fax":       MF{Type: "string", Length: 255},
				"mobil":     MF{Type: "string", Length: 255},
				"email":     MF{Type: "string", Length: 255},
				"notes":     MF{Type: "text"},
				"deleted":   MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}}},

			"event": IM{
				"_access":   SL{"customer", "employee", "place", "product", "project", "tool", "trans"},
				"_key":      SL{"calnumber"},
				"_fields":   SL{"id", "calnumber", "nervatype", "ref_id", "uid", "eventgroup", "fromdate", "todate", "subject", "place", "description", "deleted"},
				"id":        MF{Type: "id"},
				"calnumber": MF{Type: "string", Length: 150, NotNull: true, Unique: true, Default: "nextnumber"},
				"nervatype": MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true,
					Requires: IM{"nervatype": SL{"customer", "employee", "place", "product", "project", "tool", "trans"}}},
				"ref_id":      MF{Type: "integer", NotNull: true, Refname: "refnumber"},
				"uid":         MF{Type: "string", Length: 255},
				"eventgroup":  MF{References: SL{"groups", "CASCADE"}, Requires: IM{"eventgroup": SL{}}},
				"fromdate":    MF{Type: "datetime"},
				"todate":      MF{Type: "datetime"},
				"subject":     MF{Type: "string", Length: 255},
				"place":       MF{Type: "string", Length: 255},
				"description": MF{Type: "text"},
				"deleted":     MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}}},

			"customer": IM{
				"_access":     SL{"customer"},
				"_key":        SL{"custnumber"},
				"_fields":     SL{"id", "custtype", "custnumber", "custname", "taxnumber", "account", "notax", "terms", "creditlimit", "discount", "notes", "inactive", "deleted"},
				"id":          MF{Type: "id"},
				"custtype":    MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true, Requires: IM{"custtype": SL{}}},
				"custnumber":  MF{Type: "string", Length: 150, NotNull: true, Unique: true, Default: "nextnumber"},
				"custname":    MF{Type: "string", Length: 255, NotNull: true},
				"taxnumber":   MF{Type: "string", Length: 255},
				"account":     MF{Type: "string", Length: 255},
				"notax":       MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}},
				"terms":       MF{Type: "integer", Default: int64(0), NotNull: true},
				"creditlimit": MF{Type: "float", Default: float64(0), NotNull: true},
				"discount":    MF{Type: "float", Default: float64(0), NotNull: true},
				"notes":       MF{Type: "text"},
				"inactive":    MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}},
				"deleted":     MF{Type: "integer", Default: int64(0), NotNull: true}},

			"project": IM{
				"_access":     SL{"project"},
				"_key":        SL{"pronumber"},
				"_fields":     SL{"id", "pronumber", "description", "customer_id", "startdate", "enddate", "notes", "inactive", "deleted"},
				"id":          MF{Type: "id"},
				"pronumber":   MF{Type: "string", Length: 150, NotNull: true, Unique: true, Default: "nextnumber"},
				"description": MF{Type: "string", Length: 255, NotNull: true},
				"customer_id": MF{References: SL{"customer", "RESTRICT", "CASCADE"}, Refname: "custnumber"},
				"startdate":   MF{Type: "date"},
				"enddate":     MF{Type: "date"},
				"notes":       MF{Type: "text"},
				"inactive":    MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}},
				"deleted":     MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}}},

			"currency": IM{
				"_access":     SL{"setting"},
				"_key":        SL{"curr"},
				"_fields":     SL{"id", "curr", "description", "digit", "defrate", "cround"},
				"id":          MF{Type: "id"},
				"curr":        MF{Type: "string", Length: 3, NotNull: true, Unique: true},
				"description": MF{Type: "string", Length: 255, NotNull: true},
				"digit":       MF{Type: "integer", Default: int64(0), NotNull: true},
				"defrate":     MF{Type: "float", Default: float64(0), NotNull: true},
				"cround":      MF{Type: "integer", Default: int64(0), NotNull: true}},

			"place": IM{
				"_access":     SL{"setting"},
				"_key":        SL{"planumber"},
				"_fields":     SL{"id", "planumber", "placetype", "description", "curr", "defplace", "notes", "inactive", "deleted"},
				"id":          MF{Type: "id"},
				"planumber":   MF{Type: "string", Length: 150, NotNull: true, Unique: true, Default: "nextnumber"},
				"placetype":   MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true, Requires: IM{"placetype": SL{}}},
				"description": MF{Type: "string", Length: 255, NotNull: true},
				"curr":        MF{Type: "string", Length: 3, Requires: IM{"curr": SL{}}},
				"defplace":    MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}},
				"notes":       MF{Type: "text"},
				"inactive":    MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}},
				"deleted":     MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}}},

			"rate": IM{
				"_access":   SL{"setting"},
				"_key":      SL{"ratetype", "ratedate", "curr", "planumber"},
				"_fields":   SL{"id", "ratetype", "ratedate", "curr", "place_id", "rategroup", "ratevalue", "deleted"},
				"id":        MF{Type: "id"},
				"ratetype":  MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true, Requires: IM{"ratetype": SL{}}},
				"ratedate":  MF{Type: "date", NotNull: true},
				"curr":      MF{Type: "string", Length: 3, NotNull: true, Requires: IM{"curr": SL{}}},
				"place_id":  MF{References: SL{"place", "RESTRICT", "CASCADE"}, Refname: "planumber"},
				"rategroup": MF{References: SL{"groups", "RESTRICT", noAction}, Requires: IM{"rategroup": SL{}}},
				"ratevalue": MF{Type: "float", Default: float64(0), NotNull: true},
				"deleted":   MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}}},

			"tax": IM{
				"_access":     SL{"setting"},
				"_key":        SL{"taxcode"},
				"_fields":     SL{"id", "taxcode", "description", "rate", "inactive"},
				"id":          MF{Type: "id"},
				"taxcode":     MF{Type: "string", Length: 150, NotNull: true, Unique: true},
				"description": MF{Type: "string", Length: 255, NotNull: true},
				"rate":        MF{Type: "float", Default: float64(0), NotNull: true},
				"inactive":    MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}}},

			"product": IM{
				"_access":     SL{"product"},
				"_key":        SL{"partnumber"},
				"_fields":     SL{"id", "partnumber", "protype", "description", "unit", "tax_id", "notes", "webitem", "inactive", "deleted"},
				"id":          MF{Type: "id"},
				"partnumber":  MF{Type: "string", Length: 150, NotNull: true, Unique: true, Default: "nextnumber"},
				"protype":     MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true, Requires: IM{"protype": SL{}}},
				"description": MF{Type: "string", Length: 255, NotNull: true},
				"unit":        MF{Type: "string", Length: 150, NotNull: true},
				"tax_id":      MF{References: SL{"tax", "RESTRICT", "CASCADE"}, Refname: "taxcode"},
				"notes":       MF{Type: "text"},
				"webitem":     MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}},
				"inactive":    MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}},
				"deleted":     MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}}},

			"tool": IM{
				"_access":     SL{"tool"},
				"_key":        SL{"serial"},
				"_fields":     SL{"id", "serial", "description", "product_id", "toolgroup", "notes", "inactive", "deleted"},
				"id":          MF{Type: "id"},
				"serial":      MF{Type: "string", Length: 150, NotNull: true, Unique: true, Default: "nextnumber"},
				"description": MF{Type: "text", NotNull: true},
				"product_id":  MF{References: SL{"product", "RESTRICT", "CASCADE"}, Refname: "partnumber", NotNull: true},
				"toolgroup":   MF{References: SL{"groups", "RESTRICT", noAction}, Requires: IM{"toolgroup": SL{}}},
				"notes":       MF{Type: "text"},
				"inactive":    MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}},
				"deleted":     MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}}},

			"price": IM{
				"_access":     SL{"product"},
				"_key":        SL{"partnumber", "validfrom", "curr", "qty"},
				"_fields":     SL{"id", "product_id", "validfrom", "validto", "curr", "qty", "pricevalue", "discount", "calcmode", "vendorprice", "deleted"},
				"id":          MF{Type: "id"},
				"product_id":  MF{References: SL{"product", "CASCADE"}, Refname: "partnumber"},
				"validfrom":   MF{Type: "date", NotNull: true},
				"validto":     MF{Type: "date"},
				"curr":        MF{Type: "string", Length: 3, NotNull: true, Requires: IM{"curr": SL{}}},
				"qty":         MF{Type: "float", Default: float64(0)},
				"pricevalue":  MF{Type: "float", Default: float64(0), NotNull: true},
				"discount":    MF{Type: "float"},
				"calcmode":    MF{References: SL{"groups", "RESTRICT", noAction}, Requires: IM{"calcmode": SL{}}},
				"vendorprice": MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}},
				"deleted":     MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}}},

			"barcode": IM{
				"_access":     SL{"product"},
				"_key":        SL{"code"},
				"_fields":     SL{"id", "code", "product_id", "description", "barcodetype", "qty", "defcode"},
				"id":          MF{Type: "id"},
				"code":        MF{Type: "string", Length: 255, NotNull: true, Unique: true},
				"product_id":  MF{References: SL{"product", "CASCADE"}, NotNull: true, Refname: "partnumber"},
				"description": MF{Type: "text"},
				"barcodetype": MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true, Requires: IM{"barcodetype": SL{}}},
				"qty":         MF{Type: "float", Default: float64(0), NotNull: true},
				"defcode":     MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}}},

			"trans": IM{
				"_access": SL{"transtype"},
				"_key":    SL{"transnumber"},
				"_fields": SL{"id", "transnumber", "transtype", "direction", "ref_transnumber", "crdate", "transdate", "duedate", "customer_id", "employee_id",
					"department", "project_id", "place_id", "paidtype", "curr", "notax", "paid", "acrate", "notes", "intnotes", "fnote", "transtate", "closed", "deleted", "cruser_id"},
				"id":              MF{Type: "id"},
				"transnumber":     MF{Type: "string", Length: 150, NotNull: true, Unique: true, Default: "nextnumber"},
				"transtype":       MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true, Requires: IM{"transtype": SL{}}},
				"direction":       MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true, Requires: IM{"direction": SL{}}},
				"ref_transnumber": MF{Type: "string", Length: 150},
				"crdate":          MF{Type: "date", NotNull: true},
				"transdate":       MF{Type: "date", NotNull: true},
				"duedate":         MF{Type: "datetime"},
				"customer_id":     MF{References: SL{"customer", "RESTRICT", noAction}, Refname: "custnumber"},
				"employee_id":     MF{References: SL{"employee", "RESTRICT", noAction}, Refname: "empnumber"},
				"department":      MF{References: SL{"groups", "RESTRICT", noAction}, Requires: IM{"department": SL{}}},
				"project_id":      MF{References: SL{"project", "RESTRICT", noAction}, Refname: "pronumber"},
				"place_id":        MF{References: SL{"place", "RESTRICT", noAction}, Refname: "planumber"},
				"paidtype":        MF{References: SL{"groups", "RESTRICT", noAction}, Requires: IM{"paidtype": SL{}}},
				"curr":            MF{Type: "string", Length: 3, Requires: IM{"curr": SL{}}},
				"notax":           MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}},
				"paid":            MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}},
				"acrate":          MF{Type: "float", Default: float64(0)},
				"notes":           MF{Type: "text"},
				"intnotes":        MF{Type: "text"},
				"fnote":           MF{Type: "text"},
				"transtate":       MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true, Requires: IM{"transtate": SL{}}},
				"closed":          MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}},
				"deleted":         MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}},
				"cruser_id":       MF{References: SL{"employee", "RESTRICT", noAction}, Refname: "username"}},

			"item": IM{
				"_access": SL{"transtype"},
				"_key":    SL{"transnumber", "rownumber"},
				"_fields": SL{"id", "trans_id", "product_id", "unit", "qty", "fxprice", "netamount", "discount", "tax_id", "vatamount", "amount",
					"description", "deposit", "ownstock", "actionprice", "deleted"},
				"id":          MF{Type: "id"},
				"trans_id":    MF{References: SL{"trans", "CASCADE"}, Refname: "transnumber", NotNull: true},
				"product_id":  MF{References: SL{"product", "CASCADE"}, Refname: "partnumber", NotNull: true},
				"unit":        MF{Type: "string", Length: 150, NotNull: true},
				"qty":         MF{Type: "float", Default: float64(0), NotNull: true},
				"fxprice":     MF{Type: "float", Default: float64(0), NotNull: true},
				"netamount":   MF{Type: "float", Default: float64(0), NotNull: true},
				"discount":    MF{Type: "float", Default: float64(0), NotNull: true, Requires: IM{"min": float64(0), "max": float64(100)}},
				"tax_id":      MF{References: SL{"tax", "CASCADE", noAction}, Refname: "taxcode"},
				"vatamount":   MF{Type: "float", Default: float64(0), NotNull: true},
				"amount":      MF{Type: "float", Default: float64(0), NotNull: true},
				"description": MF{Type: "text", NotNull: true},
				"deposit":     MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}},
				"ownstock":    MF{Type: "float", Default: float64(0), NotNull: true},
				"actionprice": MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}},
				"deleted":     MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}}},

			"payment": IM{
				"_access":  SL{"transtype"},
				"_key":     SL{"transnumber", "rownumber"},
				"_fields":  SL{"id", "trans_id", "paiddate", "amount", "notes", "deleted"},
				"id":       MF{Type: "id"},
				"trans_id": MF{References: SL{"trans", "CASCADE"}, Refname: "transnumber"},
				"paiddate": MF{Type: "date", NotNull: true},
				"amount":   MF{Type: "float", Default: float64(0), NotNull: true},
				"notes":    MF{Type: "text"},
				"deleted":  MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}}},

			"movement": IM{
				"_access":      SL{"transtype"},
				"_key":         SL{"transnumber", "rownumber"},
				"_fields":      SL{"id", "trans_id", "shippingdate", "movetype", "product_id", "tool_id", "place_id", "qty", "notes", "shared", "deleted"},
				"id":           MF{Type: "id"},
				"trans_id":     MF{References: SL{"trans", "CASCADE"}, Refname: "transnumber"},
				"shippingdate": MF{Type: "datetime", NotNull: true},
				"movetype":     MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true, Requires: IM{"movetype": SL{}}},
				"product_id":   MF{References: SL{"product", "RESTRICT", noAction}, Refname: "partnumber"},
				"tool_id":      MF{References: SL{"tool", "RESTRICT", noAction}, Refname: "serial"},
				"place_id":     MF{References: SL{"place", "RESTRICT", noAction}, Refname: "planumber"},
				"qty":          MF{Type: "float", Default: float64(0), NotNull: true},
				"notes":        MF{Type: "text"},
				"shared":       MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}},
				"deleted":      MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}}},

			"pattern": IM{
				"_access":     SL{"setting"},
				"_key":        SL{"description"},
				"_fields":     SL{"id", "description", "transtype", "notes", "defpattern", "deleted"},
				"id":          MF{Type: "id"},
				"description": MF{Type: "string", Length: 150, NotNull: true, Unique: true},
				"transtype":   MF{References: SL{"groups", "RESTRICT", noAction}, NotNull: true, Requires: IM{"transtype": SL{}}},
				"notes":       MF{Type: "text"},
				"defpattern":  MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}},
				"deleted":     MF{Type: "integer", Default: int64(0), NotNull: true, Requires: IM{"bool": true}}}},

		"index": map[string]MI{
			"groups_namevalue_idx":  {Model: "groups", Fields: SL{"groupname", "groupvalue"}, Unique: true},
			"groups_groupname_idx":  {Model: "groups", Fields: SL{"groupname"}, Unique: false},
			"groups_groupvalue_idx": {Model: "groups", Fields: SL{"groupvalue"}, Unique: false},
			"groups_inactive_idx":   {Model: "groups", Fields: SL{"inactive"}, Unique: false},
			"groups_deleted_idx":    {Model: "groups", Fields: SL{"deleted"}, Unique: false},

			"menucmd_menukey_idx": {Model: "ui_menu", Fields: SL{"menukey"}, Unique: true},
			"menucmd_modul_idx":   {Model: "ui_menu", Fields: SL{"modul"}, Unique: false},

			"menufields_menu_idx": {Model: "ui_menufields", Fields: SL{"menu_id"}, Unique: false},

			"message_pk_idx":        {Model: "ui_message", Fields: SL{"secname", "fieldname", "lang"}, Unique: true},
			"message_fieldname_idx": {Model: "ui_message", Fields: SL{"fieldname"}, Unique: false},
			"message_lang_idx":      {Model: "ui_message", Fields: SL{"lang"}, Unique: false},
			"message_secname_idx":   {Model: "ui_message", Fields: SL{"secname"}, Unique: false},

			"report_reportkey_idx":  {Model: "ui_report", Fields: SL{"reportkey"}, Unique: true},
			"report_filetype_idx":   {Model: "ui_report", Fields: SL{"filetype"}, Unique: false},
			"report_reporttype_idx": {Model: "ui_report", Fields: SL{"nervatype"}, Unique: false},

			"employee_empnumber_idx": {Model: "employee", Fields: SL{"empnumber"}, Unique: true},
			"employee_username_idx":  {Model: "employee", Fields: SL{"username"}, Unique: true},
			"employee_inactiv_idx":   {Model: "employee", Fields: SL{"inactive"}, Unique: false},
			"employee_deleted_idx":   {Model: "employee", Fields: SL{"deleted"}, Unique: false},

			"printqueue_nervatype_idx": {Model: "ui_printqueue", Fields: SL{"nervatype"}, Unique: false},
			"printqueue_usename_idx":   {Model: "ui_printqueue", Fields: SL{"employee_id"}, Unique: false},

			"idx_userconfig_pk":           {Model: "ui_userconfig", Fields: SL{"employee_id", "cfgroup", "cfname"}, Unique: false},
			"idx_userconfig_ec":           {Model: "ui_userconfig", Fields: SL{"employee_id", "cfgroup"}, Unique: false},
			"idx_userconfig_employee_ide": {Model: "ui_userconfig", Fields: SL{"employee_id"}, Unique: false},

			"idx_link_nervatype_1": {Model: "link", Fields: SL{"nervatype_1"}, Unique: false},
			"idx_link_ref_id_1":    {Model: "link", Fields: SL{"ref_id_1"}, Unique: false},
			"idx_link_nervatype_2": {Model: "link", Fields: SL{"nervatype_2"}, Unique: false},
			"idx_link_ref_id_2":    {Model: "link", Fields: SL{"ref_id_2"}, Unique: false},
			"idx_link_deleted":     {Model: "link", Fields: SL{"deleted"}, Unique: false},

			"idx_audit_pk":        {Model: "ui_audit", Fields: SL{"usergroup", "nervatype", "subtype"}, Unique: true},
			"idx_audit_usergroup": {Model: "ui_audit", Fields: SL{"usergroup"}, Unique: false},

			"deffield_fieldname_idx":    {Model: "deffield", Fields: SL{"fieldname"}, Unique: true},
			"deffield_nervatype_id_idx": {Model: "deffield", Fields: SL{"nervatype", "subtype"}, Unique: false},
			"deffield_deleted_idx":      {Model: "deffield", Fields: SL{"deleted"}, Unique: false},

			"fieldvalue_fieldname_idx": {Model: "fieldvalue", Fields: SL{"fieldname"}, Unique: false},
			"fieldvalue_ref_id_idx":    {Model: "fieldvalue", Fields: SL{"ref_id"}, Unique: false},

			"log_logstate_idx":  {Model: "log", Fields: SL{"logstate"}, Unique: false},
			"log_nervatype_idx": {Model: "log", Fields: SL{"nervatype, ref_id"}, Unique: false},

			"numberdef_numberkey_idx": {Model: "numberdef", Fields: SL{"numberkey"}, Unique: true},

			"address_nervatype_idx": {Model: "address", Fields: SL{"nervatype", "ref_id"}, Unique: false},
			"address_deleted_idx":   {Model: "address", Fields: SL{"deleted"}, Unique: false},

			"contact_nervatype_idx": {Model: "contact", Fields: SL{"nervatype, ref_id"}, Unique: false},
			"contact_deleted_idx":   {Model: "contact", Fields: SL{"deleted"}, Unique: false},

			"event_calnumber_idx":  {Model: "event", Fields: SL{"calnumber"}, Unique: true},
			"event_fromdate_idx":   {Model: "event", Fields: SL{"fromdate"}, Unique: false},
			"event_eventgroup_idx": {Model: "event", Fields: SL{"eventgroup"}, Unique: false},
			"event_nervatype_idx":  {Model: "event", Fields: SL{"nervatype"}, Unique: false},
			"event_ref_idx":        {Model: "event", Fields: SL{"ref_id"}, Unique: false},
			"event_deleted_idx":    {Model: "event", Fields: SL{"deleted"}, Unique: false},
			"event_uid_idx":        {Model: "event", Fields: SL{"uid"}, Unique: false},

			"customer_custnumber_idx": {Model: "customer", Fields: SL{"custnumber"}, Unique: true},
			"customer_custtype_idx":   {Model: "customer", Fields: SL{"custtype"}, Unique: false},
			"customer_inactive_idx":   {Model: "customer", Fields: SL{"inactive"}, Unique: false},
			"customer_deleted_idx":    {Model: "customer", Fields: SL{"deleted"}, Unique: false},
			"customer_custname_idx":   {Model: "customer", Fields: SL{"custname"}, Unique: false},

			"project_pronumber_idx":   {Model: "project", Fields: SL{"pronumber"}, Unique: true},
			"project_customer_id_idx": {Model: "project", Fields: SL{"customer_id"}, Unique: false},
			"project_inactive_idx":    {Model: "project", Fields: SL{"inactive"}, Unique: false},
			"project_deleted_idx":     {Model: "project", Fields: SL{"deleted"}, Unique: false},

			"currency_curr_idx": {Model: "currency", Fields: SL{"curr"}, Unique: true},

			"place_planumber_idx": {Model: "place", Fields: SL{"planumber"}, Unique: true},
			"place_placetype_idx": {Model: "place", Fields: SL{"placetype"}, Unique: false},
			"place_deleted_idx":   {Model: "place", Fields: SL{"deleted"}, Unique: false},

			"rate_curr_idx":     {Model: "rate", Fields: SL{"curr"}, Unique: false},
			"rate_ref_idx":      {Model: "rate", Fields: SL{"ratedate", "curr", "place_id", "ratetype"}, Unique: false},
			"rate_ratedate_idx": {Model: "rate", Fields: SL{"ratedate"}, Unique: false},
			"rate_deleted_idx":  {Model: "rate", Fields: SL{"deleted"}, Unique: false},

			"tax_taxcode_idx":  {Model: "tax", Fields: SL{"taxcode"}, Unique: true},
			"tax_inactive_idx": {Model: "tax", Fields: SL{"inactive"}, Unique: false},

			"product_partnumber_idx": {Model: "product", Fields: SL{"partnumber"}, Unique: true},
			"product_tax_id_idx":     {Model: "product", Fields: SL{"tax_id"}, Unique: false},
			"product_inactive_idx":   {Model: "product", Fields: SL{"inactive"}, Unique: false},
			"product_deleted_idx":    {Model: "product", Fields: SL{"deleted"}, Unique: false},
			"product_protype_idx":    {Model: "product", Fields: SL{"protype"}, Unique: false},
			"product_webitem_idx":    {Model: "product", Fields: SL{"webitem"}, Unique: false},

			"tool_serial_idx":     {Model: "tool", Fields: SL{"serial"}, Unique: true},
			"tool_groups_id_idx":  {Model: "tool", Fields: SL{"toolgroup"}, Unique: false},
			"tool_inactive_idx":   {Model: "tool", Fields: SL{"inactive"}, Unique: false},
			"tool_deleted_idx":    {Model: "tool", Fields: SL{"deleted"}, Unique: false},
			"tool_product_id_idx": {Model: "tool", Fields: SL{"product_id"}, Unique: false},

			"price_curr_idx":       {Model: "price", Fields: SL{"curr"}, Unique: false},
			"price_product_id_idx": {Model: "price", Fields: SL{"product_id"}, Unique: false},
			"price_validfrom_idx":  {Model: "price", Fields: SL{"validfrom"}, Unique: false},
			"price_validto_idx":    {Model: "price", Fields: SL{"validto"}, Unique: false},
			"price_vendor_idx":     {Model: "price", Fields: SL{"vendorprice"}, Unique: false},
			"price_deleted_idx":    {Model: "price", Fields: SL{"deleted"}, Unique: false},

			"barcode_code_idx":     {Model: "barcode", Fields: SL{"code"}, Unique: true},
			"barcode_defcode_idx":  {Model: "barcode", Fields: SL{"defcode"}, Unique: false},
			"barcode_parts_id_idx": {Model: "barcode", Fields: SL{"product_id"}, Unique: false},

			"trans_transnumber_idx":     {Model: "trans", Fields: SL{"transnumber"}, Unique: true},
			"trans_curr_idx":            {Model: "trans", Fields: SL{"curr"}, Unique: false},
			"trans_duedate_idx":         {Model: "trans", Fields: SL{"duedate"}, Unique: false},
			"trans_paidtype_idx":        {Model: "trans", Fields: SL{"paidtype"}, Unique: false},
			"trans_project_id_idx":      {Model: "trans", Fields: SL{"project_id"}, Unique: false},
			"trans_employee_id_idx":     {Model: "trans", Fields: SL{"employee_id"}, Unique: false},
			"trans_cruser_idx":          {Model: "trans", Fields: SL{"cruser_id"}, Unique: false},
			"trans_customer_idx":        {Model: "trans", Fields: SL{"customer_id"}, Unique: false},
			"trans_department_idx":      {Model: "trans", Fields: SL{"department"}, Unique: false},
			"trans_transtate_idx":       {Model: "trans", Fields: SL{"transtate"}, Unique: false},
			"trans_transdate_idx":       {Model: "trans", Fields: SL{"transdate"}, Unique: false},
			"trans_crdate_idx":          {Model: "trans", Fields: SL{"crdate"}, Unique: false},
			"trans_ref_transnumber_idx": {Model: "trans", Fields: SL{"ref_transnumber"}, Unique: false},
			"trans_transtype_idx":       {Model: "trans", Fields: SL{"transtype"}, Unique: false},
			"trans_direction_idx":       {Model: "trans", Fields: SL{"direction"}, Unique: false},

			"item_product_id_idx": {Model: "item", Fields: SL{"product_id"}, Unique: false},
			"item_tax_id_idx":     {Model: "item", Fields: SL{"tax_id"}, Unique: false},
			"item_trans_id_idx":   {Model: "item", Fields: SL{"trans_id"}, Unique: false},
			"item_deleted_idx":    {Model: "item", Fields: SL{"deleted"}, Unique: false},

			"payment_paiddate_idx": {Model: "payment", Fields: SL{"paiddate"}, Unique: false},
			"payment_trans_id_idx": {Model: "payment", Fields: SL{"trans_id"}, Unique: false},
			"payment_deleted_idx":  {Model: "payment", Fields: SL{"deleted"}, Unique: false},

			"movement_product_id_idx": {Model: "movement", Fields: SL{"product_id"}, Unique: false},
			"movement_tool_id_idx":    {Model: "movement", Fields: SL{"tool_id"}, Unique: false},
			"movement_shipdate_idx":   {Model: "movement", Fields: SL{"shippingdate"}, Unique: false},
			"movement_trans_id_idx":   {Model: "movement", Fields: SL{"trans_id"}, Unique: false},
			"movement_place_id_idx":   {Model: "movement", Fields: SL{"place_id"}, Unique: false},
			"movement_movetype_idx":   {Model: "movement", Fields: SL{"movetype"}, Unique: false},
			"movement_deleted_idx":    {Model: "movement", Fields: SL{"deleted"}, Unique: false},

			"pattern_description_idx": {Model: "pattern", Fields: SL{"description"}, Unique: true},
			"pattern_transtype_idx":   {Model: "pattern", Fields: SL{"transtype"}, Unique: false},
			"pattern_deleted_idx":     {Model: "rate", Fields: SL{"deleted"}, Unique: false}},

		"data": map[string][]IM{
			"groups": {
				//aggretype
				{"groupname": "aggretype", "groupvalue": "<>"},
				{"groupname": "aggretype", "groupvalue": "avg"},
				{"groupname": "aggretype", "groupvalue": "count"},
				{"groupname": "aggretype", "groupvalue": "sum"},
				//nervatype
				{"groupname": "nervatype", "groupvalue": "address"},
				{"groupname": "nervatype", "groupvalue": "audit"},
				{"groupname": "nervatype", "groupvalue": "barcode"},
				{"groupname": "nervatype", "groupvalue": "contact"},
				{"groupname": "nervatype", "groupvalue": "currency"},
				{"groupname": "nervatype", "groupvalue": "customer"},
				{"groupname": "nervatype", "groupvalue": "deffield"},
				{"groupname": "nervatype", "groupvalue": "employee"},
				{"groupname": "nervatype", "groupvalue": "event"},
				{"groupname": "nervatype", "groupvalue": "groups"},
				{"groupname": "nervatype", "groupvalue": "item"},
				{"groupname": "nervatype", "groupvalue": "link"},
				{"groupname": "nervatype", "groupvalue": "log"},
				{"groupname": "nervatype", "groupvalue": "menu"},
				{"groupname": "nervatype", "groupvalue": "movement"},
				{"groupname": "nervatype", "groupvalue": "numberdef"},
				{"groupname": "nervatype", "groupvalue": "pattern"},
				{"groupname": "nervatype", "groupvalue": "payment"},
				{"groupname": "nervatype", "groupvalue": "place"},
				{"groupname": "nervatype", "groupvalue": "price"},
				{"groupname": "nervatype", "groupvalue": "product"},
				{"groupname": "nervatype", "groupvalue": "project"},
				{"groupname": "nervatype", "groupvalue": "rate"},
				{"groupname": "nervatype", "groupvalue": "report"},
				{"groupname": "nervatype", "groupvalue": "tax"},
				{"groupname": "nervatype", "groupvalue": "tool"},
				{"groupname": "nervatype", "groupvalue": "trans"},
				{"groupname": "nervatype", "groupvalue": "setting"},
				//fieldtype
				{"groupname": "fieldtype", "groupvalue": "bool"},
				{"groupname": "fieldtype", "groupvalue": "date"},
				{"groupname": "fieldtype", "groupvalue": "time"},
				{"groupname": "fieldtype", "groupvalue": "float"},
				{"groupname": "fieldtype", "groupvalue": "integer"},
				{"groupname": "fieldtype", "groupvalue": "string"},
				{"groupname": "fieldtype", "groupvalue": "valuelist"},
				{"groupname": "fieldtype", "groupvalue": "notes"},
				{"groupname": "fieldtype", "groupvalue": "filter"},
				{"groupname": "fieldtype", "groupvalue": "urlink"},
				{"groupname": "fieldtype", "groupvalue": "password"},
				{"groupname": "fieldtype", "groupvalue": "customer"},
				{"groupname": "fieldtype", "groupvalue": "tool"},
				{"groupname": "fieldtype", "groupvalue": "transitem"},
				{"groupname": "fieldtype", "groupvalue": "transmovement"},
				{"groupname": "fieldtype", "groupvalue": "transpayment"},
				{"groupname": "fieldtype", "groupvalue": "product"},
				{"groupname": "fieldtype", "groupvalue": "project"},
				{"groupname": "fieldtype", "groupvalue": "employee"},
				{"groupname": "fieldtype", "groupvalue": "place"},
				//filetype
				{"groupname": "filetype", "groupvalue": "csv", "description": "Comma-separated values"},
				{"groupname": "filetype", "groupvalue": "pdf", "description": "Nervatura Report"},
				//transtype
				{"groupname": "transtype", "groupvalue": "invoice"},
				{"groupname": "transtype", "groupvalue": "receipt"},
				{"groupname": "transtype", "groupvalue": "order"},
				{"groupname": "transtype", "groupvalue": "offer"},
				{"groupname": "transtype", "groupvalue": "worksheet"},
				{"groupname": "transtype", "groupvalue": "rent"},
				{"groupname": "transtype", "groupvalue": "delivery"},
				{"groupname": "transtype", "groupvalue": "inventory"},
				{"groupname": "transtype", "groupvalue": "waybill"},
				{"groupname": "transtype", "groupvalue": "production"},
				{"groupname": "transtype", "groupvalue": "formula"},
				{"groupname": "transtype", "groupvalue": "bank"},
				{"groupname": "transtype", "groupvalue": "cash"},
				//direction
				{"groupname": "direction", "groupvalue": "out"},
				{"groupname": "direction", "groupvalue": "in"},
				{"groupname": "direction", "groupvalue": "transfer"},
				//wheretype
				{"groupname": "wheretype", "groupvalue": "where"},
				{"groupname": "wheretype", "groupvalue": "having"},
				{"groupname": "wheretype", "groupvalue": "in"},
				//barcodetype
				{"groupname": "barcodetype", "groupvalue": "CODE_128", "description": "CODE128"},
				{"groupname": "barcodetype", "groupvalue": "CODE_39", "description": "CODE39"},
				{"groupname": "barcodetype", "groupvalue": "EAN_13", "description": "EAN13"},
				{"groupname": "barcodetype", "groupvalue": "EAN_8", "description": "EAN8"},
				{"groupname": "barcodetype", "groupvalue": "ITF", "description": "ITF/i2of5"},
				{"groupname": "barcodetype", "groupvalue": "QR", "description": "QR code"},
				//ratetype
				{"groupname": "ratetype", "groupvalue": "rate"},
				{"groupname": "ratetype", "groupvalue": "buy"},
				{"groupname": "ratetype", "groupvalue": "sell"},
				{"groupname": "ratetype", "groupvalue": "average"},
				//filtertype
				{"groupname": "filtertype", "groupvalue": "=="},
				{"groupname": "filtertype", "groupvalue": "=N"},
				{"groupname": "filtertype", "groupvalue": "!="},
				{"groupname": "filtertype", "groupvalue": ">="},
				{"groupname": "filtertype", "groupvalue": "<="},
				//movetype
				{"groupname": "movetype", "groupvalue": "inventory"},
				{"groupname": "movetype", "groupvalue": "tool"},
				{"groupname": "movetype", "groupvalue": "plan"},
				{"groupname": "movetype", "groupvalue": "head"},
				//transtate
				{"groupname": "transtate", "groupvalue": "ok"},
				{"groupname": "transtate", "groupvalue": "new"},
				{"groupname": "transtate", "groupvalue": "back"},
				//logstate
				{"groupname": "logstate", "groupvalue": "update"},
				{"groupname": "logstate", "groupvalue": "closed"},
				{"groupname": "logstate", "groupvalue": "deleted"},
				{"groupname": "logstate", "groupvalue": "print"},
				{"groupname": "logstate", "groupvalue": "login"},
				{"groupname": "logstate", "groupvalue": "logout"},
				//usergroup
				{"groupname": "usergroup", "groupvalue": "admin", "description": "Admin"},
				{"groupname": "usergroup", "groupvalue": "user", "description": "Employee"},
				{"groupname": "usergroup", "groupvalue": "guest", "description": "Guest"},
				{"groupname": "usergroup", "groupvalue": "demo", "description": "Demo"},
				//inputfilter
				{"groupname": "inputfilter", "groupvalue": "disabled"},
				{"groupname": "inputfilter", "groupvalue": "readonly"},
				{"groupname": "inputfilter", "groupvalue": "update"},
				{"groupname": "inputfilter", "groupvalue": "all"},
				//transfilter
				{"groupname": "transfilter", "groupvalue": "own"},
				{"groupname": "transfilter", "groupvalue": "usergroup"},
				{"groupname": "transfilter", "groupvalue": "all"},
				//protype
				{"groupname": "protype", "groupvalue": "item"},
				{"groupname": "protype", "groupvalue": "service"},
				//custtype
				{"groupname": "custtype", "groupvalue": "own"},
				{"groupname": "custtype", "groupvalue": "company"},
				{"groupname": "custtype", "groupvalue": "private"},
				{"groupname": "custtype", "groupvalue": "other"},
				//calcmode
				{"groupname": "calcmode", "groupvalue": "ded", "description": "deduction (%)"},
				{"groupname": "calcmode", "groupvalue": "add", "description": "adding (%)"},
				{"groupname": "calcmode", "groupvalue": "amo", "description": "amount (+/-)"},
				//paidtype
				{"groupname": "paidtype", "groupvalue": "cash", "description": "cash"},
				{"groupname": "paidtype", "groupvalue": "transfer", "description": "transfer"},
				{"groupname": "paidtype", "groupvalue": "credit_card", "description": "credit card"},
				//placetype
				{"groupname": "placetype", "groupvalue": "bank"},
				{"groupname": "placetype", "groupvalue": "cash"},
				{"groupname": "placetype", "groupvalue": "warehouse"},
				{"groupname": "placetype", "groupvalue": "other"},
				//method
				{"groupname": "method", "groupvalue": "get", "description": "GET"},
				{"groupname": "method", "groupvalue": "post", "description": "POST"},
				//orientation
				{"groupname": "orientation", "groupvalue": "P", "description": "Portrait"},
				{"groupname": "orientation", "groupvalue": "L", "description": "Landscape"},
				//papersize
				{"groupname": "papersize", "groupvalue": "a3", "description": "A3"},
				{"groupname": "papersize", "groupvalue": "a4", "description": "A4"},
				{"groupname": "papersize", "groupvalue": "a5", "description": "A5"},
				{"groupname": "papersize", "groupvalue": "letter", "description": "Letter"},
				{"groupname": "papersize", "groupvalue": "legal", "description": "Legal"}},

			"currency": {
				{"curr": "EUR", "description": "euro", "digit": 2, "defrate": 0, "cround": 0},
				{"curr": "USD", "description": "dollar", "digit": 2, "defrate": 0, "cround": 0}},

			"customer": {
				{"custtype": SL{"groups", "custtype", "own"}, "custnumber": "HOME", "custname": "COMPANY NAME",
					"taxnumber": "12345678-1-12"}},

			"employee": {
				{"empnumber": "admin", "username": "admin", "usergroup": SL{"groups", "usergroup", "admin"}}},

			"address": {
				{"nervatype": SL{"groups", "nervatype", "customer"}, "ref_id": SL{"customer", "HOME"}},
				{"nervatype": SL{"groups", "nervatype", "employee"}, "ref_id": SL{"employee", "admin"}}},

			"contact": {
				{"nervatype": SL{"groups", "nervatype", "employee"}, "ref_id": SL{"employee", "admin"}}},

			"place": {
				{"planumber": "bank", "placetype": SL{"groups", "placetype", "bank"}, "description": "Bank", "curr": "EUR"},
				{"planumber": "cash", "placetype": SL{"groups", "placetype", "cash"}, "description": "Cash", "curr": "EUR"},
				{"planumber": "warehouse", "placetype": SL{"groups", "placetype", "warehouse"}, "description": "Warehouse"}},

			"tax": {
				{"description": "VAT 0%", "rate": 0, "taxcode": "0%"},
				{"description": "VAT 5%", "rate": 0.05, "taxcode": "5%"},
				{"description": "VAT 10%", "rate": 0.1, "taxcode": "10%"},
				{"description": "VAT 15%", "rate": 0.15, "taxcode": "15%"},
				{"description": "VAT 20%", "rate": 0.2, "taxcode": "20%"},
				{"description": "VAT 25%", "rate": 0.25, "taxcode": "25%"}},

			"numberdef": {
				{"numberkey": "bank_transfer", "prefix": "BANK", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "statement", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "calnumber", "prefix": "EVT", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "event", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "cash", "prefix": "CASH", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "cash payment", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "custnumber", "prefix": "CUS", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "customer", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "delivery_in", "prefix": "DELIN", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "delivery in", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "delivery_out", "prefix": "DELOU", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "delivery out", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "delivery_transfer", "prefix": "DELTF", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "delivery transfer", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "empnumber", "prefix": "EMP", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "employee", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "formula_transfer", "prefix": "FRM", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "formula", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "inventory_transfer", "prefix": "VENDL", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "inventory delivery", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "invoice_in", "prefix": "INVVD", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "vendor invoice", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "invoice_out", "prefix": "INVCT", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "customer invoice", "visible": 1, "readonly": 1, "orderby": 0},
				{"numberkey": "offer_in", "prefix": "OFFVD", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "vendor offer", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "offer_out", "prefix": "OFFCT", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "customer offer", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "order_in", "prefix": "ORDVD", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "vendor order", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "order_out", "prefix": "ORDCT", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "customer order", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "partnumber", "prefix": "PRO", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "poduct", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "production_transfer", "prefix": "MAKE", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "production", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "pronumber", "prefix": "PRJ", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "project", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "planumber", "prefix": "PLA", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "place", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "receipt_in", "prefix": "RECVD", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "vendor receipt", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "receipt_out", "prefix": "RECCT", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "customer receipt", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "rent_in", "prefix": "RENVD", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "vendor rent", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "rent_out", "prefix": "RENCT", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "customer rent", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "serial", "prefix": "SER", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "tool", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "waybill", "prefix": "MOVE", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "tool movement", "visible": 1, "readonly": 0, "orderby": 0},
				{"numberkey": "worksheet_out", "prefix": "WORK", "curvalue": 0, "isyear": 1, "sep": "/", "len": 5,
					"description": "worksheet", "visible": 1, "readonly": 0, "orderby": 0}},

			"deffield": {
				{"fieldname": "trans_transitem_link", "nervatype": SL{"groups", "nervatype", "trans"},
					"fieldtype":   SL{"groups", "fieldtype", "transitem"},
					"description": "Ref.No.", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "trans_transcast", "nervatype": SL{"groups", "nervatype", "trans"},
					"fieldtype":   SL{"groups", "fieldtype", "valuelist"},
					"description": "transaction special state", "valuelist": "normal|cancellation|amendment",
					"addnew": 1, "visible": 0, "readonly": 1},
				{"fieldname": "trans_custinvoice_compname", "nervatype": SL{"groups", "nervatype", "trans"},
					"subtype": SL{"groups", "transtype", "invoice"}, "fieldtype": SL{"groups", "fieldtype", "string"},
					"description": "customer invoice company name", "addnew": 1, "visible": 0, "readonly": 1},
				{"fieldname": "trans_custinvoice_compaddress", "nervatype": SL{"groups", "nervatype", "trans"},
					"subtype": SL{"groups", "transtype", "invoice"}, "fieldtype": SL{"groups", "fieldtype", "string"},
					"description": "customer invoice company address", "addnew": 1, "visible": 0, "readonly": 1},
				{"fieldname": "trans_custinvoice_comptax", "nervatype": SL{"groups", "nervatype", "trans"},
					"subtype": SL{"groups", "transtype", "invoice"}, "fieldtype": SL{"groups", "fieldtype", "string"},
					"description": "customer invoice company taxnumber", "addnew": 1, "visible": 0, "readonly": 1},
				{"fieldname": "trans_custinvoice_custname", "nervatype": SL{"groups", "nervatype", "trans"},
					"subtype": SL{"groups", "transtype", "invoice"}, "fieldtype": SL{"groups", "fieldtype", "string"},
					"description": "customer invoice customer name", "addnew": 1, "visible": 0, "readonly": 1},
				{"fieldname": "trans_custinvoice_custaddress", "nervatype": SL{"groups", "nervatype", "trans"},
					"subtype": SL{"groups", "transtype", "invoice"}, "fieldtype": SL{"groups", "fieldtype", "string"},
					"description": "customer invoice customer address", "addnew": 1, "visible": 0, "readonly": 1},
				{"fieldname": "trans_custinvoice_custtax", "nervatype": SL{"groups", "nervatype", "trans"},
					"subtype": SL{"groups", "transtype", "invoice"}, "fieldtype": SL{"groups", "fieldtype", "string"},
					"description": "customer invoice customer taxnumber", "addnew": 1, "visible": 0, "readonly": 1},
				{"fieldname": "trans_wsdistance", "nervatype": SL{"groups", "nervatype", "trans"},
					"subtype": SL{"groups", "transtype", "worksheet"}, "fieldtype": SL{"groups", "fieldtype", "float"},
					"description": "worksheet distance", "addnew": 1, "visible": 0, "readonly": 1},
				{"fieldname": "trans_wsrepair", "nervatype": SL{"groups", "nervatype", "trans"},
					"subtype": SL{"groups", "transtype", "worksheet"}, "fieldtype": SL{"groups", "fieldtype", "float"},
					"description": "worksheet repair time (hour)", "addnew": 1, "visible": 0, "readonly": 1},
				{"fieldname": "trans_wstotal", "nervatype": SL{"groups", "nervatype", "trans"},
					"subtype": SL{"groups", "transtype", "worksheet"}, "fieldtype": SL{"groups", "fieldtype", "float"},
					"description": "worksheet total time (hour)", "addnew": 1, "visible": 0, "readonly": 1},
				{"fieldname": "trans_wsnote", "nervatype": SL{"groups", "nervatype", "trans"},
					"subtype": SL{"groups", "transtype", "worksheet"}, "fieldtype": SL{"groups", "fieldtype", "string"},
					"description": "worksheet justification", "addnew": 1, "visible": 0, "readonly": 1},
				{"fieldname": "trans_reholiday", "nervatype": SL{"groups", "nervatype", "trans"},
					"subtype": SL{"groups", "transtype", "rent"}, "fieldtype": SL{"groups", "fieldtype", "float"},
					"description": "rent holidays", "addnew": 1, "visible": 0, "readonly": 1},
				{"fieldname": "trans_rebadtool", "nervatype": SL{"groups", "nervatype", "trans"},
					"subtype": SL{"groups", "transtype", "rent"}, "fieldtype": SL{"groups", "fieldtype", "float"},
					"description": "rent bad machine", "addnew": 1, "visible": 0, "readonly": 1},
				{"fieldname": "trans_reother", "nervatype": SL{"groups", "nervatype", "trans"},
					"subtype": SL{"groups", "transtype", "rent"}, "fieldtype": SL{"groups", "fieldtype", "float"},
					"description": "rent other non-eligible", "addnew": 1, "visible": 0, "readonly": 1},
				{"fieldname": "trans_rentnote", "nervatype": SL{"groups", "nervatype", "trans"},
					"subtype": SL{"groups", "transtype", "rent"}, "fieldtype": SL{"groups", "fieldtype", "string"},
					"description": "rent justification", "addnew": 1, "visible": 0, "readonly": 1},
				{"fieldname": "link_qty", "nervatype": SL{"groups", "nervatype", "link"},
					"fieldtype":   SL{"groups", "fieldtype", "float"},
					"description": "link qty value", "addnew": 0, "visible": 0, "readonly": 0},
				{"fieldname": "link_rate", "nervatype": SL{"groups", "nervatype", "link"},
					"fieldtype":   SL{"groups", "fieldtype", "float"},
					"description": "link rate value", "addnew": 0, "visible": 0, "readonly": 0},
				{"fieldname": "product_custpartnumber", "nervatype": SL{"groups", "nervatype", "product"},
					"fieldtype":   SL{"groups", "fieldtype", "customer"},
					"description": "Customer Product No. (pricing)", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "product_alternative", "nervatype": SL{"groups", "nervatype", "product"},
					"fieldtype":   SL{"groups", "fieldtype", "product"},
					"description": "Alternative Product", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "product_element", "nervatype": SL{"groups", "nervatype", "product"},
					"fieldtype":   SL{"groups", "fieldtype", "product"},
					"description": "Element Product", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "default_bank", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "string"},
					"description": "default bank place no.", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "default_chest", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "string"},
					"description": "default petty cash place no.", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "default_warehouse", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "string"},
					"description": "default warehouse place no.", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "default_country", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "string"},
					"description": "default country", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "default_lang", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "string"},
					"description": "default language", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "default_currency", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "string"},
					"description": "default currency", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "default_deadline", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "integer"},
					"description": "default deadline (payment)", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "default_paidtype", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "string"},
					"description": "default paidtype", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "default_unit", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "string"},
					"description": "default unit", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "default_taxcode", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "string"},
					"description": "default taxcode", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "false_bool", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "string"},
					"description": "false string", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "invoice_copy", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "integer"},
					"description": "invoice copy", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "transyear", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "integer"},
					"description": "business year", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "true_bool", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "string"},
					"description": "true string", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "audit_control", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "bool"},
					"description": "set audit control", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "invoice_from_inventory", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "bool"},
					"description": "invoice from inventory(yes) or order items(no)", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "set_outstock_enabled", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "bool"},
					"description": "enabled inventory deficit", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "set_stocklimit_warning", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "bool"},
					"description": "inventory stock limit warning", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "not_logical_delete", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "bool"},
					"description": "enabled trans deletion", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "show_partcustomer", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "bool"},
					"description": "show customer number column", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "show_partnumber", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "bool"},
					"description": "show product number column", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "log_deleted", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "bool"},
					"description": "enabled deleted log", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "log_update", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "bool"},
					"description": "enabled update log", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "log_trans_closed", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "bool"},
					"description": "enabled trans closed log", "addnew": 0, "visible": 1, "readonly": 0},
				{"fieldname": "log_login", "nervatype": SL{"groups", "nervatype", "setting"},
					"fieldtype":   SL{"groups", "fieldtype", "bool"},
					"description": "enabled userlogin", "addnew": 0, "visible": 1, "readonly": 0}},

			"fieldvalue": {
				{"fieldname": "default_bank", "value": "bank"},
				{"fieldname": "default_chest", "value": "cash"},
				{"fieldname": "default_warehouse", "value": "warehouse"},
				{"fieldname": "default_country", "value": "EU"},
				{"fieldname": "default_lang", "value": "en"},
				{"fieldname": "default_currency", "value": "EUR"},
				{"fieldname": "default_deadline", "value": "8"},
				{"fieldname": "default_paidtype", "value": "transfer"},
				{"fieldname": "default_unit", "value": "piece"},
				{"fieldname": "default_taxcode", "value": "20%"},
				{"fieldname": "false_bool", "value": "FALSE"},
				{"fieldname": "invoice_copy", "value": "2"},
				{"fieldname": "transyear", "value": time.Now().Format("2006")},
				{"fieldname": "true_bool", "value": "TRUE"},
				{"fieldname": "audit_control", "value": "false"},
				{"fieldname": "invoice_from_inventory", "value": "false"},
				{"fieldname": "set_outstock_enabled", "value": "true"},
				{"fieldname": "set_stocklimit_warning", "value": "false"},
				{"fieldname": "not_logical_delete", "value": "false"},
				{"fieldname": "show_partcustomer", "value": "false"},
				{"fieldname": "show_partnumber", "value": "false"},
				{"fieldname": "log_deleted", "value": "true"},
				{"fieldname": "log_update", "value": "false"},
				{"fieldname": "log_trans_closed", "value": "false"},
				{"fieldname": "log_login", "value": "false"}}},
	}
}
