/*
This file is part of the Nervatura Framework
http://www.nervatura.com
Copyright © 2011-2017, Csaba Kappel
License: LGPLv3
https://raw.githubusercontent.com/nervatura/nervatura/master/LICENSE
*/

module.exports = {
  groups:[
	  {"groupname":"department","groupvalue":"sales","description":"Sample department"},
	  {"groupname":"department","groupvalue":"logistics","description":"Sample department"},
	  {"groupname":"department","groupvalue":"production","description":"Sample department"},
    {"groupname":"eventgroup","groupvalue":"visit"},
    {"groupname":"eventgroup","groupvalue":"pricing"},
    {"groupname":"eventgroup","groupvalue":"car"}],
  customer:{
    deffield:[
      {"fieldname":"sample_customer_float","nervatype":"customer","fieldtype":"float",
      "description":"Sample float","visible":1},
      {"fieldname":"sample_customer_date","nervatype":"customer","fieldtype":"date",
      "description":"Sample date","visible":1},
      {"fieldname":"sample_customer_valuelist","nervatype":"customer","fieldtype":"valuelist",
      "description":"Sample valuelist","valuelist":"blue~yellow~white~brown~red","visible":1},
      {"fieldname":"sample_customer_reference","nervatype":"customer","fieldtype":"customer",
      "description":"Sample customer","visible":1},
      {"fieldname":"company_page","nervatype":"event","fieldtype":"urlink","description":"Company page","visible":1}],
    customer:[
      {"custnumber":"DMCUST/00001","custtype":"company","custname":"First Customer Co.","taxnumber":"12345678-1-12","terms":8,
      "creditlimit":1000000,"discount":2,"sample_customer_float":123.4,"sample_customer_date":(new Date().getFullYear())+"-08-12"},
      {"custnumber":"DMCUST/00002","custtype":"private","custname":"Second Customer Name","taxnumber":"12121212-1-12","terms":1,
      "creditlimit":0,"discount":6,"sample_customer_float":56789.67,"sample_customer_date":(new Date().getFullYear())+"-09-01",
      "sample_customer_valuelist":"yellow","sample_customer_reference":"DMCUST/00001"},
      {"custnumber":"DMCUST/00003","custtype":"other","custname":"Third Customer Foundation","taxnumber":"10101010-1-01",
      "notax":1,"terms":4,"creditlimit":0,"sample_customer_valuelist":"brown"}],
    address:[
        {"nervatype":"customer","refnumber":"DMCUST/00001","rownumber":1,"country":"Country1","state":"state01",
      "zipcode":"1234","city":"City1","street":"street 1.","notes":"address of registered office"},
      {"nervatype":"customer","refnumber":"DMCUST/00001","rownumber":2,"country":"Country1","state":"state02",
      "zipcode":"2345","city":"City2","street":"street 2.","notes":"postal address"},
      {"nervatype":"customer","refnumber":"DMCUST/00002","rownumber":1,"country":"Country1","state":"state03",
      "zipcode":"6789","city":"City3","street":"street 3."},
      {"nervatype":"customer","refnumber":"DMCUST/00003","rownumber":1,"country":"Country2","state":"state04",
      "zipcode":"6543","city":"City4","street":"street 4."}],
    contact:[
      {"nervatype":"customer","refnumber":"DMCUST/00001","rownumber":1,"firstname":"Big","surname":"Man",
      "status":"manager","email":"man.big@company.co"},
      {"nervatype":"customer","refnumber":"DMCUST/00001","rownumber":2,"firstname":"Sales","surname":"Man",
      "status":"sales","email":"man.sales@company.co"},
      {"nervatype":"customer","refnumber":"DMCUST/00002","rownumber":1,"firstname":"Jack","surname":"Frost"},
      {"nervatype":"customer","refnumber":"DMCUST/00003","rownumber":1,"firstname":"Harry","surname":"Potter"}],
    event:[
      {"calnumber":"DMEVT/00001","nervatype":"customer","refnumber":"DMCUST/00001","eventgroup":"visit",
      "fromdate":(new Date().getFullYear())-1+"-04-05T08:00:00","todate":(new Date().getFullYear())-1+"-04-05T10:00:00","subject":"First visit",
      "place":"City1","description":"It was long ...  :-(","company_page":"http://nervatura.com/"},
      {"calnumber":"DMEVT/00002","nervatype":"customer","refnumber":"DMCUST/00001","eventgroup":"visit",
      "fromdate":(new Date().getFullYear())-1+"-04-06T08:00:00","todate":(new Date().getFullYear())-1+"-04-06T10:00:00","subject":"Second visit","place":"City1"},
      {"calnumber":"DMEVT/00003","nervatype":"customer","refnumber":"DMCUST/00002",
      "fromdate":(new Date().getFullYear())-1+"-04-07T08:00:00","todate":(new Date().getFullYear())-1+"-04-07T10:00:00","subject":"Training"},
      {"calnumber":"DMEVT/00004","nervatype":"customer","refnumber":"DMCUST/00003",
      "fromdate":(new Date().getFullYear())-1+"-04-08T08:00:00","subject":"Training"}]},
  employee:{
    deffield:[
      {"fieldname":"sample_employee_integer","nervatype":"employee","fieldtype":"integer","description":"Shoe size","visible":1}],
    employee:[
      {"empnumber":"DMEMP/00001","usergroup":"guest","startdate":(new Date().getFullYear())-2+"-12-01",
       "department":"production","sample_employee_integer":42}],
    address:[
      {"nervatype":"employee","refnumber":"DMEMP/00001","rownumber":1,"country":"Country1",
       "zipcode":"1234","city":"City1","street":"Address 3. AB. 5.."}],
    contact:[
      {"nervatype":"employee","refnumber":"DMEMP/00001","rownumber":1,"firstname":"John","surname":"Strong",
       "status":"heaver","notes":"He's a good man ..."}],
    event:[
      {"calnumber":"DMEVT/00005","nervatype":"employee","refnumber":"DMEMP/00001",
       "fromdate":(new Date().getFullYear())-1+"-12-15T00:00:00","todate":(new Date().getFullYear())-1+"-12-31T00:00:00",
       "subject":"Holiday","place":"On the beach"}]},
  product:{
    deffield:[
      {"fieldname":"sample_product_reference","nervatype":"product","fieldtype":"product","description":"Sample product","visible":1},
      {"fieldname":"sample_product_integer","nervatype":"product","fieldtype":"integer","description":"Sample integer","visible":1},
      {"fieldname":"sample_product_valuelist","nervatype":"product","fieldtype":"valuelist","description":"Sample valuelist",
       "valuelist":"easy~heavy","visible":1}],
    product:[
      {"partnumber":"DMPROD/00001","description":"Big product","protype":"item","unit":"piece","taxcode":"20%","webitem":1,
       "inactive":0,"sample_product_valuelist":"easy"},
      {"partnumber":"DMPROD/00002","description":"Good work","protype":"service","unit":"hour","taxcode":"20%","webitem":0,
      "inactive":0,"sample_product_reference":"DMPROD/00001","sample_product_integer":100000},
      {"partnumber":"DMPROD/00003","description":"Nice product","protype":"item","unit":"piece","taxcode":"20%","webitem":1,
       "inactive":0,"sample_product_valuelist":"heavy"},
      {"partnumber":"DMPROD/00004","description":"Car","protype":"item","unit":"piece","taxcode":"20%","webitem":1,
       "inactive":0,"notes":"Manufacturing products"},
      {"partnumber":"DMPROD/00005","description":"Wheel","protype":"item","unit":"piece","taxcode":"20%","webitem":1,
       "inactive":0,"notes":"Raw material, component"},
      {"partnumber":"DMPROD/00006","description":"Door","protype":"item","unit":"piece","taxcode":"20%","webitem":1,
       "inactive":0,"notes":"Raw material, component"},
      {"partnumber":"DMPROD/00007","description":"Paint","protype":"item","unit":"liter","taxcode":"20%","webitem":1,
       "inactive":0,"notes":"Raw material, component"},
      {"partnumber":"DMPROD/00008","description":"Pallet","protype":"item","unit":"piece","taxcode":"20%","webitem":1,
       "inactive":0,"notes":"Raw material, component (not share sample)"},
      {"partnumber":"DMPROD/00009","description":"Basket","protype":"item","unit":"piece","taxcode":"20%",
       "inactive":0,"notes":"Souvenir component"},
      {"partnumber":"DMPROD/00010","description":"Wine","protype":"item","unit":"piece","taxcode":"5%",
       "inactive":0,"notes":"Souvenir component"},
      {"partnumber":"DMPROD/00011","description":"Chocolate","protype":"item","unit":"piece","taxcode":"20%",
       "inactive":0,"notes":"Souvenir component"},
      {"partnumber":"DMPROD/00012","description":"Souvenir - virtual product","protype":"item","unit":"piece",
       "taxcode":"15%","inactive":0,"notes":"A technical package, which might include several real products or services",
       "product_element~1":"DMPROD/00009~1","product_element~2":"DMPROD/00010~1","product_element~3":"DMPROD/00011~2",
       "product_element~4":"DMPROD/00002~1"},
      {"partnumber":"DMPROD/00013","description":"Phone","protype":"item","unit":"piece","taxcode":"20%",
       "inactive":0,"notes":"for tool movement..."}],
    barcode:[
      {"code":"BC0123456789","partnumber":"DMPROD/00001","barcodetype":"CODE_39","description":"Barcode1","defcode":1},
      {"code":"BC1212121212","partnumber":"DMPROD/00001","barcodetype":"CODE_39","description":"Barcode2","qty":5},
      {"code":"BC0101010101","partnumber":"DMPROD/00003","barcodetype":"CODE_39","description":"Barcode3","defcode":1}],
    event:[
      {"calnumber":"DMEVT/00006","nervatype":"product","refnumber":"DMPROD/00001","eventgroup":"pricing",
       "fromdate":(new Date().getFullYear())-1+"-04-05T08:00:00","todate":(new Date().getFullYear())-1+"-04-05T15:00:00",
       "subject":"New prices","place":"Office"},
      {"calnumber":"DMEVT/00007","nervatype":"product","refnumber":"DMPROD/00002","fromdate":(new Date().getFullYear())-1+"-04-08T08:00:00",
       "todate":(new Date().getFullYear())-1+"-04-12T18:00:00","subject":"business trip","place":"Hawaii"},
      {"calnumber":"DMEVT/00008","nervatype":"product","refnumber":"DMPROD/00002","fromdate":(new Date().getFullYear())-1+"-04-12T08:00:00",
       "subject":"Inventory","description":"Inventory check in the warehouse"}],
     price:[
       {"partnumber":"DMPROD/00001","pricetype":"price","validfrom":(new Date().getFullYear())-1+"-04-05","curr":"EUR",
        "qty":0,"pricevalue":25},
       {"partnumber":"DMPROD/00001","pricetype":"price","validfrom":(new Date().getFullYear())-1+"-04-05","curr":"EUR",
        "qty":10,"pricevalue":20}]},
   project:{
     deffield:[
       {"fieldname":"sample_project_state","nervatype":"project","fieldtype":"valuelist","description":"Status",
        "valuelist":"10%~20%~30%~40%~50%~60%~70%~80%~90%~100%","visible":1},
       {"fieldname":"sample_project_leader","nervatype":"project","fieldtype":"employee","description":"Coordinator","visible":1}],
     project:[
       {"pronumber":"DMPRJ/00001","description":"Sample project","startdate":(new Date().getFullYear())-1+"-12-01",
        "custnumber":"DMCUST/00001","sample_project_state":"20%","sample_project_leader":"DMEMP/00001"}],
     address:[
       {"nervatype":"project","refnumber":"DMPRJ/00001","rownumber":1,"country":"Country1",
        "zipcode":"1234","city":"City1","street":"Address 3. AB. 5.."}],
     contact:[
       {"nervatype":"project","refnumber":"DMPRJ/00001","rownumber":1,"firstname":"Big","surname":"Man"}],
     event:[
       {"calnumber":"DMEVT/00009","nervatype":"project","refnumber":"DMPRJ/00001",
        "fromdate":(new Date().getFullYear())-1+"-12-10T09:00:00","todate":(new Date().getFullYear())-1+"-12-10T11:00:00",
        "subject":"Project meeting","place":"Office"}]},
   tool:{
     deffield:[
       {"fieldname":"sample_tool_vin","nervatype":"tool","fieldtype":"string","description":"Vehicle id.No.","visible":1},
       {"fieldname":"sample_tool_color","nervatype":"tool","fieldtype":"valuelist","description":"Car colors",
        "valuelist":"blue~yellow~white~brown~red","visible":1}],
     tool:[
       {"serial":"ABC-123","description":"Company car 1.", "partnumber":"DMPROD/00004","sample_tool_vin":"VIN12345678",
        "sample_tool_color":"red"},
       {"serial":"DEF-456","description":"Company car 2.", "partnumber":"DMPROD/00004","sample_tool_vin":"VIN87654321",
        "sample_tool_color":"blue"},
       {"serial":"IMEI-023456789","description":"NOKIA E5", "partnumber":"DMPROD/00013"}],
     event:[
       {"calnumber":"DMEVT/00010","nervatype":"tool","refnumber":"ABC-123","eventgroup":"car",
        "fromdate":(new Date().getFullYear())-1+"-04-05T08:00:00","todate":(new Date().getFullYear())-1+"-04-05T15:00:00",
        "subject":"Technical inspection","place":"Service"}]},
   place:[
     {"planumber":"material","placetype":"warehouse","description":"Raw material"}],
   trans_item: {
     trans:[
       {"transnumber":"DMORD/00001","transtype":"order","direction":"in","transdate":(new Date().getFullYear())-1+"-11-01",
        "duedate":(new Date().getFullYear())-1+"-11-10T00:00:00","custnumber":"DMCUST/00003","paidtype":"transfer","curr":"EUR",
        "department":"logistics",
        "notes":"We bought some basic materials for production and sale. It was invoiced on the basis of delivery, but not all were delivered yet."},
       {"transnumber":"DMORD/00002","transtype":"order","direction":"out","transdate":(new Date().getFullYear())-1+"-12-04",
        "duedate":(new Date().getFullYear())-1+"-12-10T00:00:00","custnumber":"DMCUST/00002","paidtype":"transfer","curr":"EUR",
        "department":"sales","notes":"Virtual product sample."},
       {"transnumber":"DMORD/00003","transtype":"order","direction":"out","transdate":(new Date().getFullYear())-1+"-12-10",
        "duedate":(new Date().getFullYear())-1+"-12-20T00:00:00","custnumber":"DMCUST/00001","paidtype":"transfer","curr":"EUR",
        "department":"sales","notes":"DEMO invoice order."},
       {"transnumber":"DMOFF/00001","transtype":"offer","direction":"out","transdate":(new Date().getFullYear())-1+"-11-05",
        "duedate":(new Date().getFullYear())-1+"-11-30T00:00:00","custnumber":"DMCUST/00001","paidtype":"transfer","curr":"EUR",
        "department":"sales","ref_transnumber":"DMORD/00003","notes":"DEMO invoice offer"},
       {"transnumber":"DMINV/00001","transtype":"invoice","direction":"out","transdate":(new Date().getFullYear())-1+"-12-10",
        "duedate":(new Date().getFullYear())-1+"-12-20T00:00:00","custnumber":"DMCUST/00001","paidtype":"transfer","curr":"EUR",
        "department":"sales","ref_transnumber":"DMORD/00003",
        "fnote":"A long and <b><i>rich text</b></i> at the bottom of the invoice...<br><br>Can be multiple lines ..."},
       {"transnumber":"DMINV/00002","transtype":"invoice","direction":"out","transdate":(new Date().getFullYear())-1+"-12-10",
        "duedate":(new Date().getFullYear())+"-01-10T00:00:00","custnumber":"DMCUST/00002","paidtype":"transfer","curr":"EUR",
        "department":"sales","ref_transnumber":"DMORD/00002","notes":"Virtual product sample."},
       {"transnumber":"DMINV/00003","transtype":"invoice","direction":"in","transdate":(new Date().getFullYear())-1+"-11-10",
        "duedate":(new Date().getFullYear())-1+"-12-20T00:00:00","custnumber":"DMCUST/00003","paidtype":"transfer","curr":"EUR",
        "department":"logistics","ref_transnumber":"DMORD/00001",
        "notes":"We bought some basic materials for production and sale. It was invoiced on the basis of delivery, but not all were delivered yet."},
       {"transnumber":"DMWORK/00001","transtype":"worksheet","direction":"out","transdate":(new Date().getFullYear())+"-01-05",
        "duedate":(new Date().getFullYear())+"-01-05T00:00:00","custnumber":"DMCUST/00001","paidtype":"transfer","curr":"EUR","department":"sales",
        "empnumber":"DMEMP/00001","trans_wsdistance":200,"trans_wstotal":3},
       {"transnumber":"DMRNT/00001","transtype":"rent","direction":"out","transdate":(new Date().getFullYear())+"-01-01",
        "duedate":(new Date().getFullYear())+"-01-11T00:00:00","custnumber":"DMCUST/00001","paidtype":"transfer","curr":"EUR",
        "department":"logistics","trans_reholiday":3}],
     item:[
       {"transnumber":"DMORD/00001","rownumber":1,"partnumber":"DMPROD/00005","qty":40,"inputmode":"fxprice","inputvalue":10},
       {"transnumber":"DMORD/00001","rownumber":2,"partnumber":"DMPROD/00006","qty":60,"inputmode":"fxprice","inputvalue":12},
       {"transnumber":"DMORD/00001","rownumber":3,"partnumber":"DMPROD/00007","qty":50,"inputmode":"fxprice","inputvalue":16},
       {"transnumber":"DMORD/00001","rownumber":4,"partnumber":"DMPROD/00008","qty":20,"inputmode":"fxprice","inputvalue":5},
       {"transnumber":"DMORD/00001","rownumber":5,"partnumber":"DMPROD/00001","qty":10,"inputmode":"fxprice","inputvalue":120},
       {"transnumber":"DMORD/00001","rownumber":6,"partnumber":"DMPROD/00003","qty":10,"inputmode":"fxprice","inputvalue":15},
       {"transnumber":"DMORD/00001","rownumber":7,"partnumber":"DMPROD/00009","qty":20,"inputmode":"fxprice","inputvalue":8},
       {"transnumber":"DMORD/00001","rownumber":8,"partnumber":"DMPROD/00010","qty":20,"inputmode":"fxprice","inputvalue":20},
       {"transnumber":"DMORD/00001","rownumber":9,"partnumber":"DMPROD/00011","qty":20,"inputmode":"fxprice","inputvalue":16},
       {"transnumber":"DMORD/00002","rownumber":1,"partnumber":"DMPROD/00012","qty":2,"inputmode":"fxprice","inputvalue":60},
       {"transnumber":"DMORD/00002","rownumber":2,"partnumber":"DMPROD/00001","qty":3,"inputmode":"fxprice","inputvalue":25},
       {"transnumber":"DMORD/00003","rownumber":1,"partnumber":"DMPROD/00002","description":"Very good work!","qty":1,
        "inputmode":"fxprice","inputvalue":120},
       {"transnumber":"DMORD/00003","rownumber":2,"partnumber":"DMPROD/00001","qty":3,"inputmode":"amount","inputvalue":600},
       {"transnumber":"DMORD/00003","rownumber":3,"partnumber":"DMPROD/00003","taxcode":"5%","qty":5,"inputmode":"netamount",
        "inputvalue":100},
       {"transnumber":"DMOFF/00001","rownumber":1,"partnumber":"DMPROD/00002","description":"Very good work!",
        "qty":1,"inputmode":"fxprice","inputvalue":120},
       {"transnumber":"DMOFF/00001","rownumber":2,"partnumber":"DMPROD/00001","qty":3,"inputmode":"amount","inputvalue":600},
       {"transnumber":"DMOFF/00001","rownumber":3,"partnumber":"DMPROD/00003","taxcode":"5%","qty":5,
        "inputmode":"netamount","inputvalue":100},
       {"transnumber":"DMINV/00001","rownumber":1,"partnumber":"DMPROD/00002","description":"Very good work!","qty":1,
        "inputmode":"fxprice","inputvalue":120},
       {"transnumber":"DMINV/00001","rownumber":2,"partnumber":"DMPROD/00001","qty":3,"inputmode":"amount","inputvalue":600},
       {"transnumber":"DMINV/00001","rownumber":3,"partnumber":"DMPROD/00003","taxcode":"5%","qty":5,
        "inputmode":"netamount","inputvalue":100},
       {"transnumber":"DMINV/00002","rownumber":1,"partnumber":"DMPROD/00012","qty":2,"inputmode":"fxprice","inputvalue":60},
       {"transnumber":"DMINV/00002","rownumber":2,"partnumber":"DMPROD/00001","qty":3,"inputmode":"fxprice","inputvalue":25},
       {"transnumber":"DMINV/00003","rownumber":1,"partnumber":"DMPROD/00005","qty":30,"inputmode":"fxprice","inputvalue":10},
       {"transnumber":"DMINV/00003","rownumber":2,"partnumber":"DMPROD/00006","qty":50,"inputmode":"fxprice","inputvalue":12},
       {"transnumber":"DMINV/00003","rownumber":3,"partnumber":"DMPROD/00007","qty":50,"inputmode":"fxprice","inputvalue":16},
       {"transnumber":"DMINV/00003","rownumber":4,"partnumber":"DMPROD/00008","qty":15,"inputmode":"fxprice","inputvalue":5},
       {"transnumber":"DMINV/00003","rownumber":5,"partnumber":"DMPROD/00001","qty":10,"inputmode":"fxprice","inputvalue":120},
       {"transnumber":"DMINV/00003","rownumber":6,"partnumber":"DMPROD/00003","qty":10,"inputmode":"fxprice","inputvalue":15},
       {"transnumber":"DMINV/00003","rownumber":7,"partnumber":"DMPROD/00009","qty":15,"inputmode":"fxprice","inputvalue":8},
       {"transnumber":"DMINV/00003","rownumber":8,"partnumber":"DMPROD/00010","qty":10,"inputmode":"fxprice","inputvalue":20},
       {"transnumber":"DMINV/00003","rownumber":9,"partnumber":"DMPROD/00011","qty":20,"inputmode":"fxprice","inputvalue":16},
       {"transnumber":"DMWORK/00001","rownumber":1,"partnumber":"DMPROD/00002","qty":2,"inputmode":"fxprice","inputvalue":130},
       {"transnumber":"DMRNT/00001","rownumber":1,"partnumber":"DMPROD/00008","qty":3,"fxprice":12,"netamount":396,
        "taxcode":"20%","vatamount":79.2,"amount":475.2}],
     link:[
       {"nervatype1":"trans","refnumber1":"DMOFF/00001","nervatype2":"trans","refnumber2":"DMORD/00003"},
       {"nervatype1":"trans","refnumber1":"DMINV/00001","nervatype2":"trans","refnumber2":"DMORD/00003"},
       {"nervatype1":"trans","refnumber1":"DMINV/00002","nervatype2":"trans","refnumber2":"DMORD/00002"},
       {"nervatype1":"trans","refnumber1":"DMINV/00003","nervatype2":"trans","refnumber2":"DMORD/00001"}]},
   trans_payment: {
     trans:[
       {"transnumber":"DMPMT/00001","transtype":"bank","direction":"transfer","transdate":(new Date().getFullYear())+"-01-15",
        "planumber":"bank","ref_transnumber":"BM0123456"},
       {"transnumber":"DMPMT/00002","transtype":"cash","direction":"out","transdate":(new Date().getFullYear())-1+"-12-18",
        "planumber":"cash"}],
      payment:[
        {"transnumber":"DMPMT/00001","rownumber":1,"paiddate":(new Date().getFullYear())-1+"-12-20","amount":-4000,
         "notes":"payment two divided..."},
        {"transnumber":"DMPMT/00001","rownumber":2,"paiddate":(new Date().getFullYear())-1+"-12-20","amount":849},
        {"transnumber":"DMPMT/00001","rownumber":3,"paiddate":(new Date().getFullYear())+"-01-10","amount":228},
        {"transnumber":"DMPMT/00002","rownumber":1,"paiddate":(new Date().getFullYear())-1+"-12-18","amount":-488}],
      link:[
        {"nervatype1":"payment","refnumber1":"DMPMT/00001~1","nervatype2":"trans","refnumber2":"DMINV/00003",
          "link_qty":4000,"link_rate":1},
        {"nervatype1":"payment","refnumber1":"DMPMT/00001~2","nervatype2":"trans","refnumber2":"DMINV/00001",
          "link_qty":849,"link_rate":1},
        {"nervatype1":"payment","refnumber1":"DMPMT/00001~3","nervatype2":"trans","refnumber2":"DMINV/00002",
          "link_qty":228,"link_rate":1},
        {"nervatype1":"payment","refnumber1":"DMPMT/00002~1","nervatype2":"trans","refnumber2":"DMINV/00003",
          "link_qty":488,"link_rate":1}]},
   trans_movement: {
     trans:[
       {"transnumber":"DMMOVE/00001","transtype":"waybill","direction":"out","transdate":(new Date().getFullYear())-1+"-12-05",
        "empnumber":"DMEMP/00001","notes":"We hand out some working tools to the employee..."},
       {"transnumber":"DMDEL/00001","transtype":"delivery","direction":"in","transdate":(new Date().getFullYear())-1+"-11-08"},
       {"transnumber":"DMDEL/00002","transtype":"delivery","direction":"out","transdate":(new Date().getFullYear())-1+"-12-10"},
       {"transnumber":"DMDEL/00003","transtype":"delivery","direction":"out","transdate":(new Date().getFullYear())-1+"-12-10"},
       {"transnumber":"DMDTF/00001","transtype":"delivery","direction":"transfer","transdate":(new Date().getFullYear())-1+"-11-08",
        "planumber":"material"},
       {"transnumber":"DMCORR/00001","transtype":"inventory","direction":"transfer","transdate":(new Date().getFullYear())-1+"-12-01",
        "planumber":"warehouse","notes":"Scrapping of some products ..."},
       {"transnumber":"DMFRM/00001","transtype":"formula","direction":"transfer","notes":"Sample formula (4 door/car)"},
       {"transnumber":"DMFRM/00002","transtype":"formula","direction":"transfer","notes":"Sample formula (3 door/car)"},
       {"transnumber":"DMMAKE/00001","transtype":"production","direction":"transfer","transdate":(new Date().getFullYear())-1+"-12-01",
        "duedate":(new Date().getFullYear())-1+"-12-02T00:00:00","planumber":"warehouse","notes":"formula: 4 door/car"}],
     movement:[
       {"transnumber":"DMMOVE/00001","rownumber":1,"movetype":"tool","shippingdate":(new Date().getFullYear())-1+"-12-05T00:00:00", 
        "serial":"DEF-456"},
       {"transnumber":"DMMOVE/00001","rownumber":2,"movetype":"tool","shippingdate":(new Date().getFullYear())-1+"-12-05T00:00:00", 
        "serial":"IMEI-023456789","notes":"mobile phone"},
       {"transnumber":"DMDEL/00001","rownumber":1,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00",
        "planumber":"material","partnumber":"DMPROD/00005","qty":30,"notes":"demo"},
       {"transnumber":"DMDEL/00001","rownumber":2,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00",
        "planumber":"material","partnumber":"DMPROD/00006","qty":50,"notes":"demo"},
       {"transnumber":"DMDEL/00001","rownumber":3,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00",
        "planumber":"material","partnumber":"DMPROD/00007","qty":50,"notes":"demo"},
       {"transnumber":"DMDEL/00001","rownumber":4,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00",
        "planumber":"material","partnumber":"DMPROD/00008","qty":15,"notes":"demo"},
       {"transnumber":"DMDEL/00001","rownumber":5,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00",
        "planumber":"material","partnumber":"DMPROD/00001","qty":10,"notes":"demo"},
       {"transnumber":"DMDEL/00001","rownumber":6,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00",
        "planumber":"material","partnumber":"DMPROD/00003","qty":10,"notes":"demo"},
       {"transnumber":"DMDEL/00001","rownumber":7,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00",
        "planumber":"material","partnumber":"DMPROD/00009","qty":15,"notes":"demo"},
       {"transnumber":"DMDEL/00001","rownumber":8,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00",
        "planumber":"material","partnumber":"DMPROD/00010","qty":10,"notes":"demo"},
       {"transnumber":"DMDEL/00001","rownumber":9,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00",
        "planumber":"material","partnumber":"DMPROD/00011","qty":20,"notes":"demo"},
       {"transnumber":"DMDEL/00002","rownumber":1,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-12-10T00:00:00",
        "planumber":"warehouse","partnumber":"DMPROD/00009","qty":-2,"notes":"demo"},
       {"transnumber":"DMDEL/00002","rownumber":2,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-12-10T00:00:00",
        "planumber":"warehouse","partnumber":"DMPROD/00010","qty":-2,"notes":"demo"},
       {"transnumber":"DMDEL/00002","rownumber":3,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-12-10T00:00:00",
        "planumber":"warehouse","partnumber":"DMPROD/00011","qty":-4,"notes":"demo"},
       {"transnumber":"DMDEL/00002","rownumber":4,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-12-10T00:00:00",
        "planumber":"warehouse","partnumber":"DMPROD/00001","qty":-3,"notes":"demo"},
       {"transnumber":"DMDEL/00003","rownumber":1,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-12-10T00:00:00",
        "planumber":"warehouse","partnumber":"DMPROD/00001","qty":-3,"notes":"demo"},
       {"transnumber":"DMDEL/00003","rownumber":2,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-12-10T00:00:00",
        "planumber":"warehouse","partnumber":"DMPROD/00003","qty":-5,"notes":"demo"},
       {"transnumber":"DMDTF/00001","rownumber":1,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00",
        "planumber":"material","partnumber":"DMPROD/00001","qty":-10,"notes":"demo"},
       {"transnumber":"DMDTF/00001","rownumber":2,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00",
        "planumber":"warehouse","partnumber":"DMPROD/00001","qty":10,"notes":"demo"},
       {"transnumber":"DMDTF/00001","rownumber":3,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00",
        "planumber":"material","partnumber":"DMPROD/00003","qty":-10,"notes":"demo"},
       {"transnumber":"DMDTF/00001","rownumber":4,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00",
        "planumber":"warehouse","partnumber":"DMPROD/00003","qty":10,"notes":"demo"},
       {"transnumber":"DMDTF/00001","rownumber":5,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00",
        "planumber":"material","partnumber":"DMPROD/00009","qty":-15,"notes":"demo"},
       {"transnumber":"DMDTF/00001","rownumber":6,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00",
        "planumber":"warehouse","partnumber":"DMPROD/00009","qty":15,"notes":"demo"},
       {"transnumber":"DMDTF/00001","rownumber":7,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00",
        "planumber":"material","partnumber":"DMPROD/00010","qty":-10,"notes":"demo"},
       {"transnumber":"DMDTF/00001","rownumber":8,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00",
        "planumber":"warehouse","partnumber":"DMPROD/00010","qty":10,"notes":"demo"},
       {"transnumber":"DMDTF/00001","rownumber":9,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00",
        "planumber":"material","partnumber":"DMPROD/00011","qty":-20,"notes":"demo"},
       {"transnumber":"DMDTF/00001","rownumber":10,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00",
        "planumber":"warehouse","partnumber":"DMPROD/00011","qty":20,"notes":"demo"},
       {"transnumber":"DMCORR/00001","rownumber":1,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-12-01T00:00:00",
        "planumber":"warehouse","partnumber":"DMPROD/00001","qty":-2,"notes":"demo"},
       {"transnumber":"DMCORR/00001","rownumber":2,"movetype":"inventory","shippingdate":(new Date().getFullYear())-1+"-12-01T00:00:00",
        "planumber":"warehouse","partnumber":"DMPROD/00010","qty":-3,"notes":"demo"},
       {"transnumber":"DMFRM/00001","rownumber":1,"movetype":"head","partnumber":"DMPROD/00004","qty":5,"shared":0},
       {"transnumber":"DMFRM/00001","rownumber":2,"movetype":"plan","partnumber":"DMPROD/00005",
        "qty":20,"shared":0,"planumber":"material"},
       {"transnumber":"DMFRM/00001","rownumber":3,"movetype":"plan","partnumber":"DMPROD/00006",
        "qty":20,"shared":0,"planumber":"material"},
       {"transnumber":"DMFRM/00001","rownumber":4,"movetype":"plan","partnumber":"DMPROD/00007",
        "qty":30,"shared":0,"planumber":"material"},
       {"transnumber":"DMFRM/00001","rownumber":5,"movetype":"plan","partnumber":"DMPROD/00008",
        "qty":1,"shared":1,"planumber":"material"},
       {"transnumber":"DMFRM/00002","rownumber":1,"movetype":"head","partnumber":"DMPROD/00004","qty":5,"shared":0},
       {"transnumber":"DMFRM/00002","rownumber":2,"movetype":"plan","partnumber":"DMPROD/00005",
        "qty":20,"shared":0,"planumber":"material"},
       {"transnumber":"DMFRM/00002","rownumber":3,"movetype":"plan","partnumber":"DMPROD/00006",
        "qty":15,"shared":0},
       {"transnumber":"DMFRM/00002","rownumber":4,"movetype":"plan","partnumber":"DMPROD/00007",
        "qty":28,"shared":0,"planumber":"material"},
       {"transnumber":"DMFRM/00002","rownumber":5,"movetype":"plan","partnumber":"DMPROD/00008",
        "qty":1,"shared":1,"planumber":"material","notes":"demo"},
       {"transnumber":"DMMAKE/00001","rownumber":1,"movetype":"inventory","partnumber":"DMPROD/00004",
        "shippingdate":(new Date().getFullYear())-1+"-12-02T00:00:00","qty":2,"shared":1,"planumber":"warehouse","notes":"demo"},
       {"transnumber":"DMMAKE/00001","rownumber":2,"movetype":"inventory","partnumber":"DMPROD/00005",
        "shippingdate":(new Date().getFullYear())-1+"-12-01T00:00:00","qty":-8,"shared":0,"planumber":"material","notes":"demo"},
       {"transnumber":"DMMAKE/00001","rownumber":3,"movetype":"inventory","partnumber":"DMPROD/00006",
        "shippingdate":(new Date().getFullYear())-1+"-12-01T00:00:00","qty":-8,"shared":0,"planumber":"material","notes":"demo"},
       {"transnumber":"DMMAKE/00001","rownumber":4,"movetype":"inventory","partnumber":"DMPROD/00007",
        "shippingdate":(new Date().getFullYear())-1+"-12-01T00:00:00","qty":-12,"shared":0,"planumber":"material","notes":"demo"},
       {"transnumber":"DMMAKE/00001","rownumber":5,"movetype":"inventory","partnumber":"DMPROD/00008",
        "shippingdate":(new Date().getFullYear())-1+"-12-01T00:00:00","qty":-1,"shared":0,"planumber":"material","notes":"demo"}],
     link:[
       {"nervatype1":"movement","refnumber1":"DMDEL/00001~1","nervatype2":"item","refnumber2":"DMORD/00001~1"},
       {"nervatype1":"movement","refnumber1":"DMDEL/00001~2","nervatype2":"item","refnumber2":"DMORD/00001~2"},
       {"nervatype1":"movement","refnumber1":"DMDEL/00001~3","nervatype2":"item","refnumber2":"DMORD/00001~3"},
       {"nervatype1":"movement","refnumber1":"DMDEL/00001~4","nervatype2":"item","refnumber2":"DMORD/00001~4"},
       {"nervatype1":"movement","refnumber1":"DMDEL/00001~5","nervatype2":"item","refnumber2":"DMORD/00001~5"},
       {"nervatype1":"movement","refnumber1":"DMDEL/00001~6","nervatype2":"item","refnumber2":"DMORD/00001~6"},
       {"nervatype1":"movement","refnumber1":"DMDEL/00001~7","nervatype2":"item","refnumber2":"DMORD/00001~7"},
       {"nervatype1":"movement","refnumber1":"DMDEL/00001~8","nervatype2":"item","refnumber2":"DMORD/00001~8"},
       {"nervatype1":"movement","refnumber1":"DMDEL/00001~9","nervatype2":"item","refnumber2":"DMORD/00001~9"},
       {"nervatype1":"movement","refnumber1":"DMDEL/00002~1","nervatype2":"item","refnumber2":"DMORD/00002~1"},
       {"nervatype1":"movement","refnumber1":"DMDEL/00002~2","nervatype2":"item","refnumber2":"DMORD/00002~1"},
       {"nervatype1":"movement","refnumber1":"DMDEL/00002~3","nervatype2":"item","refnumber2":"DMORD/00002~1"},
       {"nervatype1":"movement","refnumber1":"DMDEL/00002~4","nervatype2":"item","refnumber2":"DMORD/00002~2"},
       {"nervatype1":"movement","refnumber1":"DMDEL/00003~1","nervatype2":"item","refnumber2":"DMORD/00003~2"},
       {"nervatype1":"movement","refnumber1":"DMDEL/00003~2","nervatype2":"item","refnumber2":"DMORD/00003~3"},
       {"nervatype1":"movement","refnumber1":"DMDTF/00001~1","nervatype2":"movement","refnumber2":"DMDTF/00001~2"},
       {"nervatype1":"movement","refnumber1":"DMDTF/00001~3","nervatype2":"movement","refnumber2":"DMDTF/00001~4"},
       {"nervatype1":"movement","refnumber1":"DMDTF/00001~5","nervatype2":"movement","refnumber2":"DMDTF/00001~6"},
       {"nervatype1":"movement","refnumber1":"DMDTF/00001~7","nervatype2":"movement","refnumber2":"DMDTF/00001~8"},
       {"nervatype1":"movement","refnumber1":"DMDTF/00001~9","nervatype2":"movement","refnumber2":"DMDTF/00001~10"}]},
     menu:{
       ui_menu:[
         {"menukey":"mnu_exp_1", "description":"Server function example", "funcname":"callMenuCmd", "url":0},
         {"menukey":"mnu_exp_2", "description":"Server URL example", "funcname":"ndi/getVernum", "url":1},
         {"menukey":"mnu_exp_3", "description":"Internet URL example", "funcname":"search", "url":1, 
          "address":"https://www.google.com"}],
       ui_menufields:[
         {"menu_id":"mnu_exp_1", "fieldname":"number_1", "description":"first number", 
          "fieldtype":"float", "orderby":0},
         {"menu_id":"mnu_exp_1", "fieldname":"number_2", "description":"second number", 
          "fieldtype":"float", "orderby":1},
         {"menu_id":"mnu_exp_3", "fieldname":"q", "description":"google search", 
          "fieldtype":"string", "orderby":0}]}
}