/*
This file is part of the Nervatura Framework
http://www.nervatura.com
Copyright © 2011-2019, Csaba Kappel
License: LGPLv3
https://raw.githubusercontent.com/nervatura/nervatura/master/LICENSE
*/

module.exports = {
  groups:[
	  {"groupname":"department","groupvalue":"sales","description":"Sample department"},
	  {"groupname":"department","groupvalue":"logistics","description":"Sample department"},
	  {"groupname":"department","groupvalue":"production","description":"Sample department"},
    {"groupname":"eventgroup","groupvalue":"visit"},
    {"groupname":"eventgroup","groupvalue":"pricing"},
    {"groupname":"eventgroup","groupvalue":"car"}],
  customer:{
    deffield:[
      {"fieldname":"sample_customer_float","description":"Sample float","visible":1,
       "keys":{"nervatype":"customer","fieldtype":"float"}},
      {"fieldname":"sample_customer_date","description":"Sample date","visible":1,
       "keys":{"nervatype":"customer","fieldtype":"date"}},
      {"fieldname":"sample_customer_valuelist","description":"Sample valuelist","valuelist":"blue~yellow~white~brown~red","visible":1,
       "keys":{"nervatype":"customer","fieldtype":"valuelist"}},
      {"fieldname":"sample_customer_reference","description":"Sample customer","visible":1,
       "keys":{"nervatype":"customer","fieldtype":"customer"}},
      {"fieldname":"company_page","description":"Company page","visible":1,
       "keys":{"nervatype":"event","fieldtype":"urlink"}}],
    customer:[
      {"custnumber":"DMCUST/00001","custname":"First Customer Co.","taxnumber":"12345678-1-12","terms":8,
       "creditlimit":1000000,"discount":2,"sample_customer_float":123.4,"sample_customer_date":(new Date().getFullYear())+"-08-12",
       "keys":{"custtype":"company"}},
      {"custnumber":"DMCUST/00002","custname":"Second Customer Name","taxnumber":"12121212-1-12","terms":1,
       "creditlimit":0,"discount":6,"sample_customer_float":56789.67,"sample_customer_date":(new Date().getFullYear())+"-09-01",
       "sample_customer_valuelist":"yellow","sample_customer_reference":"DMCUST/00001",
       "keys":{"custtype":"private"}},
      {"custnumber":"DMCUST/00003","custname":"Third Customer Foundation","taxnumber":"10101010-1-01",
       "notax":1,"terms":4,"creditlimit":0,"sample_customer_valuelist":"brown",
       "keys":{"custtype":"other"}}],
    address:[
      {"country":"Country1","state":"state01",
       "zipcode":"1234","city":"City1","street":"street 1.","notes":"address of registered office",
       "keys":{"nervatype":"customer","ref_id":"customer/DMCUST/00001"}},
      {"country":"Country1","state":"state02",
       "zipcode":"2345","city":"City2","street":"street 2.","notes":"postal address",
       "keys":{"nervatype":"customer","ref_id":"customer/DMCUST/00001"}},
      {"country":"Country1","state":"state03",
       "zipcode":"6789","city":"City3","street":"street 3.",
       "keys":{"nervatype":"customer","ref_id":"customer/DMCUST/00002"}},
      {"country":"Country2","state":"state04",
       "zipcode":"6543","city":"City4","street":"street 4.",
       "keys":{"nervatype":"customer","ref_id":"customer/DMCUST/00003"}}],
    contact:[
      {"firstname":"Big","surname":"Man",
      "status":"manager","email":"man.big@company.co",
       "keys":{"nervatype":"customer","ref_id":"customer/DMCUST/00001"}},
      {"firstname":"Sales","surname":"Man",
      "status":"sales","email":"man.sales@company.co",
       "keys":{"nervatype":"customer","ref_id":"customer/DMCUST/00001"}},
      {"firstname":"Jack","surname":"Frost",
       "keys":{"nervatype":"customer","ref_id":"customer/DMCUST/00002"}},
      {"firstname":"Harry","surname":"Potter",
       "keys":{"nervatype":"customer","ref_id":"customer/DMCUST/00003"}}],
    event:[
      {"calnumber":"DMEVT/00001","fromdate":(new Date().getFullYear())-1+"-04-05T08:00:00","todate":(new Date().getFullYear())-1+"-04-05T10:00:00","subject":"First visit",
       "place":"City1","description":"It was long ...  :-(","company_page":"http://nervatura.com/",
       "keys":{"nervatype":"customer","ref_id":"customer/DMCUST/00001","eventgroup":"visit"}},
      {"calnumber":"DMEVT/00002","fromdate":(new Date().getFullYear())-1+"-04-06T08:00:00","todate":(new Date().getFullYear())-1+"-04-06T10:00:00","subject":"Second visit","place":"City1",
       "keys":{"nervatype":"customer","ref_id":"customer/DMCUST/00001","eventgroup":"visit"}},
      {"calnumber":"DMEVT/00003","fromdate":(new Date().getFullYear())-1+"-04-07T08:00:00","todate":(new Date().getFullYear())-1+"-04-07T10:00:00","subject":"Training",
       "keys":{"nervatype":"customer","ref_id":"customer/DMCUST/00002"}},
      {"calnumber":"DMEVT/00004","fromdate":(new Date().getFullYear())-1+"-04-08T08:00:00","subject":"Training",
       "keys":{"nervatype":"customer","ref_id":"customer/DMCUST/00003"}}]},
  employee:{
    deffield:[
      {"fieldname":"sample_employee_integer","description":"Shoe size","visible":1,
       "keys":{"nervatype":"employee","fieldtype":"integer"}}],
    employee:[
      {'empnumber':'user', 'username':'user', "keys":{"usergroup":"user"}},
      {'empnumber':'guest', 'username':'guest', "keys":{"usergroup":"guest"}},
      {'empnumber':'demo', 'username':'demo', "keys":{"usergroup":"demo"}},
      {"empnumber":"DMEMP/00001","startdate":(new Date().getFullYear())-2+"-12-01","sample_employee_integer":42,
       "keys":{"usergroup":"guest","department":"production"}}],
    address:[
      {"keys":{"nervatype":"employee","ref_id":"employee/user"}},
      {"keys":{"nervatype":"employee","ref_id":"employee/guest"}},
      {"keys":{"nervatype":"employee","ref_id":"employee/demo"}},
      {"country":"Country1","zipcode":"1234","city":"City1","street":"Address 3. AB. 5..",
       "keys":{"nervatype":"employee","ref_id":"employee/DMEMP/00001"}}],
    contact:[
      {"keys":{"nervatype":"employee","ref_id":"employee/user"}},
      {"keys":{"nervatype":"employee","ref_id":"employee/guest"}},
      {"keys":{"nervatype":"employee","ref_id":"employee/demo"}},
      {"firstname":"John","surname":"Strong","status":"heaver","notes":"He's a good man ...",
       "keys":{"nervatype":"employee","ref_id":"employee/DMEMP/00001"}}],
    event:[
      {"calnumber":"DMEVT/00005","fromdate":(new Date().getFullYear())-1+"-12-15T00:00:00",
       "todate":(new Date().getFullYear())-1+"-12-31T00:00:00",
       "subject":"Holiday","place":"On the beach",
       "keys":{"nervatype":"employee","ref_id":"employee/DMEMP/00001"}}]},
  product:{
    deffield:[
      {"fieldname":"sample_product_reference","description":"Sample product","visible":1,
       "keys":{"nervatype":"product","fieldtype":"product"}},
      {"fieldname":"sample_product_integer","description":"Sample integer","visible":1,
       "keys":{"nervatype":"product","fieldtype":"integer"}},
      {"fieldname":"sample_product_valuelist","description":"Sample valuelist",
       "valuelist":"easy~heavy","visible":1,
       "keys":{"nervatype":"product","fieldtype":"valuelist"}}],
    product:[
      {"partnumber":"DMPROD/00001","description":"Big product","unit":"piece","webitem":1,
       "inactive":0,"sample_product_valuelist":"easy",
       "keys":{"protype":"item","tax_id":"20%"}},
      {"partnumber":"DMPROD/00002","description":"Good work","unit":"hour","webitem":0,
      "inactive":0,"sample_product_reference":"DMPROD/00001","sample_product_integer":100000,
       "keys":{"protype":"service","tax_id":"20%"}},
      {"partnumber":"DMPROD/00003","description":"Nice product","unit":"piece","webitem":1,
       "inactive":0,"sample_product_valuelist":"heavy",
       "keys":{"protype":"item","tax_id":"20%"}},
      {"partnumber":"DMPROD/00004","description":"Car","unit":"piece","webitem":1,
       "inactive":0,"notes":"Manufacturing products",
       "keys":{"protype":"item","tax_id":"20%"}},
      {"partnumber":"DMPROD/00005","description":"Wheel","unit":"piece","webitem":1,
       "inactive":0,"notes":"Raw material, component",
       "keys":{"protype":"item","tax_id":"20%"}},
      {"partnumber":"DMPROD/00006","description":"Door","unit":"piece","webitem":1,
       "inactive":0,"notes":"Raw material, component",
       "keys":{"protype":"item","tax_id":"20%"}},
      {"partnumber":"DMPROD/00007","description":"Paint","unit":"liter","webitem":1,
       "inactive":0,"notes":"Raw material, component",
       "keys":{"protype":"item","tax_id":"20%"}},
      {"partnumber":"DMPROD/00008","description":"Pallet","unit":"piece","webitem":1,
       "inactive":0,"notes":"Raw material, component (not share sample)",
       "keys":{"protype":"item","tax_id":"20%"}},
      {"partnumber":"DMPROD/00009","description":"Basket","unit":"piece",
       "inactive":0,"notes":"Souvenir component",
       "keys":{"protype":"item","tax_id":"20%"}},
      {"partnumber":"DMPROD/00010","description":"Wine","unit":"piece",
       "inactive":0,"notes":"Souvenir component",
       "keys":{"protype":"item","tax_id":"5%"}},
      {"partnumber":"DMPROD/00011","description":"Chocolate","unit":"piece",
       "inactive":0,"notes":"Souvenir component",
       "keys":{"protype":"item","tax_id":"20%"}},
      {"partnumber":"DMPROD/00012","description":"Souvenir - virtual product","unit":"piece",
       "inactive":0,"notes":"A technical package, which might include several real products or services",
       "product_element~1":"DMPROD/00009~1","product_element~2":"DMPROD/00010~1","product_element~3":"DMPROD/00011~2",
       "product_element~4":"DMPROD/00002~1",
       "keys":{"protype":"item","tax_id":"15%"}},
      {"partnumber":"DMPROD/00013","description":"Phone","unit":"piece","inactive":0,"notes":"for tool movement...",
       "keys":{"protype":"item","tax_id":"20%"}}],
    barcode:[
      {"code":"BC0123456789","description":"Barcode1","defcode":1,
       "keys":{"product_id":"DMPROD/00001","barcodetype":"CODE_39"}},
      {"code":"BC1212121212","description":"Barcode2","qty":5,
       "keys":{"product_id":"DMPROD/00001","barcodetype":"CODE_39"}},
      {"code":"BC0101010101","description":"Barcode3","defcode":1,
       "keys":{"product_id":"DMPROD/00003","barcodetype":"CODE_39",}}],
    event:[
      {"calnumber":"DMEVT/00006",
       "fromdate":(new Date().getFullYear())-1+"-04-05T08:00:00",
       "todate":(new Date().getFullYear())-1+"-04-05T15:00:00",
       "subject":"New prices","place":"Office",
       "keys":{"nervatype":"product","ref_id":"product/DMPROD/00001","eventgroup":"pricing"}},
      {"calnumber":"DMEVT/00007","fromdate":(new Date().getFullYear())-1+"-04-08T08:00:00",
       "todate":(new Date().getFullYear())-1+"-04-12T18:00:00","subject":"business trip","place":"Hawaii",
       "keys":{"nervatype":"product","ref_id":"product/DMPROD/00002"}},
      {"calnumber":"DMEVT/00008","fromdate":(new Date().getFullYear())-1+"-04-12T08:00:00",
       "subject":"Inventory","description":"Inventory check in the warehouse",
       "keys":{"nervatype":"product","ref_id":"product/DMPROD/00002"}}],
     price:[
       {"validfrom":(new Date().getFullYear())-1+"-04-05","curr":"EUR","qty":0,"pricevalue":25,
        "keys":{"product_id":"DMPROD/00001"}},
       {"validfrom":(new Date().getFullYear())-1+"-04-05","curr":"EUR","qty":10,"pricevalue":20,
        "keys":{"product_id":"DMPROD/00001"}}]},
   project:{
     deffield:[
       {"fieldname":"sample_project_state","description":"Status",
        "valuelist":"10%~20%~30%~40%~50%~60%~70%~80%~90%~100%","visible":1,
        "keys":{"nervatype":"project","fieldtype":"valuelist"}},
       {"fieldname":"sample_project_leader","description":"Coordinator","visible":1,
        "keys":{"nervatype":"project","fieldtype":"employee"}}],
     project:[
       {"pronumber":"DMPRJ/00001","description":"Sample project","startdate":(new Date().getFullYear())-1+"-12-01",
        "sample_project_state":"20%","sample_project_leader":"DMEMP/00001",
        "keys":{"customer_id":"DMCUST/00001"}}],
     address:[
       {"country":"Country1","zipcode":"1234","city":"City1","street":"Address 3. AB. 5..",
        "keys":{"nervatype":"project","ref_id":"project/DMPRJ/00001"}}],
     contact:[
       {"firstname":"Big","surname":"Man",
       "keys":{"nervatype":"project","ref_id":"project/DMPRJ/00001"}}],
     event:[
       {"calnumber":"DMEVT/00009",
        "fromdate":(new Date().getFullYear())-1+"-12-10T09:00:00",
        "todate":(new Date().getFullYear())-1+"-12-10T11:00:00",
        "subject":"Project meeting","place":"Office",
        "keys":{"nervatype":"project","ref_id":"project/DMPRJ/00001"}}]},
   tool:{
     deffield:[
       {"fieldname":"sample_tool_vin","description":"Vehicle id.No.","visible":1,
        "keys":{"nervatype":"tool","fieldtype":"string"}},
       {"fieldname":"sample_tool_color","description":"Car colors",
        "valuelist":"blue~yellow~white~brown~red","visible":1,
        "keys":{"nervatype":"tool","fieldtype":"valuelist"}}],
     tool:[
       {"serial":"ABC-123","description":"Company car 1.",
        "sample_tool_vin":"VIN12345678","sample_tool_color":"red",
        "keys":{"product_id":"DMPROD/00004"}},
       {"serial":"DEF-456","description":"Company car 2.",
        "sample_tool_vin":"VIN87654321","sample_tool_color":"blue",
        "keys":{"product_id":"DMPROD/00004"}},
       {"serial":"IMEI-023456789","description":"NOKIA E5",
       "keys":{"product_id":"DMPROD/00013"}}],
     event:[
       {"calnumber":"DMEVT/00010","fromdate":(new Date().getFullYear())-1+"-04-05T08:00:00",
        "todate":(new Date().getFullYear())-1+"-04-05T15:00:00",
        "subject":"Technical inspection","place":"Service",
        "keys":{"nervatype":"tool","ref_id":"tool/ABC-123","eventgroup":"car"}}]},
   place:[
     {"planumber":"material","description":"Raw material",
      "keys":{"placetype":"warehouse"}}],
   trans_item: {
     trans:[
       {"transnumber":"DMORD/00001","transdate":(new Date().getFullYear())-1+"-11-01",
        "duedate":(new Date().getFullYear())-1+"-11-10T00:00:00","curr":"EUR",
        "notes":"We bought some basic materials for production and sale. It was invoiced on the basis of delivery, but not all were delivered yet.",
        "keys":{"transtype":"order","direction":"in","customer_id":"DMCUST/00003","paidtype":"transfer","department":"logistics","transtate": "ok"}},
       {"transnumber":"DMORD/00002","transdate":(new Date().getFullYear())-1+"-12-04",
        "duedate":(new Date().getFullYear())-1+"-12-10T00:00:00","curr":"EUR",
        "notes":"Virtual product sample.",
        "keys":{"transtype":"order","direction":"out","customer_id":"DMCUST/00002","paidtype":"transfer","department":"sales","transtate": "ok"}},
       {"transnumber":"DMORD/00003","transdate":(new Date().getFullYear())-1+"-12-10",
        "duedate":(new Date().getFullYear())-1+"-12-20T00:00:00","curr":"EUR",
        "notes":"DEMO invoice order.",
        "keys":{"transtype":"order","direction":"out","customer_id":"DMCUST/00001","paidtype":"transfer","department":"sales","transtate": "ok"}},
       {"transnumber":"DMOFF/00001","transdate":(new Date().getFullYear())-1+"-11-05",
        "duedate":(new Date().getFullYear())-1+"-11-30T00:00:00","curr":"EUR",
        "ref_transnumber":"DMORD/00003","notes":"DEMO invoice offer",
        "keys":{"transtype":"offer","direction":"out","customer_id":"DMCUST/00001","paidtype":"transfer","department":"sales","transtate": "ok"}},
       {"transnumber":"DMINV/00001","transdate":(new Date().getFullYear())-1+"-12-10",
        "duedate":(new Date().getFullYear())-1+"-12-20T00:00:00","curr":"EUR",
        "ref_transnumber":"DMORD/00003",
        "fnote":"A long and <b><i>rich text</b></i> at the bottom of the invoice...<br><br>Can be multiple lines ...",
        "keys":{"transtype":"invoice","direction":"out","customer_id":"DMCUST/00001","paidtype":"transfer","department":"sales","transtate": "ok"}},
       {"transnumber":"DMINV/00002","transdate":(new Date().getFullYear())-1+"-12-10",
        "duedate":(new Date().getFullYear())+"-01-10T00:00:00","curr":"EUR",
        "ref_transnumber":"DMORD/00002","notes":"Virtual product sample.",
        "keys":{"transtype":"invoice","direction":"out","customer_id":"DMCUST/00002","paidtype":"transfer","department":"sales","transtate": "ok"}},
       {"transnumber":"DMINV/00003","transdate":(new Date().getFullYear())-1+"-11-10",
        "duedate":(new Date().getFullYear())-1+"-12-20T00:00:00","curr":"EUR",
        "ref_transnumber":"DMORD/00001",
        "notes":"We bought some basic materials for production and sale. It was invoiced on the basis of delivery, but not all were delivered yet.",
        "keys":{"transtype":"invoice","direction":"in","customer_id":"DMCUST/00003","paidtype":"transfer","department":"logistics","transtate": "ok"}},
       {"transnumber":"DMWORK/00001","transdate":(new Date().getFullYear())+"-01-05",
        "duedate":(new Date().getFullYear())+"-01-05T00:00:00","curr":"EUR",
        "empnumber":"DMEMP/00001","trans_wsdistance":200,"trans_wstotal":3,
        "keys":{"transtype":"worksheet","direction":"out","customer_id":"DMCUST/00001","paidtype":"transfer","department":"sales","transtate": "ok"}},
       {"transnumber":"DMRNT/00001","transdate":(new Date().getFullYear())+"-01-01",
        "duedate":(new Date().getFullYear())+"-01-11T00:00:00","curr":"EUR","trans_reholiday":3,
        "keys":{"transtype":"rent","direction":"out","customer_id":"DMCUST/00001","paidtype":"transfer","department":"logistics","transtate": "ok"}}],
     item:[
        {"unit":"piece","qty":40,"fxprice":10,"netamount":400,"vatamount":80,"amount":480,"description":"Wheel",
         "keys":{"trans_id":"DMORD/00001","product_id":"DMPROD/00005","tax_id":"20%"}},
        {"unit":"piece","qty":60,"fxprice":12,"netamount":720,"vatamount":144,"amount":864,"description":"Door",
         "keys":{"trans_id":"DMORD/00001","product_id":"DMPROD/00006","tax_id":"20%"}},
        {"unit":"liter","qty":50,"fxprice":16,"netamount":800,"vatamount":160,"amount":960,"description":"Paint",
         "keys":{"trans_id":"DMORD/00001","product_id":"DMPROD/00007","tax_id":"20%"}},
        {"unit":"piece","qty":20,"fxprice":5,"netamount":100,"vatamount":20,"amount":120,"description":"Pallet",
         "keys":{"trans_id":"DMORD/00001","product_id":"DMPROD/00008","tax_id":"20%"}},
        {"unit":"piece","qty":10,"fxprice":120,"netamount":1200,"vatamount":240,"amount":1440,"description":"Big product",
         "keys":{"trans_id":"DMORD/00001","product_id":"DMPROD/00001","tax_id":"20%"}},
        {"unit":"piece","qty":10,"fxprice":15,"netamount":150,"vatamount":30,"amount":180,"description":"Nice product",
         "keys":{"trans_id":"DMORD/00001","product_id":"DMPROD/00003","tax_id":"20%"}},
        {"unit":"piece","qty":20,"fxprice":8,"netamount":160,"vatamount":32,"amount":192,"description":"Basket",
         "keys":{"trans_id":"DMORD/00001","product_id":"DMPROD/00009","tax_id":"20%"}},
        {"unit":"piece","qty":20,"fxprice":20,"netamount":400,"vatamount":20,"amount":420,"description":"Wine",
         "keys":{"trans_id":"DMORD/00001","product_id":"DMPROD/00010","tax_id":"5%"}},
        {"unit":"piece","qty":20,"fxprice":16,"netamount":320,"vatamount":64,"amount":384,"description":"Chocolate",
         "keys":{"trans_id":"DMORD/00001","product_id":"DMPROD/00011","tax_id":"20%"}},
        {"unit":"piece","qty":2,"fxprice":60,"netamount":120,"vatamount":18,"amount":138,"description":"Souvenir - virtual product",
         "keys":{"trans_id":"DMORD/00002","product_id":"DMPROD/00012","tax_id":"15%"}},
        {"unit":"piece","qty":3,"fxprice":25,"netamount":75,"vatamount":15,"amount":90,"description":"Big product",
         "keys":{"trans_id":"DMORD/00002","product_id":"DMPROD/00001","tax_id":"20%"}},
        {"unit":"hour","qty":1,"fxprice":120,"netamount":120,"vatamount":24,"amount":144,"description":"Very good work!",
         "keys":{"trans_id":"DMORD/00003","product_id":"DMPROD/00002","tax_id":"20%"}},
        {"unit":"piece","qty":3,"fxprice":166.67,"netamount":500,"vatamount":100,"amount":600,"description":"Big product",
         "keys":{"trans_id":"DMORD/00003","product_id":"DMPROD/00001","tax_id":"20%"}},
        {"unit":"piece","qty":5,"fxprice":20,"netamount":100,"vatamount":5,"amount":105,"description":"Nice product",
         "keys":{"trans_id":"DMORD/00003","product_id":"DMPROD/00003","tax_id":"5%"}},
        {"unit":"hour","qty":1,"fxprice":120,"netamount":120,"vatamount":24,"amount":144,"description":"Very good work!",
         "keys":{"trans_id":"DMOFF/00001","product_id":"DMPROD/00002","tax_id":"20%"}},
        {"unit":"piece","qty":3,"fxprice":166.67,"netamount":500,"vatamount":100,"amount":600,"description":"Big product",
         "keys":{"trans_id":"DMOFF/00001","product_id":"DMPROD/00001","tax_id":"20%"}},
        {"unit":"piece","qty":5,"fxprice":20,"netamount":100,"vatamount":5,"amount":105,"description":"Nice product",
         "keys":{"trans_id":"DMOFF/00001","product_id":"DMPROD/00003","tax_id":"5%"}},
        {"unit":"hour","qty":1,"fxprice":120,"netamount":120,"vatamount":24,"amount":144,"description":"Very good work!",
         "keys":{"trans_id":"DMINV/00001","product_id":"DMPROD/00002","tax_id":"20%"}},
        {"unit":"piece","qty":3,"fxprice":166.67,"netamount":500,"vatamount":100,"amount":600,"description":"Big product",
         "keys":{"trans_id":"DMINV/00001","product_id":"DMPROD/00001","tax_id":"20%"}},
        {"unit":"piece","qty":5,"fxprice":20,"netamount":100,"vatamount":5,"amount":105,"description":"Nice product",
         "keys":{"trans_id":"DMINV/00001","product_id":"DMPROD/00003","tax_id":"5%"}},
        {"unit":"piece","qty":2,"fxprice":60,"netamount":120,"vatamount":18,"amount":138,"description":"Souvenir - virtual product",
         "keys":{"trans_id":"DMINV/00002","product_id":"DMPROD/00012","tax_id":"15%"}},
        {"unit":"piece","qty":3,"fxprice":25,"netamount":75,"vatamount":15,"amount":90,"description":"Big product",
         "keys":{"trans_id":"DMINV/00002","product_id":"DMPROD/00001","tax_id":"20%"}},
        {"unit":"piece","qty":30,"fxprice":10,"netamount":300,"vatamount":60,"amount":360,"description":"Wheel",
         "keys":{"trans_id":"DMINV/00003","product_id":"DMPROD/00005","tax_id":"20%"}},
        {"unit":"piece","qty":50,"fxprice":12,"netamount":600,"vatamount":120,"amount":720,"description":"Door",
         "keys":{"trans_id":"DMINV/00003","product_id":"DMPROD/00006","tax_id":"20%"}},
        {"unit":"liter","qty":50,"fxprice":16,"netamount":800,"vatamount":160,"amount":960,"description":"Paint",
         "keys":{"trans_id":"DMINV/00003","product_id":"DMPROD/00007","tax_id":"20%"}},
        {"unit":"piece","qty":15,"fxprice":5,"netamount":75,"vatamount":15,"amount":90,"description":"Pallet",
         "keys":{"trans_id":"DMINV/00003","product_id":"DMPROD/00008","tax_id":"20%"}},
        {"unit":"piece","qty":10,"fxprice":120,"netamount":1200,"vatamount":240,"amount":1440,"description":"Big product",
         "keys":{"trans_id":"DMINV/00003","product_id":"DMPROD/00001","tax_id":"20%"}},
        {"unit":"piece","qty":10,"fxprice":15,"netamount":150,"vatamount":30,"amount":180,"description":"Nice product",
         "keys":{"trans_id":"DMINV/00003","product_id":"DMPROD/00003","tax_id":"20%"}},
        {"unit":"piece","qty":15,"fxprice":8,"netamount":120,"vatamount":24,"amount":144,"description":"Basket",
         "keys":{"trans_id":"DMINV/00003","product_id":"DMPROD/00009","tax_id":"20%"}},
        {"unit":"piece","qty":10,"fxprice":20,"netamount":200,"vatamount":10,"amount":210,"description":"Wine",
         "keys":{"trans_id":"DMINV/00003","product_id":"DMPROD/00010","tax_id":"5%"}},
        {"unit":"piece","qty":20,"fxprice":16,"netamount":320,"vatamount":64,"amount":384,"description":"Chocolate",
         "keys":{"trans_id":"DMINV/00003","product_id":"DMPROD/00011","tax_id":"20%"}},
        {"unit":"hour","qty":2,"fxprice":130,"netamount":260,"vatamount":52,"amount":312,"description":"Good work",
         "keys":{"trans_id":"DMWORK/00001","product_id":"DMPROD/00002","tax_id":"20%"}},
        {"unit":"piece","qty":3,"fxprice":12,"netamount":396,"vatamount":79.2,"amount":475.2,"description":"Pallet",
         "keys":{"trans_id":"DMRNT/00001","product_id":"DMPROD/00008","tax_id":"20%"}}],
     link:[
       {"keys":{"nervatype_1":"trans","ref_id_1":"trans/DMOFF/00001","nervatype_2":"trans","ref_id_2":"trans/DMORD/00003"}},
       {"keys":{"nervatype_1":"trans","ref_id_1":"trans/DMINV/00001","nervatype_2":"trans","ref_id_2":"trans/DMORD/00003"}},
       {"keys":{"nervatype_1":"trans","ref_id_1":"trans/DMINV/00002","nervatype_2":"trans","ref_id_2":"trans/DMORD/00002"}},
       {"keys":{"nervatype_1":"trans","ref_id_1":"trans/DMINV/00003","nervatype_2":"trans","ref_id_2":"trans/DMORD/00001"}}]},
   trans_payment: {
     trans:[
       {"transnumber":"DMPMT/00001","transdate":(new Date().getFullYear())+"-01-15","ref_transnumber":"BM0123456",
        "keys":{"transtype":"bank","direction":"transfer","place_id":"bank","transtate": "ok"}},
       {"transnumber":"DMPMT/00002","transdate":(new Date().getFullYear())-1+"-12-18",
        "keys":{"transtype":"cash","direction":"out","place_id":"cash","transtate": "ok"}}],
      payment:[
        {"paiddate":(new Date().getFullYear())-1+"-12-20","amount":-4000,"notes":"payment two divided...",
         "keys":{"trans_id":"DMPMT/00001"}},
        {"paiddate":(new Date().getFullYear())-1+"-12-20","amount":849,
         "keys":{"trans_id":"DMPMT/00001"}},
        {"paiddate":(new Date().getFullYear())+"-01-10","amount":228,
         "keys":{"trans_id":"DMPMT/00001"}},
        {"paiddate":(new Date().getFullYear())-1+"-12-18","amount":-488,
         "keys":{"trans_id":"DMPMT/00002"}}],
      link:[
        {"link_qty":4000,"link_rate":1,
         "keys":{"nervatype_1":"payment","ref_id_1":"payment/DMPMT/00001~1","nervatype_2":"trans","ref_id_2":"trans/DMINV/00003",}},
        {"link_qty":849,"link_rate":1,
         "keys":{"nervatype_1":"payment","ref_id_1":"payment/DMPMT/00001~2","nervatype_2":"trans","ref_id_2":"trans/DMINV/00001"}},
        {"link_qty":228,"link_rate":1,
         "keys":{"nervatype_1":"payment","ref_id_1":"payment/DMPMT/00001~3","nervatype_2":"trans","ref_id_2":"trans/DMINV/00002"}},
        {"link_qty":488,"link_rate":1,
         "keys":{"nervatype_1":"payment","ref_id_1":"payment/DMPMT/00002~1","nervatype_2":"trans","ref_id_2":"trans/DMINV/00003"}}]},
   trans_movement: {
     trans:[
       {"transnumber":"DMMOVE/00001","transdate":(new Date().getFullYear())-1+"-12-05",
        "notes":"We hand out some working tools to the employee...",
        "keys":{"transtype":"waybill","direction":"out","employee_id":"DMEMP/00001","transtate": "ok"}},
       {"transnumber":"DMDEL/00001","transdate":(new Date().getFullYear())-1+"-11-08",
        "keys":{"transtype":"delivery","direction":"in","transtate": "ok"}},
       {"transnumber":"DMDEL/00002","transdate":(new Date().getFullYear())-1+"-12-10",
        "keys":{"transtype":"delivery","direction":"out","transtate": "ok"}},
       {"transnumber":"DMDEL/00003","transdate":(new Date().getFullYear())-1+"-12-10",
        "keys":{"transtype":"delivery","direction":"out","transtate": "ok"}},
       {"transnumber":"DMDTF/00001","transdate":(new Date().getFullYear())-1+"-11-08",
        "keys":{"transtype":"delivery","direction":"transfer","place_id":"material","transtate": "ok"}},
       {"transnumber":"DMCORR/00001","transdate":(new Date().getFullYear())-1+"-12-01",
        "notes":"Scrapping of some products ...",
        "keys":{"transtype":"inventory","direction":"transfer","place_id":"warehouse","transtate": "ok"}},
       {"transnumber":"DMFRM/00001","transdate":(new Date().getFullYear())-1+"-12-01",
        "notes":"Sample formula (4 door/car)",
        "keys":{"transtype":"formula","direction":"transfer","transtate": "ok"}},
       {"transnumber":"DMFRM/00002","transdate":(new Date().getFullYear())-1+"-12-01",
        "notes":"Sample formula (3 door/car)",
        "keys":{"transtype":"formula","direction":"transfer","transtate": "ok"}},
       {"transnumber":"DMMAKE/00001","transdate":(new Date().getFullYear())-1+"-12-01",
        "duedate":(new Date().getFullYear())-1+"-12-02T00:00:00","notes":"formula: 4 door/car",
        "keys":{"transtype":"production","direction":"transfer","place_id":"warehouse","transtate": "ok"}}],
     movement:[
       {"shippingdate":(new Date().getFullYear())-1+"-12-05T00:00:00",
        "keys":{"trans_id":"DMMOVE/00001","movetype":"tool","tool_id":"DEF-456"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-05T00:00:00","notes":"mobile phone",
        "keys":{"trans_id":"DMMOVE/00001","movetype":"tool","tool_id":"IMEI-023456789"}},
       {"shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00","qty":30,"notes":"demo",
        "keys":{"trans_id":"DMDEL/00001","movetype":"inventory","place_id":"material","product_id":"DMPROD/00005"}},
       {"shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00","qty":50,"notes":"demo",
        "keys":{"trans_id":"DMDEL/00001","movetype":"inventory","place_id":"material","product_id":"DMPROD/00006"}},
       {"shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00","qty":50,"notes":"demo",
        "keys":{"trans_id":"DMDEL/00001","movetype":"inventory","place_id":"material","product_id":"DMPROD/00007"}},
       {"shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00","qty":15,"notes":"demo",
        "keys":{"trans_id":"DMDEL/00001","movetype":"inventory","place_id":"material","product_id":"DMPROD/00008"}},
       {"shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00","qty":10,"notes":"demo",
        "keys":{"trans_id":"DMDEL/00001","movetype":"inventory","place_id":"material","product_id":"DMPROD/00001"}},
       {"shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00","qty":10,"notes":"demo",
        "keys":{"trans_id":"DMDEL/00001","movetype":"inventory","place_id":"material","product_id":"DMPROD/00003"}},
       {"shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00","qty":15,"notes":"demo",
        "keys":{"trans_id":"DMDEL/00001","movetype":"inventory","place_id":"material","product_id":"DMPROD/00009"}},
       {"shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00","qty":10,"notes":"demo",
        "keys":{"trans_id":"DMDEL/00001","movetype":"inventory","place_id":"material","product_id":"DMPROD/00010"}},
       {"shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00","qty":20,"notes":"demo",
        "keys":{"trans_id":"DMDEL/00001","movetype":"inventory","place_id":"material","product_id":"DMPROD/00011"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-10T00:00:00","qty":-2,"notes":"demo",
        "keys":{"trans_id":"DMDEL/00002","movetype":"inventory","place_id":"warehouse","product_id":"DMPROD/00009"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-10T00:00:00","qty":-2,"notes":"demo",
        "keys":{"trans_id":"DMDEL/00002","movetype":"inventory","place_id":"warehouse","product_id":"DMPROD/00010"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-10T00:00:00","qty":-4,"notes":"demo",
        "keys":{"trans_id":"DMDEL/00002","movetype":"inventory","place_id":"warehouse","product_id":"DMPROD/00011"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-10T00:00:00","qty":-3,"notes":"demo",
        "keys":{"trans_id":"DMDEL/00002","movetype":"inventory","place_id":"warehouse","product_id":"DMPROD/00001"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-10T00:00:00","qty":-3,"notes":"demo",
        "keys":{"trans_id":"DMDEL/00003","movetype":"inventory","place_id":"warehouse","product_id":"DMPROD/00001"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-10T00:00:00","qty":-5,"notes":"demo",
        "keys":{"trans_id":"DMDEL/00003","movetype":"inventory","place_id":"warehouse","product_id":"DMPROD/00003"}},
       {"shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00","qty":-10,"notes":"demo",
        "keys":{"trans_id":"DMDTF/00001","movetype":"inventory","place_id":"material","product_id":"DMPROD/00001"}},
       {"shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00","qty":10,"notes":"demo",
        "keys":{"trans_id":"DMDTF/00001","movetype":"inventory","place_id":"warehouse","product_id":"DMPROD/00001"}},
       {"shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00","qty":-10,"notes":"demo",
        "keys":{"trans_id":"DMDTF/00001","movetype":"inventory","place_id":"material","product_id":"DMPROD/00003"}},
       {"shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00","qty":10,"notes":"demo",
        "keys":{"trans_id":"DMDTF/00001","movetype":"inventory","place_id":"warehouse","product_id":"DMPROD/00003"}},
       {"shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00","qty":-15,"notes":"demo",
        "keys":{"trans_id":"DMDTF/00001","movetype":"inventory","place_id":"material","product_id":"DMPROD/00009"}},
       {"shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00","qty":15,"notes":"demo",
        "keys":{"trans_id":"DMDTF/00001","movetype":"inventory","place_id":"warehouse","product_id":"DMPROD/00009"}},
       {"shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00","qty":-10,"notes":"demo",
        "keys":{"trans_id":"DMDTF/00001","movetype":"inventory","place_id":"material","product_id":"DMPROD/00010"}},
       {"shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00","qty":10,"notes":"demo",
        "keys":{"trans_id":"DMDTF/00001","movetype":"inventory","place_id":"warehouse","product_id":"DMPROD/00010"}},
       {"shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00","qty":-20,"notes":"demo",
        "keys":{"trans_id":"DMDTF/00001","movetype":"inventory","place_id":"material","product_id":"DMPROD/00011"}},
       {"shippingdate":(new Date().getFullYear())-1+"-11-08T00:00:00","qty":20,"notes":"demo",
        "keys":{"trans_id":"DMDTF/00001","movetype":"inventory","place_id":"warehouse","product_id":"DMPROD/00011"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-01T00:00:00","qty":-2,"notes":"demo",
        "keys":{"trans_id":"DMCORR/00001","movetype":"inventory","place_id":"warehouse","product_id":"DMPROD/00001"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-01T00:00:00","qty":-3,"notes":"demo",
        "keys":{"trans_id":"DMCORR/00001","movetype":"inventory","place_id":"warehouse","product_id":"DMPROD/00010"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-01T00:00:00","qty":5,"shared":0,
        "keys":{"trans_id":"DMFRM/00001","movetype":"head","product_id":"DMPROD/00004"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-01T00:00:00","qty":20,"shared":0,
        "keys":{"trans_id":"DMFRM/00001","movetype":"plan","product_id":"DMPROD/00005","place_id":"material"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-01T00:00:00","qty":20,"shared":0,
        "keys":{"trans_id":"DMFRM/00001","movetype":"plan","product_id":"DMPROD/00006","place_id":"material"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-01T00:00:00","qty":30,"shared":0,
        "keys":{"trans_id":"DMFRM/00001","movetype":"plan","product_id":"DMPROD/00007","place_id":"material"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-01T00:00:00","qty":1,"shared":1,
        "keys":{"trans_id":"DMFRM/00001","movetype":"plan","product_id":"DMPROD/00008","place_id":"material"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-01T00:00:00","qty":5,"shared":0,
        "keys":{"trans_id":"DMFRM/00002","movetype":"head","product_id":"DMPROD/00004"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-01T00:00:00","qty":20,"shared":0,
        "keys":{"trans_id":"DMFRM/00002","movetype":"plan","product_id":"DMPROD/00005","place_id":"material"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-01T00:00:00","qty":15,"shared":0,
        "keys":{"trans_id":"DMFRM/00002","movetype":"plan","product_id":"DMPROD/00006"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-01T00:00:00","qty":28,"shared":0,
        "keys":{"trans_id":"DMFRM/00002","movetype":"plan","product_id":"DMPROD/00007","place_id":"material"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-01T00:00:00","qty":1,"shared":1,"notes":"demo",
        "keys":{"trans_id":"DMFRM/00002","movetype":"plan","product_id":"DMPROD/00008","place_id":"material"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-02T00:00:00","qty":2,"shared":1,"notes":"demo",
        "keys":{"trans_id":"DMMAKE/00001","movetype":"inventory","product_id":"DMPROD/00004","place_id":"warehouse"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-01T00:00:00","qty":-8,"shared":0,"notes":"demo",
        "keys":{"trans_id":"DMMAKE/00001","movetype":"inventory","product_id":"DMPROD/00005","place_id":"material"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-01T00:00:00","qty":-8,"shared":0,"notes":"demo",
        "keys":{"trans_id":"DMMAKE/00001","movetype":"inventory","product_id":"DMPROD/00006","place_id":"material"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-01T00:00:00","qty":-12,"shared":0,"notes":"demo",
        "keys":{"trans_id":"DMMAKE/00001","movetype":"inventory","product_id":"DMPROD/00007","place_id":"material"}},
       {"shippingdate":(new Date().getFullYear())-1+"-12-01T00:00:00","qty":-1,"shared":0,"notes":"demo",
        "keys":{"trans_id":"DMMAKE/00001","movetype":"inventory","product_id":"DMPROD/00008","place_id":"material"}}],
     link:[
       {"keys":{"nervatype_1":"movement","ref_id_1":"movement/DMDEL/00001~1","nervatype_2":"item","ref_id_2":"item/DMORD/00001~1"}},
       {"keys":{"nervatype_1":"movement","ref_id_1":"movement/DMDEL/00001~1","nervatype_2":"item","ref_id_2":"item/DMORD/00001~1"}},
       {"keys":{"nervatype_1":"movement","ref_id_1":"movement/DMDEL/00001~2","nervatype_2":"item","ref_id_2":"item/DMORD/00001~2"}},
       {"keys":{"nervatype_1":"movement","ref_id_1":"movement/DMDEL/00001~3","nervatype_2":"item","ref_id_2":"item/DMORD/00001~3"}},
       {"keys":{"nervatype_1":"movement","ref_id_1":"movement/DMDEL/00001~4","nervatype_2":"item","ref_id_2":"item/DMORD/00001~4"}},
       {"keys":{"nervatype_1":"movement","ref_id_1":"movement/DMDEL/00001~5","nervatype_2":"item","ref_id_2":"item/DMORD/00001~5"}},
       {"keys":{"nervatype_1":"movement","ref_id_1":"movement/DMDEL/00001~6","nervatype_2":"item","ref_id_2":"item/DMORD/00001~6"}},
       {"keys":{"nervatype_1":"movement","ref_id_1":"movement/DMDEL/00001~7","nervatype_2":"item","ref_id_2":"item/DMORD/00001~7"}},
       {"keys":{"nervatype_1":"movement","ref_id_1":"movement/DMDEL/00001~8","nervatype_2":"item","ref_id_2":"item/DMORD/00001~8"}},
       {"keys":{"nervatype_1":"movement","ref_id_1":"movement/DMDEL/00001~9","nervatype_2":"item","ref_id_2":"item/DMORD/00001~9"}},
       {"keys":{"nervatype_1":"movement","ref_id_1":"movement/DMDEL/00002~1","nervatype_2":"item","ref_id_2":"item/DMORD/00002~1"}},
       {"keys":{"nervatype_1":"movement","ref_id_1":"movement/DMDEL/00002~2","nervatype_2":"item","ref_id_2":"item/DMORD/00002~1"}},
       {"keys":{"nervatype_1":"movement","ref_id_1":"movement/DMDEL/00002~3","nervatype_2":"item","ref_id_2":"item/DMORD/00002~1"}},
       {"keys":{"nervatype_1":"movement","ref_id_1":"movement/DMDEL/00002~4","nervatype_2":"item","ref_id_2":"item/DMORD/00002~2"}},
       {"keys":{"nervatype_1":"movement","ref_id_1":"movement/DMDEL/00003~1","nervatype_2":"item","ref_id_2":"item/DMORD/00003~2"}},
       {"keys":{"nervatype_1":"movement","ref_id_1":"movement/DMDEL/00003~2","nervatype_2":"item","ref_id_2":"item/DMORD/00003~3"}},
       {"keys":{"nervatype_1":"movement","ref_id_1":"movement/DMDTF/00001~1","nervatype_2":"movement","ref_id_2":"movement/DMDTF/00001~2"}},
       {"keys":{"nervatype_1":"movement","ref_id_1":"movement/DMDTF/00001~3","nervatype_2":"movement","ref_id_2":"movement/DMDTF/00001~4"}},
       {"keys":{"nervatype_1":"movement","ref_id_1":"movement/DMDTF/00001~5","nervatype_2":"movement","ref_id_2":"movement/DMDTF/00001~6"}},
       {"keys":{"nervatype_1":"movement","ref_id_1":"movement/DMDTF/00001~7","nervatype_2":"movement","ref_id_2":"movement/DMDTF/00001~8"}},
       {"keys":{"nervatype_1":"movement","ref_id_1":"movement/DMDTF/00001~9","nervatype_2":"movement","ref_id_2":"movement/DMDTF/00001~10"}}]},
     menu:{
       ui_menu:[
         {"menukey":"mnu_exp_1", "description":"Server function example", "funcname":"callMenuCmd", "url":0},
         {"menukey":"mnu_exp_2", "description":"Server URL example", "funcname":"ndi/getVernum", "url":1},
         {"menukey":"mnu_exp_3", "description":"Internet URL example", "funcname":"search", "url":1, 
          "address":"https://www.google.com"}],
       ui_menufields:[
         {"fieldname":"number_1", "description":"first number","orderby":0,
          "keys":{"menu_id":"mnu_exp_1","fieldtype":"float"}},
         {"fieldname":"number_2", "description":"second number","orderby":1,
          "keys":{"menu_id":"mnu_exp_1","fieldtype":"float"}},
         {"fieldname":"q", "description":"google search","orderby":0,
          "keys":{"menu_id":"mnu_exp_3","fieldtype":"string"}}]}
}
