/*
This file is part of the Nervatura Framework
http://www.nervatura.com
Copyright © 2011-2019, Csaba Kappel
License: LGPLv3
https://raw.githubusercontent.com/nervatura/nervatura/master/LICENSE
*/

module.exports = {
  model: {
    groups: {
      _access:['setting'],
      _key:['groupname', 'groupvalue'],
      id: {type:'id'},
      groupname: {type:'string', length:150, notnull:true},
      groupvalue: {type:'string', length:150, notnull:true},
      description: {type:'text'},
      inactive: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      deleted: {type:'integer', default:0, notnull:true, requires:{bool:true}}
    },
    
    ui_language: {
      _access:['setting'],
      _key:['lang'],
      id: {type:'id'},
      lang: {type:'string', length:2, notnull:true, unique:true},
      description: {type:'string', length:150}
    },
  
    ui_menu: {
      _access:['setting'],
      _key:['menukey'],
      id: {type:'id'},
      menukey: {type:'string', length:255, notnull:true, unique:true},
      description: {type:'string', length:255, notnull:true},
      modul: {type:'string', length:255},
      icon: {type:'string', length:255},
      funcname: {type:'string', length:255, notnull:true},
      url: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      address: {type:'text'}
    },
      
    ui_menufields: {
      _access:['setting'],
      _key:['menukey', 'fieldname'],
      id: {type:'id'},
      menu_id: {references:['ui_menu','CASCADE'], notnull:true, refname:'menukey'},
      fieldname: {type:'string', length:150, notnull:true},
      description: {type:'string', length:255, notnull:true},
      fieldtype: {references:['groups','RESTRICT','NO ACTION'], notnull:true, 
        requires:{fieldtype:['bool','date','integer','float','string']}},
      orderby: {type:'integer', default:0, notnull:true}
    },
        
    ui_message: {
      _access:['setting'],
      _key:['secname', 'fieldname', 'lang'],
      id: {type:'id'},
      secname: {type:'string', length:150, notnull:true},
      fieldname: {type:'string', length:150, notnull:true},
      lang: {type:'string', length:2},
      msg: {type:'text', notnull:true}
    },
  
    ui_report: {
      _access:['setting'],
      _key:['reportkey'],
      id: {type:'id'},                   
      reportkey: {type:'string', length:255, notnull:true, unique:true},
      nervatype: {references:['groups','RESTRICT','NO ACTION'], notnull:true, requires:{nervatype:[]}},
      transtype: {references:['groups','RESTRICT','NO ACTION'], requires:{transtype:[]}},
      direction: {references:['groups','RESTRICT','NO ACTION'], requires:{direction:[]}},
      repname: {type:'string', length:255, notnull:true},
      description: {type:'string', length:255},
      label: {type:'string', length:255},
      filetype: {references:['groups','RESTRICT','NO ACTION'], notnull:true, requires:{filetype:[]}},
      report: {type:'text'}
    },
  
    ui_reportfields: {
      _access:['setting'],
      _key:['reportkey', 'fieldname'],
      id: {type:'id'},
      report_id: {references:['ui_report','CASCADE'], notnull:true, refname:'reportkey'},
      fieldname: {type:'string', length:150, notnull:true},
      fieldtype: {references:['groups','RESTRICT','NO ACTION'], notnull:true, requires:{fieldtype:[]}},
      wheretype: {references:['groups','RESTRICT','NO ACTION'], notnull:true, requires:{wheretype:[]}},
      description: {type:'string', length:255},
      orderby: {type:'integer', default:0, notnull:true},
      sqlstr: {type:'text'},
      parameter: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      dataset: {type:'string', length:150},
      defvalue: {type:'string', length:255},
      valuelist: {type:'text'}
    },
  
    ui_reportsources: {
      _access:['setting'],
      _key:['reportkey', 'dataset'],
      id: {type:'id'},
      report_id: {references:['ui_report','CASCADE'], notnull:true, refname:'reportkey'},
      dataset: {type:'string', length:150, notnull:true},
      sqlstr: {type:'text'}
    },
    
    employee: {
      _access:['employee'],
      _key:['empnumber'],
      id: {type:'id'},
      empnumber: {type:'string', length:150, notnull:true, unique:true, default:'nextnumber'},
      username: {type:'string', length:150, unique:true},
      usergroup: {references:['groups','RESTRICT','NO ACTION'], notnull:true, requires:{usergroup:[]}},
      startdate: {type:'date'},
      enddate: {type:'date'},
      department: {references:['groups','RESTRICT','NO ACTION'], requires:{department:[]}},
      password: {type:'password', length:512},
      registration_key: {type:'string', length:512},
      inactive: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      deleted: {type:'integer', default:0, notnull:true, requires:{bool:true}}
    },
  
    ui_printqueue: {
      _access:['setting'],
      _key:[],
      id: {type:'id'},
      nervatype: {references:['groups','CASCADE'], notnull:true, requires:{nervatype:[]}},
      ref_id: {type:'integer', notnull:true},
      qty: {type:'float', default:0, notnull:true},
      employee_id: {references:['employee','CASCADE','NO ACTION'], notnull:true, refname:'empnumber'},
      report_id: {references:['ui_report','CASCADE','NO ACTION'], notnull:true, refname:'reportkey'},
      crdate: {type:'datetime', notnull:true}//, default:'CURRENT_TIMESTAMP'}
    },
  
    ui_userconfig: {
      _access:['setting'],
      _key:['empnumber', 'section', 'cfgroup', 'cfname'],
      id: {type:'id'},
      employee_id: {references:['employee','CASCADE'], notnull:true, refname:'empnumber'},
      section: {type:'string', length:150},
      cfgroup: {type:'string', length:150, notnull:true},
      cfname: {type:'string', length:150, notnull:true},
      cfvalue: {type:'text'},
      orderby: {type:'integer', default:0, notnull:true}
    },
  
    link: {
      _access:['address', 'barcode', 'contact', 'currency', 'customer', 'employee', 'event', 'groups', 'item', 
        'movement', 'payment', 'price', 'place', 'product', 'project', 'rate', 'tax', 'tool', 'trans', 'setting'],
      _key:['nervatype1', 'refnumber1', 'nervatype2', 'refnumber2'],
      id: {type:'id'},
      nervatype_1: {references:['groups','RESTRICT','NO ACTION'], notnull:true, requires:{nervatype:[]}, refname:'nervatype1'},
      ref_id_1: {type:'integer', notnull:true, refname:'refnumber1'},
      nervatype_2: {references:['groups','RESTRICT','NO ACTION'], notnull:true, requires:{nervatype:[]}, refname:'nervatype2'},
      ref_id_2: {type:'integer', notnull:true, refname:'refnumber2'},
      deleted: {type:'integer', default:0, notnull:true, requires:{bool:true}}
    },
  
    ui_audit: {
      _access:['setting'],
      _key:['usergroup', 'nervatype', 'subtype'],
      id: {type:'id'},
      usergroup: {references:['groups','CASCADE'], notnull:true, requires:{usergroup:[]}},
      nervatype: {references:['groups','RESTRICT','NO ACTION'], notnull:true, requires:{nervatype:[]}},
      subtype: {type:'integer'},
      inputfilter: {references:['groups','RESTRICT','NO ACTION'], notnull:true, requires:{inputfilter:[]}},
      supervisor: {type:'integer', default:1, notnull:true, requires:{bool:true}}
    },
  
    deffield: {
      _access:['setting'],
      _key:['fieldname'],
      id: {type:'id'},
      fieldname: {type:'string', length:150, notnull:true, unique:true},
      nervatype: {references:['groups','RESTRICT','NO ACTION'], notnull:true, 
        requires:{nervatype:['address', 'barcode', 'contact', 'currency', 'customer', 'employee', 'event', 'item', 'link', 
          'log', 'movement', 'payment', 'price', 'place', 'product', 'project', 'rate', 'tax', 'tool', 'trans', 'setting']}},
      subtype: {references:['groups','RESTRICT','NO ACTION'], 
        requires:{custtype:[],placetype:[],protype:[],toolgroup:[],transtype:[]}},
      fieldtype: {references:['groups','RESTRICT','NO ACTION'], notnull:true, requires:{fieldtype:[]}},
      description: {type:'text', notnull:true},
      valuelist: {type:'text'},
      addnew: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      visible: {type:'integer', default:1, notnull:true, requires:{bool:true}},
      readonly: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      deleted: {type:'integer', default:0, notnull:true, requires:{bool:true}}
    },
  
    fieldvalue: {
      _access:['address', 'barcode', 'contact', 'currency', 'customer', 'employee', 
        'event', 'groups', 'item', 'link', 'log', 'movement', 'price', 'place', 'product', 
        'project', 'rate', 'tax', 'tool', 'trans', 'setting'],
      _key:['fieldname', 'refnumber', 'rownumber'],
      id: {type:'id'},
      fieldname: {type:'string', length:150},
      ref_id: {type:'integer', refname:'refnumber'},
      value: {type:'text'},
      notes: {type:'text'},
      deleted: {type:'integer', default:0, notnull:true, requires:{bool:true}}
    },
  
    log: {
      _access:['setting'],
      _key:['empnumber', 'crdate'],
      id: {type:'id'},
      employee_id: {references:['employee','RESTRICT','NO ACTION'], notnull:true, refname:'empnumber'},
      crdate: {type:'datetime', notnull:true}, //default:'CURRENT_TIMESTAMP'},
      nervatype: {references:['groups','RESTRICT','NO ACTION'], 
        requires:{nervatype:['address', 'barcode', 'contact', 'currency', 'customer', 'employee', 'deffield', 'event', 'groups', 
          'item', 'link', 'movement', 'payment', 'price', 'place', 'product', 'project', 'rate', 'tax', 'tool', 'trans', 'setting']}},
      ref_id: {type:'integer', refname:'refnumber'},
      logstate: {references:['groups','CASCADE'], notnull:true, requires:{logstate:[]}}
    },
      
    numberdef: {
      _access:['setting'],
      _key:['numberkey'],
      id: {type:'id'},
      numberkey: {type:'string', length:150, notnull:true, unique:true},
      prefix: {type:'string', length:150},
      curvalue: {type:'integer', default:0, notnull:true},
      isyear: {type:'integer', default:1, notnull:true, requires:{bool:true}},
      sep: {type:'string', length:1, default:"'/'", notnull:true},
      len: {type:'integer', default:5, notnull:true},
      description: {type:'text'},
      visible: {type:'integer', default:1, notnull:true, requires:{bool:true}},
      readonly: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      orderby: {type:'integer', default:0, notnull:true}
    },
        
    address: {
      _access:['customer','employee','event','place','product','project','tool','trans'],
      _key:['nervatype', 'refnumber', 'rownumber'],
      id: {type:'id'},
      nervatype: {references:['groups','RESTRICT','NO ACTION'], notnull:true, 
        requires:{nervatype:['customer', 'employee', 'event', 'place', 'product', 'project', 'tool', 'trans']}},
      ref_id: {type:'integer', notnull:true, refname:'refnumber'},
      country: {type:'string', length:255},
      state: {type:'string', length:255},
      zipcode: {type:'string', length:150},
      city: {type:'string', length:255},
      street: {type:'text'},
      notes: {type:'text'},
      deleted: {type:'integer', default:0, notnull:true, requires:{bool:true}}
    },
        
    contact: {
      _access:['customer','employee','event','place','product','project','tool','trans'],
      _key:['nervatype', 'refnumber', 'rownumber'],
      id: {type:'id'},
      nervatype: {references:['groups','RESTRICT','NO ACTION'], notnull:true,
        requires:{nervatype:['customer', 'employee', 'event', 'place', 'product', 'project', 'tool', 'trans']}},
      ref_id: {type:'integer', notnull:true, refname:'refnumber'},
      firstname: {type:'string', length:255},
      surname: {type:'string', length:255},
      status: {type:'string', length:255},
      phone: {type:'string', length:255},
      fax: {type:'string', length:255},
      mobil: {type:'string', length:255},
      email: {type:'string', length:255},
      notes: {type:'text'},
      deleted: {type:'integer', default:0, notnull:true, requires:{bool:true}}
    },
  
    event: {
      _access:['customer', 'employee', 'place', 'product', 'project', 'tool', 'trans'],
      _key:['calnumber'],
      id: {type:'id'},
      calnumber: {type:'string', length:150, notnull:true, unique:true, default:'nextnumber'},
      nervatype: {references:['groups','RESTRICT','NO ACTION'], notnull:true,
        requires:{nervatype:['customer', 'employee', 'place', 'product', 'project', 'tool', 'trans']}},
      ref_id: {type:'integer', notnull:true, refname:'refnumber'},
      uid: {type:'string', length:255},
      eventgroup: {references:['groups','CASCADE'], requires:{eventgroup:[]}},
      fromdate: {type:'datetime'},
      todate: {type:'datetime'},
      subject: {type:'string', length:255},
      place: {type:'string', length:255},
      description: {type:'text'},
      deleted: {type:'integer', default:0, notnull:true, requires:{bool:true}}
    },
          
    customer: {
      _access:['customer'],
      _key:['custnumber'],
      id: {type:'id'},
      custtype: {references:['groups','RESTRICT','NO ACTION'], notnull:true, requires:{custtype:[]}},
      custnumber: {type:'string', length:150, notnull:true, unique:true, default:'nextnumber'},
      custname: {type:'string', length:255, notnull:true},
      taxnumber: {type:'string', length:255},
      account: {type:'string', length:255},
      notax: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      terms: {type:'integer', default:0, notnull:true},
      creditlimit: {type:'float', default:0, notnull:true},
      discount: {type:'float', default:0, notnull:true},
      notes: {type:'text'},
      inactive: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      deleted: {type:'integer', default:0, notnull:true}
    },
  
    project: {
      _access:['project'],
      _key:['pronumber'],
      id: {type:'id'},
      pronumber: {type:'string', length:150, notnull:true, unique:true, default:'nextnumber'},
      description: {type:'string', length:255, notnull:true},
      customer_id: {references:['customer','RESTRICT','CASCADE'], refname:'custnumber'},
      startdate: {type:'date'},
      enddate: {type:'date'},
      notes: {type:'text'},
      inactive: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      deleted: {type:'integer', default:0, notnull:true, requires:{bool:true}}
    },
        
    currency: {
      _access:['setting'],
      _key:['curr'],
      id: {type:'id'},
      curr: {type:'string', length:3, notnull:true, unique:true},
      description: {type:'string', length:255, notnull:true},
      digit: {type:'integer', default:0, notnull:true},
      defrate: {type:'float', default:0, notnull:true},
      cround: {type:'integer', default:0, notnull:true}
    },
        
    place: {
      _access:['setting'],
      _key:['planumber'],
      id: {type:'id'},
      planumber: {type:'string', length:150, notnull:true, unique:true, default:'nextnumber'},
      placetype: {references:['groups','RESTRICT','NO ACTION'], notnull:true, requires:{placetype:[]}},
      description: {type:'string', length:255, notnull:true},
      curr: {type:'string', length:3, requires:{curr:[]}},
      defplace: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      notes: {type:'text'},
      inactive: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      deleted: {type:'integer', default:0, notnull:true, requires:{bool:true}}
    },
  
    rate: {
      _access:['setting'],
      _key:['ratetype', 'ratedate', 'curr', 'planumber'],
      id: {type:'id'},
      ratetype: {references:['groups','RESTRICT','NO ACTION'], notnull:true, requires:{ratetype:[]}},
      ratedate: {type:'date', notnull:true},
      curr: {type:'string', length:3, notnull:true, requires:{curr:[]}},
      place_id: {references:['place','RESTRICT','CASCADE'], refname:'planumber'},
      rategroup: {references:['groups','RESTRICT','NO ACTION'], requires:{rategroup:[]}},
      ratevalue: {type:'float', default:0, notnull:true},
      deleted: {type:'integer', default:0, notnull:true, requires:{bool:true}}
    },
  
    tax: {
      _access:['setting'],
      _key:['taxcode'],
      id: {type:'id'},
      taxcode: {type:'string', length:150, notnull:true, unique:true},                
      description: {type:'string', length:255, notnull:true},
      rate: {type:'float', default:0, notnull:true},
      inactive: {type:'integer', default:0, notnull:true, requires:{bool:true}}
    },
  
    product: {
      _access:['product'],
      _key:['partnumber'],
      id: {type:'id'},
      partnumber: {type:'string', length:150, notnull:true, unique:true, default:'nextnumber'},
      protype: {references:['groups','RESTRICT','NO ACTION'], notnull:true, requires:{protype:[]}},
      description: {type:'string', length:255, notnull:true},
      unit: {type:'string', length:150, notnull:true},
      tax_id: {references:['tax','RESTRICT','CASCADE'], refname:'taxcode'},
      notes: {type:'text'},
      webitem: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      inactive: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      deleted: {type:'integer', default:0, notnull:true, requires:{bool:true}}
    },
  
    tool: {
      _access:['tool'],
      _key:['serial'],
      id: {type:'id'},
      serial: {type:'string', length:150, notnull:true, unique:true, default:'nextnumber'},
      description: {type:'text', notnull:true},
      product_id: {references:['product','RESTRICT','CASCADE'], refname:'partnumber', notnull:true},
      toolgroup: {references:['groups','RESTRICT','NO ACTION'], requires:{toolgroup:[]}},
      notes: {type:'text'},
      inactive: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      deleted: {type:'integer', default:0, notnull:true, requires:{bool:true}}
    },
  
    price: {
      _access:['product'],
      _key:['partnumber', 'validfrom', 'curr', 'qty'],
      id: {type:'id'},
      product_id: {references:['product','CASCADE'], refname:'partnumber'},
      validfrom: {type:'date', notnull:true},
      validto: {type:'date'},
      curr: {type:'string', length:3, notnull:true, requires:{curr:[]}},
      qty: {type:'float', default:0},
      pricevalue: {type:'float', default:0, notnull:true},
      discount: {type:'float'},
      calcmode: {references:['groups','RESTRICT','NO ACTION'], requires:{calcmode:[]}},
      vendorprice: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      deleted: {type:'integer', default:0, notnull:true, requires:{bool:true}}
    },
  
    barcode: {
      _access:['product'],
      _key:['code'],
      id: {type:'id'},
      code: {type:'string', length:255, notnull:true, unique:true},
      product_id: {references:['product','CASCADE'], notnull:true, refname:'partnumber'},
      description: {type:'text'},
      barcodetype: {references:['groups','RESTRICT','NO ACTION'], notnull:true, requires:{barcodetype:[]}},
      qty: {type:'float', default:0, notnull:true},
      defcode: {type:'integer', default:0, notnull:true, requires:{bool:true}}
    },
  
    trans: {
      _access:['transtype'],
      _key:['transnumber'],
      id: {type:'id'},
      transnumber: {type:'string', length:150, notnull:true, unique:true, default:'nextnumber'},
      transtype: {references:['groups','RESTRICT','NO ACTION'], notnull:true, requires:{transtype:[]}},
      direction: {references:['groups','RESTRICT','NO ACTION'], notnull:true, requires:{direction:[]}},
      ref_transnumber: {type:'string', length:150},
      crdate: {type:'date', notnull:true},
      transdate: {type:'date', notnull:true},
      duedate: {type:'datetime'},
      customer_id: {references:['customer','RESTRICT','NO ACTION'], refname:'custnumber'},
      employee_id: {references:['employee','RESTRICT','NO ACTION'], refname:'empnumber'},
      department: {references:['groups','RESTRICT','NO ACTION'], requires:{department:[]}},
      project_id: {references:['project','RESTRICT','NO ACTION'], refname:'pronumber'},
      place_id: {references:['place','RESTRICT','NO ACTION'], refname:'planumber'},
      paidtype: {references:['groups','RESTRICT','NO ACTION'], requires:{paidtype:[]}},
      curr: {type:'string', length:3, requires:{curr:[]}},
      notax: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      paid: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      acrate: {type:'float', default:0},
      notes: {type:'text'},
      intnotes: {type:'text'},
      fnote: {type:'text'},
      transtate: {references:['groups','RESTRICT','NO ACTION'], notnull:true, requires:{transtate:[]}},
      closed: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      deleted: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      cruser_id: {references:['employee','RESTRICT','NO ACTION'], refname:'username'}
    },
  
    item: {
      _access:['transtype'],
      _key:['transnumber', 'rownumber'],
      id: {type:'id'},
      trans_id: {references:['trans','CASCADE'], refname:'transnumber', notnull:true},
      product_id: {references:['product','CASCADE'], refname:'partnumber', notnull:true},
      unit: {type:'string', length:150, notnull:true},
      qty: {type:'float', default:0, notnull:true},
      fxprice: {type:'float', default:0, notnull:true},
      netamount: {type:'float', default:0, notnull:true},
      discount: {type:'float', default:0, notnull:true, requires:{min:0, max:100}},
      tax_id: {references:['tax','CASCADE','NO ACTION'], refname:'taxcode'},
      vatamount: {type:'float', default:0, notnull:true},
      amount: {type:'float', default:0, notnull:true},
      description: {type:'text', notnull:true},
      deposit: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      ownstock: {type:'float', default:0, notnull:true},
      actionprice: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      deleted: {type:'integer', default:0, notnull:true, requires:{bool:true}}
    },
  
    payment: {
      _access:['transtype'],
      _key:['transnumber', 'rownumber'],
      id: {type:'id'},
      trans_id: {references:['trans','CASCADE'], refname:'transnumber'},
      paiddate: {type:'date', notnull:true},
      amount: {type:'float', default:0, notnull:true},
      notes: {type:'text'},
      deleted: {type:'integer', default:0, notnull:true, requires:{bool:true}}
    },
  
    movement: {
      _access:['transtype'],
      _key:['transnumber', 'rownumber'],
      id: {type:'id'},
      trans_id: {references:['trans','CASCADE'], refname:'transnumber'},
      shippingdate: {type:'datetime', notnull:true},
      movetype: {references:['groups','RESTRICT','NO ACTION'], notnull:true, requires:{movetype:[]}},
      product_id: {references:['product','RESTRICT','NO ACTION'], refname:'partnumber'},
      tool_id: {references:['tool','RESTRICT','NO ACTION'], refname:'serial'},
      place_id: {references:['place','RESTRICT','NO ACTION'], refname:'planumber'},
      qty: {type:'float', default:0, notnull:true},
      notes: {type:'text'},
      shared: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      deleted: {type:'integer', default:0, notnull:true, requires:{bool:true}}
    },
  
    pattern: {
      _access:['setting'],
      _key:['description'],
      id: {type:'id'},
      description: {type:'string', length:150, notnull:true, unique:true},
      transtype: {references:['groups','RESTRICT','NO ACTION'], notnull:true, requires:{transtype:[]}},
      notes: {type:'text'},
      defpattern: {type:'integer', default:0, notnull:true, requires:{bool:true}},
      deleted: {type:'integer', default:0, notnull:true, requires:{bool:true}}
    }
  },
			  
  index:{
    groups_namevalue_idx: {model:'groups', fields:['groupname', 'groupvalue'], unique:true},
    groups_groupname_idx: {model:'groups', fields:['groupname'], unique:false},
    groups_groupvalue_idx: {model:'groups', fields:['groupvalue'], unique:false},
    groups_inactive_idx: {model:'groups', fields:['inactive'], unique:false},
    groups_deleted_idx: {model:'groups', fields:['deleted'], unique:false},
    
    menucmd_menukey_idx: {model:'ui_menu', fields:['menukey'], unique:true},
    menucmd_modul_idx: {model:'ui_menu', fields:['modul'], unique:false},
        
    menufields_menu_idx: {model:'ui_menufields', fields:['menu_id'], unique:false},
    
    message_pk_idx: {model:'ui_message', fields:['secname', 'fieldname', 'lang'], unique:true},
    message_fieldname_idx: {model:'ui_message', fields:['fieldname'], unique:false},
    message_lang_idx: {model:'ui_message', fields:['lang'], unique:false},
    message_secname_idx: {model:'ui_message', fields:['secname'], unique:false},
    
    report_reportkey_idx: {model:'ui_report', fields:['reportkey'], unique:true},
    report_filetype_idx: {model:'ui_report', fields:['filetype'], unique:false},
    report_reporttype_idx: {model:'ui_report', fields:['nervatype'], unique:false},
    
    reportfields_pk_idx: {model:'ui_reportfields', fields:['report_id', 'fieldname'], unique:true},
    reportfields_report_id_idx: {model:'ui_reportfields', fields:['report_id'], unique:false},
    
    reportsources_pk_idx: {model:'ui_reportsources', fields:['report_id', 'dataset'], unique:true},
    reportsources_reports_idx: {model:'ui_reportsources', fields:['report_id'], unique:false},
    
    employee_empnumber_idx: {model:'employee', fields:['empnumber'], unique:true},
    employee_username_idx: {model:'employee', fields:['username'], unique:true},
    employee_inactiv_idx: {model:'employee', fields:['inactive'], unique:false},
    employee_deleted_idx: {model:'employee', fields:['deleted'], unique:false},
    
    printqueue_nervatype_idx: {model:'ui_printqueue', fields:['nervatype'], unique:false},
    printqueue_usename_idx: {model:'ui_printqueue', fields:['employee_id'], unique:false},
  
    idx_userconfig_pk: {model:'ui_userconfig', fields:['employee_id', 'cfgroup', 'cfname'], unique:false},
    idx_userconfig_ec: {model:'ui_userconfig', fields:['employee_id', 'cfgroup'], unique:false},
    idx_userconfig_employee_ide: {model:'ui_userconfig', fields:['employee_id'], unique:false},
  
    idx_link_nervatype_1: {model:'link', fields:['nervatype_1'], unique:false},
    idx_link_ref_id_1: {model:'link', fields:['ref_id_1'], unique:false},
    idx_link_nervatype_2: {model:'link', fields:['nervatype_2'], unique:false},
    idx_link_ref_id_2: {model:'link', fields:['ref_id_2'], unique:false},
    idx_link_deleted: {model:'link', fields:['deleted'], unique:false},
    
    idx_audit_pk: {model:'ui_audit', fields:['usergroup', 'nervatype', 'subtype'], unique:true},
    idx_audit_usergroup: {model:'ui_audit', fields:['usergroup'], unique:false},
    
    deffield_fieldname_idx: {model:'deffield', fields:['fieldname'], unique:true},
    deffield_nervatype_id_idx: {model:'deffield', fields:['nervatype', 'subtype'], unique:false},
    deffield_deleted_idx: {model:'deffield', fields:['deleted'], unique:false},
  
    fieldvalue_fieldname_idx: {model:'fieldvalue', fields:['fieldname'], unique:false},
    fieldvalue_ref_id_idx: {model:'fieldvalue', fields:['ref_id'], unique:false},
  
    log_logstate_idx: {model:'log', fields:['logstate'], unique:false},
    log_nervatype_idx: {model:'log', fields:['nervatype, ref_id'], unique:false},
    
    numberdef_numberkey_idx: {model:'numberdef', fields:['numberkey'], unique:true},
    
    address_nervatype_idx: {model:'address', fields:['nervatype', 'ref_id'], unique:false},
    address_deleted_idx: {model:'address', fields:['deleted'], unique:false},
    
    contact_nervatype_idx: {model:'contact', fields:['nervatype, ref_id'], unique:false},
    contact_deleted_idx: {model:'contact', fields:['deleted'], unique:false},
    
    event_calnumber_idx: {model:'event', fields:['calnumber'], unique:true},
    event_fromdate_idx: {model:'event', fields:['fromdate'], unique:false},
    event_eventgroup_idx: {model:'event', fields:['eventgroup'], unique:false},
    event_nervatype_idx: {model:'event', fields:['nervatype'], unique:false},
    event_ref_idx: {model:'event', fields:['ref_id'], unique:false},
    event_deleted_idx: {model:'event', fields:['deleted'], unique:false},
    event_uid_idx: {model:'event', fields:['uid'], unique:false},
    
    customer_custnumber_idx: {model:'customer', fields:['custnumber'], unique:true},
    customer_custtype_idx: {model:'customer', fields:['custtype'], unique:false},
    customer_inactive_idx: {model:'customer', fields:['inactive'], unique:false},
    customer_deleted_idx: {model:'customer', fields:['deleted'], unique:false},
    customer_custname_idx: {model:'customer', fields:['custname'], unique:false},
    
    project_pronumber_idx: {model:'project', fields:['pronumber'], unique:true},
    project_customer_id_idx: {model:'project', fields:['customer_id'], unique:false},
    project_inactive_idx: {model:'project', fields:['inactive'], unique:false},
    project_deleted_idx: {model:'project', fields:['deleted'], unique:false},
    
    currency_curr_idx: {model:'currency', fields:['curr'], unique:true},
    
    place_planumber_idx: {model:'place', fields:['planumber'], unique:true},
    place_placetype_idx: {model:'place', fields:['placetype'], unique:false},
    place_deleted_idx: {model:'place', fields:['deleted'], unique:false},
    
    rate_curr_idx: {model:'rate', fields:['curr'], unique:false},
    rate_ref_idx: {model:'rate', fields:['ratedate', 'curr', 'place_id', 'ratetype'], unique:false},
    rate_ratedate_idx: {model:'rate', fields:['ratedate'], unique:false},
    rate_deleted_idx: {model:'rate', fields:['deleted'], unique:false},
    
    tax_taxcode_idx: {model:'tax', fields:['taxcode'], unique:true},
    tax_inactive_idx: {model:'tax', fields:['inactive'], unique:false},
  
    product_partnumber_idx: {model:'product', fields:['partnumber'], unique:true},
    product_tax_id_idx: {model:'product', fields:['tax_id'], unique:false},
    product_inactive_idx: {model:'product', fields:['inactive'], unique:false},
    product_deleted_idx: {model:'product', fields:['deleted'], unique:false},
    product_protype_idx: {model:'product', fields:['protype'], unique:false},
    product_webitem_idx: {model:'product', fields:['webitem'], unique:false},
    
    tool_serial_idx: {model:'tool', fields:['serial'], unique:true},
    tool_groups_id_idx: {model:'tool', fields:['toolgroup'], unique:false},
    tool_inactive_idx: {model:'tool', fields:['inactive'], unique:false},
    tool_deleted_idx: {model:'tool', fields:['deleted'], unique:false},
    tool_product_id_idx: {model:'tool', fields:['product_id'], unique:false},
    
    price_curr_idx: {model:'price', fields:['curr'], unique:false},
    price_product_id_idx: {model:'price', fields:['product_id'], unique:false},
    price_validfrom_idx: {model:'price', fields:['validfrom'], unique:false},
    price_validto_idx: {model:'price', fields:['validto'], unique:false},
    price_vendor_idx: {model:'price', fields:['vendorprice'], unique:false},
    price_deleted_idx: {model:'price', fields:['deleted'], unique:false},
  
    barcode_code_idx: {model:'barcode', fields:['code'], unique:true},
    barcode_defcode_idx: {model:'barcode', fields:['defcode'], unique:false},
    barcode_parts_id_idx: {model:'barcode', fields:['product_id'], unique:false},
  
    trans_transnumber_idx: {model:'trans', fields:['transnumber'], unique:true},
    trans_curr_idx: {model:'trans', fields:['curr'], unique:false},
    trans_duedate_idx: {model:'trans', fields:['duedate'], unique:false},
    trans_paidtype_idx: {model:'trans', fields:['paidtype'], unique:false},
    trans_project_id_idx: {model:'trans', fields:['project_id'], unique:false},
    trans_employee_id_idx: {model:'trans', fields:['employee_id'], unique:false},
    trans_cruser_idx: {model:'trans', fields:['cruser_id'], unique:false},
    trans_customer_idx: {model:'trans', fields:['customer_id'], unique:false},
    trans_department_idx: {model:'trans', fields:['department'], unique:false},
    trans_transtate_idx: {model:'trans', fields:['transtate'], unique:false},
    trans_transdate_idx: {model:'trans', fields:['transdate'], unique:false},
    trans_crdate_idx: {model:'trans', fields:['crdate'], unique:false},
    trans_ref_transnumber_idx: {model:'trans', fields:['ref_transnumber'], unique:false},
    trans_transtype_idx: {model:'trans', fields:['transtype'], unique:false},
    trans_direction_idx: {model:'trans', fields:['direction'], unique:false},
  
    item_product_id_idx: {model:'item', fields:['product_id'], unique:false},
    item_tax_id_idx: {model:'item', fields:['tax_id'], unique:false},
    item_trans_id_idx: {model:'item', fields:['trans_id'], unique:false},
    item_deleted_idx: {model:'item', fields:['deleted'], unique:false},
  
    payment_paiddate_idx: {model:'payment', fields:['paiddate'], unique:false},
    payment_trans_id_idx: {model:'payment', fields:['trans_id'], unique:false},
    payment_deleted_idx: {model:'payment', fields:['deleted'], unique:false},
  
    movement_product_id_idx: {model:'movement', fields:['product_id'], unique:false},
    movement_tool_id_idx: {model:'movement', fields:['tool_id'], unique:false},
    movement_shipdate_idx: {model:'movement', fields:['shippingdate'], unique:false},
    movement_trans_id_idx: {model:'movement', fields:['trans_id'], unique:false},
    movement_place_id_idx: {model:'movement', fields:['place_id'], unique:false},
    movement_movetype_idx: {model:'movement', fields:['movetype'], unique:false},
    movement_deleted_idx: {model:'movement', fields:['deleted'], unique:false},
  
    pattern_description_idx: {model:'pattern', fields:['description'], unique:true},
    pattern_transtype_idx: {model:'pattern', fields:['transtype'], unique:false},
    pattern_deleted_idx: {model:'rate', fields:['deleted'], unique:false}
  },
  
  data: {
    groups: [
      //aggretype
      {'groupname':'aggretype', 'groupvalue':'<>'},
      {'groupname':'aggretype', 'groupvalue':'avg'},
      {'groupname':'aggretype', 'groupvalue':'count'},
      {'groupname':'aggretype', 'groupvalue':'sum'},
      //nervatype
      {'groupname':'nervatype', 'groupvalue':'address'},
      {'groupname':'nervatype', 'groupvalue':'audit'},
      {'groupname':'nervatype', 'groupvalue':'barcode'},
      {'groupname':'nervatype', 'groupvalue':'contact'},
      {'groupname':'nervatype', 'groupvalue':'currency'},
      {'groupname':'nervatype', 'groupvalue':'customer'},
      {'groupname':'nervatype', 'groupvalue':'deffield'},
      {'groupname':'nervatype', 'groupvalue':'employee'},
      {'groupname':'nervatype', 'groupvalue':'event'},
      {'groupname':'nervatype', 'groupvalue':'groups'},
      {'groupname':'nervatype', 'groupvalue':'item'},
      {'groupname':'nervatype', 'groupvalue':'link'},
      {'groupname':'nervatype', 'groupvalue':'log'},
      {'groupname':'nervatype', 'groupvalue':'menu'},
      {'groupname':'nervatype', 'groupvalue':'movement'},
      {'groupname':'nervatype', 'groupvalue':'numberdef'},
      {'groupname':'nervatype', 'groupvalue':'pattern'},
      {'groupname':'nervatype', 'groupvalue':'payment'},
      {'groupname':'nervatype', 'groupvalue':'place'},
      {'groupname':'nervatype', 'groupvalue':'price'},
      {'groupname':'nervatype', 'groupvalue':'product'},
      {'groupname':'nervatype', 'groupvalue':'project'},
      {'groupname':'nervatype', 'groupvalue':'rate'},
      {'groupname':'nervatype', 'groupvalue':'report'},
      {'groupname':'nervatype', 'groupvalue':'tax'},
      {'groupname':'nervatype', 'groupvalue':'tool'},
      {'groupname':'nervatype', 'groupvalue':'trans'},
      {'groupname':'nervatype', 'groupvalue':'setting'},
      //fieldtype
      {'groupname':'fieldtype', 'groupvalue':'bool'},
      {'groupname':'fieldtype', 'groupvalue':'date'},
      {'groupname':'fieldtype', 'groupvalue':'time'},
      {'groupname':'fieldtype', 'groupvalue':'float'},
      {'groupname':'fieldtype', 'groupvalue':'integer'},
      {'groupname':'fieldtype', 'groupvalue':'string'},
      {'groupname':'fieldtype', 'groupvalue':'valuelist'},
      {'groupname':'fieldtype', 'groupvalue':'notes'},
      {'groupname':'fieldtype', 'groupvalue':'filter'},
      {'groupname':'fieldtype', 'groupvalue':'urlink'},
      {'groupname':'fieldtype', 'groupvalue':'password'},
      {'groupname':'fieldtype', 'groupvalue':'customer'},
      {'groupname':'fieldtype', 'groupvalue':'tool'},
      {'groupname':'fieldtype', 'groupvalue':'transitem'},
      {'groupname':'fieldtype', 'groupvalue':'transmovement'},
      {'groupname':'fieldtype', 'groupvalue':'transpayment'},
      {'groupname':'fieldtype', 'groupvalue':'product'},
      {'groupname':'fieldtype', 'groupvalue':'project'},
      {'groupname':'fieldtype', 'groupvalue':'employee'},
      {'groupname':'fieldtype', 'groupvalue':'place'},
      //filetype
      {'groupname':'filetype', 'groupvalue':'xls', 'description':'MsExcel workbook'},
      {'groupname':'filetype', 'groupvalue':'html', 'description':'HTML document'},
      {'groupname':'filetype', 'groupvalue':'gshi', 'description':'Genshi template'},
      {'groupname':'filetype', 'groupvalue':'ntr', 'description':'Nervatura Report'},
      //transtype
      {'groupname':'transtype', 'groupvalue':'invoice'},
      {'groupname':'transtype', 'groupvalue':'receipt'},
      {'groupname':'transtype', 'groupvalue':'order'},
      {'groupname':'transtype', 'groupvalue':'offer'},
      {'groupname':'transtype', 'groupvalue':'worksheet'},
      {'groupname':'transtype', 'groupvalue':'rent'},
      {'groupname':'transtype', 'groupvalue':'delivery'},
      {'groupname':'transtype', 'groupvalue':'inventory'},
      {'groupname':'transtype', 'groupvalue':'waybill'},
      {'groupname':'transtype', 'groupvalue':'production'},
      {'groupname':'transtype', 'groupvalue':'formula'},
      {'groupname':'transtype', 'groupvalue':'bank'},
      {'groupname':'transtype', 'groupvalue':'cash'},
      //direction
      {'groupname':'direction', 'groupvalue':'out'},
      {'groupname':'direction', 'groupvalue':'in'},
      {'groupname':'direction', 'groupvalue':'transfer'},
      //wheretype
      {'groupname':'wheretype', 'groupvalue':'where'},
      {'groupname':'wheretype', 'groupvalue':'having'},
      {'groupname':'wheretype', 'groupvalue':'in'},
      //barcodetype
      {'groupname':'barcodetype', 'groupvalue':'AZTEC', 'description':'AZTEC'},
      {'groupname':'barcodetype', 'groupvalue':'CODABAR', 'description':'CODABAR'},
      {'groupname':'barcodetype', 'groupvalue':'CODE_128', 'description':'CODE_128'},
      {'groupname':'barcodetype', 'groupvalue':'CODE_39', 'description':'CODE_39'},
      {'groupname':'barcodetype', 'groupvalue':'CODE_93', 'description':'CODE_93'},
      {'groupname':'barcodetype', 'groupvalue':'DATA_MATRIX', 'description':'DATA_MATRIX'},
      {'groupname':'barcodetype', 'groupvalue':'EAN_13', 'description':'EAN_13'},
      {'groupname':'barcodetype', 'groupvalue':'EAN_8', 'description':'EAN_8'},
      {'groupname':'barcodetype', 'groupvalue':'ITF', 'description':'ITF'},
      {'groupname':'barcodetype', 'groupvalue':'MSI', 'description':'MSI'},
      {'groupname':'barcodetype', 'groupvalue':'PDF417', 'description':'PDF417'},
      {'groupname':'barcodetype', 'groupvalue':'QR_CODE', 'description':'QR_CODE'},
      {'groupname':'barcodetype', 'groupvalue':'RSS_EXPANDED', 'description':'RSS_EXPANDED'},
      {'groupname':'barcodetype', 'groupvalue':'RSS14', 'description':'RSS14'},
      {'groupname':'barcodetype', 'groupvalue':'UPC_A', 'description':'UPC_A'},
      {'groupname':'barcodetype', 'groupvalue':'UPC_E', 'description':'UPC_E'},
      //ratetype 
      {'groupname':'ratetype', 'groupvalue':'rate'},
      {'groupname':'ratetype', 'groupvalue':'buy'},
      {'groupname':'ratetype', 'groupvalue':'sell'},
      {'groupname':'ratetype', 'groupvalue':'average'},
      //filtertype
      {'groupname':'filtertype', 'groupvalue':'=='},
      {'groupname':'filtertype', 'groupvalue':'=N'},
      {'groupname':'filtertype', 'groupvalue':'!='},
      {'groupname':'filtertype', 'groupvalue':'>='},
      {'groupname':'filtertype', 'groupvalue':'<='},
      //movetype
      {'groupname':'movetype', 'groupvalue':'inventory'},
      {'groupname':'movetype', 'groupvalue':'tool'},
      {'groupname':'movetype', 'groupvalue':'plan'},
      {'groupname':'movetype', 'groupvalue':'head'},
      //transtate
      {'groupname':'transtate', 'groupvalue':'ok'},
      {'groupname':'transtate', 'groupvalue':'new'},
      {'groupname':'transtate', 'groupvalue':'back'},
      //logstate
      {'groupname':'logstate', 'groupvalue':'update'},
      {'groupname':'logstate', 'groupvalue':'closed'},
      {'groupname':'logstate', 'groupvalue':'deleted'},
      {'groupname':'logstate', 'groupvalue':'print'},
      {'groupname':'logstate', 'groupvalue':'login'},
      {'groupname':'logstate', 'groupvalue':'logout'},
      //usergroup
      {'groupname':'usergroup', 'groupvalue':'admin', 'description':'Admin'},
      {'groupname':'usergroup', 'groupvalue':'user', 'description':'Employee'},
      {'groupname':'usergroup', 'groupvalue':'guest', 'description':'Guest'},
      {'groupname':'usergroup', 'groupvalue':'demo', 'description':'Demo'},
      //inputfilter
      {'groupname':'inputfilter', 'groupvalue':'disabled'},
      {'groupname':'inputfilter', 'groupvalue':'readonly'},
      {'groupname':'inputfilter', 'groupvalue':'update'},
      {'groupname':'inputfilter', 'groupvalue':'all'},
      //transfilter
      {'groupname':'transfilter', 'groupvalue':'own'},
      {'groupname':'transfilter', 'groupvalue':'usergroup'},
      {'groupname':'transfilter', 'groupvalue':'all'},
      //protype
      {'groupname':'protype', 'groupvalue':'item'},
      {'groupname':'protype', 'groupvalue':'service'},
      //custtype
      {'groupname':'custtype', 'groupvalue':'own'},
      {'groupname':'custtype', 'groupvalue':'company'},
      {'groupname':'custtype', 'groupvalue':'private'},
      {'groupname':'custtype', 'groupvalue':'other'},
      //calcmode
      {'groupname':'calcmode', 'groupvalue':'ded', 'description':'deduction (%)'},
      {'groupname':'calcmode', 'groupvalue':'add', 'description':'adding (%)'},
      {'groupname':'calcmode', 'groupvalue':'amo', 'description':'amount (+/-)'},
      //paidtype
      {'groupname':'paidtype', 'groupvalue':'cash', 'description':'cash'},
      {'groupname':'paidtype', 'groupvalue':'transfer', 'description':'transfer'},
      {'groupname':'paidtype', 'groupvalue':'credit_card', 'description':'credit card'},
      //placetype
      {'groupname':'placetype', 'groupvalue':'bank'},
      {'groupname':'placetype', 'groupvalue':'cash'},
      {'groupname':'placetype', 'groupvalue':'warehouse'},
      {'groupname':'placetype', 'groupvalue':'other'},
      //toolgroup
      {'groupname':'toolgroup', 'groupvalue':'printer', 'description':'Printer'},
      //orientation
      {'groupname':'orientation', 'groupvalue':'P', 'description':'Portrait'},
      {'groupname':'orientation', 'groupvalue':'L', 'description':'Landscape'},
      //papersize
      {'groupname':'papersize', 'groupvalue':'a3', 'description':'A3'},
      {'groupname':'papersize', 'groupvalue':'a4', 'description':'A4'},
      {'groupname':'papersize', 'groupvalue':'a5', 'description':'A5'},
      {'groupname':'papersize', 'groupvalue':'letter', 'description':'Letter'},
      {'groupname':'papersize', 'groupvalue':'legal', 'description':'Legal'}],
    
    currency: [
      {'curr':'EUR', 'description':'euro', 'digit':2, 'defrate':0, 'cround':0},
      {'curr':'USD', 'description':'dollar', 'digit':2, 'defrate':0, 'cround':0}],
    
    customer: [
      {'custtype':['groups', 'custtype', 'own'], 'custnumber':'HOME', 'custname':'COMPANY NAME', 
        'taxnumber':'12345678-1-12'}],
    
    employee: [
      {'empnumber':'admin', 'username':'admin', 'usergroup':['groups', 'usergroup', 'admin']}],
    
    address: [
      {'nervatype':['groups', 'nervatype', 'customer'], 'ref_id':['customer','HOME']},
      {'nervatype':['groups', 'nervatype', 'employee'], 'ref_id':['employee','admin']}],
      
    contact: [
      {'nervatype':['groups', 'nervatype', 'employee'], 'ref_id':['employee','admin']}],
    
    place: [
      {'planumber':'bank', 'placetype':['groups', 'placetype', 'bank'], 'description':'Bank', 'curr':'EUR'},
      {'planumber':'cash', 'placetype':['groups', 'placetype', 'cash'], 'description':'Cash', 'curr':'EUR'},
      {'planumber':'warehouse', 'placetype':['groups', 'placetype', 'warehouse'], 'description':'Warehouse'}],
    
    tax: [
      {'description':'VAT 0%', 'rate':0, 'taxcode':'0%'},
      {'description':'VAT 5%', 'rate':0.05, 'taxcode':'5%'},
      {'description':'VAT 10%', 'rate':0.1, 'taxcode':'10%'},
      {'description':'VAT 15%', 'rate':0.15, 'taxcode':'15%'},
      {'description':'VAT 20%', 'rate':0.2, 'taxcode':'20%'},
      {'description':'VAT 25%', 'rate':0.25, 'taxcode':'25%'}],
             
    product: [
      {'protype':['groups', 'protype', 'item'], 'partnumber':'printer', 'description':'Generic printer', 
       'unit':'piece', 'tax_id':['tax','0%']}],
    
    numberdef: [
      {'numberkey': 'bank_transfer', 'prefix':  'BANK', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'statement', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'calnumber', 'prefix':  'EVT', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'event', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'cash', 'prefix':  'CASH', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'cash payment', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'custnumber', 'prefix':  'CUS', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'customer', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'delivery_in', 'prefix':  'DELIN', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'delivery in', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'delivery_out', 'prefix':  'DELOU', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'delivery out', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'delivery_transfer', 'prefix':  'DELTF', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'delivery transfer', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'empnumber', 'prefix':  'EMP', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'employee', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'formula_transfer', 'prefix':  'FRM', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'formula', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'inventory_transfer', 'prefix':  'VENDL', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'inventory delivery', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'invoice_in', 'prefix':  'INVVD', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'vendor invoice', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'invoice_out', 'prefix':  'INVCT', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'customer invoice', 'visible': 1, 'readonly': 1, 'orderby': 0},
      {'numberkey': 'offer_in', 'prefix':  'OFFVD', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'vendor offer', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'offer_out', 'prefix':  'OFFCT', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'customer offer', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'order_in', 'prefix':  'ORDVD', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'vendor order', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'order_out', 'prefix':  'ORDCT', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'customer order', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'partnumber', 'prefix':  'PRO', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'poduct', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'production_transfer', 'prefix':  'MAKE', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'production', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'pronumber', 'prefix':  'PRJ', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'project', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'planumber', 'prefix':  'PLA', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'place', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'receipt_in', 'prefix':  'RECVD', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'vendor receipt', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'receipt_out', 'prefix':  'RECCT', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'customer receipt', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'rent_in', 'prefix':  'RENVD', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'vendor rent', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'rent_out', 'prefix':  'RENCT', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'customer rent', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'serial', 'prefix':  'SER', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'tool', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'waybill', 'prefix':  'MOVE', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'tool movement', 'visible': 1, 'readonly': 0, 'orderby': 0},
      {'numberkey': 'worksheet_out', 'prefix':  'WORK', 'curvalue': 0, 'isyear': 1, 'sep':  '/', 'len': 5, 
        'description':  'worksheet', 'visible': 1, 'readonly': 0, 'orderby': 0}],
      
    deffield: [
      {'fieldname':'trans_transitem_link', 'nervatype':['groups', 'nervatype', 'trans'], 
        'fieldtype':['groups', 'fieldtype', 'transitem'], 
        'description':'Ref.No.', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'trans_transcast', 'nervatype':['groups', 'nervatype', 'trans'],
        'fieldtype':['groups', 'fieldtype', 'valuelist'], 
        'description':'transaction special state', 'valuelist':'normal|cancellation|amendment', 
        'addnew':1, 'visible':0, 'readonly':1},
      {'fieldname':'trans_custinvoice_compname', 'nervatype':['groups', 'nervatype', 'trans'],
        'subtype':['groups', 'transtype', 'invoice'], 'fieldtype':['groups', 'fieldtype', 'string'], 
        'description':'customer invoice company name', 'addnew':1, 'visible':0, 'readonly':1},
      {'fieldname':'trans_custinvoice_compaddress', 'nervatype':['groups', 'nervatype', 'trans'],
        'subtype':['groups', 'transtype', 'invoice'], 'fieldtype':['groups', 'fieldtype', 'string'], 
        'description':'customer invoice company address', 'addnew':1, 'visible':0, 'readonly':1},
      {'fieldname':'trans_custinvoice_comptax', 'nervatype':['groups', 'nervatype', 'trans'],
        'subtype':['groups', 'transtype', 'invoice'], 'fieldtype':['groups', 'fieldtype', 'string'], 
        'description':'customer invoice company taxnumber', 'addnew':1, 'visible':0, 'readonly':1},
      {'fieldname':'trans_custinvoice_custname', 'nervatype':['groups', 'nervatype', 'trans'],
        'subtype':['groups', 'transtype', 'invoice'], 'fieldtype':['groups', 'fieldtype', 'string'], 
        'description':'customer invoice customer name', 'addnew':1, 'visible':0, 'readonly':1},
      {'fieldname':'trans_custinvoice_custaddress', 'nervatype':['groups', 'nervatype', 'trans'], 
        'subtype':['groups', 'transtype', 'invoice'], 'fieldtype':['groups', 'fieldtype', 'string'], 
        'description':'customer invoice customer address', 'addnew':1, 'visible':0, 'readonly':1},
      {'fieldname':'trans_custinvoice_custtax', 'nervatype':['groups', 'nervatype', 'trans'], 
        'subtype':['groups', 'transtype', 'invoice'], 'fieldtype':['groups', 'fieldtype', 'string'], 
        'description':'customer invoice customer taxnumber', 'addnew':1, 'visible':0, 'readonly':1},
      {'fieldname':'trans_closed_policy_invoice_out', 'nervatype':['groups', 'nervatype', 'trans'],
        'fieldtype':['groups', 'fieldtype', 'string'],
       'description':'transaction closed policy', 'valuelist':'print', 'addnew':0, 'visible':0, 'readonly':1},
      {'fieldname':'trans_closed_policy_receipt_out', 'nervatype':['groups', 'nervatype', 'trans'],
        'fieldtype':['groups', 'fieldtype', 'string'],
        'description':'transaction closed policy', 'valuelist':'print', 'addnew':0, 'visible':0, 'readonly':1},
      {'fieldname':'trans_wsdistance','nervatype':['groups', 'nervatype', 'trans'],
        'subtype':['groups', 'transtype', 'worksheet'], 'fieldtype':['groups', 'fieldtype', 'float'],
        'description':'worksheet distance', 'addnew':1, 'visible':0, 'readonly':1},
      {'fieldname':'trans_wsrepair','nervatype':['groups', 'nervatype', 'trans'], 
        'subtype':['groups', 'transtype', 'worksheet'], 'fieldtype':['groups', 'fieldtype', 'float'],
        'description':'worksheet repair time (hour)', 'addnew':1, 'visible':0, 'readonly':1},
      {'fieldname':'trans_wstotal','nervatype':['groups', 'nervatype', 'trans'], 
        'subtype':['groups', 'transtype', 'worksheet'], 'fieldtype':['groups', 'fieldtype', 'float'],
        'description':'worksheet total time (hour)', 'addnew':1, 'visible':0, 'readonly':1},
      {'fieldname':'trans_wsnote','nervatype':['groups', 'nervatype', 'trans'], 
        'subtype':['groups', 'transtype', 'worksheet'], 'fieldtype':['groups', 'fieldtype', 'string'],
        'description':'worksheet justification', 'addnew':1, 'visible':0, 'readonly':1},
      {'fieldname':'trans_reholiday','nervatype':['groups', 'nervatype', 'trans'],
        'subtype':['groups', 'transtype', 'rent'], 'fieldtype':['groups', 'fieldtype', 'float'],
        'description':'rent holidays', 'addnew':1, 'visible':0, 'readonly':1},
      {'fieldname':'trans_rebadtool','nervatype':['groups', 'nervatype', 'trans'],
        'subtype':['groups', 'transtype', 'rent'], 'fieldtype':['groups', 'fieldtype', 'float'],
        'description':'rent bad machine', 'addnew':1, 'visible':0, 'readonly':1},
      {'fieldname':'trans_reother','nervatype':['groups', 'nervatype', 'trans'],
        'subtype':['groups', 'transtype', 'rent'], 'fieldtype':['groups', 'fieldtype', 'float'],
        'description':'rent other non-eligible', 'addnew':1, 'visible':0, 'readonly':1},
      {'fieldname':'trans_rentnote','nervatype':['groups', 'nervatype', 'trans'],
        'subtype':['groups', 'transtype', 'rent'], 'fieldtype':['groups', 'fieldtype', 'string'],
        'description':'rent justification', 'addnew':1, 'visible':0, 'readonly':1},
      {'fieldname':'tool_printertype', 'nervatype':['groups', 'nervatype', 'tool'], 
        'fieldtype':['groups', 'fieldtype', 'valuelist'], 
        'description':'Printer type', 'valuelist':'local|network|mail', 'addnew':0, 'visible':1, 'readonly':0},
      /*
      {'fieldname':'tool_printer_mail_smtp','nervatype':['groups', 'nervatype', 'tool'], 
        'fieldtype':['groups', 'fieldtype', 'string'],
        'description':'Printer mail smtp', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'tool_printer_mail_sender','nervatype':['groups', 'nervatype', 'tool'], 
        'fieldtype':['groups', 'fieldtype', 'string'],
        'description':'Printer mail sender', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'tool_printer_mail_address','nervatype':['groups', 'nervatype', 'tool'], 
        'fieldtype':['groups', 'fieldtype', 'string'],
        'description':'Printer mail address', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'tool_printer_mail_subject','nervatype':['groups', 'nervatype', 'tool'], 
        'fieldtype':['groups', 'fieldtype', 'string'],
        'description':'Printer mail subject', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'tool_printer_mail_message','nervatype':['groups', 'nervatype', 'tool'], 
        'fieldtype':['groups', 'fieldtype', 'string'],
        'description':'Printer mail message', 'addnew':0, 'visible':1, 'readonly':0},
      */
      {'fieldname':'link_qty', 'nervatype':['groups', 'nervatype', 'link'],
        'fieldtype':['groups', 'fieldtype', 'float'],
        'description':'link qty value', 'addnew':0, 'visible':0, 'readonly':0},
      {'fieldname':'link_rate', 'nervatype':['groups', 'nervatype', 'link'],
        'fieldtype':['groups', 'fieldtype', 'float'],
        'description':'link rate value', 'addnew':0, 'visible':0, 'readonly':0},
      {'fieldname':'product_custpartnumber', 'nervatype':['groups', 'nervatype', 'product'],
        'fieldtype':['groups', 'fieldtype', 'customer'],
        'description':'Customer Product No. (pricing)', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'product_alternative', 'nervatype':['groups', 'nervatype', 'product'],
        'fieldtype':['groups', 'fieldtype', 'product'],
        'description':'Alternative Product', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'product_element', 'nervatype':['groups', 'nervatype', 'product'],
        'fieldtype':['groups', 'fieldtype', 'product'],
        'description':'Element Product', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'printer_gsprint', 'nervatype':['groups', 'nervatype', 'setting'], 
        'fieldtype':['groups', 'fieldtype', 'string'], 
        'description':'gsprint path (windows pdf printing)', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'printer_in_tool', 'nervatype':['groups', 'nervatype', 'setting'], 
        'fieldtype':['groups', 'fieldtype', 'bool'], 
        'description':'show printers in tools', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'default_bank', 'nervatype':['groups', 'nervatype', 'setting'], 
        'fieldtype':['groups', 'fieldtype', 'string'],
        'description':'default bank place no.', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'default_chest', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'string'],
        'description':'default petty cash place no.', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'default_warehouse', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'string'],
        'description':'default warehouse place no.', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'default_country', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'string'],
        'description':'default country', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'default_lang', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'string'],
        'description':'default language', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'default_currency', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'string'],
        'description':'default currency', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'default_deadline', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'integer'],
        'description':'default deadline (payment)', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'default_paidtype', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'string'],
        'description':'default paidtype', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'default_unit', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'string'],
        'description':'default unit', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'default_taxcode', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'string'],
        'description':'default taxcode', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'default_printer', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'string'],
        'description':'default server printer', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'default_mail_smtp', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'string'],
        'description':'default mail smtp', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'default_mail_sender', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'string'],
        'description':'default mail sender', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'false_bool', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'string'],
        'description':'false string', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'invoice_copy', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'integer'],
        'description':'invoice copy', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'transyear', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'integer'],
        'description':'business year', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'true_bool', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'string'],
        'description':'true string', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'audit_control', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'bool'],
        'description':'set audit control', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'invoice_from_inventory', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'bool'],
        'description':'invoice from inventory(yes) or order items(no)', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'set_outstock_enabled', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'bool'],
        'description':'enabled inventory deficit', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'set_stocklimit_warning', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'bool'],
        'description':'inventory stock limit warning', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'not_logical_delete', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'bool'],
        'description':'enabled trans deletion', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'show_partcustomer', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'bool'],
        'description':'show customer number column', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'show_partnumber', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'bool'],
        'description':'show product number column', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'log_deleted', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'bool'],
        'description':'enabled deleted log', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'log_update', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'bool'],
        'description':'enabled update log', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'log_trans_closed', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'bool'],
        'description':'enabled trans closed log', 'addnew':0, 'visible':1, 'readonly':0},
      {'fieldname':'log_login', 'nervatype':['groups', 'nervatype', 'setting'],
        'fieldtype':['groups', 'fieldtype', 'bool'],
        'description':'enabled userlogin', 'addnew':0, 'visible':1, 'readonly':0}],
    
    fieldvalue: [
      {'fieldname':'printer_gsprint', 'value':'C:\\Progra~1\\Ghostgum\\gsview\\gsprint'},
      {'fieldname':'printer_in_tool', 'value':'false'},
      {'fieldname':'default_bank', 'value':'bank'},
      {'fieldname':'default_chest', 'value':'cash'},
      {'fieldname':'default_warehouse', 'value':'warehouse'},
      {'fieldname':'default_country', 'value':'EU'},
      {'fieldname':'default_lang', 'value':'en'},
      {'fieldname':'default_currency', 'value':'EUR'},
      {'fieldname':'default_deadline', 'value':'8'},
      {'fieldname':'default_paidtype', 'value':'transfer'},
      {'fieldname':'default_unit', 'value':'piece'},
      {'fieldname':'default_taxcode', 'value':'20%'},
      {'fieldname':'default_printer', 'value':''},
      {'fieldname':'default_mail_smtp', 'value':'', 
        'notes':'Sample: smtps://user%40gmail.com:pass@smtp.gmail.com'},
      {'fieldname':'default_mail_sender', 'value':'', 
        'notes':'Sample: Sender Name <sender@server.com> or sender@server.com'},
      {'fieldname':'false_bool', 'value':'FALSE'},
      {'fieldname':'invoice_copy', 'value':'2'},
      {'fieldname':'transyear', 'value':(new Date().getFullYear())},
      {'fieldname':'true_bool', 'value':'TRUE'},
      {'fieldname':'audit_control', 'value':'false'},
      {'fieldname':'invoice_from_inventory', 'value':'false'},
      {'fieldname':'set_outstock_enabled', 'value':'true'},
      {'fieldname':'set_stocklimit_warning', 'value':'false'},
      {'fieldname':'not_logical_delete', 'value':'false'},
      {'fieldname':'show_partcustomer', 'value':'false'},
      {'fieldname':'show_partnumber', 'value':'false'},
      {'fieldname':'log_deleted', 'value':'true'},
      {'fieldname':'log_update', 'value':'false'},
      {'fieldname':'log_trans_closed', 'value':'false'},
      {'fieldname':'log_login', 'value':'false'}]
  }
}