<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace GPBMetadata;

class Store
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ì
store.proto	nervatura"
RequestEmpty"2
ResponseStatus
success (
message (	"I
RequestAuthLogin
	user_name (	
password (	
database (	"3
ResponseAuthLogin
token (	
version (	":
RequestPasswordChange
password (	
confirm (	"#
RequestTokenDecode
token (	"b
ResponseTokenDecode
code (	
	user_name (	
database (	
exp (	
iss (	"&

RequestGet

id (
code (	"J
RequestDelete

id (
code (	
model (2.nervatura.Model"2
RequestQueryFilter
field (	
value (	"]
RequestQuery.
filters (2.nervatura.RequestQueryFilter
limit (
offset ("Ñ
RequestFunction
function (	2
args (2$.nervatura.RequestFunction.ArgsEntry+
	ArgsEntry
key (	
value (	:8"q
RequestView!
name (2.nervatura.ViewName
filter (	
order_by (	
limit (
offset (".
RequestDatabase
alias (	
demo ("h

JsonString-
data (2.nervatura.JsonString.DataEntry+
	DataEntry
key (	
value (	:8"
	JsonBytes
data ("¢
Address
country (	
state (	
zip_code (	
city (	
street (	
notes (	
tags (	*
address_map (2.nervatura.JsonString"µ
Contact

first_name (	
surname (	
status (	
phone (	
mobile (	
email (	
notes (	
tags (	*
contact_map	 (2.nervatura.JsonString"ß
Event
uid (	
subject (	

start_time (	
end_time (	
place (	
description (	
tags (	(
	event_map (2.nervatura.JsonString"É
Bookmark.
bookmark_type (2.nervatura.BookmarkType
label (	
key (	
code (	&
filters (2.nervatura.JsonString1
columns (2 .nervatura.Bookmark.ColumnsEntry

time_stamp (	.
ColumnsEntry
key (	
value (:8"@
AuthMeta
tags (	&
	bookmarks (2.nervatura.Bookmark"‘
Auth

id (
code (	
	user_name (	(

user_group (2.nervatura.UserGroup
disabled (&
	auth_meta (2.nervatura.AuthMeta\'
auth_map (2.nervatura.JsonString

time_stamp (	"T
CurrencyMeta
description (	
digit (

cash_round (
tags (	"ï
Currency

id (
code (	.
currency_meta (2.nervatura.CurrencyMeta+
currency_map (2.nervatura.JsonString

time_stamp (	"/

Currencies!
data (2.nervatura.Currency"´
CustomerMeta

tax_number (	
account (	
tax_free (
terms (
credit_limit (
discount (
notes (	
inactive (
tags	 (	"À
Customer

id (
code (	.
customer_type (2.nervatura.CustomerType
customer_name (	%
	addresses (2.nervatura.Address$
contacts (2.nervatura.Contact 
events (2.nervatura.Event.
customer_meta (2.nervatura.CustomerMeta+
customer_map	 (2.nervatura.JsonString

time_stamp
 (	".
	Customers!
data (2.nervatura.Customer"c
EmployeeMeta

start_date (	
end_date (	
inactive (
notes (	
tags (	"Å
Employee

id (
code (	#
address (2.nervatura.Address#
contact (2.nervatura.Contact 
events (2.nervatura.Event.
employee_meta (2.nervatura.EmployeeMeta+
employee_map (2.nervatura.JsonString

time_stamp (	".
	Employees!
data (2.nervatura.Employee"ﬁ
ItemMeta
unit (	
qty (
fx_price (

net_amount (
discount (

vat_amount (
amount (
description (	
deposit	 (
	own_stock
 (
action_price (
tags (	"¡
Item

id (
code (	

trans_code (	
product_code (	
tax_code (	&
	item_meta (2.nervatura.ItemMeta\'
item_map (2.nervatura.JsonString

time_stamp (	"&
Items
data (2.nervatura.Item"3
LinkMeta
qty (
rate (
tags (	"É
Link

id (
code (	(
link_type_1 (2.nervatura.LinkType
link_code_1 (	(
link_type_2 (2.nervatura.LinkType
link_code_2 (	&
	link_meta (2.nervatura.LinkMeta\'
link_map (2.nervatura.JsonString

time_stamp	 (	"&
Links
data (2.nervatura.Link"∏
Log

id (
code (	$
log_type (2.nervatura.LogType
ref_type (	
ref_code (	
	auth_code (	&
log_map (2.nervatura.JsonString

time_stamp (	"$
Logs
data (2.nervatura.Log"H
MovementMeta
qty (
notes (	
shared (
tags (	"◊
Movement

id (
code (	.
movement_type (2.nervatura.MovementType
shipping_time (	

trans_code (	
product_code (	
	tool_code (	

place_code (	
	item_code	 (	
movement_code
 (	.
movement_meta (2.nervatura.MovementMeta+
movement_map (2.nervatura.JsonString

time_stamp (	".
	Movements!
data (2.nervatura.Movement":
PaymentMeta
amount (
notes (	
tags (	"∏
Payment

id (
code (	
	paid_date (	

trans_code (	,
payment_meta (2.nervatura.PaymentMeta*
payment_map (2.nervatura.JsonString

time_stamp (	",
Payments 
data (2.nervatura.Payment":
	PlaceMeta
notes (	
inactive (
tags (	"À
Place

id (
code (	(

place_type (2.nervatura.PlaceType

place_name (	
currency_code (	#
address (2.nervatura.Address$
contacts (2.nervatura.Contact 
events (2.nervatura.Event(

place_meta	 (2.nervatura.PlaceMeta(
	place_map
 (2.nervatura.JsonString

time_stamp (	"(
Places
data (2.nervatura.Place".
	PriceMeta
price_value (
tags (	"™
Price

id (
code (	(

price_type (2.nervatura.PriceType

valid_from (	
valid_to (	
product_code (	
currency_code (	
customer_code (	
qty	 ((

price_meta
 (2.nervatura.PriceMeta(
	price_map (2.nervatura.JsonString

time_stamp (	"(
Prices
data (2.nervatura.Price"£
ProductMeta
unit (	,
barcode_type (2.nervatura.BarcodeType
barcode_data (	
barcode_qty (
notes (	
inactive (
tags (	"â
Product

id (
code (	,
product_type (2.nervatura.ProductType
product_name (	
tax_code (	 
events (2.nervatura.Event,
product_meta (2.nervatura.ProductMeta*
product_map (2.nervatura.JsonString

time_stamp	 (	",
Products 
data (2.nervatura.Product"b
ProjectMeta

start_date (	
end_date (	
notes (	
inactive (
tags (	"≠
Project

id (
code (	
project_name (	
customer_code (	%
	addresses (2.nervatura.Address$
contacts (2.nervatura.Contact 
events (2.nervatura.Event,
project_meta (2.nervatura.ProjectMeta*
project_map	 (2.nervatura.JsonString

time_stamp
 (	",
Projects 
data (2.nervatura.Project",
RateMeta

rate_value (
tags (	"Î
Rate

id (
code (	&
	rate_type (2.nervatura.RateType
	rate_date (	

place_code (	
currency_code (	&
	rate_meta (2.nervatura.RateMeta\'
rate_map (2.nervatura.JsonString

time_stamp	 (	"&
Rates
data (2.nervatura.Rate"@
TaxMeta
description (	

rate_value (
tags (	"Å
Tax

id (
code (	$
tax_meta (2.nervatura.TaxMeta&
tax_map (2.nervatura.JsonString

time_stamp (	"%
Taxes
data (2.nervatura.Tax"P
ToolMeta
serial_number (	
notes (	
inactive (
tags (	"“
Tool

id (
code (	
description (	
product_code (	 
events (2.nervatura.Event&
	tool_meta (2.nervatura.ToolMeta\'
tool_map (2.nervatura.JsonString

time_stamp (	"&
Tools
data (2.nervatura.Tool"S
	Worksheet
distance (
repair (
total (
justification (	"O
Rent
holiday (
bad_tool (
other (
justification (	"¢
Invoice
company_name (	
company_address (	
company_tax_number (	
customer_name (	
customer_address (	
customer_tax_number (	"£
	TransMeta
due_time (	

ref_number (	&
	paid_type (2.nervatura.PaidType
tax_free (
paid (
rate (
closed (&
status (2.nervatura.TransStatus*
trans_state	 (2.nervatura.TransState
notes
 (	
internal_notes (	
report_notes (	\'
	worksheet (2.nervatura.Worksheet
rent (2.nervatura.Rent#
invoice (2.nervatura.Invoice
tags (	"Ü
Trans

id (
code (	(

trans_type (2.nervatura.TransType

trans_date (	\'
	direction (2.nervatura.Direction

trans_code (	
customer_code (	
employee_code (	
project_code	 (	

place_code
 (	
currency_code (	
	auth_code (	(

trans_meta (2.nervatura.TransMeta(
	trans_map (2.nervatura.JsonString

time_stamp (	".
Transactions
data (2.nervatura.Trans"•
Config

id (
code (	*
config_type (2.nervatura.ConfigType#
map (2.nervatura.ConfigMapH -
shortcut (2.nervatura.ConfigShortcutH +
message (2.nervatura.ConfigMessageH +
pattern (2.nervatura.ConfigPatternH )
report (2.nervatura.ConfigReportH 2
print_queue	 (2.nervatura.ConfigPrintQueueH ,
config_data
 (2.nervatura.JsonStringH 

time_stamp (	B
data"*
Configs
data (2.nervatura.Config"í
	ConfigMap

field_name (	(

field_type (2.nervatura.FieldType
description (	
tags (	$
filter (2.nervatura.MapFilter"{
ConfigShortcutField

field_name (	
description (	,

field_type (2.nervatura.ShortcutField
order ("÷
ConfigShortcut
shortcut_key (	
description (	
modul (	
icon (	)
method (2.nervatura.ShortcutMethod
funcname (	
address (	.
fields (2.nervatura.ConfigShortcutField"J
ConfigMessage
section (	
key (	
lang (	
value (	"v
ConfigPattern(

trans_type (2.nervatura.TransType
description (	
notes (	
default_pattern ("
ConfigPrintQueue
ref_type (	
ref_code (	
qty (
report_code (	
	auth_code (	

time_stamp (	"§
ConfigReport

report_key (	
report_type (	-

trans_type (2.nervatura.TransTypeH à,
	direction (2.nervatura.DirectionHà&
	file_type (2.nervatura.FileType
report_name (	
description (	
label (	
template	 (	B
_trans_typeB

_direction*=
	UserGroup

GROUP_USER 
GROUP_ADMIN
GROUP_GUEST*`
CustomerType
CUSTOMER_COMPANY 
CUSTOMER_PRIVATE
CUSTOMER_OTHER
CUSTOMER_OWN*∑
LinkType
LINK_CUSTOMER 
LINK_EMPLOYEE
	LINK_ITEM
LINK_MOVEMENT
LINK_PAYMENT

LINK_PLACE
LINK_PRODUCT
LINK_PROJECT
	LINK_TOOL

LINK_TRANS	*9
LogType

LOG_INSERT 

LOG_UPDATE

LOG_DELETE*_
MovementType
MOVEMENT_INVENTORY 
MOVEMENT_TOOL
MOVEMENT_PLAN
MOVEMENT_HEAD*Q
	PlaceType
PLACE_WAREHOUSE 

PLACE_BANK

PLACE_CASH
PLACE_OTHER*1
	PriceType
PRICE_CUSTOMER 
PRICE_VENDOR*t
BarcodeType
BARCODE_CODE_39 
BARCODE_CODE_128
BARCODE_EAN_8
BARCODE_EAN_13
BARCODE_QR_CODE*I
ProductType
PRODUCT_ITEM 
PRODUCT_SERVICE
PRODUCT_VIRTUAL*H
RateType
	RATE_RATE 
RATE_BUY
	RATE_SELL
RATE_AVERAGE*\\
PaidType
PAID_ONLINE 
	PAID_CARD
PAID_TRANSFER
	PAID_CASH

PAID_OTHER*L
TransStatus
TRANS_NORMAL 
TRANS_CANCELLATION
TRANS_AMENDMENT*9

TransState
TRANS_OK 
	TRANS_NEW

TRANS_BACK*H
	Direction
DIRECTION_OUT 
DIRECTION_IN
DIRECTION_TRANSFER*˝
	TransType
TRANS_INVOICE 
TRANS_RECEIPT
TRANS_ORDER
TRANS_OFFER
TRANS_WORKSHEET

TRANS_RENT
TRANS_DELIVERY
TRANS_INVENTORY
TRANS_WAYBILL
TRANS_PRODUCTION	
TRANS_FORMULA


TRANS_BANK

TRANS_CASH*ï

ConfigType

CONFIG_MAP 
CONFIG_SHORTCUT
CONFIG_MESSAGE
CONFIG_PATTERN
CONFIG_REPORT
CONFIG_PRINT_QUEUE
CONFIG_DATA*Ó
	FieldType
FIELD_STRING 

FIELD_BOOL
FIELD_INTEGER
FIELD_NUMBER

FIELD_DATE
FIELD_DATETIME

FIELD_MEMO

FIELD_ENUM
	FIELD_URL
FIELD_CUSTOMER	
FIELD_EMPLOYEE

FIELD_PLACE
FIELD_PRODUCT
FIELD_PROJECT

FIELD_TOOL
FIELD_TRANS
FIELD_TRANS_ITEM
FIELD_TRANS_MOVEMENT
FIELD_TRANS_PAYMENT*Ú
	MapFilter
FILTER_ADDRESS 
FILTER_BARCODE
FILTER_CONTACT
FILTER_CURRENCY
FILTER_CUSTOMER
FILTER_EMPLOYEE
FILTER_EVENT
FILTER_ITEM
FILTER_MOVEMENT
FILTER_PAYMENT	
FILTER_PLACE

FILTER_PRICE
FILTER_PRODUCT
FILTER_PROJECT
FILTER_RATE

FILTER_TAX
FILTER_TOOL
FILTER_USER
FILTER_TRANS
FILTER_INVOICE
FILTER_RECEIPT
FILTER_ORDER
FILTER_OFFER
FILTER_WORKSHEET
FILTER_RENT
FILTER_DELIVERY
FILTER_INVENTORY
FILTER_WAYBILL
FILTER_PRODUCTION
FILTER_FORMULA
FILTER_BANK
FILTER_CASH*1
ShortcutMethod

METHOD_GET 
METHOD_POST*u
ShortcutField
SHORTCUT_STRING 
SHORTCUT_BOOL
SHORTCUT_INTEGER
SHORTCUT_NUMBER
SHORTCUT_DATE*&
FileType
FILE_PDF 
FILE_CSV*Œ
Model
AUTH 

CONFIG
CURRENCY
CUSTOMER
EMPLOYEE
ITEM
LINK
MOVEMENT
PAYMENT	
PLACE		
PRICE

PRODUCT
PROJECT
RATE
TAX
TOOL	
TRANS*å
ViewName
VIEW_CONFIG_DATA 
VIEW_CONFIG_MAP
VIEW_CONFIG_MESSAGE
VIEW_CONFIG_PATTERN
VIEW_CONFIG_PRINT_QUEUE
VIEW_CONFIG_REPORT
VIEW_CONFIG_SHORTCUT
VIEW_CURRENCY_MAP
VIEW_CURRENCY_TAGS
VIEW_CURRENCY_VIEW	
VIEW_CUSTOMER_ADDRESSES

VIEW_CUSTOMER_CONTACTS
VIEW_CUSTOMER_EVENTS
VIEW_CUSTOMER_MAP
VIEW_CUSTOMER_TAGS
VIEW_CUSTOMER_VIEW
VIEW_EMPLOYEE_EVENTS
VIEW_EMPLOYEE_MAP
VIEW_EMPLOYEE_TAGS
VIEW_EMPLOYEE_VIEW
VIEW_ITEM_MAP
VIEW_ITEM_TAGS
VIEW_ITEM_VIEW
VIEW_LINK_MAP
VIEW_LINK_TAGS
VIEW_LINK_VIEW
VIEW_MOVEMENT_MAP
VIEW_MOVEMENT_TAGS
VIEW_MOVEMENT_STOCK
VIEW_MOVEMENT_INVENTORY
VIEW_MOVEMENT_WAYBILL
VIEW_MOVEMENT_FORMULA
VIEW_MOVEMENT_VIEW 
VIEW_PAYMENT_MAP!
VIEW_PAYMENT_INVOICE"
VIEW_PAYMENT_TAGS#
VIEW_PAYMENT_VIEW$
VIEW_PLACE_MAP%
VIEW_PLACE_TAGS&
VIEW_PLACE_VIEW\'
VIEW_PRICE_MAP(
VIEW_PRICE_TAGS)
VIEW_PRICE_VIEW*
VIEW_PRODUCT_MAP+
VIEW_PRODUCT_TAGS,
VIEW_PRODUCT_VIEW-
VIEW_PRODUCT_COMPONENTS.
VIEW_PROJECT_MAP/
VIEW_PROJECT_TAGS0
VIEW_PROJECT_VIEW1
VIEW_RATE_MAP2
VIEW_RATE_TAGS3
VIEW_RATE_VIEW4
VIEW_TAX_MAP5
VIEW_TAX_TAGS6
VIEW_TAX_VIEW7
VIEW_TOOL_MAP8
VIEW_TOOL_TAGS9
VIEW_TOOL_VIEW:
VIEW_TRANS_MAP;
VIEW_TRANS_TAGS<
VIEW_TRANS_VIEW=*9
BookmarkType
BOOKMARK_BROWSER 
BOOKMARK_EDITOR2Ë
APIH
	AuthLogin.nervatura.RequestAuthLogin.nervatura.ResponseAuthLogin" 0

AuthUpdate.nervatura.Auth.nervatura.Auth" 3
AuthGet.nervatura.RequestGet.nervatura.Auth" M
AuthPassword .nervatura.RequestPasswordChange.nervatura.ResponseStatus" G
AuthPasswordReset.nervatura.RequestGet.nervatura.ResponseStatus" 8

TokenLogin.nervatura.RequestEmpty.nervatura.Auth" G
TokenRefresh.nervatura.RequestEmpty.nervatura.ResponseAuthLogin" N
TokenDecode.nervatura.RequestTokenDecode.nervatura.ResponseTokenDecode" >
Database.nervatura.RequestDatabase.nervatura.JsonBytes" ?
Delete.nervatura.RequestDelete.nervatura.ResponseStatus" >
Function.nervatura.RequestFunction.nervatura.JsonBytes" 6
View.nervatura.RequestView.nervatura.JsonBytes" 6
ConfigUpdate.nervatura.Config.nervatura.Config" 7
	ConfigGet.nervatura.RequestGet.nervatura.Config" <
ConfigQuery.nervatura.RequestQuery.nervatura.Configs" <
CurrencyUpdate.nervatura.Currency.nervatura.Currency" ;
CurrencyGet.nervatura.RequestGet.nervatura.Currency" A
CurrencyQuery.nervatura.RequestQuery.nervatura.Currencies" <
CustomerUpdate.nervatura.Customer.nervatura.Customer" ;
CustomerGet.nervatura.RequestGet.nervatura.Customer" @
CustomerQuery.nervatura.RequestQuery.nervatura.Customers" <
EmployeeUpdate.nervatura.Employee.nervatura.Employee" ;
EmployeeGet.nervatura.RequestGet.nervatura.Employee" @
EmployeeQuery.nervatura.RequestQuery.nervatura.Employees" 0

ItemUpdate.nervatura.Item.nervatura.Item" 3
ItemGet.nervatura.RequestGet.nervatura.Item" 8
	ItemQuery.nervatura.RequestQuery.nervatura.Items" 0

LinkUpdate.nervatura.Link.nervatura.Link" 3
LinkGet.nervatura.RequestGet.nervatura.Link" 8
	LinkQuery.nervatura.RequestQuery.nervatura.Links" 1
LogGet.nervatura.RequestGet.nervatura.Log" 6
LogQuery.nervatura.RequestQuery.nervatura.Logs" <
MovementUpdate.nervatura.Movement.nervatura.Movement" ;
MovementGet.nervatura.RequestGet.nervatura.Movement" @
MovementQuery.nervatura.RequestQuery.nervatura.Movements" 9
PaymentUpdate.nervatura.Payment.nervatura.Payment" 9

PaymentGet.nervatura.RequestGet.nervatura.Payment" >
PaymentQuery.nervatura.RequestQuery.nervatura.Payments" 3
PlaceUpdate.nervatura.Place.nervatura.Place" 5
PlaceGet.nervatura.RequestGet.nervatura.Place" :

PlaceQuery.nervatura.RequestQuery.nervatura.Places" 3
PriceUpdate.nervatura.Price.nervatura.Price" 5
PriceGet.nervatura.RequestGet.nervatura.Price" :

PriceQuery.nervatura.RequestQuery.nervatura.Prices" 9
ProductUpdate.nervatura.Product.nervatura.Product" 9

ProductGet.nervatura.RequestGet.nervatura.Product" >
ProductQuery.nervatura.RequestQuery.nervatura.Products" 9
ProjectUpdate.nervatura.Project.nervatura.Project" 9

ProjectGet.nervatura.RequestGet.nervatura.Project" >
ProjectQuery.nervatura.RequestQuery.nervatura.Projects" 0

RateUpdate.nervatura.Rate.nervatura.Rate" 3
RateGet.nervatura.RequestGet.nervatura.Rate" 8
	RateQuery.nervatura.RequestQuery.nervatura.Rates" -
	TaxUpdate.nervatura.Tax.nervatura.Tax" 1
TaxGet.nervatura.RequestGet.nervatura.Tax" 7
TaxQuery.nervatura.RequestQuery.nervatura.Taxes" 0

ToolUpdate.nervatura.Tool.nervatura.Tool" 3
ToolGet.nervatura.RequestGet.nervatura.Tool" 8
	ToolQuery.nervatura.RequestQuery.nervatura.Tools" 3
TransUpdate.nervatura.Trans.nervatura.Trans" 5
TransGet.nervatura.RequestGet.nervatura.Trans" @

TransQuery.nervatura.RequestQuery.nervatura.Transactions" B:Z8github.com/nervatura/nervatura/v6/pkg/service/grpc/protobproto3'
        , true);

        static::$is_initialized = true;
    }
}

