<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Auth message
 *
 * Generated from protobuf message <code>nervatura.Auth</code>
 */
class Auth extends \Google\Protobuf\Internal\Message
{
    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: USR1731101982N123 ("USR" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Friendly username, nickname or email for login.
     * It can be changed, but it is a unique identifier at the database level.
     *
     * Generated from protobuf field <code>string user_name = 3;</code>
     */
    protected $user_name = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field. Default value: GROUP_USER
     *
     * Generated from protobuf field <code>.nervatura.UserGroup user_group = 4;</code>
     */
    protected $user_group = 0;
    /**
     * Generated from protobuf field <code>bool disabled = 5;</code>
     */
    protected $disabled = false;
    /**
     * Generated from protobuf field <code>.nervatura.AuthMeta auth_meta = 6;</code>
     */
    protected $auth_meta = null;
    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString auth_map = 7;</code>
     */
    protected $auth_map = null;
    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 8;</code>
     */
    protected $time_stamp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           Database primary key
     *           Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *     @type string $code
     *           Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     *           Example: USR1731101982N123 ("USR" + UNIX Time stamp + "N" + current ID)
     *     @type string $user_name
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           Friendly username, nickname or email for login.
     *           It can be changed, but it is a unique identifier at the database level.
     *     @type int $user_group
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           ENUM field. Default value: GROUP_USER
     *     @type bool $disabled
     *     @type \Nervatura\AuthMeta $auth_meta
     *     @type \Nervatura\JsonString $auth_map
     *           Flexible key-value map for additional metadata. The value is any json type.
     *     @type string $time_stamp
     *           Timestamp of data creation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: USR1731101982N123 ("USR" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: USR1731101982N123 ("USR" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Friendly username, nickname or email for login.
     * It can be changed, but it is a unique identifier at the database level.
     *
     * Generated from protobuf field <code>string user_name = 3;</code>
     * @return string
     */
    public function getUserName()
    {
        return $this->user_name;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Friendly username, nickname or email for login.
     * It can be changed, but it is a unique identifier at the database level.
     *
     * Generated from protobuf field <code>string user_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_name = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field. Default value: GROUP_USER
     *
     * Generated from protobuf field <code>.nervatura.UserGroup user_group = 4;</code>
     * @return int
     */
    public function getUserGroup()
    {
        return $this->user_group;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field. Default value: GROUP_USER
     *
     * Generated from protobuf field <code>.nervatura.UserGroup user_group = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setUserGroup($var)
    {
        GPBUtil::checkEnum($var, \Nervatura\UserGroup::class);
        $this->user_group = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool disabled = 5;</code>
     * @return bool
     */
    public function getDisabled()
    {
        return $this->disabled;
    }

    /**
     * Generated from protobuf field <code>bool disabled = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setDisabled($var)
    {
        GPBUtil::checkBool($var);
        $this->disabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.AuthMeta auth_meta = 6;</code>
     * @return \Nervatura\AuthMeta
     */
    public function getAuthMeta()
    {
        return isset($this->auth_meta) ? $this->auth_meta : null;
    }

    public function hasAuthMeta()
    {
        return isset($this->auth_meta);
    }

    public function clearAuthMeta()
    {
        unset($this->auth_meta);
    }

    /**
     * Generated from protobuf field <code>.nervatura.AuthMeta auth_meta = 6;</code>
     * @param \Nervatura\AuthMeta $var
     * @return $this
     */
    public function setAuthMeta($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\AuthMeta::class);
        $this->auth_meta = $var;

        return $this;
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString auth_map = 7;</code>
     * @return \Nervatura\JsonString
     */
    public function getAuthMap()
    {
        return isset($this->auth_map) ? $this->auth_map : null;
    }

    public function hasAuthMap()
    {
        return isset($this->auth_map);
    }

    public function clearAuthMap()
    {
        unset($this->auth_map);
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString auth_map = 7;</code>
     * @param \Nervatura\JsonString $var
     * @return $this
     */
    public function setAuthMap($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\JsonString::class);
        $this->auth_map = $var;

        return $this;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 8;</code>
     * @return string
     */
    public function getTimeStamp()
    {
        return $this->time_stamp;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_stamp = $var;

        return $this;
    }

}

