<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * AuthMeta Bookmark message
 *
 * Generated from protobuf message <code>nervatura.Bookmark</code>
 */
class Bookmark extends \Google\Protobuf\Internal\Message
{
    /**
     * ENUM field. Valid values: BROWSER, EDITOR
     *
     * Generated from protobuf field <code>.nervatura.BookmarkType bookmark_type = 1;</code>
     */
    protected $bookmark_type = 0;
    /**
     * Label of the bookmark
     *
     * Generated from protobuf field <code>string label = 2;</code>
     */
    protected $label = '';
    /**
     * Editor model or browser view name
     *
     * Generated from protobuf field <code>string key = 3;</code>
     */
    protected $key = '';
    /**
     * Model code
     *
     * Generated from protobuf field <code>string code = 4;</code>
     */
    protected $code = '';
    /**
     * Browser filters
     *
     * Generated from protobuf field <code>.nervatura.JsonString filters = 5;</code>
     */
    protected $filters = null;
    /**
     * Browser visible columns
     *
     * Generated from protobuf field <code>map<string, bool> columns = 6;</code>
     */
    private $columns;
    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 7;</code>
     */
    protected $time_stamp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $bookmark_type
     *           ENUM field. Valid values: BROWSER, EDITOR
     *     @type string $label
     *           Label of the bookmark
     *     @type string $key
     *           Editor model or browser view name
     *     @type string $code
     *           Model code
     *     @type \Nervatura\JsonString $filters
     *           Browser filters
     *     @type array|\Google\Protobuf\Internal\MapField $columns
     *           Browser visible columns
     *     @type string $time_stamp
     *           Timestamp of data creation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * ENUM field. Valid values: BROWSER, EDITOR
     *
     * Generated from protobuf field <code>.nervatura.BookmarkType bookmark_type = 1;</code>
     * @return int
     */
    public function getBookmarkType()
    {
        return $this->bookmark_type;
    }

    /**
     * ENUM field. Valid values: BROWSER, EDITOR
     *
     * Generated from protobuf field <code>.nervatura.BookmarkType bookmark_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setBookmarkType($var)
    {
        GPBUtil::checkEnum($var, \Nervatura\BookmarkType::class);
        $this->bookmark_type = $var;

        return $this;
    }

    /**
     * Label of the bookmark
     *
     * Generated from protobuf field <code>string label = 2;</code>
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * Label of the bookmark
     *
     * Generated from protobuf field <code>string label = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->label = $var;

        return $this;
    }

    /**
     * Editor model or browser view name
     *
     * Generated from protobuf field <code>string key = 3;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Editor model or browser view name
     *
     * Generated from protobuf field <code>string key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Model code
     *
     * Generated from protobuf field <code>string code = 4;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Model code
     *
     * Generated from protobuf field <code>string code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Browser filters
     *
     * Generated from protobuf field <code>.nervatura.JsonString filters = 5;</code>
     * @return \Nervatura\JsonString
     */
    public function getFilters()
    {
        return isset($this->filters) ? $this->filters : null;
    }

    public function hasFilters()
    {
        return isset($this->filters);
    }

    public function clearFilters()
    {
        unset($this->filters);
    }

    /**
     * Browser filters
     *
     * Generated from protobuf field <code>.nervatura.JsonString filters = 5;</code>
     * @param \Nervatura\JsonString $var
     * @return $this
     */
    public function setFilters($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\JsonString::class);
        $this->filters = $var;

        return $this;
    }

    /**
     * Browser visible columns
     *
     * Generated from protobuf field <code>map<string, bool> columns = 6;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getColumns()
    {
        return $this->columns;
    }

    /**
     * Browser visible columns
     *
     * Generated from protobuf field <code>map<string, bool> columns = 6;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setColumns($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::BOOL);
        $this->columns = $arr;

        return $this;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 7;</code>
     * @return string
     */
    public function getTimeStamp()
    {
        return $this->time_stamp;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_stamp = $var;

        return $this;
    }

}

