<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use UnexpectedValueException;

/**
 * Protobuf type <code>nervatura.ConfigType</code>
 */
class ConfigType
{
    /**
     * Generated from protobuf enum <code>CONFIG_MAP = 0;</code>
     */
    const CONFIG_MAP = 0;
    /**
     * Generated from protobuf enum <code>CONFIG_SHORTCUT = 1;</code>
     */
    const CONFIG_SHORTCUT = 1;
    /**
     * Generated from protobuf enum <code>CONFIG_MESSAGE = 2;</code>
     */
    const CONFIG_MESSAGE = 2;
    /**
     * Generated from protobuf enum <code>CONFIG_PATTERN = 3;</code>
     */
    const CONFIG_PATTERN = 3;
    /**
     * Generated from protobuf enum <code>CONFIG_REPORT = 4;</code>
     */
    const CONFIG_REPORT = 4;
    /**
     * Generated from protobuf enum <code>CONFIG_PRINT_QUEUE = 5;</code>
     */
    const CONFIG_PRINT_QUEUE = 5;
    /**
     * Generated from protobuf enum <code>CONFIG_DATA = 6;</code>
     */
    const CONFIG_DATA = 6;

    private static $valueToName = [
        self::CONFIG_MAP => 'CONFIG_MAP',
        self::CONFIG_SHORTCUT => 'CONFIG_SHORTCUT',
        self::CONFIG_MESSAGE => 'CONFIG_MESSAGE',
        self::CONFIG_PATTERN => 'CONFIG_PATTERN',
        self::CONFIG_REPORT => 'CONFIG_REPORT',
        self::CONFIG_PRINT_QUEUE => 'CONFIG_PRINT_QUEUE',
        self::CONFIG_DATA => 'CONFIG_DATA',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

