<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ConfigShortcutField message
 *
 * Generated from protobuf message <code>nervatura.ConfigShortcutField</code>
 */
class ConfigShortcutField extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string field_name = 1;</code>
     */
    protected $field_name = '';
    /**
     * Generated from protobuf field <code>string description = 2;</code>
     */
    protected $description = '';
    /**
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.ShortcutField field_type = 3;</code>
     */
    protected $field_type = 0;
    /**
     * Generated from protobuf field <code>int64 order = 4;</code>
     */
    protected $order = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $field_name
     *     @type string $description
     *     @type int $field_type
     *           ENUM field.
     *     @type int|string $order
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string field_name = 1;</code>
     * @return string
     */
    public function getFieldName()
    {
        return $this->field_name;
    }

    /**
     * Generated from protobuf field <code>string field_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFieldName($var)
    {
        GPBUtil::checkString($var, True);
        $this->field_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.ShortcutField field_type = 3;</code>
     * @return int
     */
    public function getFieldType()
    {
        return $this->field_type;
    }

    /**
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.ShortcutField field_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setFieldType($var)
    {
        GPBUtil::checkEnum($var, \Nervatura\ShortcutField::class);
        $this->field_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 order = 4;</code>
     * @return int|string
     */
    public function getOrder()
    {
        return $this->order;
    }

    /**
     * Generated from protobuf field <code>int64 order = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrder($var)
    {
        GPBUtil::checkInt64($var);
        $this->order = $var;

        return $this;
    }

}

