<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Config message
 *
 * Generated from protobuf message <code>nervatura.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: CNF1731101982N123 ("CNF" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.ConfigType config_type = 3;</code>
     */
    protected $config_type = 0;
    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 11;</code>
     */
    protected $time_stamp = '';
    protected $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           Database primary key
     *           Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *     @type string $code
     *           Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     *           Example: CNF1731101982N123 ("CNF" + UNIX Time stamp + "N" + current ID)
     *     @type int $config_type
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           ENUM field.
     *     @type \Nervatura\ConfigMap $map
     *     @type \Nervatura\ConfigShortcut $shortcut
     *     @type \Nervatura\ConfigMessage $message
     *     @type \Nervatura\ConfigPattern $pattern
     *     @type \Nervatura\ConfigReport $report
     *     @type \Nervatura\ConfigPrintQueue $print_queue
     *     @type \Nervatura\JsonString $config_data
     *     @type string $time_stamp
     *           Timestamp of data creation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: CNF1731101982N123 ("CNF" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: CNF1731101982N123 ("CNF" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.ConfigType config_type = 3;</code>
     * @return int
     */
    public function getConfigType()
    {
        return $this->config_type;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.ConfigType config_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setConfigType($var)
    {
        GPBUtil::checkEnum($var, \Nervatura\ConfigType::class);
        $this->config_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.ConfigMap map = 4;</code>
     * @return \Nervatura\ConfigMap
     */
    public function getMap()
    {
        return $this->readOneof(4);
    }

    public function hasMap()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.nervatura.ConfigMap map = 4;</code>
     * @param \Nervatura\ConfigMap $var
     * @return $this
     */
    public function setMap($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\ConfigMap::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.ConfigShortcut shortcut = 5;</code>
     * @return \Nervatura\ConfigShortcut
     */
    public function getShortcut()
    {
        return $this->readOneof(5);
    }

    public function hasShortcut()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.nervatura.ConfigShortcut shortcut = 5;</code>
     * @param \Nervatura\ConfigShortcut $var
     * @return $this
     */
    public function setShortcut($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\ConfigShortcut::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.ConfigMessage message = 6;</code>
     * @return \Nervatura\ConfigMessage
     */
    public function getMessage()
    {
        return $this->readOneof(6);
    }

    public function hasMessage()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.nervatura.ConfigMessage message = 6;</code>
     * @param \Nervatura\ConfigMessage $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\ConfigMessage::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.ConfigPattern pattern = 7;</code>
     * @return \Nervatura\ConfigPattern
     */
    public function getPattern()
    {
        return $this->readOneof(7);
    }

    public function hasPattern()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>.nervatura.ConfigPattern pattern = 7;</code>
     * @param \Nervatura\ConfigPattern $var
     * @return $this
     */
    public function setPattern($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\ConfigPattern::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.ConfigReport report = 8;</code>
     * @return \Nervatura\ConfigReport
     */
    public function getReport()
    {
        return $this->readOneof(8);
    }

    public function hasReport()
    {
        return $this->hasOneof(8);
    }

    /**
     * Generated from protobuf field <code>.nervatura.ConfigReport report = 8;</code>
     * @param \Nervatura\ConfigReport $var
     * @return $this
     */
    public function setReport($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\ConfigReport::class);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.ConfigPrintQueue print_queue = 9;</code>
     * @return \Nervatura\ConfigPrintQueue
     */
    public function getPrintQueue()
    {
        return $this->readOneof(9);
    }

    public function hasPrintQueue()
    {
        return $this->hasOneof(9);
    }

    /**
     * Generated from protobuf field <code>.nervatura.ConfigPrintQueue print_queue = 9;</code>
     * @param \Nervatura\ConfigPrintQueue $var
     * @return $this
     */
    public function setPrintQueue($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\ConfigPrintQueue::class);
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.JsonString config_data = 10;</code>
     * @return \Nervatura\JsonString
     */
    public function getConfigData()
    {
        return $this->readOneof(10);
    }

    public function hasConfigData()
    {
        return $this->hasOneof(10);
    }

    /**
     * Generated from protobuf field <code>.nervatura.JsonString config_data = 10;</code>
     * @param \Nervatura\JsonString $var
     * @return $this
     */
    public function setConfigData($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\JsonString::class);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 11;</code>
     * @return string
     */
    public function getTimeStamp()
    {
        return $this->time_stamp;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_stamp = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getData()
    {
        return $this->whichOneof("data");
    }

}

