<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ConfigShortcut message
 *
 * Generated from protobuf message <code>nervatura.ConfigShortcut</code>
 */
class ConfigShortcut extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string shortcut_key = 1;</code>
     */
    protected $shortcut_key = '';
    /**
     * Generated from protobuf field <code>string description = 2;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string modul = 3;</code>
     */
    protected $modul = '';
    /**
     * Generated from protobuf field <code>string icon = 4;</code>
     */
    protected $icon = '';
    /**
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.ShortcutMethod method = 5;</code>
     */
    protected $method = 0;
    /**
     * Generated from protobuf field <code>string funcname = 6;</code>
     */
    protected $funcname = '';
    /**
     * Generated from protobuf field <code>string address = 7;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>repeated .nervatura.ConfigShortcutField fields = 8;</code>
     */
    private $fields;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $shortcut_key
     *     @type string $description
     *     @type string $modul
     *     @type string $icon
     *     @type int $method
     *           ENUM field.
     *     @type string $funcname
     *     @type string $address
     *     @type \Nervatura\ConfigShortcutField[]|\Google\Protobuf\Internal\RepeatedField $fields
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string shortcut_key = 1;</code>
     * @return string
     */
    public function getShortcutKey()
    {
        return $this->shortcut_key;
    }

    /**
     * Generated from protobuf field <code>string shortcut_key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setShortcutKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->shortcut_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string modul = 3;</code>
     * @return string
     */
    public function getModul()
    {
        return $this->modul;
    }

    /**
     * Generated from protobuf field <code>string modul = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setModul($var)
    {
        GPBUtil::checkString($var, True);
        $this->modul = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string icon = 4;</code>
     * @return string
     */
    public function getIcon()
    {
        return $this->icon;
    }

    /**
     * Generated from protobuf field <code>string icon = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIcon($var)
    {
        GPBUtil::checkString($var, True);
        $this->icon = $var;

        return $this;
    }

    /**
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.ShortcutMethod method = 5;</code>
     * @return int
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.ShortcutMethod method = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkEnum($var, \Nervatura\ShortcutMethod::class);
        $this->method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string funcname = 6;</code>
     * @return string
     */
    public function getFuncname()
    {
        return $this->funcname;
    }

    /**
     * Generated from protobuf field <code>string funcname = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setFuncname($var)
    {
        GPBUtil::checkString($var, True);
        $this->funcname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address = 7;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .nervatura.ConfigShortcutField fields = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFields()
    {
        return $this->fields;
    }

    /**
     * Generated from protobuf field <code>repeated .nervatura.ConfigShortcutField fields = 8;</code>
     * @param \Nervatura\ConfigShortcutField[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFields($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nervatura\ConfigShortcutField::class);
        $this->fields = $arr;

        return $this;
    }

}

