<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ConfigPrintQueue message
 *
 * Generated from protobuf message <code>nervatura.ConfigPrintQueue</code>
 */
class ConfigPrintQueue extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ref_type = 1;</code>
     */
    protected $ref_type = '';
    /**
     * Generated from protobuf field <code>string ref_code = 2;</code>
     */
    protected $ref_code = '';
    /**
     * Generated from protobuf field <code>int64 qty = 3;</code>
     */
    protected $qty = 0;
    /**
     * Generated from protobuf field <code>string report_code = 4;</code>
     */
    protected $report_code = '';
    /**
     * Generated from protobuf field <code>string auth_code = 5;</code>
     */
    protected $auth_code = '';
    /**
     * Generated from protobuf field <code>string time_stamp = 6;</code>
     */
    protected $time_stamp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ref_type
     *     @type string $ref_code
     *     @type int|string $qty
     *     @type string $report_code
     *     @type string $auth_code
     *     @type string $time_stamp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ref_type = 1;</code>
     * @return string
     */
    public function getRefType()
    {
        return $this->ref_type;
    }

    /**
     * Generated from protobuf field <code>string ref_type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRefType($var)
    {
        GPBUtil::checkString($var, True);
        $this->ref_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ref_code = 2;</code>
     * @return string
     */
    public function getRefCode()
    {
        return $this->ref_code;
    }

    /**
     * Generated from protobuf field <code>string ref_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRefCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->ref_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 qty = 3;</code>
     * @return int|string
     */
    public function getQty()
    {
        return $this->qty;
    }

    /**
     * Generated from protobuf field <code>int64 qty = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setQty($var)
    {
        GPBUtil::checkInt64($var);
        $this->qty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string report_code = 4;</code>
     * @return string
     */
    public function getReportCode()
    {
        return $this->report_code;
    }

    /**
     * Generated from protobuf field <code>string report_code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setReportCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->report_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string auth_code = 5;</code>
     * @return string
     */
    public function getAuthCode()
    {
        return $this->auth_code;
    }

    /**
     * Generated from protobuf field <code>string auth_code = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->auth_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string time_stamp = 6;</code>
     * @return string
     */
    public function getTimeStamp()
    {
        return $this->time_stamp;
    }

    /**
     * Generated from protobuf field <code>string time_stamp = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_stamp = $var;

        return $this;
    }

}

