<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * CurrencyMeta message
 *
 * Generated from protobuf message <code>nervatura.CurrencyMeta</code>
 */
class CurrencyMeta extends \Google\Protobuf\Internal\Message
{
    /**
     * The name of the currency.
     *
     * Generated from protobuf field <code>string description = 1;</code>
     */
    protected $description = '';
    /**
     * The number of decimal places used for recording and rounding by the program.
     *
     * Generated from protobuf field <code>int64 digit = 2;</code>
     */
    protected $digit = 0;
    /**
     * Rounding value for cash. Could be used in case the smallest banknote in circulation for that certain currency is not 1.
     *
     * Generated from protobuf field <code>int64 cash_round = 3;</code>
     */
    protected $cash_round = 0;
    /**
     * Additional tags for the currency
     *
     * Generated from protobuf field <code>repeated string tags = 4;</code>
     */
    private $tags;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $description
     *           The name of the currency.
     *     @type int|string $digit
     *           The number of decimal places used for recording and rounding by the program.
     *     @type int|string $cash_round
     *           Rounding value for cash. Could be used in case the smallest banknote in circulation for that certain currency is not 1.
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $tags
     *           Additional tags for the currency
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * The name of the currency.
     *
     * Generated from protobuf field <code>string description = 1;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * The name of the currency.
     *
     * Generated from protobuf field <code>string description = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * The number of decimal places used for recording and rounding by the program.
     *
     * Generated from protobuf field <code>int64 digit = 2;</code>
     * @return int|string
     */
    public function getDigit()
    {
        return $this->digit;
    }

    /**
     * The number of decimal places used for recording and rounding by the program.
     *
     * Generated from protobuf field <code>int64 digit = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDigit($var)
    {
        GPBUtil::checkInt64($var);
        $this->digit = $var;

        return $this;
    }

    /**
     * Rounding value for cash. Could be used in case the smallest banknote in circulation for that certain currency is not 1.
     *
     * Generated from protobuf field <code>int64 cash_round = 3;</code>
     * @return int|string
     */
    public function getCashRound()
    {
        return $this->cash_round;
    }

    /**
     * Rounding value for cash. Could be used in case the smallest banknote in circulation for that certain currency is not 1.
     *
     * Generated from protobuf field <code>int64 cash_round = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCashRound($var)
    {
        GPBUtil::checkInt64($var);
        $this->cash_round = $var;

        return $this;
    }

    /**
     * Additional tags for the currency
     *
     * Generated from protobuf field <code>repeated string tags = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Additional tags for the currency
     *
     * Generated from protobuf field <code>repeated string tags = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

}

