<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Currency message
 *
 * Generated from protobuf message <code>nervatura.Currency</code>
 */
class Currency extends \Google\Protobuf\Internal\Message
{
    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * The ISO 4217 code of the currency. It cannot be modified after creation.
     *
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>.nervatura.CurrencyMeta currency_meta = 3;</code>
     */
    protected $currency_meta = null;
    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString currency_map = 4;</code>
     */
    protected $currency_map = null;
    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 5;</code>
     */
    protected $time_stamp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           Database primary key
     *           Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *     @type string $code
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           The ISO 4217 code of the currency. It cannot be modified after creation.
     *     @type \Nervatura\CurrencyMeta $currency_meta
     *     @type \Nervatura\JsonString $currency_map
     *           Flexible key-value map for additional metadata. The value is any json type.
     *     @type string $time_stamp
     *           Timestamp of data creation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * The ISO 4217 code of the currency. It cannot be modified after creation.
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * The ISO 4217 code of the currency. It cannot be modified after creation.
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.CurrencyMeta currency_meta = 3;</code>
     * @return \Nervatura\CurrencyMeta
     */
    public function getCurrencyMeta()
    {
        return isset($this->currency_meta) ? $this->currency_meta : null;
    }

    public function hasCurrencyMeta()
    {
        return isset($this->currency_meta);
    }

    public function clearCurrencyMeta()
    {
        unset($this->currency_meta);
    }

    /**
     * Generated from protobuf field <code>.nervatura.CurrencyMeta currency_meta = 3;</code>
     * @param \Nervatura\CurrencyMeta $var
     * @return $this
     */
    public function setCurrencyMeta($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\CurrencyMeta::class);
        $this->currency_meta = $var;

        return $this;
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString currency_map = 4;</code>
     * @return \Nervatura\JsonString
     */
    public function getCurrencyMap()
    {
        return isset($this->currency_map) ? $this->currency_map : null;
    }

    public function hasCurrencyMap()
    {
        return isset($this->currency_map);
    }

    public function clearCurrencyMap()
    {
        unset($this->currency_map);
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString currency_map = 4;</code>
     * @param \Nervatura\JsonString $var
     * @return $this
     */
    public function setCurrencyMap($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\JsonString::class);
        $this->currency_map = $var;

        return $this;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 5;</code>
     * @return string
     */
    public function getTimeStamp()
    {
        return $this->time_stamp;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_stamp = $var;

        return $this;
    }

}

