<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use UnexpectedValueException;

/**
 * Protobuf type <code>nervatura.CustomerType</code>
 */
class CustomerType
{
    /**
     * Generated from protobuf enum <code>CUSTOMER_COMPANY = 0;</code>
     */
    const CUSTOMER_COMPANY = 0;
    /**
     * Generated from protobuf enum <code>CUSTOMER_PRIVATE = 1;</code>
     */
    const CUSTOMER_PRIVATE = 1;
    /**
     * Generated from protobuf enum <code>CUSTOMER_OTHER = 2;</code>
     */
    const CUSTOMER_OTHER = 2;
    /**
     * Generated from protobuf enum <code>CUSTOMER_OWN = 3;</code>
     */
    const CUSTOMER_OWN = 3;

    private static $valueToName = [
        self::CUSTOMER_COMPANY => 'CUSTOMER_COMPANY',
        self::CUSTOMER_PRIVATE => 'CUSTOMER_PRIVATE',
        self::CUSTOMER_OTHER => 'CUSTOMER_OTHER',
        self::CUSTOMER_OWN => 'CUSTOMER_OWN',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

