<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * CustomerMeta message
 *
 * Generated from protobuf message <code>nervatura.CustomerMeta</code>
 */
class CustomerMeta extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tax_number = 1;</code>
     */
    protected $tax_number = '';
    /**
     * Generated from protobuf field <code>string account = 2;</code>
     */
    protected $account = '';
    /**
     * Tax-free
     *
     * Generated from protobuf field <code>bool tax_free = 3;</code>
     */
    protected $tax_free = false;
    /**
     * Payment per.
     *
     * Generated from protobuf field <code>int64 terms = 4;</code>
     */
    protected $terms = 0;
    /**
     * Customer's credit limit. Data is used by financial reports.
     *
     * Generated from protobuf field <code>double credit_limit = 5;</code>
     */
    protected $credit_limit = 0.0;
    /**
     * If new product line is added (offer, order, invoice etc.) all products will receive the discount percentage specified in this field. If the product has a separate customer price, the value specified here will not be considered by the program.
     *
     * Generated from protobuf field <code>double discount = 6;</code>
     */
    protected $discount = 0.0;
    /**
     * Generated from protobuf field <code>string notes = 7;</code>
     */
    protected $notes = '';
    /**
     * Generated from protobuf field <code>bool inactive = 8;</code>
     */
    protected $inactive = false;
    /**
     * Additional tags for the customer
     *
     * Generated from protobuf field <code>repeated string tags = 9;</code>
     */
    private $tags;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tax_number
     *     @type string $account
     *     @type bool $tax_free
     *           Tax-free
     *     @type int|string $terms
     *           Payment per.
     *     @type float $credit_limit
     *           Customer's credit limit. Data is used by financial reports.
     *     @type float $discount
     *           If new product line is added (offer, order, invoice etc.) all products will receive the discount percentage specified in this field. If the product has a separate customer price, the value specified here will not be considered by the program.
     *     @type string $notes
     *     @type bool $inactive
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $tags
     *           Additional tags for the customer
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tax_number = 1;</code>
     * @return string
     */
    public function getTaxNumber()
    {
        return $this->tax_number;
    }

    /**
     * Generated from protobuf field <code>string tax_number = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTaxNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->tax_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string account = 2;</code>
     * @return string
     */
    public function getAccount()
    {
        return $this->account;
    }

    /**
     * Generated from protobuf field <code>string account = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkString($var, True);
        $this->account = $var;

        return $this;
    }

    /**
     * Tax-free
     *
     * Generated from protobuf field <code>bool tax_free = 3;</code>
     * @return bool
     */
    public function getTaxFree()
    {
        return $this->tax_free;
    }

    /**
     * Tax-free
     *
     * Generated from protobuf field <code>bool tax_free = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setTaxFree($var)
    {
        GPBUtil::checkBool($var);
        $this->tax_free = $var;

        return $this;
    }

    /**
     * Payment per.
     *
     * Generated from protobuf field <code>int64 terms = 4;</code>
     * @return int|string
     */
    public function getTerms()
    {
        return $this->terms;
    }

    /**
     * Payment per.
     *
     * Generated from protobuf field <code>int64 terms = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTerms($var)
    {
        GPBUtil::checkInt64($var);
        $this->terms = $var;

        return $this;
    }

    /**
     * Customer's credit limit. Data is used by financial reports.
     *
     * Generated from protobuf field <code>double credit_limit = 5;</code>
     * @return float
     */
    public function getCreditLimit()
    {
        return $this->credit_limit;
    }

    /**
     * Customer's credit limit. Data is used by financial reports.
     *
     * Generated from protobuf field <code>double credit_limit = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setCreditLimit($var)
    {
        GPBUtil::checkDouble($var);
        $this->credit_limit = $var;

        return $this;
    }

    /**
     * If new product line is added (offer, order, invoice etc.) all products will receive the discount percentage specified in this field. If the product has a separate customer price, the value specified here will not be considered by the program.
     *
     * Generated from protobuf field <code>double discount = 6;</code>
     * @return float
     */
    public function getDiscount()
    {
        return $this->discount;
    }

    /**
     * If new product line is added (offer, order, invoice etc.) all products will receive the discount percentage specified in this field. If the product has a separate customer price, the value specified here will not be considered by the program.
     *
     * Generated from protobuf field <code>double discount = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setDiscount($var)
    {
        GPBUtil::checkDouble($var);
        $this->discount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string notes = 7;</code>
     * @return string
     */
    public function getNotes()
    {
        return $this->notes;
    }

    /**
     * Generated from protobuf field <code>string notes = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setNotes($var)
    {
        GPBUtil::checkString($var, True);
        $this->notes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool inactive = 8;</code>
     * @return bool
     */
    public function getInactive()
    {
        return $this->inactive;
    }

    /**
     * Generated from protobuf field <code>bool inactive = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setInactive($var)
    {
        GPBUtil::checkBool($var);
        $this->inactive = $var;

        return $this;
    }

    /**
     * Additional tags for the customer
     *
     * Generated from protobuf field <code>repeated string tags = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Additional tags for the customer
     *
     * Generated from protobuf field <code>repeated string tags = 9;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

}

