<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Customer message
 *
 * Generated from protobuf message <code>nervatura.Customer</code>
 */
class Customer extends \Google\Protobuf\Internal\Message
{
    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: CUS1731101982N123 ("CUS" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field. Default value: CUSTOMER_COMPANY
     *
     * Generated from protobuf field <code>.nervatura.CustomerType customer_type = 3;</code>
     */
    protected $customer_type = 0;
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Full name of the customer
     *
     * Generated from protobuf field <code>string customer_name = 4;</code>
     */
    protected $customer_name = '';
    /**
     * Generated from protobuf field <code>repeated .nervatura.Address addresses = 5;</code>
     */
    private $addresses;
    /**
     * Generated from protobuf field <code>repeated .nervatura.Contact contacts = 6;</code>
     */
    private $contacts;
    /**
     * Generated from protobuf field <code>repeated .nervatura.Event events = 7;</code>
     */
    private $events;
    /**
     * Generated from protobuf field <code>.nervatura.CustomerMeta customer_meta = 8;</code>
     */
    protected $customer_meta = null;
    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString customer_map = 9;</code>
     */
    protected $customer_map = null;
    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 10;</code>
     */
    protected $time_stamp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           Database primary key
     *           Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *     @type string $code
     *           Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     *           Example: CUS1731101982N123 ("CUS" + UNIX Time stamp + "N" + current ID)
     *     @type int $customer_type
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           ENUM field. Default value: CUSTOMER_COMPANY
     *     @type string $customer_name
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           Full name of the customer
     *     @type \Nervatura\Address[]|\Google\Protobuf\Internal\RepeatedField $addresses
     *     @type \Nervatura\Contact[]|\Google\Protobuf\Internal\RepeatedField $contacts
     *     @type \Nervatura\Event[]|\Google\Protobuf\Internal\RepeatedField $events
     *     @type \Nervatura\CustomerMeta $customer_meta
     *     @type \Nervatura\JsonString $customer_map
     *           Flexible key-value map for additional metadata. The value is any json type.
     *     @type string $time_stamp
     *           Timestamp of data creation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: CUS1731101982N123 ("CUS" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: CUS1731101982N123 ("CUS" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field. Default value: CUSTOMER_COMPANY
     *
     * Generated from protobuf field <code>.nervatura.CustomerType customer_type = 3;</code>
     * @return int
     */
    public function getCustomerType()
    {
        return $this->customer_type;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field. Default value: CUSTOMER_COMPANY
     *
     * Generated from protobuf field <code>.nervatura.CustomerType customer_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCustomerType($var)
    {
        GPBUtil::checkEnum($var, \Nervatura\CustomerType::class);
        $this->customer_type = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Full name of the customer
     *
     * Generated from protobuf field <code>string customer_name = 4;</code>
     * @return string
     */
    public function getCustomerName()
    {
        return $this->customer_name;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Full name of the customer
     *
     * Generated from protobuf field <code>string customer_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerName($var)
    {
        GPBUtil::checkString($var, True);
        $this->customer_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .nervatura.Address addresses = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAddresses()
    {
        return $this->addresses;
    }

    /**
     * Generated from protobuf field <code>repeated .nervatura.Address addresses = 5;</code>
     * @param \Nervatura\Address[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAddresses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nervatura\Address::class);
        $this->addresses = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .nervatura.Contact contacts = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getContacts()
    {
        return $this->contacts;
    }

    /**
     * Generated from protobuf field <code>repeated .nervatura.Contact contacts = 6;</code>
     * @param \Nervatura\Contact[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setContacts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nervatura\Contact::class);
        $this->contacts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .nervatura.Event events = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * Generated from protobuf field <code>repeated .nervatura.Event events = 7;</code>
     * @param \Nervatura\Event[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEvents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nervatura\Event::class);
        $this->events = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.CustomerMeta customer_meta = 8;</code>
     * @return \Nervatura\CustomerMeta
     */
    public function getCustomerMeta()
    {
        return isset($this->customer_meta) ? $this->customer_meta : null;
    }

    public function hasCustomerMeta()
    {
        return isset($this->customer_meta);
    }

    public function clearCustomerMeta()
    {
        unset($this->customer_meta);
    }

    /**
     * Generated from protobuf field <code>.nervatura.CustomerMeta customer_meta = 8;</code>
     * @param \Nervatura\CustomerMeta $var
     * @return $this
     */
    public function setCustomerMeta($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\CustomerMeta::class);
        $this->customer_meta = $var;

        return $this;
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString customer_map = 9;</code>
     * @return \Nervatura\JsonString
     */
    public function getCustomerMap()
    {
        return isset($this->customer_map) ? $this->customer_map : null;
    }

    public function hasCustomerMap()
    {
        return isset($this->customer_map);
    }

    public function clearCustomerMap()
    {
        unset($this->customer_map);
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString customer_map = 9;</code>
     * @param \Nervatura\JsonString $var
     * @return $this
     */
    public function setCustomerMap($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\JsonString::class);
        $this->customer_map = $var;

        return $this;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 10;</code>
     * @return string
     */
    public function getTimeStamp()
    {
        return $this->time_stamp;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_stamp = $var;

        return $this;
    }

}

