<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use UnexpectedValueException;

/**
 * Protobuf type <code>nervatura.Direction</code>
 */
class Direction
{
    /**
     * Generated from protobuf enum <code>DIRECTION_OUT = 0;</code>
     */
    const DIRECTION_OUT = 0;
    /**
     * Generated from protobuf enum <code>DIRECTION_IN = 1;</code>
     */
    const DIRECTION_IN = 1;
    /**
     * Generated from protobuf enum <code>DIRECTION_TRANSFER = 2;</code>
     */
    const DIRECTION_TRANSFER = 2;

    private static $valueToName = [
        self::DIRECTION_OUT => 'DIRECTION_OUT',
        self::DIRECTION_IN => 'DIRECTION_IN',
        self::DIRECTION_TRANSFER => 'DIRECTION_TRANSFER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

