<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Employee message
 *
 * Generated from protobuf message <code>nervatura.Employee</code>
 */
class Employee extends \Google\Protobuf\Internal\Message
{
    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: EMP1731101982N123 ("EMP" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>.nervatura.Address address = 3;</code>
     */
    protected $address = null;
    /**
     * Generated from protobuf field <code>.nervatura.Contact contact = 4;</code>
     */
    protected $contact = null;
    /**
     * Generated from protobuf field <code>repeated .nervatura.Event events = 5;</code>
     */
    private $events;
    /**
     * Generated from protobuf field <code>.nervatura.EmployeeMeta employee_meta = 6;</code>
     */
    protected $employee_meta = null;
    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString employee_map = 7;</code>
     */
    protected $employee_map = null;
    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 8;</code>
     */
    protected $time_stamp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           Database primary key
     *           Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *     @type string $code
     *           Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     *           Example: EMP1731101982N123 ("EMP" + UNIX Time stamp + "N" + current ID)
     *     @type \Nervatura\Address $address
     *     @type \Nervatura\Contact $contact
     *     @type \Nervatura\Event[]|\Google\Protobuf\Internal\RepeatedField $events
     *     @type \Nervatura\EmployeeMeta $employee_meta
     *     @type \Nervatura\JsonString $employee_map
     *           Flexible key-value map for additional metadata. The value is any json type.
     *     @type string $time_stamp
     *           Timestamp of data creation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: EMP1731101982N123 ("EMP" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: EMP1731101982N123 ("EMP" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.Address address = 3;</code>
     * @return \Nervatura\Address
     */
    public function getAddress()
    {
        return isset($this->address) ? $this->address : null;
    }

    public function hasAddress()
    {
        return isset($this->address);
    }

    public function clearAddress()
    {
        unset($this->address);
    }

    /**
     * Generated from protobuf field <code>.nervatura.Address address = 3;</code>
     * @param \Nervatura\Address $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\Address::class);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.Contact contact = 4;</code>
     * @return \Nervatura\Contact
     */
    public function getContact()
    {
        return isset($this->contact) ? $this->contact : null;
    }

    public function hasContact()
    {
        return isset($this->contact);
    }

    public function clearContact()
    {
        unset($this->contact);
    }

    /**
     * Generated from protobuf field <code>.nervatura.Contact contact = 4;</code>
     * @param \Nervatura\Contact $var
     * @return $this
     */
    public function setContact($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\Contact::class);
        $this->contact = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .nervatura.Event events = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * Generated from protobuf field <code>repeated .nervatura.Event events = 5;</code>
     * @param \Nervatura\Event[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEvents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nervatura\Event::class);
        $this->events = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.EmployeeMeta employee_meta = 6;</code>
     * @return \Nervatura\EmployeeMeta
     */
    public function getEmployeeMeta()
    {
        return isset($this->employee_meta) ? $this->employee_meta : null;
    }

    public function hasEmployeeMeta()
    {
        return isset($this->employee_meta);
    }

    public function clearEmployeeMeta()
    {
        unset($this->employee_meta);
    }

    /**
     * Generated from protobuf field <code>.nervatura.EmployeeMeta employee_meta = 6;</code>
     * @param \Nervatura\EmployeeMeta $var
     * @return $this
     */
    public function setEmployeeMeta($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\EmployeeMeta::class);
        $this->employee_meta = $var;

        return $this;
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString employee_map = 7;</code>
     * @return \Nervatura\JsonString
     */
    public function getEmployeeMap()
    {
        return isset($this->employee_map) ? $this->employee_map : null;
    }

    public function hasEmployeeMap()
    {
        return isset($this->employee_map);
    }

    public function clearEmployeeMap()
    {
        unset($this->employee_map);
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString employee_map = 7;</code>
     * @param \Nervatura\JsonString $var
     * @return $this
     */
    public function setEmployeeMap($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\JsonString::class);
        $this->employee_map = $var;

        return $this;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 8;</code>
     * @return string
     */
    public function getTimeStamp()
    {
        return $this->time_stamp;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_stamp = $var;

        return $this;
    }

}

