<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Event message
 *
 * Generated from protobuf message <code>nervatura.Event</code>
 */
class Event extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string uid = 1;</code>
     */
    protected $uid = '';
    /**
     * Generated from protobuf field <code>string subject = 2;</code>
     */
    protected $subject = '';
    /**
     * ISO 8601 date-time
     *
     * Generated from protobuf field <code>string start_time = 3;</code>
     */
    protected $start_time = '';
    /**
     * ISO 8601 date-time
     *
     * Generated from protobuf field <code>string end_time = 4;</code>
     */
    protected $end_time = '';
    /**
     * Generated from protobuf field <code>string place = 5;</code>
     */
    protected $place = '';
    /**
     * Generated from protobuf field <code>string description = 6;</code>
     */
    protected $description = '';
    /**
     * Additional tags for the event
     *
     * Generated from protobuf field <code>repeated string tags = 7;</code>
     */
    private $tags;
    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString event_map = 8;</code>
     */
    protected $event_map = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $uid
     *     @type string $subject
     *     @type string $start_time
     *           ISO 8601 date-time
     *     @type string $end_time
     *           ISO 8601 date-time
     *     @type string $place
     *     @type string $description
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $tags
     *           Additional tags for the event
     *     @type \Nervatura\JsonString $event_map
     *           Flexible key-value map for additional metadata. The value is any json type.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string uid = 1;</code>
     * @return string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>string uid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subject = 2;</code>
     * @return string
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * Generated from protobuf field <code>string subject = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSubject($var)
    {
        GPBUtil::checkString($var, True);
        $this->subject = $var;

        return $this;
    }

    /**
     * ISO 8601 date-time
     *
     * Generated from protobuf field <code>string start_time = 3;</code>
     * @return string
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    /**
     * ISO 8601 date-time
     *
     * Generated from protobuf field <code>string start_time = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->start_time = $var;

        return $this;
    }

    /**
     * ISO 8601 date-time
     *
     * Generated from protobuf field <code>string end_time = 4;</code>
     * @return string
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    /**
     * ISO 8601 date-time
     *
     * Generated from protobuf field <code>string end_time = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->end_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string place = 5;</code>
     * @return string
     */
    public function getPlace()
    {
        return $this->place;
    }

    /**
     * Generated from protobuf field <code>string place = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPlace($var)
    {
        GPBUtil::checkString($var, True);
        $this->place = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 6;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Additional tags for the event
     *
     * Generated from protobuf field <code>repeated string tags = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Additional tags for the event
     *
     * Generated from protobuf field <code>repeated string tags = 7;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString event_map = 8;</code>
     * @return \Nervatura\JsonString
     */
    public function getEventMap()
    {
        return isset($this->event_map) ? $this->event_map : null;
    }

    public function hasEventMap()
    {
        return isset($this->event_map);
    }

    public function clearEventMap()
    {
        unset($this->event_map);
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString event_map = 8;</code>
     * @param \Nervatura\JsonString $var
     * @return $this
     */
    public function setEventMap($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\JsonString::class);
        $this->event_map = $var;

        return $this;
    }

}

