<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use UnexpectedValueException;

/**
 * Protobuf type <code>nervatura.FileType</code>
 */
class FileType
{
    /**
     * Generated from protobuf enum <code>FILE_PDF = 0;</code>
     */
    const FILE_PDF = 0;
    /**
     * Generated from protobuf enum <code>FILE_CSV = 1;</code>
     */
    const FILE_CSV = 1;

    private static $valueToName = [
        self::FILE_PDF => 'FILE_PDF',
        self::FILE_CSV => 'FILE_CSV',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

