<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ItemMeta message
 *
 * Generated from protobuf message <code>nervatura.ItemMeta</code>
 */
class ItemMeta extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string unit = 1;</code>
     */
    protected $unit = '';
    /**
     * Generated from protobuf field <code>double qty = 2;</code>
     */
    protected $qty = 0.0;
    /**
     * Generated from protobuf field <code>double fx_price = 3;</code>
     */
    protected $fx_price = 0.0;
    /**
     * Generated from protobuf field <code>double net_amount = 4;</code>
     */
    protected $net_amount = 0.0;
    /**
     * Generated from protobuf field <code>double discount = 5;</code>
     */
    protected $discount = 0.0;
    /**
     * Generated from protobuf field <code>double vat_amount = 6;</code>
     */
    protected $vat_amount = 0.0;
    /**
     * Generated from protobuf field <code>double amount = 7;</code>
     */
    protected $amount = 0.0;
    /**
     * Generated from protobuf field <code>string description = 8;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>bool deposit = 9;</code>
     */
    protected $deposit = false;
    /**
     * Generated from protobuf field <code>double own_stock = 10;</code>
     */
    protected $own_stock = 0.0;
    /**
     * Generated from protobuf field <code>bool action_price = 11;</code>
     */
    protected $action_price = false;
    /**
     * Additional tags for the item
     *
     * Generated from protobuf field <code>repeated string tags = 12;</code>
     */
    private $tags;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $unit
     *     @type float $qty
     *     @type float $fx_price
     *     @type float $net_amount
     *     @type float $discount
     *     @type float $vat_amount
     *     @type float $amount
     *     @type string $description
     *     @type bool $deposit
     *     @type float $own_stock
     *     @type bool $action_price
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $tags
     *           Additional tags for the item
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string unit = 1;</code>
     * @return string
     */
    public function getUnit()
    {
        return $this->unit;
    }

    /**
     * Generated from protobuf field <code>string unit = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUnit($var)
    {
        GPBUtil::checkString($var, True);
        $this->unit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double qty = 2;</code>
     * @return float
     */
    public function getQty()
    {
        return $this->qty;
    }

    /**
     * Generated from protobuf field <code>double qty = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setQty($var)
    {
        GPBUtil::checkDouble($var);
        $this->qty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double fx_price = 3;</code>
     * @return float
     */
    public function getFxPrice()
    {
        return $this->fx_price;
    }

    /**
     * Generated from protobuf field <code>double fx_price = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setFxPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->fx_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double net_amount = 4;</code>
     * @return float
     */
    public function getNetAmount()
    {
        return $this->net_amount;
    }

    /**
     * Generated from protobuf field <code>double net_amount = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setNetAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->net_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double discount = 5;</code>
     * @return float
     */
    public function getDiscount()
    {
        return $this->discount;
    }

    /**
     * Generated from protobuf field <code>double discount = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setDiscount($var)
    {
        GPBUtil::checkDouble($var);
        $this->discount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double vat_amount = 6;</code>
     * @return float
     */
    public function getVatAmount()
    {
        return $this->vat_amount;
    }

    /**
     * Generated from protobuf field <code>double vat_amount = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setVatAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->vat_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double amount = 7;</code>
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>double amount = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 8;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool deposit = 9;</code>
     * @return bool
     */
    public function getDeposit()
    {
        return $this->deposit;
    }

    /**
     * Generated from protobuf field <code>bool deposit = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setDeposit($var)
    {
        GPBUtil::checkBool($var);
        $this->deposit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double own_stock = 10;</code>
     * @return float
     */
    public function getOwnStock()
    {
        return $this->own_stock;
    }

    /**
     * Generated from protobuf field <code>double own_stock = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setOwnStock($var)
    {
        GPBUtil::checkDouble($var);
        $this->own_stock = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool action_price = 11;</code>
     * @return bool
     */
    public function getActionPrice()
    {
        return $this->action_price;
    }

    /**
     * Generated from protobuf field <code>bool action_price = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setActionPrice($var)
    {
        GPBUtil::checkBool($var);
        $this->action_price = $var;

        return $this;
    }

    /**
     * Additional tags for the item
     *
     * Generated from protobuf field <code>repeated string tags = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Additional tags for the item
     *
     * Generated from protobuf field <code>repeated string tags = 12;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

}

