<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Item message
 *
 * Generated from protobuf message <code>nervatura.Item</code>
 */
class Item extends \Google\Protobuf\Internal\Message
{
    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: ITM1731101982N123 ("ITM" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Trans">Trans</a>.Code
     *
     * Generated from protobuf field <code>string trans_code = 3;</code>
     */
    protected $trans_code = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Product">Product</a>.Code
     *
     * Generated from protobuf field <code>string product_code = 4;</code>
     */
    protected $product_code = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Tax">Tax</a>.Code
     *
     * Generated from protobuf field <code>string tax_code = 5;</code>
     */
    protected $tax_code = '';
    /**
     * Generated from protobuf field <code>.nervatura.ItemMeta item_meta = 6;</code>
     */
    protected $item_meta = null;
    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString item_map = 7;</code>
     */
    protected $item_map = null;
    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 8;</code>
     */
    protected $time_stamp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           Database primary key
     *           Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *     @type string $code
     *           Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     *           Example: ITM1731101982N123 ("ITM" + UNIX Time stamp + "N" + current ID)
     *     @type string $trans_code
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           Reference to <a href="#Trans">Trans</a>.Code
     *     @type string $product_code
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           Reference to <a href="#Product">Product</a>.Code
     *     @type string $tax_code
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           Reference to <a href="#Tax">Tax</a>.Code
     *     @type \Nervatura\ItemMeta $item_meta
     *     @type \Nervatura\JsonString $item_map
     *           Flexible key-value map for additional metadata. The value is any json type.
     *     @type string $time_stamp
     *           Timestamp of data creation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: ITM1731101982N123 ("ITM" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: ITM1731101982N123 ("ITM" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Trans">Trans</a>.Code
     *
     * Generated from protobuf field <code>string trans_code = 3;</code>
     * @return string
     */
    public function getTransCode()
    {
        return $this->trans_code;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Trans">Trans</a>.Code
     *
     * Generated from protobuf field <code>string trans_code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTransCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->trans_code = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Product">Product</a>.Code
     *
     * Generated from protobuf field <code>string product_code = 4;</code>
     * @return string
     */
    public function getProductCode()
    {
        return $this->product_code;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Product">Product</a>.Code
     *
     * Generated from protobuf field <code>string product_code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setProductCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->product_code = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Tax">Tax</a>.Code
     *
     * Generated from protobuf field <code>string tax_code = 5;</code>
     * @return string
     */
    public function getTaxCode()
    {
        return $this->tax_code;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Tax">Tax</a>.Code
     *
     * Generated from protobuf field <code>string tax_code = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTaxCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->tax_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.ItemMeta item_meta = 6;</code>
     * @return \Nervatura\ItemMeta
     */
    public function getItemMeta()
    {
        return isset($this->item_meta) ? $this->item_meta : null;
    }

    public function hasItemMeta()
    {
        return isset($this->item_meta);
    }

    public function clearItemMeta()
    {
        unset($this->item_meta);
    }

    /**
     * Generated from protobuf field <code>.nervatura.ItemMeta item_meta = 6;</code>
     * @param \Nervatura\ItemMeta $var
     * @return $this
     */
    public function setItemMeta($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\ItemMeta::class);
        $this->item_meta = $var;

        return $this;
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString item_map = 7;</code>
     * @return \Nervatura\JsonString
     */
    public function getItemMap()
    {
        return isset($this->item_map) ? $this->item_map : null;
    }

    public function hasItemMap()
    {
        return isset($this->item_map);
    }

    public function clearItemMap()
    {
        unset($this->item_map);
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString item_map = 7;</code>
     * @param \Nervatura\JsonString $var
     * @return $this
     */
    public function setItemMap($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\JsonString::class);
        $this->item_map = $var;

        return $this;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 8;</code>
     * @return string
     */
    public function getTimeStamp()
    {
        return $this->time_stamp;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_stamp = $var;

        return $this;
    }

}

