<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use UnexpectedValueException;

/**
 * Protobuf type <code>nervatura.LinkType</code>
 */
class LinkType
{
    /**
     * Generated from protobuf enum <code>LINK_CUSTOMER = 0;</code>
     */
    const LINK_CUSTOMER = 0;
    /**
     * Generated from protobuf enum <code>LINK_EMPLOYEE = 1;</code>
     */
    const LINK_EMPLOYEE = 1;
    /**
     * Generated from protobuf enum <code>LINK_ITEM = 2;</code>
     */
    const LINK_ITEM = 2;
    /**
     * Generated from protobuf enum <code>LINK_MOVEMENT = 3;</code>
     */
    const LINK_MOVEMENT = 3;
    /**
     * Generated from protobuf enum <code>LINK_PAYMENT = 4;</code>
     */
    const LINK_PAYMENT = 4;
    /**
     * Generated from protobuf enum <code>LINK_PLACE = 5;</code>
     */
    const LINK_PLACE = 5;
    /**
     * Generated from protobuf enum <code>LINK_PRODUCT = 6;</code>
     */
    const LINK_PRODUCT = 6;
    /**
     * Generated from protobuf enum <code>LINK_PROJECT = 7;</code>
     */
    const LINK_PROJECT = 7;
    /**
     * Generated from protobuf enum <code>LINK_TOOL = 8;</code>
     */
    const LINK_TOOL = 8;
    /**
     * Generated from protobuf enum <code>LINK_TRANS = 9;</code>
     */
    const LINK_TRANS = 9;

    private static $valueToName = [
        self::LINK_CUSTOMER => 'LINK_CUSTOMER',
        self::LINK_EMPLOYEE => 'LINK_EMPLOYEE',
        self::LINK_ITEM => 'LINK_ITEM',
        self::LINK_MOVEMENT => 'LINK_MOVEMENT',
        self::LINK_PAYMENT => 'LINK_PAYMENT',
        self::LINK_PLACE => 'LINK_PLACE',
        self::LINK_PRODUCT => 'LINK_PRODUCT',
        self::LINK_PROJECT => 'LINK_PROJECT',
        self::LINK_TOOL => 'LINK_TOOL',
        self::LINK_TRANS => 'LINK_TRANS',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

