<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Link message
 *
 * Generated from protobuf message <code>nervatura.Link</code>
 */
class Link extends \Google\Protobuf\Internal\Message
{
    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: LNK1731101982N123 ("LNK" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.LinkType link_type_1 = 3;</code>
     */
    protected $link_type_1 = 0;
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to LinkType1.code
     *
     * Generated from protobuf field <code>string link_code_1 = 4;</code>
     */
    protected $link_code_1 = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.LinkType link_type_2 = 5;</code>
     */
    protected $link_type_2 = 0;
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to LinkType2.code
     *
     * Generated from protobuf field <code>string link_code_2 = 6;</code>
     */
    protected $link_code_2 = '';
    /**
     * Generated from protobuf field <code>.nervatura.LinkMeta link_meta = 7;</code>
     */
    protected $link_meta = null;
    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString link_map = 8;</code>
     */
    protected $link_map = null;
    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 9;</code>
     */
    protected $time_stamp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           Database primary key
     *           Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *     @type string $code
     *           Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     *           Example: LNK1731101982N123 ("LNK" + UNIX Time stamp + "N" + current ID)
     *     @type int $link_type_1
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           ENUM field.
     *     @type string $link_code_1
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           Reference to LinkType1.code
     *     @type int $link_type_2
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           ENUM field.
     *     @type string $link_code_2
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           Reference to LinkType2.code
     *     @type \Nervatura\LinkMeta $link_meta
     *     @type \Nervatura\JsonString $link_map
     *           Flexible key-value map for additional metadata. The value is any json type.
     *     @type string $time_stamp
     *           Timestamp of data creation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: LNK1731101982N123 ("LNK" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: LNK1731101982N123 ("LNK" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.LinkType link_type_1 = 3;</code>
     * @return int
     */
    public function getLinkType1()
    {
        return $this->link_type_1;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.LinkType link_type_1 = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLinkType1($var)
    {
        GPBUtil::checkEnum($var, \Nervatura\LinkType::class);
        $this->link_type_1 = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to LinkType1.code
     *
     * Generated from protobuf field <code>string link_code_1 = 4;</code>
     * @return string
     */
    public function getLinkCode1()
    {
        return $this->link_code_1;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to LinkType1.code
     *
     * Generated from protobuf field <code>string link_code_1 = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLinkCode1($var)
    {
        GPBUtil::checkString($var, True);
        $this->link_code_1 = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.LinkType link_type_2 = 5;</code>
     * @return int
     */
    public function getLinkType2()
    {
        return $this->link_type_2;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.LinkType link_type_2 = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setLinkType2($var)
    {
        GPBUtil::checkEnum($var, \Nervatura\LinkType::class);
        $this->link_type_2 = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to LinkType2.code
     *
     * Generated from protobuf field <code>string link_code_2 = 6;</code>
     * @return string
     */
    public function getLinkCode2()
    {
        return $this->link_code_2;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to LinkType2.code
     *
     * Generated from protobuf field <code>string link_code_2 = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setLinkCode2($var)
    {
        GPBUtil::checkString($var, True);
        $this->link_code_2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.LinkMeta link_meta = 7;</code>
     * @return \Nervatura\LinkMeta
     */
    public function getLinkMeta()
    {
        return isset($this->link_meta) ? $this->link_meta : null;
    }

    public function hasLinkMeta()
    {
        return isset($this->link_meta);
    }

    public function clearLinkMeta()
    {
        unset($this->link_meta);
    }

    /**
     * Generated from protobuf field <code>.nervatura.LinkMeta link_meta = 7;</code>
     * @param \Nervatura\LinkMeta $var
     * @return $this
     */
    public function setLinkMeta($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\LinkMeta::class);
        $this->link_meta = $var;

        return $this;
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString link_map = 8;</code>
     * @return \Nervatura\JsonString
     */
    public function getLinkMap()
    {
        return isset($this->link_map) ? $this->link_map : null;
    }

    public function hasLinkMap()
    {
        return isset($this->link_map);
    }

    public function clearLinkMap()
    {
        unset($this->link_map);
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString link_map = 8;</code>
     * @param \Nervatura\JsonString $var
     * @return $this
     */
    public function setLinkMap($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\JsonString::class);
        $this->link_map = $var;

        return $this;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 9;</code>
     * @return string
     */
    public function getTimeStamp()
    {
        return $this->time_stamp;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_stamp = $var;

        return $this;
    }

}

