<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use UnexpectedValueException;

/**
 * Protobuf type <code>nervatura.LogType</code>
 */
class LogType
{
    /**
     * Generated from protobuf enum <code>LOG_INSERT = 0;</code>
     */
    const LOG_INSERT = 0;
    /**
     * Generated from protobuf enum <code>LOG_UPDATE = 1;</code>
     */
    const LOG_UPDATE = 1;
    /**
     * Generated from protobuf enum <code>LOG_DELETE = 2;</code>
     */
    const LOG_DELETE = 2;

    private static $valueToName = [
        self::LOG_INSERT => 'LOG_INSERT',
        self::LOG_UPDATE => 'LOG_UPDATE',
        self::LOG_DELETE => 'LOG_DELETE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

