<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use UnexpectedValueException;

/**
 * Protobuf type <code>nervatura.MapFilter</code>
 */
class MapFilter
{
    /**
     * Generated from protobuf enum <code>FILTER_ADDRESS = 0;</code>
     */
    const FILTER_ADDRESS = 0;
    /**
     * Generated from protobuf enum <code>FILTER_BARCODE = 1;</code>
     */
    const FILTER_BARCODE = 1;
    /**
     * Generated from protobuf enum <code>FILTER_CONTACT = 2;</code>
     */
    const FILTER_CONTACT = 2;
    /**
     * Generated from protobuf enum <code>FILTER_CURRENCY = 3;</code>
     */
    const FILTER_CURRENCY = 3;
    /**
     * Generated from protobuf enum <code>FILTER_CUSTOMER = 4;</code>
     */
    const FILTER_CUSTOMER = 4;
    /**
     * Generated from protobuf enum <code>FILTER_EMPLOYEE = 5;</code>
     */
    const FILTER_EMPLOYEE = 5;
    /**
     * Generated from protobuf enum <code>FILTER_EVENT = 6;</code>
     */
    const FILTER_EVENT = 6;
    /**
     * Generated from protobuf enum <code>FILTER_ITEM = 7;</code>
     */
    const FILTER_ITEM = 7;
    /**
     * Generated from protobuf enum <code>FILTER_MOVEMENT = 8;</code>
     */
    const FILTER_MOVEMENT = 8;
    /**
     * Generated from protobuf enum <code>FILTER_PAYMENT = 9;</code>
     */
    const FILTER_PAYMENT = 9;
    /**
     * Generated from protobuf enum <code>FILTER_PLACE = 10;</code>
     */
    const FILTER_PLACE = 10;
    /**
     * Generated from protobuf enum <code>FILTER_PRICE = 11;</code>
     */
    const FILTER_PRICE = 11;
    /**
     * Generated from protobuf enum <code>FILTER_PRODUCT = 12;</code>
     */
    const FILTER_PRODUCT = 12;
    /**
     * Generated from protobuf enum <code>FILTER_PROJECT = 13;</code>
     */
    const FILTER_PROJECT = 13;
    /**
     * Generated from protobuf enum <code>FILTER_RATE = 14;</code>
     */
    const FILTER_RATE = 14;
    /**
     * Generated from protobuf enum <code>FILTER_TAX = 15;</code>
     */
    const FILTER_TAX = 15;
    /**
     * Generated from protobuf enum <code>FILTER_TOOL = 16;</code>
     */
    const FILTER_TOOL = 16;
    /**
     * Generated from protobuf enum <code>FILTER_USER = 17;</code>
     */
    const FILTER_USER = 17;
    /**
     * Generated from protobuf enum <code>FILTER_TRANS = 18;</code>
     */
    const FILTER_TRANS = 18;
    /**
     * Generated from protobuf enum <code>FILTER_INVOICE = 19;</code>
     */
    const FILTER_INVOICE = 19;
    /**
     * Generated from protobuf enum <code>FILTER_RECEIPT = 20;</code>
     */
    const FILTER_RECEIPT = 20;
    /**
     * Generated from protobuf enum <code>FILTER_ORDER = 21;</code>
     */
    const FILTER_ORDER = 21;
    /**
     * Generated from protobuf enum <code>FILTER_OFFER = 22;</code>
     */
    const FILTER_OFFER = 22;
    /**
     * Generated from protobuf enum <code>FILTER_WORKSHEET = 23;</code>
     */
    const FILTER_WORKSHEET = 23;
    /**
     * Generated from protobuf enum <code>FILTER_RENT = 24;</code>
     */
    const FILTER_RENT = 24;
    /**
     * Generated from protobuf enum <code>FILTER_DELIVERY = 25;</code>
     */
    const FILTER_DELIVERY = 25;
    /**
     * Generated from protobuf enum <code>FILTER_INVENTORY = 26;</code>
     */
    const FILTER_INVENTORY = 26;
    /**
     * Generated from protobuf enum <code>FILTER_WAYBILL = 27;</code>
     */
    const FILTER_WAYBILL = 27;
    /**
     * Generated from protobuf enum <code>FILTER_PRODUCTION = 28;</code>
     */
    const FILTER_PRODUCTION = 28;
    /**
     * Generated from protobuf enum <code>FILTER_FORMULA = 29;</code>
     */
    const FILTER_FORMULA = 29;
    /**
     * Generated from protobuf enum <code>FILTER_BANK = 30;</code>
     */
    const FILTER_BANK = 30;
    /**
     * Generated from protobuf enum <code>FILTER_CASH = 31;</code>
     */
    const FILTER_CASH = 31;

    private static $valueToName = [
        self::FILTER_ADDRESS => 'FILTER_ADDRESS',
        self::FILTER_BARCODE => 'FILTER_BARCODE',
        self::FILTER_CONTACT => 'FILTER_CONTACT',
        self::FILTER_CURRENCY => 'FILTER_CURRENCY',
        self::FILTER_CUSTOMER => 'FILTER_CUSTOMER',
        self::FILTER_EMPLOYEE => 'FILTER_EMPLOYEE',
        self::FILTER_EVENT => 'FILTER_EVENT',
        self::FILTER_ITEM => 'FILTER_ITEM',
        self::FILTER_MOVEMENT => 'FILTER_MOVEMENT',
        self::FILTER_PAYMENT => 'FILTER_PAYMENT',
        self::FILTER_PLACE => 'FILTER_PLACE',
        self::FILTER_PRICE => 'FILTER_PRICE',
        self::FILTER_PRODUCT => 'FILTER_PRODUCT',
        self::FILTER_PROJECT => 'FILTER_PROJECT',
        self::FILTER_RATE => 'FILTER_RATE',
        self::FILTER_TAX => 'FILTER_TAX',
        self::FILTER_TOOL => 'FILTER_TOOL',
        self::FILTER_USER => 'FILTER_USER',
        self::FILTER_TRANS => 'FILTER_TRANS',
        self::FILTER_INVOICE => 'FILTER_INVOICE',
        self::FILTER_RECEIPT => 'FILTER_RECEIPT',
        self::FILTER_ORDER => 'FILTER_ORDER',
        self::FILTER_OFFER => 'FILTER_OFFER',
        self::FILTER_WORKSHEET => 'FILTER_WORKSHEET',
        self::FILTER_RENT => 'FILTER_RENT',
        self::FILTER_DELIVERY => 'FILTER_DELIVERY',
        self::FILTER_INVENTORY => 'FILTER_INVENTORY',
        self::FILTER_WAYBILL => 'FILTER_WAYBILL',
        self::FILTER_PRODUCTION => 'FILTER_PRODUCTION',
        self::FILTER_FORMULA => 'FILTER_FORMULA',
        self::FILTER_BANK => 'FILTER_BANK',
        self::FILTER_CASH => 'FILTER_CASH',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

