<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use UnexpectedValueException;

/**
 * Protobuf type <code>nervatura.Model</code>
 */
class Model
{
    /**
     * Generated from protobuf enum <code>AUTH = 0;</code>
     */
    const AUTH = 0;
    /**
     * Generated from protobuf enum <code>CONFIG = 1;</code>
     */
    const CONFIG = 1;
    /**
     * Generated from protobuf enum <code>CURRENCY = 2;</code>
     */
    const CURRENCY = 2;
    /**
     * Generated from protobuf enum <code>CUSTOMER = 3;</code>
     */
    const CUSTOMER = 3;
    /**
     * Generated from protobuf enum <code>EMPLOYEE = 4;</code>
     */
    const EMPLOYEE = 4;
    /**
     * Generated from protobuf enum <code>ITEM = 5;</code>
     */
    const ITEM = 5;
    /**
     * Generated from protobuf enum <code>LINK = 6;</code>
     */
    const LINK = 6;
    /**
     * Generated from protobuf enum <code>MOVEMENT = 7;</code>
     */
    const MOVEMENT = 7;
    /**
     * Generated from protobuf enum <code>PAYMENT = 8;</code>
     */
    const PAYMENT = 8;
    /**
     * Generated from protobuf enum <code>PLACE = 9;</code>
     */
    const PLACE = 9;
    /**
     * Generated from protobuf enum <code>PRICE = 10;</code>
     */
    const PRICE = 10;
    /**
     * Generated from protobuf enum <code>PRODUCT = 11;</code>
     */
    const PRODUCT = 11;
    /**
     * Generated from protobuf enum <code>PROJECT = 12;</code>
     */
    const PROJECT = 12;
    /**
     * Generated from protobuf enum <code>RATE = 13;</code>
     */
    const RATE = 13;
    /**
     * Generated from protobuf enum <code>TAX = 14;</code>
     */
    const TAX = 14;
    /**
     * Generated from protobuf enum <code>TOOL = 15;</code>
     */
    const TOOL = 15;
    /**
     * Generated from protobuf enum <code>TRANS = 16;</code>
     */
    const TRANS = 16;

    private static $valueToName = [
        self::AUTH => 'AUTH',
        self::CONFIG => 'CONFIG',
        self::CURRENCY => 'CURRENCY',
        self::CUSTOMER => 'CUSTOMER',
        self::EMPLOYEE => 'EMPLOYEE',
        self::ITEM => 'ITEM',
        self::LINK => 'LINK',
        self::MOVEMENT => 'MOVEMENT',
        self::PAYMENT => 'PAYMENT',
        self::PLACE => 'PLACE',
        self::PRICE => 'PRICE',
        self::PRODUCT => 'PRODUCT',
        self::PROJECT => 'PROJECT',
        self::RATE => 'RATE',
        self::TAX => 'TAX',
        self::TOOL => 'TOOL',
        self::TRANS => 'TRANS',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

