<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use UnexpectedValueException;

/**
 * Protobuf type <code>nervatura.MovementType</code>
 */
class MovementType
{
    /**
     * Generated from protobuf enum <code>MOVEMENT_INVENTORY = 0;</code>
     */
    const MOVEMENT_INVENTORY = 0;
    /**
     * Generated from protobuf enum <code>MOVEMENT_TOOL = 1;</code>
     */
    const MOVEMENT_TOOL = 1;
    /**
     * Generated from protobuf enum <code>MOVEMENT_PLAN = 2;</code>
     */
    const MOVEMENT_PLAN = 2;
    /**
     * Generated from protobuf enum <code>MOVEMENT_HEAD = 3;</code>
     */
    const MOVEMENT_HEAD = 3;

    private static $valueToName = [
        self::MOVEMENT_INVENTORY => 'MOVEMENT_INVENTORY',
        self::MOVEMENT_TOOL => 'MOVEMENT_TOOL',
        self::MOVEMENT_PLAN => 'MOVEMENT_PLAN',
        self::MOVEMENT_HEAD => 'MOVEMENT_HEAD',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

