<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MovementMeta message
 *
 * Generated from protobuf message <code>nervatura.MovementMeta</code>
 */
class MovementMeta extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double qty = 1;</code>
     */
    protected $qty = 0.0;
    /**
     * Generated from protobuf field <code>string notes = 2;</code>
     */
    protected $notes = '';
    /**
     * Generated from protobuf field <code>bool shared = 3;</code>
     */
    protected $shared = false;
    /**
     * Additional tags for the movement
     *
     * Generated from protobuf field <code>repeated string tags = 4;</code>
     */
    private $tags;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $qty
     *     @type string $notes
     *     @type bool $shared
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $tags
     *           Additional tags for the movement
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double qty = 1;</code>
     * @return float
     */
    public function getQty()
    {
        return $this->qty;
    }

    /**
     * Generated from protobuf field <code>double qty = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setQty($var)
    {
        GPBUtil::checkDouble($var);
        $this->qty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string notes = 2;</code>
     * @return string
     */
    public function getNotes()
    {
        return $this->notes;
    }

    /**
     * Generated from protobuf field <code>string notes = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNotes($var)
    {
        GPBUtil::checkString($var, True);
        $this->notes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool shared = 3;</code>
     * @return bool
     */
    public function getShared()
    {
        return $this->shared;
    }

    /**
     * Generated from protobuf field <code>bool shared = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setShared($var)
    {
        GPBUtil::checkBool($var);
        $this->shared = $var;

        return $this;
    }

    /**
     * Additional tags for the movement
     *
     * Generated from protobuf field <code>repeated string tags = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Additional tags for the movement
     *
     * Generated from protobuf field <code>repeated string tags = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

}

