<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Movement message
 *
 * Generated from protobuf message <code>nervatura.Movement</code>
 */
class Movement extends \Google\Protobuf\Internal\Message
{
    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: MOV1731101982N123 ("MOV" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.MovementType movement_type = 3;</code>
     */
    protected $movement_type = 0;
    /**
     * ISO 8601 date-time
     *
     * Generated from protobuf field <code>string shipping_time = 4;</code>
     */
    protected $shipping_time = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Trans">Trans</a>.Code
     *
     * Generated from protobuf field <code>string trans_code = 5;</code>
     */
    protected $trans_code = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Product">Product</a>.Code
     *
     * Generated from protobuf field <code>string product_code = 6;</code>
     */
    protected $product_code = '';
    /**
     * Reference to <a href="#Tool">Tool</a>.Code
     *
     * Generated from protobuf field <code>string tool_code = 7;</code>
     */
    protected $tool_code = '';
    /**
     * Reference to <a href="#Place">Place</a>.Code
     *
     * Generated from protobuf field <code>string place_code = 8;</code>
     */
    protected $place_code = '';
    /**
     * Reference to <a href="#Item">Item</a>.Code
     *
     * Generated from protobuf field <code>string item_code = 9;</code>
     */
    protected $item_code = '';
    /**
     * Reference to <a href="#Movement">Movement</a>.Code
     *
     * Generated from protobuf field <code>string movement_code = 10;</code>
     */
    protected $movement_code = '';
    /**
     * Generated from protobuf field <code>.nervatura.MovementMeta movement_meta = 11;</code>
     */
    protected $movement_meta = null;
    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString movement_map = 12;</code>
     */
    protected $movement_map = null;
    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 13;</code>
     */
    protected $time_stamp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           Database primary key
     *           Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *     @type string $code
     *           Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     *           Example: MOV1731101982N123 ("MOV" + UNIX Time stamp + "N" + current ID)
     *     @type int $movement_type
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           ENUM field.
     *     @type string $shipping_time
     *           ISO 8601 date-time
     *     @type string $trans_code
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           Reference to <a href="#Trans">Trans</a>.Code
     *     @type string $product_code
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           Reference to <a href="#Product">Product</a>.Code
     *     @type string $tool_code
     *           Reference to <a href="#Tool">Tool</a>.Code
     *     @type string $place_code
     *           Reference to <a href="#Place">Place</a>.Code
     *     @type string $item_code
     *           Reference to <a href="#Item">Item</a>.Code
     *     @type string $movement_code
     *           Reference to <a href="#Movement">Movement</a>.Code
     *     @type \Nervatura\MovementMeta $movement_meta
     *     @type \Nervatura\JsonString $movement_map
     *           Flexible key-value map for additional metadata. The value is any json type.
     *     @type string $time_stamp
     *           Timestamp of data creation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: MOV1731101982N123 ("MOV" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: MOV1731101982N123 ("MOV" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.MovementType movement_type = 3;</code>
     * @return int
     */
    public function getMovementType()
    {
        return $this->movement_type;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.MovementType movement_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMovementType($var)
    {
        GPBUtil::checkEnum($var, \Nervatura\MovementType::class);
        $this->movement_type = $var;

        return $this;
    }

    /**
     * ISO 8601 date-time
     *
     * Generated from protobuf field <code>string shipping_time = 4;</code>
     * @return string
     */
    public function getShippingTime()
    {
        return $this->shipping_time;
    }

    /**
     * ISO 8601 date-time
     *
     * Generated from protobuf field <code>string shipping_time = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setShippingTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->shipping_time = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Trans">Trans</a>.Code
     *
     * Generated from protobuf field <code>string trans_code = 5;</code>
     * @return string
     */
    public function getTransCode()
    {
        return $this->trans_code;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Trans">Trans</a>.Code
     *
     * Generated from protobuf field <code>string trans_code = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTransCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->trans_code = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Product">Product</a>.Code
     *
     * Generated from protobuf field <code>string product_code = 6;</code>
     * @return string
     */
    public function getProductCode()
    {
        return $this->product_code;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Product">Product</a>.Code
     *
     * Generated from protobuf field <code>string product_code = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setProductCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->product_code = $var;

        return $this;
    }

    /**
     * Reference to <a href="#Tool">Tool</a>.Code
     *
     * Generated from protobuf field <code>string tool_code = 7;</code>
     * @return string
     */
    public function getToolCode()
    {
        return $this->tool_code;
    }

    /**
     * Reference to <a href="#Tool">Tool</a>.Code
     *
     * Generated from protobuf field <code>string tool_code = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setToolCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->tool_code = $var;

        return $this;
    }

    /**
     * Reference to <a href="#Place">Place</a>.Code
     *
     * Generated from protobuf field <code>string place_code = 8;</code>
     * @return string
     */
    public function getPlaceCode()
    {
        return $this->place_code;
    }

    /**
     * Reference to <a href="#Place">Place</a>.Code
     *
     * Generated from protobuf field <code>string place_code = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setPlaceCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->place_code = $var;

        return $this;
    }

    /**
     * Reference to <a href="#Item">Item</a>.Code
     *
     * Generated from protobuf field <code>string item_code = 9;</code>
     * @return string
     */
    public function getItemCode()
    {
        return $this->item_code;
    }

    /**
     * Reference to <a href="#Item">Item</a>.Code
     *
     * Generated from protobuf field <code>string item_code = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setItemCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->item_code = $var;

        return $this;
    }

    /**
     * Reference to <a href="#Movement">Movement</a>.Code
     *
     * Generated from protobuf field <code>string movement_code = 10;</code>
     * @return string
     */
    public function getMovementCode()
    {
        return $this->movement_code;
    }

    /**
     * Reference to <a href="#Movement">Movement</a>.Code
     *
     * Generated from protobuf field <code>string movement_code = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setMovementCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->movement_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.MovementMeta movement_meta = 11;</code>
     * @return \Nervatura\MovementMeta
     */
    public function getMovementMeta()
    {
        return isset($this->movement_meta) ? $this->movement_meta : null;
    }

    public function hasMovementMeta()
    {
        return isset($this->movement_meta);
    }

    public function clearMovementMeta()
    {
        unset($this->movement_meta);
    }

    /**
     * Generated from protobuf field <code>.nervatura.MovementMeta movement_meta = 11;</code>
     * @param \Nervatura\MovementMeta $var
     * @return $this
     */
    public function setMovementMeta($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\MovementMeta::class);
        $this->movement_meta = $var;

        return $this;
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString movement_map = 12;</code>
     * @return \Nervatura\JsonString
     */
    public function getMovementMap()
    {
        return isset($this->movement_map) ? $this->movement_map : null;
    }

    public function hasMovementMap()
    {
        return isset($this->movement_map);
    }

    public function clearMovementMap()
    {
        unset($this->movement_map);
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString movement_map = 12;</code>
     * @param \Nervatura\JsonString $var
     * @return $this
     */
    public function setMovementMap($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\JsonString::class);
        $this->movement_map = $var;

        return $this;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 13;</code>
     * @return string
     */
    public function getTimeStamp()
    {
        return $this->time_stamp;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_stamp = $var;

        return $this;
    }

}

