<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Payment message
 *
 * Generated from protobuf message <code>nervatura.Payment</code>
 */
class Payment extends \Google\Protobuf\Internal\Message
{
    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: PMT1731101982N123 ("PMT" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ISO 8601 date-time
     *
     * Generated from protobuf field <code>string paid_date = 3;</code>
     */
    protected $paid_date = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Trans">Trans</a>.Code
     *
     * Generated from protobuf field <code>string trans_code = 4;</code>
     */
    protected $trans_code = '';
    /**
     * Generated from protobuf field <code>.nervatura.PaymentMeta payment_meta = 5;</code>
     */
    protected $payment_meta = null;
    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString payment_map = 6;</code>
     */
    protected $payment_map = null;
    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 7;</code>
     */
    protected $time_stamp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           Database primary key
     *           Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *     @type string $code
     *           Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     *           Example: PMT1731101982N123 ("PMT" + UNIX Time stamp + "N" + current ID)
     *     @type string $paid_date
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           ISO 8601 date-time
     *     @type string $trans_code
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           Reference to <a href="#Trans">Trans</a>.Code
     *     @type \Nervatura\PaymentMeta $payment_meta
     *     @type \Nervatura\JsonString $payment_map
     *           Flexible key-value map for additional metadata. The value is any json type.
     *     @type string $time_stamp
     *           Timestamp of data creation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: PMT1731101982N123 ("PMT" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: PMT1731101982N123 ("PMT" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ISO 8601 date-time
     *
     * Generated from protobuf field <code>string paid_date = 3;</code>
     * @return string
     */
    public function getPaidDate()
    {
        return $this->paid_date;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ISO 8601 date-time
     *
     * Generated from protobuf field <code>string paid_date = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPaidDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->paid_date = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Trans">Trans</a>.Code
     *
     * Generated from protobuf field <code>string trans_code = 4;</code>
     * @return string
     */
    public function getTransCode()
    {
        return $this->trans_code;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Trans">Trans</a>.Code
     *
     * Generated from protobuf field <code>string trans_code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTransCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->trans_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.PaymentMeta payment_meta = 5;</code>
     * @return \Nervatura\PaymentMeta
     */
    public function getPaymentMeta()
    {
        return isset($this->payment_meta) ? $this->payment_meta : null;
    }

    public function hasPaymentMeta()
    {
        return isset($this->payment_meta);
    }

    public function clearPaymentMeta()
    {
        unset($this->payment_meta);
    }

    /**
     * Generated from protobuf field <code>.nervatura.PaymentMeta payment_meta = 5;</code>
     * @param \Nervatura\PaymentMeta $var
     * @return $this
     */
    public function setPaymentMeta($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\PaymentMeta::class);
        $this->payment_meta = $var;

        return $this;
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString payment_map = 6;</code>
     * @return \Nervatura\JsonString
     */
    public function getPaymentMap()
    {
        return isset($this->payment_map) ? $this->payment_map : null;
    }

    public function hasPaymentMap()
    {
        return isset($this->payment_map);
    }

    public function clearPaymentMap()
    {
        unset($this->payment_map);
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString payment_map = 6;</code>
     * @param \Nervatura\JsonString $var
     * @return $this
     */
    public function setPaymentMap($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\JsonString::class);
        $this->payment_map = $var;

        return $this;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 7;</code>
     * @return string
     */
    public function getTimeStamp()
    {
        return $this->time_stamp;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_stamp = $var;

        return $this;
    }

}

