<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use UnexpectedValueException;

/**
 * Protobuf type <code>nervatura.PlaceType</code>
 */
class PlaceType
{
    /**
     * Generated from protobuf enum <code>PLACE_WAREHOUSE = 0;</code>
     */
    const PLACE_WAREHOUSE = 0;
    /**
     * Generated from protobuf enum <code>PLACE_BANK = 1;</code>
     */
    const PLACE_BANK = 1;
    /**
     * Generated from protobuf enum <code>PLACE_CASH = 2;</code>
     */
    const PLACE_CASH = 2;
    /**
     * Generated from protobuf enum <code>PLACE_OTHER = 3;</code>
     */
    const PLACE_OTHER = 3;

    private static $valueToName = [
        self::PLACE_WAREHOUSE => 'PLACE_WAREHOUSE',
        self::PLACE_BANK => 'PLACE_BANK',
        self::PLACE_CASH => 'PLACE_CASH',
        self::PLACE_OTHER => 'PLACE_OTHER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

