<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use UnexpectedValueException;

/**
 * Protobuf type <code>nervatura.PriceType</code>
 */
class PriceType
{
    /**
     * Generated from protobuf enum <code>PRICE_CUSTOMER = 0;</code>
     */
    const PRICE_CUSTOMER = 0;
    /**
     * Generated from protobuf enum <code>PRICE_VENDOR = 1;</code>
     */
    const PRICE_VENDOR = 1;

    private static $valueToName = [
        self::PRICE_CUSTOMER => 'PRICE_CUSTOMER',
        self::PRICE_VENDOR => 'PRICE_VENDOR',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

