<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Price message
 *
 * Generated from protobuf message <code>nervatura.Price</code>
 */
class Price extends \Google\Protobuf\Internal\Message
{
    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation. 
     * Example: PRC1731101982N123 ("PRC" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.PriceType price_type = 3;</code>
     */
    protected $price_type = 0;
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Start of validity, mandatory data. ISO 8601 date
     *
     * Generated from protobuf field <code>string valid_from = 4;</code>
     */
    protected $valid_from = '';
    /**
     * End of validity, can be left empty. ISO 8601 date
     *
     * Generated from protobuf field <code>string valid_to = 5;</code>
     */
    protected $valid_to = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Product">Product</a>.Code
     *
     * Generated from protobuf field <code>string product_code = 6;</code>
     */
    protected $product_code = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Currency">Currency</a>.Code
     *
     * Generated from protobuf field <code>string currency_code = 7;</code>
     */
    protected $currency_code = '';
    /**
     * Optional field. Reference to <a href="#Customer">Customer</a>.Code
     *
     * Generated from protobuf field <code>string customer_code = 8;</code>
     */
    protected $customer_code = '';
    /**
     * Price ranges can also be specified, thus different price can be set for a smaller and bigger quantity of the same product.
     * The quantity should be used as the lower threshold, ie. this should be the minimum quantity for the price set.
     *
     * Generated from protobuf field <code>double qty = 9;</code>
     */
    protected $qty = 0.0;
    /**
     * Generated from protobuf field <code>.nervatura.PriceMeta price_meta = 10;</code>
     */
    protected $price_meta = null;
    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString price_map = 11;</code>
     */
    protected $price_map = null;
    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 12;</code>
     */
    protected $time_stamp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           Database primary key
     *           Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *     @type string $code
     *           Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation. 
     *           Example: PRC1731101982N123 ("PRC" + UNIX Time stamp + "N" + current ID)
     *     @type int $price_type
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           ENUM field.
     *     @type string $valid_from
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           Start of validity, mandatory data. ISO 8601 date
     *     @type string $valid_to
     *           End of validity, can be left empty. ISO 8601 date
     *     @type string $product_code
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           Reference to <a href="#Product">Product</a>.Code
     *     @type string $currency_code
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           Reference to <a href="#Currency">Currency</a>.Code
     *     @type string $customer_code
     *           Optional field. Reference to <a href="#Customer">Customer</a>.Code
     *     @type float $qty
     *           Price ranges can also be specified, thus different price can be set for a smaller and bigger quantity of the same product.
     *           The quantity should be used as the lower threshold, ie. this should be the minimum quantity for the price set.
     *     @type \Nervatura\PriceMeta $price_meta
     *     @type \Nervatura\JsonString $price_map
     *           Flexible key-value map for additional metadata. The value is any json type.
     *     @type string $time_stamp
     *           Timestamp of data creation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation. 
     * Example: PRC1731101982N123 ("PRC" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation. 
     * Example: PRC1731101982N123 ("PRC" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.PriceType price_type = 3;</code>
     * @return int
     */
    public function getPriceType()
    {
        return $this->price_type;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.PriceType price_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPriceType($var)
    {
        GPBUtil::checkEnum($var, \Nervatura\PriceType::class);
        $this->price_type = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Start of validity, mandatory data. ISO 8601 date
     *
     * Generated from protobuf field <code>string valid_from = 4;</code>
     * @return string
     */
    public function getValidFrom()
    {
        return $this->valid_from;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Start of validity, mandatory data. ISO 8601 date
     *
     * Generated from protobuf field <code>string valid_from = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setValidFrom($var)
    {
        GPBUtil::checkString($var, True);
        $this->valid_from = $var;

        return $this;
    }

    /**
     * End of validity, can be left empty. ISO 8601 date
     *
     * Generated from protobuf field <code>string valid_to = 5;</code>
     * @return string
     */
    public function getValidTo()
    {
        return $this->valid_to;
    }

    /**
     * End of validity, can be left empty. ISO 8601 date
     *
     * Generated from protobuf field <code>string valid_to = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setValidTo($var)
    {
        GPBUtil::checkString($var, True);
        $this->valid_to = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Product">Product</a>.Code
     *
     * Generated from protobuf field <code>string product_code = 6;</code>
     * @return string
     */
    public function getProductCode()
    {
        return $this->product_code;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Product">Product</a>.Code
     *
     * Generated from protobuf field <code>string product_code = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setProductCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->product_code = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Currency">Currency</a>.Code
     *
     * Generated from protobuf field <code>string currency_code = 7;</code>
     * @return string
     */
    public function getCurrencyCode()
    {
        return $this->currency_code;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Currency">Currency</a>.Code
     *
     * Generated from protobuf field <code>string currency_code = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrencyCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency_code = $var;

        return $this;
    }

    /**
     * Optional field. Reference to <a href="#Customer">Customer</a>.Code
     *
     * Generated from protobuf field <code>string customer_code = 8;</code>
     * @return string
     */
    public function getCustomerCode()
    {
        return $this->customer_code;
    }

    /**
     * Optional field. Reference to <a href="#Customer">Customer</a>.Code
     *
     * Generated from protobuf field <code>string customer_code = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->customer_code = $var;

        return $this;
    }

    /**
     * Price ranges can also be specified, thus different price can be set for a smaller and bigger quantity of the same product.
     * The quantity should be used as the lower threshold, ie. this should be the minimum quantity for the price set.
     *
     * Generated from protobuf field <code>double qty = 9;</code>
     * @return float
     */
    public function getQty()
    {
        return $this->qty;
    }

    /**
     * Price ranges can also be specified, thus different price can be set for a smaller and bigger quantity of the same product.
     * The quantity should be used as the lower threshold, ie. this should be the minimum quantity for the price set.
     *
     * Generated from protobuf field <code>double qty = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setQty($var)
    {
        GPBUtil::checkDouble($var);
        $this->qty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.PriceMeta price_meta = 10;</code>
     * @return \Nervatura\PriceMeta
     */
    public function getPriceMeta()
    {
        return isset($this->price_meta) ? $this->price_meta : null;
    }

    public function hasPriceMeta()
    {
        return isset($this->price_meta);
    }

    public function clearPriceMeta()
    {
        unset($this->price_meta);
    }

    /**
     * Generated from protobuf field <code>.nervatura.PriceMeta price_meta = 10;</code>
     * @param \Nervatura\PriceMeta $var
     * @return $this
     */
    public function setPriceMeta($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\PriceMeta::class);
        $this->price_meta = $var;

        return $this;
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString price_map = 11;</code>
     * @return \Nervatura\JsonString
     */
    public function getPriceMap()
    {
        return isset($this->price_map) ? $this->price_map : null;
    }

    public function hasPriceMap()
    {
        return isset($this->price_map);
    }

    public function clearPriceMap()
    {
        unset($this->price_map);
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString price_map = 11;</code>
     * @param \Nervatura\JsonString $var
     * @return $this
     */
    public function setPriceMap($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\JsonString::class);
        $this->price_map = $var;

        return $this;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 12;</code>
     * @return string
     */
    public function getTimeStamp()
    {
        return $this->time_stamp;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_stamp = $var;

        return $this;
    }

}

