<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use UnexpectedValueException;

/**
 * Protobuf type <code>nervatura.ProductType</code>
 */
class ProductType
{
    /**
     * Generated from protobuf enum <code>PRODUCT_ITEM = 0;</code>
     */
    const PRODUCT_ITEM = 0;
    /**
     * Generated from protobuf enum <code>PRODUCT_SERVICE = 1;</code>
     */
    const PRODUCT_SERVICE = 1;
    /**
     * Generated from protobuf enum <code>PRODUCT_VIRTUAL = 2;</code>
     */
    const PRODUCT_VIRTUAL = 2;

    private static $valueToName = [
        self::PRODUCT_ITEM => 'PRODUCT_ITEM',
        self::PRODUCT_SERVICE => 'PRODUCT_SERVICE',
        self::PRODUCT_VIRTUAL => 'PRODUCT_VIRTUAL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

