<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Product message
 *
 * Generated from protobuf message <code>nervatura.Product</code>
 */
class Product extends \Google\Protobuf\Internal\Message
{
    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: PRD1731101982N123 ("PRD" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.ProductType product_type = 3;</code>
     */
    protected $product_type = 0;
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * The full name of the product or short description.
     *
     * Generated from protobuf field <code>string product_name = 4;</code>
     */
    protected $product_name = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Tax">Tax</a>.Code
     *
     * Generated from protobuf field <code>string tax_code = 5;</code>
     */
    protected $tax_code = '';
    /**
     * Generated from protobuf field <code>repeated .nervatura.Event events = 6;</code>
     */
    private $events;
    /**
     * Generated from protobuf field <code>.nervatura.ProductMeta product_meta = 7;</code>
     */
    protected $product_meta = null;
    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString product_map = 8;</code>
     */
    protected $product_map = null;
    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 9;</code>
     */
    protected $time_stamp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           Database primary key
     *           Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *     @type string $code
     *           Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     *           Example: PRD1731101982N123 ("PRD" + UNIX Time stamp + "N" + current ID)
     *     @type int $product_type
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           ENUM field.
     *     @type string $product_name
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           The full name of the product or short description.
     *     @type string $tax_code
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           Reference to <a href="#Tax">Tax</a>.Code
     *     @type \Nervatura\Event[]|\Google\Protobuf\Internal\RepeatedField $events
     *     @type \Nervatura\ProductMeta $product_meta
     *     @type \Nervatura\JsonString $product_map
     *           Flexible key-value map for additional metadata. The value is any json type.
     *     @type string $time_stamp
     *           Timestamp of data creation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: PRD1731101982N123 ("PRD" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: PRD1731101982N123 ("PRD" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.ProductType product_type = 3;</code>
     * @return int
     */
    public function getProductType()
    {
        return $this->product_type;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.ProductType product_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setProductType($var)
    {
        GPBUtil::checkEnum($var, \Nervatura\ProductType::class);
        $this->product_type = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * The full name of the product or short description.
     *
     * Generated from protobuf field <code>string product_name = 4;</code>
     * @return string
     */
    public function getProductName()
    {
        return $this->product_name;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * The full name of the product or short description.
     *
     * Generated from protobuf field <code>string product_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setProductName($var)
    {
        GPBUtil::checkString($var, True);
        $this->product_name = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Tax">Tax</a>.Code
     *
     * Generated from protobuf field <code>string tax_code = 5;</code>
     * @return string
     */
    public function getTaxCode()
    {
        return $this->tax_code;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Tax">Tax</a>.Code
     *
     * Generated from protobuf field <code>string tax_code = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTaxCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->tax_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .nervatura.Event events = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * Generated from protobuf field <code>repeated .nervatura.Event events = 6;</code>
     * @param \Nervatura\Event[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEvents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nervatura\Event::class);
        $this->events = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.ProductMeta product_meta = 7;</code>
     * @return \Nervatura\ProductMeta
     */
    public function getProductMeta()
    {
        return isset($this->product_meta) ? $this->product_meta : null;
    }

    public function hasProductMeta()
    {
        return isset($this->product_meta);
    }

    public function clearProductMeta()
    {
        unset($this->product_meta);
    }

    /**
     * Generated from protobuf field <code>.nervatura.ProductMeta product_meta = 7;</code>
     * @param \Nervatura\ProductMeta $var
     * @return $this
     */
    public function setProductMeta($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\ProductMeta::class);
        $this->product_meta = $var;

        return $this;
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString product_map = 8;</code>
     * @return \Nervatura\JsonString
     */
    public function getProductMap()
    {
        return isset($this->product_map) ? $this->product_map : null;
    }

    public function hasProductMap()
    {
        return isset($this->product_map);
    }

    public function clearProductMap()
    {
        unset($this->product_map);
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString product_map = 8;</code>
     * @param \Nervatura\JsonString $var
     * @return $this
     */
    public function setProductMap($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\JsonString::class);
        $this->product_map = $var;

        return $this;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 9;</code>
     * @return string
     */
    public function getTimeStamp()
    {
        return $this->time_stamp;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_stamp = $var;

        return $this;
    }

}

