<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Project message
 *
 * Generated from protobuf message <code>nervatura.Project</code>
 */
class Project extends \Google\Protobuf\Internal\Message
{
    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: PRJ1731101982N123 ("PRJ" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * The name of the project.
     *
     * Generated from protobuf field <code>string project_name = 3;</code>
     */
    protected $project_name = '';
    /**
     * Reference to <a href="#Customer">Customer</a>.Code
     *
     * Generated from protobuf field <code>string customer_code = 4;</code>
     */
    protected $customer_code = '';
    /**
     * Generated from protobuf field <code>repeated .nervatura.Address addresses = 5;</code>
     */
    private $addresses;
    /**
     * Generated from protobuf field <code>repeated .nervatura.Contact contacts = 6;</code>
     */
    private $contacts;
    /**
     * Generated from protobuf field <code>repeated .nervatura.Event events = 7;</code>
     */
    private $events;
    /**
     * Generated from protobuf field <code>.nervatura.ProjectMeta project_meta = 8;</code>
     */
    protected $project_meta = null;
    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString project_map = 9;</code>
     */
    protected $project_map = null;
    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 10;</code>
     */
    protected $time_stamp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           Database primary key
     *           Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *     @type string $code
     *           Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     *           Example: PRJ1731101982N123 ("PRJ" + UNIX Time stamp + "N" + current ID)
     *     @type string $project_name
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           The name of the project.
     *     @type string $customer_code
     *           Reference to <a href="#Customer">Customer</a>.Code
     *     @type \Nervatura\Address[]|\Google\Protobuf\Internal\RepeatedField $addresses
     *     @type \Nervatura\Contact[]|\Google\Protobuf\Internal\RepeatedField $contacts
     *     @type \Nervatura\Event[]|\Google\Protobuf\Internal\RepeatedField $events
     *     @type \Nervatura\ProjectMeta $project_meta
     *     @type \Nervatura\JsonString $project_map
     *           Flexible key-value map for additional metadata. The value is any json type.
     *     @type string $time_stamp
     *           Timestamp of data creation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: PRJ1731101982N123 ("PRJ" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: PRJ1731101982N123 ("PRJ" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * The name of the project.
     *
     * Generated from protobuf field <code>string project_name = 3;</code>
     * @return string
     */
    public function getProjectName()
    {
        return $this->project_name;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * The name of the project.
     *
     * Generated from protobuf field <code>string project_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setProjectName($var)
    {
        GPBUtil::checkString($var, True);
        $this->project_name = $var;

        return $this;
    }

    /**
     * Reference to <a href="#Customer">Customer</a>.Code
     *
     * Generated from protobuf field <code>string customer_code = 4;</code>
     * @return string
     */
    public function getCustomerCode()
    {
        return $this->customer_code;
    }

    /**
     * Reference to <a href="#Customer">Customer</a>.Code
     *
     * Generated from protobuf field <code>string customer_code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->customer_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .nervatura.Address addresses = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAddresses()
    {
        return $this->addresses;
    }

    /**
     * Generated from protobuf field <code>repeated .nervatura.Address addresses = 5;</code>
     * @param \Nervatura\Address[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAddresses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nervatura\Address::class);
        $this->addresses = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .nervatura.Contact contacts = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getContacts()
    {
        return $this->contacts;
    }

    /**
     * Generated from protobuf field <code>repeated .nervatura.Contact contacts = 6;</code>
     * @param \Nervatura\Contact[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setContacts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nervatura\Contact::class);
        $this->contacts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .nervatura.Event events = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * Generated from protobuf field <code>repeated .nervatura.Event events = 7;</code>
     * @param \Nervatura\Event[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEvents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nervatura\Event::class);
        $this->events = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.ProjectMeta project_meta = 8;</code>
     * @return \Nervatura\ProjectMeta
     */
    public function getProjectMeta()
    {
        return isset($this->project_meta) ? $this->project_meta : null;
    }

    public function hasProjectMeta()
    {
        return isset($this->project_meta);
    }

    public function clearProjectMeta()
    {
        unset($this->project_meta);
    }

    /**
     * Generated from protobuf field <code>.nervatura.ProjectMeta project_meta = 8;</code>
     * @param \Nervatura\ProjectMeta $var
     * @return $this
     */
    public function setProjectMeta($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\ProjectMeta::class);
        $this->project_meta = $var;

        return $this;
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString project_map = 9;</code>
     * @return \Nervatura\JsonString
     */
    public function getProjectMap()
    {
        return isset($this->project_map) ? $this->project_map : null;
    }

    public function hasProjectMap()
    {
        return isset($this->project_map);
    }

    public function clearProjectMap()
    {
        unset($this->project_map);
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString project_map = 9;</code>
     * @param \Nervatura\JsonString $var
     * @return $this
     */
    public function setProjectMap($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\JsonString::class);
        $this->project_map = $var;

        return $this;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 10;</code>
     * @return string
     */
    public function getTimeStamp()
    {
        return $this->time_stamp;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_stamp = $var;

        return $this;
    }

}

