<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Rate message
 *
 * Generated from protobuf message <code>nervatura.Rate</code>
 */
class Rate extends \Google\Protobuf\Internal\Message
{
    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: RAT1731101982N123 ("RAT" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.RateType rate_type = 3;</code>
     */
    protected $rate_type = 0;
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ISO 8601 date
     *
     * Generated from protobuf field <code>string rate_date = 4;</code>
     */
    protected $rate_date = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Place">Place</a>.Code
     *
     * Generated from protobuf field <code>string place_code = 5;</code>
     */
    protected $place_code = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Currency">Currency</a>.Code
     *
     * Generated from protobuf field <code>string currency_code = 6;</code>
     */
    protected $currency_code = '';
    /**
     * Generated from protobuf field <code>.nervatura.RateMeta rate_meta = 7;</code>
     */
    protected $rate_meta = null;
    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString rate_map = 8;</code>
     */
    protected $rate_map = null;
    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 9;</code>
     */
    protected $time_stamp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           Database primary key
     *           Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *     @type string $code
     *           Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     *           Example: RAT1731101982N123 ("RAT" + UNIX Time stamp + "N" + current ID)
     *     @type int $rate_type
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           ENUM field.
     *     @type string $rate_date
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           ISO 8601 date
     *     @type string $place_code
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           Reference to <a href="#Place">Place</a>.Code
     *     @type string $currency_code
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           Reference to <a href="#Currency">Currency</a>.Code
     *     @type \Nervatura\RateMeta $rate_meta
     *     @type \Nervatura\JsonString $rate_map
     *           Flexible key-value map for additional metadata. The value is any json type.
     *     @type string $time_stamp
     *           Timestamp of data creation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: RAT1731101982N123 ("RAT" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: RAT1731101982N123 ("RAT" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.RateType rate_type = 3;</code>
     * @return int
     */
    public function getRateType()
    {
        return $this->rate_type;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.RateType rate_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRateType($var)
    {
        GPBUtil::checkEnum($var, \Nervatura\RateType::class);
        $this->rate_type = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ISO 8601 date
     *
     * Generated from protobuf field <code>string rate_date = 4;</code>
     * @return string
     */
    public function getRateDate()
    {
        return $this->rate_date;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ISO 8601 date
     *
     * Generated from protobuf field <code>string rate_date = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRateDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->rate_date = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Place">Place</a>.Code
     *
     * Generated from protobuf field <code>string place_code = 5;</code>
     * @return string
     */
    public function getPlaceCode()
    {
        return $this->place_code;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Place">Place</a>.Code
     *
     * Generated from protobuf field <code>string place_code = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPlaceCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->place_code = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Currency">Currency</a>.Code
     *
     * Generated from protobuf field <code>string currency_code = 6;</code>
     * @return string
     */
    public function getCurrencyCode()
    {
        return $this->currency_code;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Currency">Currency</a>.Code
     *
     * Generated from protobuf field <code>string currency_code = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrencyCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.RateMeta rate_meta = 7;</code>
     * @return \Nervatura\RateMeta
     */
    public function getRateMeta()
    {
        return isset($this->rate_meta) ? $this->rate_meta : null;
    }

    public function hasRateMeta()
    {
        return isset($this->rate_meta);
    }

    public function clearRateMeta()
    {
        unset($this->rate_meta);
    }

    /**
     * Generated from protobuf field <code>.nervatura.RateMeta rate_meta = 7;</code>
     * @param \Nervatura\RateMeta $var
     * @return $this
     */
    public function setRateMeta($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\RateMeta::class);
        $this->rate_meta = $var;

        return $this;
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString rate_map = 8;</code>
     * @return \Nervatura\JsonString
     */
    public function getRateMap()
    {
        return isset($this->rate_map) ? $this->rate_map : null;
    }

    public function hasRateMap()
    {
        return isset($this->rate_map);
    }

    public function clearRateMap()
    {
        unset($this->rate_map);
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString rate_map = 8;</code>
     * @param \Nervatura\JsonString $var
     * @return $this
     */
    public function setRateMap($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\JsonString::class);
        $this->rate_map = $var;

        return $this;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 9;</code>
     * @return string
     */
    public function getTimeStamp()
    {
        return $this->time_stamp;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_stamp = $var;

        return $this;
    }

}

