<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nervatura.RequestView</code>
 */
class RequestView extends \Google\Protobuf\Internal\Message
{
    /**
     * Predefined view name
     *
     * Generated from protobuf field <code>.nervatura.ViewName name = 1;</code>
     */
    protected $name = 0;
    /**
     * Valid SQL WHERE clause
     *
     * Generated from protobuf field <code>string filter = 2;</code>
     */
    protected $filter = '';
    /**
     * Valid SQL ORDER BY clause
     *
     * Generated from protobuf field <code>repeated string order_by = 3;</code>
     */
    private $order_by;
    /**
     * Limit the number of records
     *
     * Generated from protobuf field <code>int64 limit = 4;</code>
     */
    protected $limit = 0;
    /**
     * Skip the first N records
     *
     * Generated from protobuf field <code>int64 offset = 5;</code>
     */
    protected $offset = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $name
     *           Predefined view name
     *     @type string $filter
     *           Valid SQL WHERE clause
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $order_by
     *           Valid SQL ORDER BY clause
     *     @type int|string $limit
     *           Limit the number of records
     *     @type int|string $offset
     *           Skip the first N records
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Predefined view name
     *
     * Generated from protobuf field <code>.nervatura.ViewName name = 1;</code>
     * @return int
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Predefined view name
     *
     * Generated from protobuf field <code>.nervatura.ViewName name = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkEnum($var, \Nervatura\ViewName::class);
        $this->name = $var;

        return $this;
    }

    /**
     * Valid SQL WHERE clause
     *
     * Generated from protobuf field <code>string filter = 2;</code>
     * @return string
     */
    public function getFilter()
    {
        return $this->filter;
    }

    /**
     * Valid SQL WHERE clause
     *
     * Generated from protobuf field <code>string filter = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkString($var, True);
        $this->filter = $var;

        return $this;
    }

    /**
     * Valid SQL ORDER BY clause
     *
     * Generated from protobuf field <code>repeated string order_by = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrderBy()
    {
        return $this->order_by;
    }

    /**
     * Valid SQL ORDER BY clause
     *
     * Generated from protobuf field <code>repeated string order_by = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrderBy($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->order_by = $arr;

        return $this;
    }

    /**
     * Limit the number of records
     *
     * Generated from protobuf field <code>int64 limit = 4;</code>
     * @return int|string
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * Limit the number of records
     *
     * Generated from protobuf field <code>int64 limit = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt64($var);
        $this->limit = $var;

        return $this;
    }

    /**
     * Skip the first N records
     *
     * Generated from protobuf field <code>int64 offset = 5;</code>
     * @return int|string
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * Skip the first N records
     *
     * Generated from protobuf field <code>int64 offset = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkInt64($var);
        $this->offset = $var;

        return $this;
    }

}

