<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nervatura.RequestDatabase</code>
 */
class RequestDatabase extends \Google\Protobuf\Internal\Message
{
    /**
     * Database alias name
     *
     * Generated from protobuf field <code>string alias = 1;</code>
     */
    protected $alias = '';
    /**
     * Create demo data
     *
     * Generated from protobuf field <code>bool demo = 2;</code>
     */
    protected $demo = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $alias
     *           Database alias name
     *     @type bool $demo
     *           Create demo data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Database alias name
     *
     * Generated from protobuf field <code>string alias = 1;</code>
     * @return string
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     * Database alias name
     *
     * Generated from protobuf field <code>string alias = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAlias($var)
    {
        GPBUtil::checkString($var, True);
        $this->alias = $var;

        return $this;
    }

    /**
     * Create demo data
     *
     * Generated from protobuf field <code>bool demo = 2;</code>
     * @return bool
     */
    public function getDemo()
    {
        return $this->demo;
    }

    /**
     * Create demo data
     *
     * Generated from protobuf field <code>bool demo = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setDemo($var)
    {
        GPBUtil::checkBool($var);
        $this->demo = $var;

        return $this;
    }

}

