<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nervatura.RequestQueryFilter</code>
 */
class RequestQueryFilter extends \Google\Protobuf\Internal\Message
{
    /**
     * Fieldname. If it starts with like_, gte_, lte_, gt_, lt_, in_, not_, the value is a string and the filter is applied to the field as a LIKE, GTE, LTE, GT, LT, IN, NOT operation.
     *
     * Generated from protobuf field <code>string field = 1;</code>
     */
    protected $field = '';
    /**
     * Generated from protobuf field <code>string value = 2;</code>
     */
    protected $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $field
     *           Fieldname. If it starts with like_, gte_, lte_, gt_, lt_, in_, not_, the value is a string and the filter is applied to the field as a LIKE, GTE, LTE, GT, LT, IN, NOT operation.
     *     @type string $value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Fieldname. If it starts with like_, gte_, lte_, gt_, lt_, in_, not_, the value is a string and the filter is applied to the field as a LIKE, GTE, LTE, GT, LT, IN, NOT operation.
     *
     * Generated from protobuf field <code>string field = 1;</code>
     * @return string
     */
    public function getField()
    {
        return $this->field;
    }

    /**
     * Fieldname. If it starts with like_, gte_, lte_, gt_, lt_, in_, not_, the value is a string and the filter is applied to the field as a LIKE, GTE, LTE, GT, LT, IN, NOT operation.
     *
     * Generated from protobuf field <code>string field = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setField($var)
    {
        GPBUtil::checkString($var, True);
        $this->field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>string value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

}

