<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nervatura.RequestQuery</code>
 */
class RequestQuery extends \Google\Protobuf\Internal\Message
{
    /**
     * Fieldname and filter value
     *
     * Generated from protobuf field <code>repeated .nervatura.RequestQueryFilter filters = 1;</code>
     */
    private $filters;
    /**
     * Limit the number of records
     *
     * Generated from protobuf field <code>int64 limit = 2;</code>
     */
    protected $limit = 0;
    /**
     * Skip the first N records
     *
     * Generated from protobuf field <code>int64 offset = 3;</code>
     */
    protected $offset = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Nervatura\RequestQueryFilter[]|\Google\Protobuf\Internal\RepeatedField $filters
     *           Fieldname and filter value
     *     @type int|string $limit
     *           Limit the number of records
     *     @type int|string $offset
     *           Skip the first N records
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Fieldname and filter value
     *
     * Generated from protobuf field <code>repeated .nervatura.RequestQueryFilter filters = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFilters()
    {
        return $this->filters;
    }

    /**
     * Fieldname and filter value
     *
     * Generated from protobuf field <code>repeated .nervatura.RequestQueryFilter filters = 1;</code>
     * @param \Nervatura\RequestQueryFilter[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFilters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nervatura\RequestQueryFilter::class);
        $this->filters = $arr;

        return $this;
    }

    /**
     * Limit the number of records
     *
     * Generated from protobuf field <code>int64 limit = 2;</code>
     * @return int|string
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * Limit the number of records
     *
     * Generated from protobuf field <code>int64 limit = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt64($var);
        $this->limit = $var;

        return $this;
    }

    /**
     * Skip the first N records
     *
     * Generated from protobuf field <code>int64 offset = 3;</code>
     * @return int|string
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * Skip the first N records
     *
     * Generated from protobuf field <code>int64 offset = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkInt64($var);
        $this->offset = $var;

        return $this;
    }

}

