<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nervatura.RequestFunction</code>
 */
class RequestFunction extends \Google\Protobuf\Internal\Message
{
    /**
     * Server function name.
     * Valid function names: report_install, report_list, report_get, product_price, email_send
     *
     * Generated from protobuf field <code>string function = 1;</code>
     */
    protected $function = '';
    /**
     * Function arguments
     *
     * Generated from protobuf field <code>map<string, string> args = 2;</code>
     */
    private $args;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $function
     *           Server function name.
     *           Valid function names: report_install, report_list, report_get, product_price, email_send
     *     @type array|\Google\Protobuf\Internal\MapField $args
     *           Function arguments
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Server function name.
     * Valid function names: report_install, report_list, report_get, product_price, email_send
     *
     * Generated from protobuf field <code>string function = 1;</code>
     * @return string
     */
    public function getFunction()
    {
        return $this->function;
    }

    /**
     * Server function name.
     * Valid function names: report_install, report_list, report_get, product_price, email_send
     *
     * Generated from protobuf field <code>string function = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFunction($var)
    {
        GPBUtil::checkString($var, True);
        $this->function = $var;

        return $this;
    }

    /**
     * Function arguments
     *
     * Generated from protobuf field <code>map<string, string> args = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getArgs()
    {
        return $this->args;
    }

    /**
     * Function arguments
     *
     * Generated from protobuf field <code>map<string, string> args = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setArgs($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->args = $arr;

        return $this;
    }

}

