<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nervatura.RequestDelete</code>
 */
class RequestDelete extends \Google\Protobuf\Internal\Message
{
    /**
     * Database primary key. If specified, the code does not need to be set.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Database independent unique external key. If specified, the id does not need to be set.
     *
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';
    /**
     * Model name
     *
     * Generated from protobuf field <code>.nervatura.Model model = 3;</code>
     */
    protected $model = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           Database primary key. If specified, the code does not need to be set.
     *     @type string $code
     *           Database independent unique external key. If specified, the id does not need to be set.
     *     @type int $model
     *           Model name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Database primary key. If specified, the code does not need to be set.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Database primary key. If specified, the code does not need to be set.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Database independent unique external key. If specified, the id does not need to be set.
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Database independent unique external key. If specified, the id does not need to be set.
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Model name
     *
     * Generated from protobuf field <code>.nervatura.Model model = 3;</code>
     * @return int
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * Model name
     *
     * Generated from protobuf field <code>.nervatura.Model model = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setModel($var)
    {
        GPBUtil::checkEnum($var, \Nervatura\Model::class);
        $this->model = $var;

        return $this;
    }

}

