<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nervatura.RequestPasswordChange</code>
 */
class RequestPasswordChange extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string password = 1;</code>
     */
    protected $password = '';
    /**
     * Generated from protobuf field <code>string confirm = 2;</code>
     */
    protected $confirm = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $password
     *     @type string $confirm
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string password = 1;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string confirm = 2;</code>
     * @return string
     */
    public function getConfirm()
    {
        return $this->confirm;
    }

    /**
     * Generated from protobuf field <code>string confirm = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setConfirm($var)
    {
        GPBUtil::checkString($var, True);
        $this->confirm = $var;

        return $this;
    }

}

