<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nervatura.ResponseTokenDecode</code>
 */
class ResponseTokenDecode extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string code = 1;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>string user_name = 2;</code>
     */
    protected $user_name = '';
    /**
     * Generated from protobuf field <code>string database = 3;</code>
     */
    protected $database = '';
    /**
     * JWT expiration time
     *
     * Generated from protobuf field <code>string exp = 4;</code>
     */
    protected $exp = '';
    /**
     * JWT issuer
     *
     * Generated from protobuf field <code>string iss = 5;</code>
     */
    protected $iss = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $code
     *     @type string $user_name
     *     @type string $database
     *     @type string $exp
     *           JWT expiration time
     *     @type string $iss
     *           JWT issuer
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string code = 1;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_name = 2;</code>
     * @return string
     */
    public function getUserName()
    {
        return $this->user_name;
    }

    /**
     * Generated from protobuf field <code>string user_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string database = 3;</code>
     * @return string
     */
    public function getDatabase()
    {
        return $this->database;
    }

    /**
     * Generated from protobuf field <code>string database = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDatabase($var)
    {
        GPBUtil::checkString($var, True);
        $this->database = $var;

        return $this;
    }

    /**
     * JWT expiration time
     *
     * Generated from protobuf field <code>string exp = 4;</code>
     * @return string
     */
    public function getExp()
    {
        return $this->exp;
    }

    /**
     * JWT expiration time
     *
     * Generated from protobuf field <code>string exp = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setExp($var)
    {
        GPBUtil::checkString($var, True);
        $this->exp = $var;

        return $this;
    }

    /**
     * JWT issuer
     *
     * Generated from protobuf field <code>string iss = 5;</code>
     * @return string
     */
    public function getIss()
    {
        return $this->iss;
    }

    /**
     * JWT issuer
     *
     * Generated from protobuf field <code>string iss = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setIss($var)
    {
        GPBUtil::checkString($var, True);
        $this->iss = $var;

        return $this;
    }

}

