<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use UnexpectedValueException;

/**
 * Protobuf type <code>nervatura.ShortcutField</code>
 */
class ShortcutField
{
    /**
     * Generated from protobuf enum <code>SHORTCUT_STRING = 0;</code>
     */
    const SHORTCUT_STRING = 0;
    /**
     * Generated from protobuf enum <code>SHORTCUT_BOOL = 1;</code>
     */
    const SHORTCUT_BOOL = 1;
    /**
     * Generated from protobuf enum <code>SHORTCUT_INTEGER = 2;</code>
     */
    const SHORTCUT_INTEGER = 2;
    /**
     * Generated from protobuf enum <code>SHORTCUT_NUMBER = 3;</code>
     */
    const SHORTCUT_NUMBER = 3;
    /**
     * Generated from protobuf enum <code>SHORTCUT_DATE = 4;</code>
     */
    const SHORTCUT_DATE = 4;

    private static $valueToName = [
        self::SHORTCUT_STRING => 'SHORTCUT_STRING',
        self::SHORTCUT_BOOL => 'SHORTCUT_BOOL',
        self::SHORTCUT_INTEGER => 'SHORTCUT_INTEGER',
        self::SHORTCUT_NUMBER => 'SHORTCUT_NUMBER',
        self::SHORTCUT_DATE => 'SHORTCUT_DATE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

