<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use UnexpectedValueException;

/**
 * Protobuf type <code>nervatura.ShortcutMethod</code>
 */
class ShortcutMethod
{
    /**
     * Generated from protobuf enum <code>METHOD_GET = 0;</code>
     */
    const METHOD_GET = 0;
    /**
     * Generated from protobuf enum <code>METHOD_POST = 1;</code>
     */
    const METHOD_POST = 1;

    private static $valueToName = [
        self::METHOD_GET => 'METHOD_GET',
        self::METHOD_POST => 'METHOD_POST',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

