<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * TaxMeta message
 *
 * Generated from protobuf message <code>nervatura.TaxMeta</code>
 */
class TaxMeta extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string description = 1;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>double rate_value = 2;</code>
     */
    protected $rate_value = 0.0;
    /**
     * Additional tags for the tax
     *
     * Generated from protobuf field <code>repeated string tags = 3;</code>
     */
    private $tags;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $description
     *     @type float $rate_value
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $tags
     *           Additional tags for the tax
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string description = 1;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double rate_value = 2;</code>
     * @return float
     */
    public function getRateValue()
    {
        return $this->rate_value;
    }

    /**
     * Generated from protobuf field <code>double rate_value = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setRateValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->rate_value = $var;

        return $this;
    }

    /**
     * Additional tags for the tax
     *
     * Generated from protobuf field <code>repeated string tags = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Additional tags for the tax
     *
     * Generated from protobuf field <code>repeated string tags = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

}

