<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Tool message
 *
 * Generated from protobuf message <code>nervatura.Tool</code>
 */
class Tool extends \Google\Protobuf\Internal\Message
{
    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: SER1731101982N123 ("SER" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * The description of the tool.
     *
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Product">Product</a>.Code
     *
     * Generated from protobuf field <code>string product_code = 4;</code>
     */
    protected $product_code = '';
    /**
     * Generated from protobuf field <code>repeated .nervatura.Event events = 5;</code>
     */
    private $events;
    /**
     * Generated from protobuf field <code>.nervatura.ToolMeta tool_meta = 6;</code>
     */
    protected $tool_meta = null;
    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString tool_map = 7;</code>
     */
    protected $tool_map = null;
    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 8;</code>
     */
    protected $time_stamp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           Database primary key
     *           Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *     @type string $code
     *           Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     *           Example: SER1731101982N123 ("SER" + UNIX Time stamp + "N" + current ID)
     *     @type string $description
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           The description of the tool.
     *     @type string $product_code
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           Reference to <a href="#Product">Product</a>.Code
     *     @type \Nervatura\Event[]|\Google\Protobuf\Internal\RepeatedField $events
     *     @type \Nervatura\ToolMeta $tool_meta
     *     @type \Nervatura\JsonString $tool_map
     *           Flexible key-value map for additional metadata. The value is any json type.
     *     @type string $time_stamp
     *           Timestamp of data creation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: SER1731101982N123 ("SER" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: SER1731101982N123 ("SER" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * The description of the tool.
     *
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * The description of the tool.
     *
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Product">Product</a>.Code
     *
     * Generated from protobuf field <code>string product_code = 4;</code>
     * @return string
     */
    public function getProductCode()
    {
        return $this->product_code;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * Reference to <a href="#Product">Product</a>.Code
     *
     * Generated from protobuf field <code>string product_code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setProductCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->product_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .nervatura.Event events = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * Generated from protobuf field <code>repeated .nervatura.Event events = 5;</code>
     * @param \Nervatura\Event[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEvents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nervatura\Event::class);
        $this->events = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.ToolMeta tool_meta = 6;</code>
     * @return \Nervatura\ToolMeta
     */
    public function getToolMeta()
    {
        return isset($this->tool_meta) ? $this->tool_meta : null;
    }

    public function hasToolMeta()
    {
        return isset($this->tool_meta);
    }

    public function clearToolMeta()
    {
        unset($this->tool_meta);
    }

    /**
     * Generated from protobuf field <code>.nervatura.ToolMeta tool_meta = 6;</code>
     * @param \Nervatura\ToolMeta $var
     * @return $this
     */
    public function setToolMeta($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\ToolMeta::class);
        $this->tool_meta = $var;

        return $this;
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString tool_map = 7;</code>
     * @return \Nervatura\JsonString
     */
    public function getToolMap()
    {
        return isset($this->tool_map) ? $this->tool_map : null;
    }

    public function hasToolMap()
    {
        return isset($this->tool_map);
    }

    public function clearToolMap()
    {
        unset($this->tool_map);
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString tool_map = 7;</code>
     * @param \Nervatura\JsonString $var
     * @return $this
     */
    public function setToolMap($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\JsonString::class);
        $this->tool_map = $var;

        return $this;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 8;</code>
     * @return string
     */
    public function getTimeStamp()
    {
        return $this->time_stamp;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_stamp = $var;

        return $this;
    }

}

