<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use UnexpectedValueException;

/**
 * Protobuf type <code>nervatura.TransType</code>
 */
class TransType
{
    /**
     * Generated from protobuf enum <code>TRANS_INVOICE = 0;</code>
     */
    const TRANS_INVOICE = 0;
    /**
     * Generated from protobuf enum <code>TRANS_RECEIPT = 1;</code>
     */
    const TRANS_RECEIPT = 1;
    /**
     * Generated from protobuf enum <code>TRANS_ORDER = 2;</code>
     */
    const TRANS_ORDER = 2;
    /**
     * Generated from protobuf enum <code>TRANS_OFFER = 3;</code>
     */
    const TRANS_OFFER = 3;
    /**
     * Generated from protobuf enum <code>TRANS_WORKSHEET = 4;</code>
     */
    const TRANS_WORKSHEET = 4;
    /**
     * Generated from protobuf enum <code>TRANS_RENT = 5;</code>
     */
    const TRANS_RENT = 5;
    /**
     * Generated from protobuf enum <code>TRANS_DELIVERY = 6;</code>
     */
    const TRANS_DELIVERY = 6;
    /**
     * Generated from protobuf enum <code>TRANS_INVENTORY = 7;</code>
     */
    const TRANS_INVENTORY = 7;
    /**
     * Generated from protobuf enum <code>TRANS_WAYBILL = 8;</code>
     */
    const TRANS_WAYBILL = 8;
    /**
     * Generated from protobuf enum <code>TRANS_PRODUCTION = 9;</code>
     */
    const TRANS_PRODUCTION = 9;
    /**
     * Generated from protobuf enum <code>TRANS_FORMULA = 10;</code>
     */
    const TRANS_FORMULA = 10;
    /**
     * Generated from protobuf enum <code>TRANS_BANK = 11;</code>
     */
    const TRANS_BANK = 11;
    /**
     * Generated from protobuf enum <code>TRANS_CASH = 12;</code>
     */
    const TRANS_CASH = 12;

    private static $valueToName = [
        self::TRANS_INVOICE => 'TRANS_INVOICE',
        self::TRANS_RECEIPT => 'TRANS_RECEIPT',
        self::TRANS_ORDER => 'TRANS_ORDER',
        self::TRANS_OFFER => 'TRANS_OFFER',
        self::TRANS_WORKSHEET => 'TRANS_WORKSHEET',
        self::TRANS_RENT => 'TRANS_RENT',
        self::TRANS_DELIVERY => 'TRANS_DELIVERY',
        self::TRANS_INVENTORY => 'TRANS_INVENTORY',
        self::TRANS_WAYBILL => 'TRANS_WAYBILL',
        self::TRANS_PRODUCTION => 'TRANS_PRODUCTION',
        self::TRANS_FORMULA => 'TRANS_FORMULA',
        self::TRANS_BANK => 'TRANS_BANK',
        self::TRANS_CASH => 'TRANS_CASH',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

