<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Trans message
 *
 * Generated from protobuf message <code>nervatura.Trans</code>
 */
class Trans extends \Google\Protobuf\Internal\Message
{
    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: TRN1731101982N123 ("TRN" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.TransType trans_type = 3;</code>
     */
    protected $trans_type = 0;
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ISO 8601 date
     *
     * Generated from protobuf field <code>string trans_date = 4;</code>
     */
    protected $trans_date = '';
    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.Direction direction = 5;</code>
     */
    protected $direction = 0;
    /**
     * Reference to <a href="#Trans">Trans</a>.Code
     *
     * Generated from protobuf field <code>string trans_code = 6;</code>
     */
    protected $trans_code = '';
    /**
     * Reference to <a href="#Customer">Customer</a>.Code
     *
     * Generated from protobuf field <code>string customer_code = 7;</code>
     */
    protected $customer_code = '';
    /**
     * Reference to <a href="#Employee">Employee</a>.Code
     *
     * Generated from protobuf field <code>string employee_code = 8;</code>
     */
    protected $employee_code = '';
    /**
     * Reference to <a href="#Project">Project</a>.Code
     *
     * Generated from protobuf field <code>string project_code = 9;</code>
     */
    protected $project_code = '';
    /**
     * Reference to <a href="#Place">Place</a>.Code
     *
     * Generated from protobuf field <code>string place_code = 10;</code>
     */
    protected $place_code = '';
    /**
     * Reference to <a href="#Currency">Currency</a>.Code
     *
     * Generated from protobuf field <code>string currency_code = 11;</code>
     */
    protected $currency_code = '';
    /**
     * Reference to <a href="#Auth">Auth</a>.Code
     *
     * Generated from protobuf field <code>string auth_code = 12;</code>
     */
    protected $auth_code = '';
    /**
     * Generated from protobuf field <code>.nervatura.TransMeta trans_meta = 13;</code>
     */
    protected $trans_meta = null;
    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString trans_map = 14;</code>
     */
    protected $trans_map = null;
    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 15;</code>
     */
    protected $time_stamp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           Database primary key
     *           Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *     @type string $code
     *           Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     *           Example: TRN1731101982N123 ("TRN" + UNIX Time stamp + "N" + current ID)
     *     @type int $trans_type
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           ENUM field.
     *     @type string $trans_date
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           ISO 8601 date
     *     @type int $direction
     *           <span class="text-red-500 font-bold">*</span> Required field.
     *           ENUM field.
     *     @type string $trans_code
     *           Reference to <a href="#Trans">Trans</a>.Code
     *     @type string $customer_code
     *           Reference to <a href="#Customer">Customer</a>.Code
     *     @type string $employee_code
     *           Reference to <a href="#Employee">Employee</a>.Code
     *     @type string $project_code
     *           Reference to <a href="#Project">Project</a>.Code
     *     @type string $place_code
     *           Reference to <a href="#Place">Place</a>.Code
     *     @type string $currency_code
     *           Reference to <a href="#Currency">Currency</a>.Code
     *     @type string $auth_code
     *           Reference to <a href="#Auth">Auth</a>.Code
     *     @type \Nervatura\TransMeta $trans_meta
     *     @type \Nervatura\JsonString $trans_map
     *           Flexible key-value map for additional metadata. The value is any json type.
     *     @type string $time_stamp
     *           Timestamp of data creation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Database primary key
     * Database dependent serial number type. Its value is unique only at table level and may change during data migrations.
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: TRN1731101982N123 ("TRN" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Database independent unique external key. If not specified, it is generated on creation. It cannot be modified after creation.
     * Example: TRN1731101982N123 ("TRN" + UNIX Time stamp + "N" + current ID)
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.TransType trans_type = 3;</code>
     * @return int
     */
    public function getTransType()
    {
        return $this->trans_type;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.TransType trans_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTransType($var)
    {
        GPBUtil::checkEnum($var, \Nervatura\TransType::class);
        $this->trans_type = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ISO 8601 date
     *
     * Generated from protobuf field <code>string trans_date = 4;</code>
     * @return string
     */
    public function getTransDate()
    {
        return $this->trans_date;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ISO 8601 date
     *
     * Generated from protobuf field <code>string trans_date = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTransDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->trans_date = $var;

        return $this;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.Direction direction = 5;</code>
     * @return int
     */
    public function getDirection()
    {
        return $this->direction;
    }

    /**
     * <span class="text-red-500 font-bold">*</span> Required field.
     * ENUM field.
     *
     * Generated from protobuf field <code>.nervatura.Direction direction = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setDirection($var)
    {
        GPBUtil::checkEnum($var, \Nervatura\Direction::class);
        $this->direction = $var;

        return $this;
    }

    /**
     * Reference to <a href="#Trans">Trans</a>.Code
     *
     * Generated from protobuf field <code>string trans_code = 6;</code>
     * @return string
     */
    public function getTransCode()
    {
        return $this->trans_code;
    }

    /**
     * Reference to <a href="#Trans">Trans</a>.Code
     *
     * Generated from protobuf field <code>string trans_code = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTransCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->trans_code = $var;

        return $this;
    }

    /**
     * Reference to <a href="#Customer">Customer</a>.Code
     *
     * Generated from protobuf field <code>string customer_code = 7;</code>
     * @return string
     */
    public function getCustomerCode()
    {
        return $this->customer_code;
    }

    /**
     * Reference to <a href="#Customer">Customer</a>.Code
     *
     * Generated from protobuf field <code>string customer_code = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->customer_code = $var;

        return $this;
    }

    /**
     * Reference to <a href="#Employee">Employee</a>.Code
     *
     * Generated from protobuf field <code>string employee_code = 8;</code>
     * @return string
     */
    public function getEmployeeCode()
    {
        return $this->employee_code;
    }

    /**
     * Reference to <a href="#Employee">Employee</a>.Code
     *
     * Generated from protobuf field <code>string employee_code = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setEmployeeCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->employee_code = $var;

        return $this;
    }

    /**
     * Reference to <a href="#Project">Project</a>.Code
     *
     * Generated from protobuf field <code>string project_code = 9;</code>
     * @return string
     */
    public function getProjectCode()
    {
        return $this->project_code;
    }

    /**
     * Reference to <a href="#Project">Project</a>.Code
     *
     * Generated from protobuf field <code>string project_code = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setProjectCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->project_code = $var;

        return $this;
    }

    /**
     * Reference to <a href="#Place">Place</a>.Code
     *
     * Generated from protobuf field <code>string place_code = 10;</code>
     * @return string
     */
    public function getPlaceCode()
    {
        return $this->place_code;
    }

    /**
     * Reference to <a href="#Place">Place</a>.Code
     *
     * Generated from protobuf field <code>string place_code = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setPlaceCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->place_code = $var;

        return $this;
    }

    /**
     * Reference to <a href="#Currency">Currency</a>.Code
     *
     * Generated from protobuf field <code>string currency_code = 11;</code>
     * @return string
     */
    public function getCurrencyCode()
    {
        return $this->currency_code;
    }

    /**
     * Reference to <a href="#Currency">Currency</a>.Code
     *
     * Generated from protobuf field <code>string currency_code = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrencyCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency_code = $var;

        return $this;
    }

    /**
     * Reference to <a href="#Auth">Auth</a>.Code
     *
     * Generated from protobuf field <code>string auth_code = 12;</code>
     * @return string
     */
    public function getAuthCode()
    {
        return $this->auth_code;
    }

    /**
     * Reference to <a href="#Auth">Auth</a>.Code
     *
     * Generated from protobuf field <code>string auth_code = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->auth_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.nervatura.TransMeta trans_meta = 13;</code>
     * @return \Nervatura\TransMeta
     */
    public function getTransMeta()
    {
        return isset($this->trans_meta) ? $this->trans_meta : null;
    }

    public function hasTransMeta()
    {
        return isset($this->trans_meta);
    }

    public function clearTransMeta()
    {
        unset($this->trans_meta);
    }

    /**
     * Generated from protobuf field <code>.nervatura.TransMeta trans_meta = 13;</code>
     * @param \Nervatura\TransMeta $var
     * @return $this
     */
    public function setTransMeta($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\TransMeta::class);
        $this->trans_meta = $var;

        return $this;
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString trans_map = 14;</code>
     * @return \Nervatura\JsonString
     */
    public function getTransMap()
    {
        return isset($this->trans_map) ? $this->trans_map : null;
    }

    public function hasTransMap()
    {
        return isset($this->trans_map);
    }

    public function clearTransMap()
    {
        unset($this->trans_map);
    }

    /**
     * Flexible key-value map for additional metadata. The value is any json type.
     *
     * Generated from protobuf field <code>.nervatura.JsonString trans_map = 14;</code>
     * @param \Nervatura\JsonString $var
     * @return $this
     */
    public function setTransMap($var)
    {
        GPBUtil::checkMessage($var, \Nervatura\JsonString::class);
        $this->trans_map = $var;

        return $this;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 15;</code>
     * @return string
     */
    public function getTimeStamp()
    {
        return $this->time_stamp;
    }

    /**
     * Timestamp of data creation
     *
     * Generated from protobuf field <code>string time_stamp = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_stamp = $var;

        return $this;
    }

}

