<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use UnexpectedValueException;

/**
 * Protobuf type <code>nervatura.ViewName</code>
 */
class ViewName
{
    /**
     * Generated from protobuf enum <code>VIEW_CONFIG_DATA = 0;</code>
     */
    const VIEW_CONFIG_DATA = 0;
    /**
     * Generated from protobuf enum <code>VIEW_CONFIG_MAP = 1;</code>
     */
    const VIEW_CONFIG_MAP = 1;
    /**
     * Generated from protobuf enum <code>VIEW_CONFIG_MESSAGE = 2;</code>
     */
    const VIEW_CONFIG_MESSAGE = 2;
    /**
     * Generated from protobuf enum <code>VIEW_CONFIG_PATTERN = 3;</code>
     */
    const VIEW_CONFIG_PATTERN = 3;
    /**
     * Generated from protobuf enum <code>VIEW_CONFIG_PRINT_QUEUE = 4;</code>
     */
    const VIEW_CONFIG_PRINT_QUEUE = 4;
    /**
     * Generated from protobuf enum <code>VIEW_CONFIG_REPORT = 5;</code>
     */
    const VIEW_CONFIG_REPORT = 5;
    /**
     * Generated from protobuf enum <code>VIEW_CONFIG_SHORTCUT = 6;</code>
     */
    const VIEW_CONFIG_SHORTCUT = 6;
    /**
     * Generated from protobuf enum <code>VIEW_CURRENCY_MAP = 7;</code>
     */
    const VIEW_CURRENCY_MAP = 7;
    /**
     * Generated from protobuf enum <code>VIEW_CURRENCY_TAGS = 8;</code>
     */
    const VIEW_CURRENCY_TAGS = 8;
    /**
     * Generated from protobuf enum <code>VIEW_CURRENCY_VIEW = 9;</code>
     */
    const VIEW_CURRENCY_VIEW = 9;
    /**
     * Generated from protobuf enum <code>VIEW_CUSTOMER_ADDRESSES = 10;</code>
     */
    const VIEW_CUSTOMER_ADDRESSES = 10;
    /**
     * Generated from protobuf enum <code>VIEW_CUSTOMER_CONTACTS = 11;</code>
     */
    const VIEW_CUSTOMER_CONTACTS = 11;
    /**
     * Generated from protobuf enum <code>VIEW_CUSTOMER_EVENTS = 12;</code>
     */
    const VIEW_CUSTOMER_EVENTS = 12;
    /**
     * Generated from protobuf enum <code>VIEW_CUSTOMER_MAP = 13;</code>
     */
    const VIEW_CUSTOMER_MAP = 13;
    /**
     * Generated from protobuf enum <code>VIEW_CUSTOMER_TAGS = 14;</code>
     */
    const VIEW_CUSTOMER_TAGS = 14;
    /**
     * Generated from protobuf enum <code>VIEW_CUSTOMER_VIEW = 15;</code>
     */
    const VIEW_CUSTOMER_VIEW = 15;
    /**
     * Generated from protobuf enum <code>VIEW_EMPLOYEE_EVENTS = 16;</code>
     */
    const VIEW_EMPLOYEE_EVENTS = 16;
    /**
     * Generated from protobuf enum <code>VIEW_EMPLOYEE_MAP = 17;</code>
     */
    const VIEW_EMPLOYEE_MAP = 17;
    /**
     * Generated from protobuf enum <code>VIEW_EMPLOYEE_TAGS = 18;</code>
     */
    const VIEW_EMPLOYEE_TAGS = 18;
    /**
     * Generated from protobuf enum <code>VIEW_EMPLOYEE_VIEW = 19;</code>
     */
    const VIEW_EMPLOYEE_VIEW = 19;
    /**
     * Generated from protobuf enum <code>VIEW_ITEM_MAP = 20;</code>
     */
    const VIEW_ITEM_MAP = 20;
    /**
     * Generated from protobuf enum <code>VIEW_ITEM_TAGS = 21;</code>
     */
    const VIEW_ITEM_TAGS = 21;
    /**
     * Generated from protobuf enum <code>VIEW_ITEM_VIEW = 22;</code>
     */
    const VIEW_ITEM_VIEW = 22;
    /**
     * Generated from protobuf enum <code>VIEW_LINK_MAP = 23;</code>
     */
    const VIEW_LINK_MAP = 23;
    /**
     * Generated from protobuf enum <code>VIEW_LINK_TAGS = 24;</code>
     */
    const VIEW_LINK_TAGS = 24;
    /**
     * Generated from protobuf enum <code>VIEW_LINK_VIEW = 25;</code>
     */
    const VIEW_LINK_VIEW = 25;
    /**
     * Generated from protobuf enum <code>VIEW_MOVEMENT_MAP = 26;</code>
     */
    const VIEW_MOVEMENT_MAP = 26;
    /**
     * Generated from protobuf enum <code>VIEW_MOVEMENT_TAGS = 27;</code>
     */
    const VIEW_MOVEMENT_TAGS = 27;
    /**
     * Generated from protobuf enum <code>VIEW_MOVEMENT_STOCK = 28;</code>
     */
    const VIEW_MOVEMENT_STOCK = 28;
    /**
     * Generated from protobuf enum <code>VIEW_MOVEMENT_INVENTORY = 29;</code>
     */
    const VIEW_MOVEMENT_INVENTORY = 29;
    /**
     * Generated from protobuf enum <code>VIEW_MOVEMENT_WAYBILL = 30;</code>
     */
    const VIEW_MOVEMENT_WAYBILL = 30;
    /**
     * Generated from protobuf enum <code>VIEW_MOVEMENT_FORMULA = 31;</code>
     */
    const VIEW_MOVEMENT_FORMULA = 31;
    /**
     * Generated from protobuf enum <code>VIEW_MOVEMENT_VIEW = 32;</code>
     */
    const VIEW_MOVEMENT_VIEW = 32;
    /**
     * Generated from protobuf enum <code>VIEW_PAYMENT_MAP = 33;</code>
     */
    const VIEW_PAYMENT_MAP = 33;
    /**
     * Generated from protobuf enum <code>VIEW_PAYMENT_INVOICE = 34;</code>
     */
    const VIEW_PAYMENT_INVOICE = 34;
    /**
     * Generated from protobuf enum <code>VIEW_PAYMENT_TAGS = 35;</code>
     */
    const VIEW_PAYMENT_TAGS = 35;
    /**
     * Generated from protobuf enum <code>VIEW_PAYMENT_VIEW = 36;</code>
     */
    const VIEW_PAYMENT_VIEW = 36;
    /**
     * Generated from protobuf enum <code>VIEW_PLACE_MAP = 37;</code>
     */
    const VIEW_PLACE_MAP = 37;
    /**
     * Generated from protobuf enum <code>VIEW_PLACE_TAGS = 38;</code>
     */
    const VIEW_PLACE_TAGS = 38;
    /**
     * Generated from protobuf enum <code>VIEW_PLACE_VIEW = 39;</code>
     */
    const VIEW_PLACE_VIEW = 39;
    /**
     * Generated from protobuf enum <code>VIEW_PRICE_MAP = 40;</code>
     */
    const VIEW_PRICE_MAP = 40;
    /**
     * Generated from protobuf enum <code>VIEW_PRICE_TAGS = 41;</code>
     */
    const VIEW_PRICE_TAGS = 41;
    /**
     * Generated from protobuf enum <code>VIEW_PRICE_VIEW = 42;</code>
     */
    const VIEW_PRICE_VIEW = 42;
    /**
     * Generated from protobuf enum <code>VIEW_PRODUCT_MAP = 43;</code>
     */
    const VIEW_PRODUCT_MAP = 43;
    /**
     * Generated from protobuf enum <code>VIEW_PRODUCT_TAGS = 44;</code>
     */
    const VIEW_PRODUCT_TAGS = 44;
    /**
     * Generated from protobuf enum <code>VIEW_PRODUCT_VIEW = 45;</code>
     */
    const VIEW_PRODUCT_VIEW = 45;
    /**
     * Generated from protobuf enum <code>VIEW_PRODUCT_COMPONENTS = 46;</code>
     */
    const VIEW_PRODUCT_COMPONENTS = 46;
    /**
     * Generated from protobuf enum <code>VIEW_PROJECT_MAP = 47;</code>
     */
    const VIEW_PROJECT_MAP = 47;
    /**
     * Generated from protobuf enum <code>VIEW_PROJECT_TAGS = 48;</code>
     */
    const VIEW_PROJECT_TAGS = 48;
    /**
     * Generated from protobuf enum <code>VIEW_PROJECT_VIEW = 49;</code>
     */
    const VIEW_PROJECT_VIEW = 49;
    /**
     * Generated from protobuf enum <code>VIEW_RATE_MAP = 50;</code>
     */
    const VIEW_RATE_MAP = 50;
    /**
     * Generated from protobuf enum <code>VIEW_RATE_TAGS = 51;</code>
     */
    const VIEW_RATE_TAGS = 51;
    /**
     * Generated from protobuf enum <code>VIEW_RATE_VIEW = 52;</code>
     */
    const VIEW_RATE_VIEW = 52;
    /**
     * Generated from protobuf enum <code>VIEW_TAX_MAP = 53;</code>
     */
    const VIEW_TAX_MAP = 53;
    /**
     * Generated from protobuf enum <code>VIEW_TAX_TAGS = 54;</code>
     */
    const VIEW_TAX_TAGS = 54;
    /**
     * Generated from protobuf enum <code>VIEW_TAX_VIEW = 55;</code>
     */
    const VIEW_TAX_VIEW = 55;
    /**
     * Generated from protobuf enum <code>VIEW_TOOL_MAP = 56;</code>
     */
    const VIEW_TOOL_MAP = 56;
    /**
     * Generated from protobuf enum <code>VIEW_TOOL_TAGS = 57;</code>
     */
    const VIEW_TOOL_TAGS = 57;
    /**
     * Generated from protobuf enum <code>VIEW_TOOL_VIEW = 58;</code>
     */
    const VIEW_TOOL_VIEW = 58;
    /**
     * Generated from protobuf enum <code>VIEW_TRANS_MAP = 59;</code>
     */
    const VIEW_TRANS_MAP = 59;
    /**
     * Generated from protobuf enum <code>VIEW_TRANS_TAGS = 60;</code>
     */
    const VIEW_TRANS_TAGS = 60;
    /**
     * Generated from protobuf enum <code>VIEW_TRANS_VIEW = 61;</code>
     */
    const VIEW_TRANS_VIEW = 61;

    private static $valueToName = [
        self::VIEW_CONFIG_DATA => 'VIEW_CONFIG_DATA',
        self::VIEW_CONFIG_MAP => 'VIEW_CONFIG_MAP',
        self::VIEW_CONFIG_MESSAGE => 'VIEW_CONFIG_MESSAGE',
        self::VIEW_CONFIG_PATTERN => 'VIEW_CONFIG_PATTERN',
        self::VIEW_CONFIG_PRINT_QUEUE => 'VIEW_CONFIG_PRINT_QUEUE',
        self::VIEW_CONFIG_REPORT => 'VIEW_CONFIG_REPORT',
        self::VIEW_CONFIG_SHORTCUT => 'VIEW_CONFIG_SHORTCUT',
        self::VIEW_CURRENCY_MAP => 'VIEW_CURRENCY_MAP',
        self::VIEW_CURRENCY_TAGS => 'VIEW_CURRENCY_TAGS',
        self::VIEW_CURRENCY_VIEW => 'VIEW_CURRENCY_VIEW',
        self::VIEW_CUSTOMER_ADDRESSES => 'VIEW_CUSTOMER_ADDRESSES',
        self::VIEW_CUSTOMER_CONTACTS => 'VIEW_CUSTOMER_CONTACTS',
        self::VIEW_CUSTOMER_EVENTS => 'VIEW_CUSTOMER_EVENTS',
        self::VIEW_CUSTOMER_MAP => 'VIEW_CUSTOMER_MAP',
        self::VIEW_CUSTOMER_TAGS => 'VIEW_CUSTOMER_TAGS',
        self::VIEW_CUSTOMER_VIEW => 'VIEW_CUSTOMER_VIEW',
        self::VIEW_EMPLOYEE_EVENTS => 'VIEW_EMPLOYEE_EVENTS',
        self::VIEW_EMPLOYEE_MAP => 'VIEW_EMPLOYEE_MAP',
        self::VIEW_EMPLOYEE_TAGS => 'VIEW_EMPLOYEE_TAGS',
        self::VIEW_EMPLOYEE_VIEW => 'VIEW_EMPLOYEE_VIEW',
        self::VIEW_ITEM_MAP => 'VIEW_ITEM_MAP',
        self::VIEW_ITEM_TAGS => 'VIEW_ITEM_TAGS',
        self::VIEW_ITEM_VIEW => 'VIEW_ITEM_VIEW',
        self::VIEW_LINK_MAP => 'VIEW_LINK_MAP',
        self::VIEW_LINK_TAGS => 'VIEW_LINK_TAGS',
        self::VIEW_LINK_VIEW => 'VIEW_LINK_VIEW',
        self::VIEW_MOVEMENT_MAP => 'VIEW_MOVEMENT_MAP',
        self::VIEW_MOVEMENT_TAGS => 'VIEW_MOVEMENT_TAGS',
        self::VIEW_MOVEMENT_STOCK => 'VIEW_MOVEMENT_STOCK',
        self::VIEW_MOVEMENT_INVENTORY => 'VIEW_MOVEMENT_INVENTORY',
        self::VIEW_MOVEMENT_WAYBILL => 'VIEW_MOVEMENT_WAYBILL',
        self::VIEW_MOVEMENT_FORMULA => 'VIEW_MOVEMENT_FORMULA',
        self::VIEW_MOVEMENT_VIEW => 'VIEW_MOVEMENT_VIEW',
        self::VIEW_PAYMENT_MAP => 'VIEW_PAYMENT_MAP',
        self::VIEW_PAYMENT_INVOICE => 'VIEW_PAYMENT_INVOICE',
        self::VIEW_PAYMENT_TAGS => 'VIEW_PAYMENT_TAGS',
        self::VIEW_PAYMENT_VIEW => 'VIEW_PAYMENT_VIEW',
        self::VIEW_PLACE_MAP => 'VIEW_PLACE_MAP',
        self::VIEW_PLACE_TAGS => 'VIEW_PLACE_TAGS',
        self::VIEW_PLACE_VIEW => 'VIEW_PLACE_VIEW',
        self::VIEW_PRICE_MAP => 'VIEW_PRICE_MAP',
        self::VIEW_PRICE_TAGS => 'VIEW_PRICE_TAGS',
        self::VIEW_PRICE_VIEW => 'VIEW_PRICE_VIEW',
        self::VIEW_PRODUCT_MAP => 'VIEW_PRODUCT_MAP',
        self::VIEW_PRODUCT_TAGS => 'VIEW_PRODUCT_TAGS',
        self::VIEW_PRODUCT_VIEW => 'VIEW_PRODUCT_VIEW',
        self::VIEW_PRODUCT_COMPONENTS => 'VIEW_PRODUCT_COMPONENTS',
        self::VIEW_PROJECT_MAP => 'VIEW_PROJECT_MAP',
        self::VIEW_PROJECT_TAGS => 'VIEW_PROJECT_TAGS',
        self::VIEW_PROJECT_VIEW => 'VIEW_PROJECT_VIEW',
        self::VIEW_RATE_MAP => 'VIEW_RATE_MAP',
        self::VIEW_RATE_TAGS => 'VIEW_RATE_TAGS',
        self::VIEW_RATE_VIEW => 'VIEW_RATE_VIEW',
        self::VIEW_TAX_MAP => 'VIEW_TAX_MAP',
        self::VIEW_TAX_TAGS => 'VIEW_TAX_TAGS',
        self::VIEW_TAX_VIEW => 'VIEW_TAX_VIEW',
        self::VIEW_TOOL_MAP => 'VIEW_TOOL_MAP',
        self::VIEW_TOOL_TAGS => 'VIEW_TOOL_TAGS',
        self::VIEW_TOOL_VIEW => 'VIEW_TOOL_VIEW',
        self::VIEW_TRANS_MAP => 'VIEW_TRANS_MAP',
        self::VIEW_TRANS_TAGS => 'VIEW_TRANS_TAGS',
        self::VIEW_TRANS_VIEW => 'VIEW_TRANS_VIEW',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

