<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Nervatura;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Trans Worksheet message
 *
 * Generated from protobuf message <code>nervatura.Worksheet</code>
 */
class Worksheet extends \Google\Protobuf\Internal\Message
{
    /**
     * Distance (km)
     *
     * Generated from protobuf field <code>double distance = 1;</code>
     */
    protected $distance = 0.0;
    /**
     * Repair time (hour)
     *
     * Generated from protobuf field <code>double repair = 2;</code>
     */
    protected $repair = 0.0;
    /**
     * Total time (hour)
     *
     * Generated from protobuf field <code>double total = 3;</code>
     */
    protected $total = 0.0;
    /**
     * Worksheet justification
     *
     * Generated from protobuf field <code>string justification = 4;</code>
     */
    protected $justification = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $distance
     *           Distance (km)
     *     @type float $repair
     *           Repair time (hour)
     *     @type float $total
     *           Total time (hour)
     *     @type string $justification
     *           Worksheet justification
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Distance (km)
     *
     * Generated from protobuf field <code>double distance = 1;</code>
     * @return float
     */
    public function getDistance()
    {
        return $this->distance;
    }

    /**
     * Distance (km)
     *
     * Generated from protobuf field <code>double distance = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setDistance($var)
    {
        GPBUtil::checkDouble($var);
        $this->distance = $var;

        return $this;
    }

    /**
     * Repair time (hour)
     *
     * Generated from protobuf field <code>double repair = 2;</code>
     * @return float
     */
    public function getRepair()
    {
        return $this->repair;
    }

    /**
     * Repair time (hour)
     *
     * Generated from protobuf field <code>double repair = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setRepair($var)
    {
        GPBUtil::checkDouble($var);
        $this->repair = $var;

        return $this;
    }

    /**
     * Total time (hour)
     *
     * Generated from protobuf field <code>double total = 3;</code>
     * @return float
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Total time (hour)
     *
     * Generated from protobuf field <code>double total = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkDouble($var);
        $this->total = $var;

        return $this;
    }

    /**
     * Worksheet justification
     *
     * Generated from protobuf field <code>string justification = 4;</code>
     * @return string
     */
    public function getJustification()
    {
        return $this->justification;
    }

    /**
     * Worksheet justification
     *
     * Generated from protobuf field <code>string justification = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setJustification($var)
    {
        GPBUtil::checkString($var, True);
        $this->justification = $var;

        return $this;
    }

}

